scalalib/src/mill/scalalib/CrossModuleBase.scala
scalalib/test/src/mill/scalalib/HelloWorldTests.scala

Sometimes you want different modules in a build to have different Scala 3 versions, one the older and one the newer.
The current resolve implementation in `CrossModuleBase` is tailored to Scala 2 since it assumes that the binary version is `x.y` while in Scala 3 it's just the first part.
This change adapts the algorithm to consider 1 or 2 parts depending if it is Scala 3 or not.
Pull Request: https://github.com/com-lihaoyi/mill/pull/2877

Allow resolving moduleDeps with older Scala 3 versions

---

main/eval/src/mill/eval/EvaluatorCore.scala
main/eval/test/src/mill/eval/TaskTests.scala

Anonymous tasks can be defined as `val` or `def`. This is in contrast to named targets, which always need to be defined as `def`.
Also, anonymous tasks end up in the terminal group of the target that's using them.
If the same anonymous task is used in multiple targets, it also ends up multiple time in the task results. When a `Evaluator.Results` is created, this clashes, due to the use of a `Strict.Agg` for `Evalutor.Results.evaluated`.
This change deduplicated the results before constructing the `Evaluator.Results`.
Fix: https://github.com/com-lihaoyi/mill/issues/2958

Fix issue #2958 - deduplicate (anonymous) tasks in result

---

docs/modules/ROOT/pages/Installation_IDE_Support.adoc

ArchLinux community repository has been merged into extra repository, according to https://archlinux.org/news/git-migration-announcement/. Current mill package URL doesn't work.

Fix outdated ArchLinux package URL

---

runner/src/mill/runner/CliImports.scala
runner/src/mill/runner/MillBuildBootstrap.scala
runner/src/mill/runner/MillBuildRootModule.scala

Since the cli option `--import` is supposed to affect only the runtime
classpath, there is no need to persist it's value in the generated scripts.
Instead, we hold it in an `DynamicVariable` at script evaluation time.
Pull request: https://github.com/com-lihaoyi/mill/pull/2978

Don't leak runtime cli imports into generated build scripts

---

bsp/worker/src/mill/bsp/worker/BspCompileProblemReporter.scala

Since some compiler messages do not belong to a single source file, they are not actionable (in the sense of a BSP `build/publishDiagnostics`). In such situation (no text document), we send `build/logMessage` instead.
Fix https://github.com/com-lihaoyi/mill/issues/2926

BSP: Send `logMessage` instead of diagnostics when `textDocument` is unknown

---

main/eval/src/mill/eval/GroupEvaluator.scala
main/eval/src/mill/eval/KeyLock.scala

With this change, we synchronize evaluations of the same terminal task. This isn't necessarily needed for normal Mill executions, but in a BSP context, where multiple requests where handled concurrently in the same Mill instance, evaluating the same task concurrently  can happen.
We don't synchronize multiple Mill-instances (e.g. run in two shells) or multiple evaluator-instances (which should have different `out`-dirs anyway).
Fix: https://github.com/com-lihaoyi/mill/issues/2818
Pull request: https://github.com/com-lihaoyi/mill/pull/2980

Synchronize evaluateGroupCached to avoid concurrent access to cache

---

main/eval/src/mill/eval/EvaluatorPaths.scala
main/eval/test/src/mill/eval/EvaluatorPathsTests.scala

In case a segment path matches one of the reserved name of the Windows filesystem namespace, we insert a `~` directly after the offending segment part.
Here is a excerpt from an official [Win32 documentation](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions):
> * Do not use the following reserved names for the name of a file:
>
> CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, COM¹, COM², COM³, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9, LPT¹, LPT², and LPT³. Also avoid these names followed immediately by an extension; for example, NUL.txt and NUL.tar.gz are both equivalent to NUL. For more information, see [Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-f …

Properly sanitize Windows reserved names in evaluator paths

---

scalalib/src/mill/scalalib/PublishModule.scala
scalalib/src/mill/scalalib/publish/LocalIvyPublisher.scala
scalalib/src/mill/scalalib/publish/LocalM2Publisher.scala

The new targets are cached and invalidate properly when the target files (which are outside of Mills cache folder) are changed or removed from the repository cache, as the `PathRef.revalidate` flag is used and enforced by Mill.
Fix https://github.com/com-lihaoyi/mill/issues/2975
Pull request: https://github.com/com-lihaoyi/mill/pull/2976

Add `publishLocalCached` and `publishM2LocalCached` targets

---

integration/failure/cross-collisions/repo/build.sc
integration/failure/cross-collisions/test/src/CrossCollisionsTests.scala
main/api/src/mill/api/MillException.scala
main/define/src/mill/define/Cross.scala

Also add an implicit `ToSegements[os.SubPath]` to accept `os.SubPath` as values in cross modules.
Fix https://github.com/com-lihaoyi/mill/issues/2835

Detect colliding cross module values

---

main/eval/src/mill/eval/EvaluatorPaths.scala
main/eval/test/src/mill/eval/EvaluatorPathsTests.scala

Fix: https://github.com/com-lihaoyi/mill/issues/2835

Mask forward slashes in cross values to fix their cache locations

---

scalajslib/src/mill/scalajslib/ScalaJSModule.scala

When using Scala.js 1.15.0+ together with Scala 2, we now add an explicit dependency to the `scalajs-scalalib` artifact. That artifact comes with Scala.js 1.15.0+, and is double-versioned with the Scala version and the Scala.js version.
As SIP-51 gets implemented and future versions of the Scala library may break forward binary compatibility, the new `scalajs-scalalib` will be able to bring in new APIs back to existing Scala.js versions.
This commit mimics the changes done to sbt-scalajs in https://github.com/scala-js/scala-js/pull/4913/files#diff-adc7ad642b8f89aab3d2a81ac25b23e345bbea758b1c8bbea46cc9d1f351834c

Prepare the Scala.js integration for SIP-51.

---

build.sc
integration/feature/docannotations/test/src/DocAnnotationsTests.scala
main/client/src/mill/main/client/MillClientMain.java
main/resolve/src/mill/resolve/Resolve.scala
main/test/src/mill/main/MainModuleTests.scala
mill
runner/src/mill/runner/MillCliConfig.scala

Also updated the bash launchers' special casing of `-i` to allow for it to be part of a combined token, as long as the combined token starts with `-i`
With the `installLocalCache`ed version of Mill, I can now run:
```bash
$ ./mill -ikw contrib.__.compile
```
and the flags `-i`, `-k`, and `-w` will all take effect independently
The auto-kebab-case name mapping applies to Mill's own CLI args, the args of user-defined `T.command`s, but _not_ the names of the target/command themselves. e.g. you can call;
- `./mill --noServer core.ivyDepsTree --withCompile --withRuntime` or
- `./mill --no-server core.ivyDepsTree --with-compile --with-runtime`
but you cannot call 
- `./mill --no-server core.ivy-deps-tree --with-compile --with-runtime`
It should be easy to add name-mapping for the target …

Bump MainArgs to 0.6.1

---

build.sc
scalalib/test/resources/testrunner/doneMessageFailure/src/DoneMessageFailureFramework.scala
scalalib/test/resources/testrunner/doneMessageNull/src/DoneMessageNullFramework.scala
scalalib/test/resources/testrunner/doneMessageSuccess/src/DoneMessageSuccessFramework.scala
scalalib/test/src/mill/scalalib/TestRunnerTests.scala
testrunner/src/mill/testrunner/TestRunnerUtils.scala

Fixes #2992 
We are returning the doneMessage from the test framework as value of the test task, but we are not printing it. Moreover, the output is shortcircuited when a task fails, so it's not passed to the `test` command.
This PR uses `ctx.log.outputStream.println(doneMessage)` to print the message before returning it so users can clearly see it in case of both success and failure.
This was discovered because of the way weaver works on Scala.js Since the `TestRunnerTests` are on `scalalib` and can't use Scala.js code, I implemented some dummy `sbt.testing.Framework`s which just return a fixed `done` message.
Pull Request: https://github.com/com-lihaoyi/mill/pull/2993

Print `done` message from test framework to stdout

---

scalalib/src/mill/scalalib/Dep.scala

This ensures, that we can populate the `type` attribute to be used by coursier.
I have not checked whether this is self-complete to work with other dependency type.
Maybe, we need some follow up PRs to refine it.

Added support for `type` attribute when parsing dependencies

---

main/resolve/src/mill/resolve/ParseArgs.scala
main/resolve/src/mill/resolve/Resolve.scala
main/resolve/src/mill/resolve/ResolveCore.scala
main/resolve/test/src/mill/main/ResolveTests.scala
main/test/src/mill/util/TestGraphs.scala

This PR add support for new selector pattern `_:Type`.
In addition to `_` and `__`, which select arbitrary segments, the `_:MyType` and `__:MyType` patterns can select modules of the specified type.
The type is matched by it's name and optionally by it's enclosing types and packages, separated by a `.` sign. Since this is also used to separate target path segments, a type selector segment containing a `.` needs to be enclosed in parenthesis. A full qualified type can be enforced with the `_root_` package. 
Example: Find all test jars
```sh
> mill resolve __:TestModule.jar
> mill resolve "(__:scalalib.TestModule).jar"
> mill resolve "(__:mill.scalalib.TestModule).jar"
> mill resolve "(__:_root_.mill.scalalib.TestModule).jar"
```
If a `^` or `!` is preceding the type pattern, it only …

Support type selectors in Resolve

---

contrib/buildinfo/readme.adoc

Hi there,
I stumbled upon a few missing pieces when setting up `BuildInfo` for my project, so I added them here:
- `buildInfoPackageName` is required and not optional
- added a little usage example

Extend documentation for contrib.BuildInfo

---

scalalib/src/mill/scalalib/dependency/versions/VersionsFinder.scala

Searching for updates can take quite some time, especially for larger projects.
This change adds some progress messages via Mills ticker log messages.
More important, I restructured the implementation such that work is distributed over more tasks. If the used evaluator is run with parallel jobs, this will significantly increase the speed.

Restructure `VersionFinder`, increase speed, added ticker messages

---

scalalib/src/mill/scalalib/JavaModule.scala

Resolve some inconsistencies between the BSP and non-BSP versions of `compileClasspath` and `transitiveCompileClasspath`.
The `bspTransitiveCompileClasspath` contained resolved ivy dependencies, which resulted in too many and potentially conflicting jars ending up in the same classpath.
Fix https://github.com/com-lihaoyi/mill/issues/3013

Fix bsp compile classpath inconsistencies

---

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala

Since BSP clients can handle incomplete result lists (e.g. they request a task on 5 build targets, but only receive the results for 3 of them), we just don't include the failed targets in the final request result. This is also what sbt and Bloop does to handle failures.
In addition, we send a log message to the server, so the failure doesn't go unnoticed.
Fix: https://github.com/com-lihaoyi/mill/issues/3011
Pull request: https://github.com/com-lihaoyi/mill/pull/3022

Make BSP task processing more resilient

---

build.sc

This is to fix security issue CVE-2024-25710.
Supersedes https://github.com/com-lihaoyi/mill/pull/3048

Force transitive dependency commons-compress to 1.26.0 or newer

---

example/basic/1-simple-scala/build.sc

This avoids the build error:
```
resolvedIvyDeps 
Resolution failed for 1 modules:
--------------------------------------------
com.lihaoyi:scalatags_3:0.8.2 
not found: /home/cosmin/.ivy2/local/com.lihaoyi/scalatags_3/0.8.2/ivys/ivy.xml
not found: https://repo1.maven.org/maven2/com/lihaoyi/scalatags_3/0.8.2/scalatags_3-0.8.2.pom
--------------------------------------------
For additional information on library dependencies, see the docs at
https://mill-build.com/mill/Library_Dependencies.html
```

Update example `build.sc` with current library versions

---

contrib/bintray/src/mill/contrib/bintray/BintrayPublisher.scala
contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
contrib/proguard/test/src/mill/contrib/proguard/ProguardTests.scala
contrib/versionfile/test/src/mill/contrib/versionfile/VersionFileModuleTests.scala
main/codesig/src/JvmModel.scala
main/codesig/src/ResolvedCalls.scala
main/codesig/test/cases/callgraph/realistic/3-par-merge-sort/src/Hello.scala
main/codesig/test/src/Util.scala
main/define/test/src/mill/define/ApplicativeTests.scala
main/define/test/src/mill/define/CacherTests.scala
main/eval/test/src/mill/eval/JavaCompileJarTests.scala
scalajslib/test/src/mill/scalajslib/SmallModulesForTests.scala
scalalib/test/src/mill/scalalib/CycleTests.scala

I'm not sure if some of those warnings were intentional.
If so, please let me know and I'll take them out of the PR.

Fix some warnings

---

build.sc

The bridges are already on Maven Central.
Pull Request: https://github.com/com-lihaoyi/mill/pull/3066

Add 2.13.13 and 2.12.19 to supported bridges list

---

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
bsp/worker/src/mill/bsp/worker/MillJvmBuildServer.scala
bsp/worker/src/mill/bsp/worker/MillScalaBuildServer.scala
build.sc

Implemented the new `JmvCompileClasspath` request as part of the JVM extension.
If the client reports to support the `JvmCompileClasspathReceiver` capability,
we also return an empty classpath from the `ScalacOptions` request.
Update bsp4j from 2.2.0-M1 to 2.2.0-M2
See:
* https://github.com/build-server-protocol/build-server-protocol/pull/650
* https://github.com/build-server-protocol/build-server-protocol/pull/656
* https://github.com/build-server-protocol/build-server-protocol/pull/657

BSP: Handle new `JvmCompileClasspath` request

---

contrib/scoverage/api/src/mill/contrib/scoverage/api/ScoverageReportWorkerApi.scala
contrib/scoverage/readme.adoc
contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala
contrib/scoverage/src/mill/contrib/scoverage/ScoverageReport.scala
contrib/scoverage/test/src/mill/contrib/scoverage/HelloWorldTests.scala
contrib/scoverage/worker/src/mill/contrib/scoverage/worker/ScoverageReportWorkerImpl.scala
contrib/scoverage/worker2/src/mill/contrib/scoverage/worker/ScoverageReportWorkerImpl.scala

To help the integration of Mill based projects in some CI/CD platforms like GitLab you have to support Cobertura XML-based coverage report.
This PR adds a new `ReportType` and its corresponding action to produce Cobertura XML-based coverage report.

Add support for Cobertura XML report task to help integration

---

build.sc
scalajslib/src/mill/scalajslib/ScalaJSModule.scala
scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala
scalajslib/worker-api/src/mill/scalajslib/worker/api/ScalaJSWorkerApi.scala
scalajslib/worker/1/src/mill/scalajslib/worker/ScalaJSWorkerImpl.scala

`minify` is a new feature released today by Scala.js https://www.scala-js.org/news/2024/03/19/announcing-scalajs-1.16.0
Pull Request: https://github.com/com-lihaoyi/mill/pull/3094

Support Scala.js minify via `scalaJSMinify: Target[String]`

---

docs/modules/ROOT/pages/Installation_IDE_Support.adoc

- Docs for Continuous cache invalidation when mill / metals target different JVMs #3057
- Rephrased and formatted paragraph

Docs for Continuous cache invalidation

---

contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala

This reverts PR https://github.com/com-lihaoyi/mill/pull/2989
Fix https://github.com/com-lihaoyi/mill/issues/3097

Scoverage inner module defaults to `skipIdea = outer.skipIdea`

---

contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala
example/misc/7-contrib-scoverage/build.sc
example/misc/7-contrib-scoverage/src/Foo.scala
example/misc/7-contrib-scoverage/test/src/FooTests.scala

I encountered an issue with the way scoverage plugin alters the dependency tree of the test module by changing its module dependency from the `outer` module to the `outer.scoverage` module.
This shadow modification of the dependency tree produces a side effect that impacts the IDEA configuration generation.
When the IDEA configuration generation resolves the dependencies instead of using the outer module as a dependency for the test project it depends on the `outer.scoverage` module which should not be generated as it does not exist factually but more virtually.
Instead of modifying the dependency tree at compile-time I change it at runtime by removing the `outer.localRunClasspath()` from the `test.runClasspath()` and appending, instead, the `outer.scoverage.localRunClasspath()`
This …

Isolate scoverage modules from their parent modules

---

contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala

The previous version the `ScoverageTests.runClasspath` was more modified and reorganized.
In this version, only the outer complied classes folder is replaced (in place) by the outer.scoverage complied classes folder.
An additional runtime dependency is also added: `org.scoverage::scalac-scoverage-runtime`.
All duplicated entries in the classpath are also removed.

Scoverage improve classpath override to the minimal

---

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala

- BSP: Add some docs and todos
- BSP: Avoid MatchError and also consider compileModuleDeps as deps
Fix: #3110

Improve internal BSP API and docs, fix a match error condition

---

example/src/mill/integration/ExampleTestSuite.scala

The idea is, that our example integration tests should finish after a short period of time. But sometimes then hang in CI, so we simply abort and retry them automatically, instaed of manually.
The hardcoded timeout of 5 minutes is just a guess. I want to see the CI results. Maybe, we can make it configurable per test suite.

Retry example integration tests that didn't finish after 5 minutes

---

mill

There is an issue in the build pipeline the following job is falling:
```
./mill --import ivy:io.chris-kipp::mill-github-dependency-graph::0.2.5 showNamed io.kipp.mill.github.dependency.graph.Graph/generate
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
0 5[7](https://github.com/com-lihaoyi/mill/actions/runs/8752465078/job/24020171634#step:5:8).3M    0 19288    0     0   9993      0  1:40:23  0:00:01  1:40:22  9993
94 57.3M   94 54.1M    0     0  22.1M      0  0:00:02  0:00:02 --:--:-- 22.1M
[10](https://github.com/com-lihaoyi/mill/actions/runs/8752465078/job/2402 …
```

Fix mill script for parameter starting with -i

---

build.sc
scalalib/src/mill/scalalib/TestModule.scala

fixes #2700
I am verifying with MUnit.

TestModule: Support generation of JUnit-compatible xml report

---

contrib/docker/src/mill/contrib/docker/DockerModule.scala

previously the docker build would re-run if the user had `pullBaseImage` set to true. now it always checks the remote repository for a new version of the base image, but only re-runs the build if the base image hash has changed

Use docker image hash to determine if build should rerun

---

build.sc

Beside the version bump, this release is binary compatible to 0.9.x for Scala 2.13.

Update os-lib from 0.9.3 to 0.10.0

---

build.sc
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

This PR updates Zinc to 1.10.0. We make use of a new `ConsistentFileAnalysisStore` which is used by zinc to store internal analysis data used for incremental compilation. The new store is faster and more reproducible.

Update zinc from 1.9.6 to 1.10.0, use improved analysis store

---

contrib/docker/readme.adoc
contrib/docker/src/mill/contrib/docker/DockerModule.scala

A very minor change to the contrib.docker plugin (and its docs).
Allows to build for other architectures - a use case that becomes more and more useful with ARM architectures becoming more relevant.
**Relevant docs:**
[docker buildx (Buildkit)](https://docs.docker.com/reference/cli/docker/buildx/build/#platform)

Add multi platform support to contrib.docker through docker buildx

---

scalajslib/src/mill/scalajslib/ScalaJSModule.scala
scalajslib/src/mill/scalajslib/api/ScalaJSApi.scala
scalalib/src/mill/scalalib/TestModule.scala
scalalib/test/src/mill/scalalib/TestRunnerTests.scala
scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala

Rework the JUnit XML reporting feature. After a couple of tests, the XML report output is not compliant with the "standard"
I try to make it more compliant without breaking the great first solution!
I took inspiration from the pseudo specification and SBT implementation.
One important point is that Maven and SBT are producing one output file per `<testsuite>` a.k.a. per test (spec...) class 
while this solution (original) is producing one `<testsuites>` output file for the entire module. The specification supports it. We should keep this approach.
In this PR:
* Follow the "specification" provided in https://github.com/testmoapp/junitxml
* Fix the failure/error reporting as there is not necessarily an exception and error message provided (optional)
* Call the junit report from `testLocal` …

Improve the support of JUnit XML report

---

idea/src/mill/idea/GenIdeaImpl.scala
integration/feature/gen-idea/repo/extended/idea/libraries/scala3_library_3_3_0_2_jar.xml
integration/feature/gen-idea/repo/extended/idea/libraries/scala_SDK_2_13_6.xml
integration/feature/gen-idea/repo/extended/idea/libraries/scala_SDK_3_0_2.xml
integration/feature/gen-idea/repo/extended/idea/libraries/scala_library_2_13_6_jar.xml
integration/feature/gen-idea/repo/extended/idea/mill_modules/helloworld.iml
integration/feature/gen-idea/repo/extended/idea/mill_modules/helloworld.subscala3.iml
integration/feature/gen-idea/repo/extended/idea/mill_modules/helloworld.test.iml
integration/feature/gen-idea/repo/extended/idea/mill_modules/mill-build.iml
integration/feature/gen-idea/repo/hello-idea/build.sc
integration/feature/gen-idea/repo/hello-idea/idea/libraries/scala3_library_3_3_3_1_jar.xml
integration/feature/gen-idea/repo/hello-idea/idea/libraries/scala_SDK_2_12_5.xml
integration/feature/gen-idea/repo/hello-idea/idea/libraries/scala_SDK_2_13_14.xml
integration/feature/gen-idea/repo/hello-idea/idea/libraries/scala_SDK_3_3_1.xml
integration/feature/gen-idea/repo/hello-idea/idea/libraries/scala_library_2_12_5_jar.xml
integration/feature/gen-idea/repo/hello-idea/idea/libraries/scala_library_2_13_14_jar.xml
integration/feature/gen-idea/repo/hello-idea/idea/mill_modules/helloidea.iml
integration/feature/gen-idea/repo/hello-idea/idea/mill_modules/helloidea.scala3.iml
integration/feature/gen-idea/repo/hello-idea/idea/mill_modules/helloidea.scala3.test.iml
integration/feature/gen-idea/repo/hello-idea/idea/mill_modules/helloidea.test.iml
integration/feature/gen-idea/repo/hello-idea/idea/mill_modules/mill-build.iml
integration/feature/gen-idea/repo/hello-idea/idea/modules.xml

Previously, we attached the compiler setup to the scala-library entry. This doen't work well for Scala 3 projects, since there multiple scala-library entries are present, one for Scala 2 and one for Scala 3. If the Scala 2 version comes first, IJ uses the wrong compiler setup.
This change splits the scala-library from the compiler setup. The compiler setup now becomes a dedicated synthetic `scala-SDK` library entry for each Scala module. The scala-library no longer has any special semantic and is just an ordinary jar. Only one scala-SDK entry is added to each Scala module resulting in a proper setup.
Fix https://github.com/com-lihaoyi/mill/issues/2867

GenIdea: Use synthetic scala-SDK entry for compiler setup

---

build.sc
docs/antora.yml
scalajslib/test/src/mill/scalajslib/OutputPatternsTests.scala
scalajslib/test/src/mill/scalajslib/SmallModulesForTests.scala
scalajslib/test/src/mill/scalajslib/SourceMapTests.scala
scalajslib/test/src/mill/scalajslib/TopLevelExportsTests.scala

semanticdb-scalac dropped support for Scala 2.13.10, so I bumped the Scala version for some tests.

Update semanticdb-scalac from 4.9.3 to 4.9.4

---

scalalib/src/mill/scalalib/TestModule.scala

There is a bug in the way the `testsuite` element is generated.
```
<testsuite name="MyTest" tests="4" failures="0" errors="0" skipped="0"
time="0.724">
timestamp=2024-05-21T18:57:25
...
</testsuite>
```
```
<testsuite name="MyTest" tests="4" failures="0" errors="0" skipped="0"
time="0.724" timestamp="2024-05-21T18:57:25">
...
</testsuite>
```
The `timestamp` attribute in not an attribute...

Fix timestamp attribute in junit xml report

---

.github/workflows/actions.yml
.github/workflows/run-mill-action.yml
build.sc

Fixed the build setup to build compiler brigdes. There were missing dependencies. I added all transitive dependencies of the source package to the compile classpath.
Also extended the CI setup to build essential compiler bridges with each CI run to detect any issues as early as possible.
Fix https://github.com/com-lihaoyi/mill/issues/2576

Fix compiler bridge build setup and build essential versions in CI

---

build.sc

Add comment to `scalaVersion`
Pull Request: https://github.com/com-lihaoyi/mill/pull/3166

Add Scala 2.13.14 to bridgeScalaVersions

---

build.sc
contrib/playlib/worker/src-shared/mill/playlib/worker/RouteCompilerWorkerBase.scala

Router compiler API changed slightly. To use the convenience constructor, I have to use the `new` keyword.

Update Play 3.0 version from 3.0.1 to 3.0.3

---

scalalib/src/mill/scalalib/TestModule.scala
scalalib/test/src/mill/scalalib/TestModuleTests.scala
scalalib/test/src/mill/scalalib/TestRunnerTests.scala

Add unit tests to the JUnit XML report generation.

Add unit tests to the JUnit xml report generation

---

contrib/sonatypecentral/readme.adoc

Class method name changes that were made in the process of approving https://github.com/com-lihaoyi/mill/pull/3130 left out corresponding documentation changes. This PR adjusts the documentation so that it reflects the final implementation.

Update documentation for Sonatype Central

---

runner/src/mill/runner/MillBuildRootModule.scala
scalalib/src/mill/scalalib/Lib.scala

This should fix issues where plugins bring in potentially incompatible or duplicate version of an already provided Mill dependency.
We override `resolveDeps` and exclude all provided mill artifacts. Direct dependency are not filtered out, only transitive onces. If exclusions turn out to be a problem in some setups, the protected `resolveDepsExclusions` target can be customized, e.g. by returning an empty set of exclusions.

Exclude mill provided dependencies in meta builds

---

scalalib/src/mill/scalalib/TestModule.scala
scalalib/test/src/mill/scalalib/TestRunnerTests.scala

Example usage:
```
> mill show __.discoverTestClasses
{
"foo.test.discoverTestClasses": [
"foo.tests.FooTests",
"foo.tests.FoobarTests"
]
"bar.test.discoverTestClasses": [
"foo.tests.BarTests"
]
}
```
Fix https://github.com/com-lihaoyi/mill/issues/3169

Add `TestModule.discoveredTestClasses` target to ease test inspection

---

scalajslib/worker/1/src/mill/scalajslib/worker/ScalaJSWorkerImpl.scala

For some reason logging with `scala.Console` doesn't work with the Scala.js linker in server-client mode, maybe it's related to some classloader issue. This works around the problem by using `System.out` instead, which works correctly.
Pull Request: https://github.com/com-lihaoyi/mill/pull/3196

Fix Scala.js toolchain logs in server-client mode

---

build.sc

Not sure when it ended up broken, but the github URL format doesn't match the URLs generated (missing a `/download/` segment), and `millVersion` is incorrectly providing the unstable path even for commits for which no unstable release was published

Fix download links in docs

---

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala

Fixes #1918.
Pull Request: https://github.com/com-lihaoyi/mill/pull/3211

Fix classpath regression in Bloop export #1918

---

build.sc
contrib/bloop/src/mill/contrib/bloop/Bloop.scala
contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
integration/feature/bloop/repo/build.sc
integration/feature/bloop/test/src/BloopTests.scala

After Mill `0.11` `mill-contrib-bloop` stopped supporting the build module.
Now `BloopImpl` gets a sequence of `Evaluator`s and gets all modules for all the evaluators in `Evaluator.allBootstrapEvaluators`, so it supports the build module again.
Pull Request: https://github.com/com-lihaoyi/mill/pull/3208

Support `build.sc` in Bloop

---

build.sc
integration/feature/gen-idea/repo/hello-idea/idea/libraries/scala_SDK_2_13_14.xml
integration/feature/gen-idea/test/src/GenIdeaUtils.scala
integration/feature/plugin-classpath/repo/build.sc
integration/feature/plugin-classpath/test/src/MillPluginClasspathTest.scala
integration/src/mill/integration/IntegrationTestSuite.scala

Also refer to transitive modules coordinates in the `BuildInfo.millEmbededDeps` data field.
Added an integration test to make sure it's effectively excluding transitive Mill dependencies.
Fix https://github.com/com-lihaoyi/mill/issues/3207

Improve Mill plugin classpath exclusions

---

scalajslib/worker/1/src/mill/scalajslib/worker/ScalaJSWorkerImpl.scala

Taken from https://github.com/com-lihaoyi/mill/issues/601#issuecomment-627786914

Better exception message when JS test framework runner is not found

---

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3100, which for some reason is happening frequently enough on my laptop to really hamper my productivity. With a version of Mill built from this PR, the problem seems to have gone away.
We don't really have a strong concurrency model for what's meant to happen when multiple Mill commands are being evaluated at once, and trying to come up with one is a complex task that I don't think is worth the effort. Bazel works fine with a coarse-grained lock even for huge codebases and organizations, so this should do for Mill for now.
Pull request: https://github.com/com-lihaoyi/mill/pull/3243

Add coarse grained lock around BSP requests to avoid deadlocks

---

docs/modules/ROOT/pages/Intro_to_Mill_for_Java.adoc
docs/modules/ROOT/pages/Intro_to_Mill_for_Scala.adoc
docs/modules/ROOT/partials/Intro_to_Mill_Header.adoc

Removes reference to Scala from the Intro to Mill for Java page

Tweak Java documentation

---

build.sc
integration/feature/subprocess-stdout/repo/build.sc
integration/feature/subprocess-stdout/repo/mill
integration/feature/subprocess-stdout/test/src/SubprocessStdoutTests.scala
integration/src/mill/integration/IntegrationTestSuite.scala
main/api/src/mill/api/SystemStreams.scala
main/client/src/mill/main/client/InputPumper.java
main/client/src/mill/main/client/MillClientMain.java
main/util/src/mill/util/Jvm.scala
runner/src/mill/runner/MillServerMain.scala
scalajslib/worker/1/src/mill/scalajslib/worker/ScalaJSWorkerImpl.scala

Depends on https://github.com/com-lihaoyi/os-lib/pull/283
This moves the subprocess stream handling logic out of `Jvm.spawnSubprocess` and makes it apply to all `os.proc` invocations, greatly reducing the room for error. With this, `Jvm.spawnSubprocess` becomes a very thin wrapper around `os.proc.spawn`. We also rely directly on OS-Lib's own pumper threads to pump to our destination, rather than having them pump into in-memory buffers and then spawning our own pumper threads to pump from those buffers to the destination
I spent some time looking into how to do the stdout/err handling at the process level, but couldn't find any reasonable mechanism to do so that allows us to preserve the ordering of the stdout/stderr. This is the original motivation to squishing it into one stream via …

Automatically pump `os.proc` streams when `SystemStreams` are redirected

---

build.sc
docs/modules/ROOT/pages/Mill_Design_Principles.adoc
example/basic/2-custom-build-logic/build.sc
example/cross/1-simple/build.sc
example/cross/3-outside-dependency/build.sc
example/cross/4-cross-dependencies/build.sc
example/cross/5-multiple-cross-axes/build.sc
example/tasks/1-task-graph/build.sc
example/tasks/2-primary-tasks/build.sc
example/tasks/7-modules/build.sc
example/tasks/8-diy-java-modules/build.sc

Many of these diagrams were already present in various blog posts, so I just copied those over. Others I wrote from scratch, which using graphviz isnt too hard

Integrate graphviz into Mill docs, sprinkle diagrams throughout the docsite

---

build.sc
docs/antora.yml

Fixes https://github.com/com-lihaoyi/mill/issues/2455
They can now be added to `val docTags`, and will appear as previous versions on the docsite
To support this mostly transparently, I checkout the relevant versions of com-lihaoyi/mill as part of `githubPages` and run `./mill` to build their docs. This saves us the hassle of storing the materialized `.adoc` files somewhere and worrying about them getting stale/corrupted/accessible/etc.
The versions listed in `docs/antora.yml` are incorrect for some of the old tags like 0.11.10. We probably should generate them in `build.sc` to avoid duplication.
If we intend to support ongoing development of old branches, we probably should use moving `0.11.x` branches rather than fixed `0.11.x` tags for the doc-site, so that improvements to the …

Wire up post-0.11.x old docsites into Antora

---

scalajslib/src/mill/scalajslib/ScalaJSModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3324
Pull Request: https://github.com/com-lihaoyi/mill/pull/3327

Add error log when passing args to `run` on `ScalaJSModule`

---

.github/workflows/actions.yml
.github/workflows/run-mill-action.yml

- Stop running Scala.js, Native, and contrib tests across both JVM versions
- Cut down windows tests to avoid running the same tests against both JVM versions; rather run each set of tests once but pick the version arbitrarily so both JVM versions get some coverage
- We don't need `{__.publishLocal,dev.assembly,__.compile}` on windows because the `integration._.{local,fork,server}` tests should exercise those code paths
- Cut down job timeout from 90min to 60min. Most jobs finish in <25min right now, so 60min should be plenty of time and give faster feedback if jobs get stuck
For the various test suites, every test is still run on both Java8 and Java 17, and on Windows or Linux: e.g. "Java8/Windows + Java17/Linux" or "Java17/Windows + Java8/Linux". Not as good as full coverage of all …

Trim down CI matrix further

---

runner/src/mill/runner/MillMain.scala

The bug stems from the fact that a `PipedInputStream` is passed to `MillMain.main0` where `DummyInputStream` used to be. This PR fixes the bug by using a `PipedInputStream` instead of a `DummyInputStream` on the check that leads to the warning being printed.
Fixes #2869.

Fix the warning not being printed when -i/--interactive/--no-server/--bsp are not the first argument

---

build.sc

With a stable version shown by default, users won't see newly added but unreleased features.
User interested in a pre-release (e.g. the latest main snapshot build) can select that version manually, and are able to test the latest changes.
With this change in effect, we can request proper initial documentation for feature additions. This not only improves the experience for early adaptors but also the understanding of the to-be added feature while in the review process.

Doc: Default to latest stable version

---

idea/src/mill/idea/GenIdeaImpl.scala
integration/ide/gen-idea/repo/hello-idea/build.sc
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/modulea.iml
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/moduleb.iml
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/modulec.iml
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/moduled.iml
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/modulee.iml
integration/ide/gen-idea/repo/hello-idea/idea/modules.xml
scalalib/api/src/mill/scalalib/api/ZincWorkerUtil.scala
scalalib/src/mill/scalalib/internal/ModuleUtils.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Since IDEA 2024.2, module dependencies in the `.iml` files are no longer interpreted transitively.
Therefore, we need to unroll all transitive module dependencies when generating the project files.
Fix https://github.com/com-lihaoyi/mill/issues/3354

GenIdea: unroll module dependencies

---

idea/src/mill/idea/GenIdeaImpl.scala
integration/ide/gen-idea/repo/hello-idea/build.sc
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/modulea.iml
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/moduleb.iml
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/modulec.iml
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/moduled.iml
integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/modulee.iml
integration/ide/gen-idea/repo/hello-idea/idea/modules.xml
scalalib/api/src/mill/scalalib/api/ZincWorkerUtil.scala
scalalib/src/mill/scalalib/internal/ModuleUtils.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Since IDEA 2024.2, module dependencies in the `.iml` files are no longer
interpreted transitively.
Therefore, we need to unroll all transitive module dependencies when
generating the project files.
Fix https://github.com/com-lihaoyi/mill/issues/3354
Original Pull request: https://github.com/com-lihaoyi/mill/pull/3355

GenIdea: unroll module dependencies (backport of #3355)

---

main/api/src/mill/api/SystemStreams.scala

Sometimes when you run tests in client/server mode and interrupt the run, it leaves the server stuck at the stack trace below. Eventually, `jps` shows a bunch of `MillServerMain` processes that seem to be stuck
The problem seems to go away when using unwrapped streams. I suspect it's due to https://github.com/com-lihaoyi/os-lib/issues/28 which means that the `InputPumper` calling `.available()` never gets `-1` to indicate the stream is complete, but instead keeps getting `0` telling it to try again.
The failure mode is nondeterministic, but running `./mill main.resolve.test`, entering garbage into the terminal, and `Ctrl-C` to cancel seems to reproduce it reasonably well in a few minutes. And with this PR, I haven't been able to reproduce it: no matter how I fiddle with `./mill …

Use unwrapped underlying subprocess input streams when pumping

---

integration/invalidation/multi-level-editing/test/src/MultiLevelBuildTests.scala
main/client/src/mill/main/client/MillClientMain.java
main/client/src/mill/main/client/OutFiles.java
main/client/src/mill/main/client/ServerFiles.java
main/client/src/mill/main/client/lock/Locks.java
main/eval/src/mill/eval/EvaluatorCore.scala
runner/src/mill/runner/MillBuildBootstrap.scala
runner/src/mill/runner/MillServerMain.scala

This makes the documentation somewhat discoverable: both grepping the codebase would pull it up, as would jump-to-definition from any of the use sites in the code (which is why this is better than having it in some readme file or docsite page). We could also link to it from the docs to make it more discoverable.
Pull request: https://github.com/com-lihaoyi/mill/pull/3361

Move inline file paths to static helper methods so we can describe them and document them

---

main/client/src/mill/main/client/lock/FileLock.java
main/client/src/mill/main/client/lock/FileLocked.java
main/client/src/mill/main/client/lock/FileTryLocked.java
main/client/src/mill/main/client/lock/Locks.java
main/client/src/mill/main/client/lock/MemoryLock.java
main/client/src/mill/main/client/lock/MemoryLocked.java
main/client/src/mill/main/client/lock/MemoryTryLocked.java
main/client/src/mill/main/client/lock/TryLocked.java

follow up for https://github.com/com-lihaoyi/mill/pull/3363
* Remove the `public`-ness from `FileTryLocked` and `MemoryTryLocked`. They do not need to be public, as people should only access them through the `TryLocked` interface
* Add `final` to the fields that do not need to be mutated (i.e. all of them)
* Make `Locks` `final`, and replace weird anonymous class initializers with a proper constructor

Tighten up `mill/main/client/lock` files

---

runner/src/mill/runner/MillBuildRootModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3371
The direct problem is that we are generating code with resolved type aliases, resulting in the `JavaTests` aliases being resolved to deprecated `JavaModuleTests` traits. However, in general generated code should probably not display warnings at all, so better to just slap `@nowarn` on the whole chunk rather than trying to fix the immediate alias resolution problem

Avoid spurious deprecation warnings in generated code

---

example/javamodule/5-resources/foo/test/src/FooTests.java
main/api/src/mill/api/WorkspaceRoot.scala
main/client/src/mill/main/client/EnvVars.java
main/eval/src/mill/eval/EvaluatorCore.scala
main/server/test/src/mill/main/server/ClientServerTests.scala
main/test/src/mill/util/TestUtil.scala
main/testkit/src/mill/testkit/MillTestkit.scala
main/util/src/mill/util/Util.scala
runner/client/src/mill/runner/client/MillProcessLauncher.java
scalalib/src/mill/scalalib/Lib.scala
scalalib/src/mill/scalalib/RunModule.scala
scalalib/src/mill/scalalib/TestModule.scala

Also got rid of `MILL_TEST_DEST_FOLDER` since https://github.com/com-lihaoyi/mill/pull/3347 makes `os.pwd` sufficient.
There are also a few other `MILL_*` things that look like env vars but are actually system properties, so I left them out of this PR

Consolidate and document Mill environment variables

---

main/eval/src/mill/eval/EvaluatorCore.scala
main/eval/src/mill/eval/GroupEvaluator.scala
main/eval/src/mill/eval/JsonArrayLogger.scala
runner/src/mill/runner/Watching.scala

Pre-compute a bunch of values we use to compute the code signature of enclosing objects of task methods. 
Cuts down the time taken of a hot no-op `./mill __.compile` (i.e. pure overhead) on the Mill repo from ~4000ms to ~2000ms
Benchmarked were run ad hoc on my laptop by making the `-w` flag loop immediately rather than waiting
```diff
diff --git a/runner/src/mill/runner/Watching.scala b/runner/src/mill/runner/Watching.scala
index 08e8df5e3f..e8f41a3cc5 100644
--- a/runner/src/mill/runner/Watching.scala
+++ b/runner/src/mill/runner/Watching.scala
@@ -23,6 +23,7 @@ object Watching {
evaluate: Option[T] => Result[T]
): (Boolean, T) = {
var prevState: Option[T] = None
+    var previous = System.currentTimeMillis()
while (true) {
val Result(watchables, errorOpt, result) = evaluate(prevState) …
```

Optimize Mill evaluation logic

---

main/eval/src/mill/eval/Evaluator.scala

The new `.getOrThrow` API allows to short-circuit the result of a `Result`. This prints a correct error message when `Result.Failure` is thrown in a method returning `T`, instead of returned via a method returning `Result[T]`.
Pull Request: https://github.com/com-lihaoyi/mill/pull/3391

Print pretty error message when Result.Failure is thrown

---

main/eval/src/mill/eval/Evaluator.scala

The new `.getOrThrow` API allows to short-circuit the result of a `Result`. This prints a correct error message when `Result.Failure` is thrown in a method returning `T`, instead of returned via a method returning `Result[T]`.
Backport of pull request: https://github.com/com-lihaoyi/mill/pull/3391
Pull Request: https://github.com/com-lihaoyi/mill/pull/3393

Print pretty error message when Result.Failure is thrown (Backport #3391)

---

runner/src/mill/runner/MillBuildRootModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3371
The direct problem is that we are generating code with resolved type aliases, resulting in the `JavaTests` aliases being resolved to deprecated `JavaModuleTests` traits. However, in general generated code should probably not display warnings at all, so better to just slap `@nowarn` on the whole chunk rather than trying to fix the immediate alias resolution problem
Pull Request: https://github.com/com-lihaoyi/mill/pull/3400

Avoid spurious deprecation warnings in generated code (Backport #3379)

---

runner/client/src/mill/runner/client/MillProcessLauncher.java

Fix https://github.com/com-lihaoyi/mill/issues/3395

Add a unique integer to the sandbox dir of `mill --no-server`

---

ci/release-maven.sh

https://github.com/com-lihaoyi/mill/commit/a293b46e made use a locally built mill to release to sonatype, since the previous versions did not work with the latest sonatype API. But it neglected to run `ci/patch-mill-bootstrap.sh`, resulting in failures like https://github.com/com-lihaoyi/mill/actions/runs/10472316798/job/29046150876 ever since https://github.com/com-lihaoyi/mill/commit/33fa9530f165a5e5e1d367a5b51b291c2bb15d1f landed. This reverts back to the original usage of committed `./mill` script for publishing, since we've now re-bootstrapped on a new enough version that publishing works without needing to build a local version

Fix sonatype release

---

docs/modules/ROOT/pages/Java_Build_Examples.adoc

The target audience of this documentation section are Java developers. So, they probably do not care about the Scala/SBT. 
Further, it isn't actively used in this section of the docs

Remove Reference to Scala Specific Modules in Java Section

---

contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
contrib/docker/src/mill/contrib/docker/DockerModule.scala
contrib/docker/test/src/mill/contrib/docker/DockerModuleTest.scala
scalalib/test/src/mill/scalalib/TestRunnerTests.scala

`sys.props("doesntexist")` returns `null` instead of throwing like I expected, so this change ensures any misconfiguration resulting in missing environment variables throws

Put back ??? in sys.props calls

---

build.sc
mill-build/build.sc

Since we now have a meta build, we should manage all plugins in one place.

Move build dependencies into meta build

---

main/define/src/mill/define/Discover.scala
main/src/mill/main/RootModule.scala
runner/src/mill/runner/MillBuildRootModule.scala

Move a bunch of logic into helper methods in order to minimize the complexity of the codegen
This PR shouldn't have any runtime impact, just a bit of internal tidying up

Clean up MillBuildRootModule codegen

---

main/eval/src/mill/eval/Evaluator.scala
main/eval/src/mill/eval/EvaluatorCore.scala
main/eval/src/mill/eval/EvaluatorImpl.scala
main/src/mill/main/RunScript.scala

Introduced a new `serialCommandExec` parameter in `Evaluator.evaluate` and added required binary compatibility shims.
Fix https://github.com/com-lihaoyi/mill/issues/3359

Make serial command execution at the evaluation end optional

---

example/depth/tasks/2-primary-tasks/build.sc
example/depth/tasks/3-anonymous-tasks/build.sc
integration/failure/module-init-error/test/src/ModuleInitErrorTests.scala
main/eval/src/mill/eval/Evaluator.scala
main/eval/src/mill/eval/EvaluatorImpl.scala
main/resolve/src/mill/resolve/Resolve.scala
main/resolve/test/src/mill/main/ResolveTests.scala
main/src/mill/main/MainModule.scala
main/src/mill/main/RunScript.scala
main/test/src/mill/util/TestGraphs.scala
readme.adoc
runner/src/mill/runner/MillBuildBootstrap.scala
runner/src/mill/runner/MillCliConfig.scala
runner/src/mill/runner/MillMain.scala
testkit/src/mill/testkit/UnitTester.scala

This aligns the semantics with MainArgs library defaults. Previously we grandfathered in the "positional by default" behavior because Mill pre-dates mainargs, with original behavior inherited from Ammonite. But most CLIs do not allow keyword args to be naively replaced by positional args, and MainArgs thus chose to have such behavior as opt-in. Mill should follow suite
Added a flag `--allow-positional-command-args` to fall back to the old behavior, and covered this behavior with example tests, docs, and updated the changelog.
This is a binary-compatible but semantically-incompatible change, so it should go into 0.12.0. It's a pretty painful breaking change, but it's definitely the right thing to do long term, so better to get it over with. People can also add …

Make Mill commands require named CLI parameters by default

---

mill-build/build.sc

Bump Mill-Scalafix to 0.4.1

---

scalajslib/src/mill/scalajslib/ScalaJSModule.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/RunModule.scala
scalalib/src/mill/scalalib/scalafmt/ScalafmtModule.scala

These are commands that probably do not expect named params that I found in a cursory audit, that would otherwise be broken by https://github.com/com-lihaoyi/mill/pull/3431. We can annotate others as we find them

Mark `reformatAll`/`checkReformatAll`/`runMain` arguments as positional

---

integration/failure/root-subfolder-module-collision/test/src/RootSubfolderModuleCollisionTests.scala
integration/failure/subfolder-missing-build-prefix/repo/build.mill
integration/failure/subfolder-missing-build-prefix/repo/sub/package.mill
integration/failure/subfolder-missing-build-prefix/test/src/SubfolderMissingBuildPrefix.scala
integration/ide/bsp-modules/repo/build.mill
integration/invalidation/invalidation/repo/build.mill
runner/src/mill/runner/CodeGen.scala

This ensures that IDEs can trace the execution since we pretend that everything lives in `package build`. Previously, if the `build.` prefix is elided, we get code that works but the IDE does the wrong thing. Now that code is a compile error and you need to use `build.` which the IDE can understand

Be stricter about requiring `build.` prefix for cross-`package.mill`-file references

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/Bundled_Libraries.adoc

Since that's all there is on that page

Rename `External Reference` to `Bundled Libraries`

---

testkit/src/mill/testkit/IntegrationTesterBase.scala

Since https://github.com/com-lihaoyi/mill/pull/3347 made all test suites run with `pwd` in the test's `.dest` folder by default, we are already guaranteed that different concurrent test suites will not collide, so we do not need the `out/blah/blah` segments to avoid conflicts

Remove unnecessary subfolder wrappers for integration tests

---

example/javalib/builds/9-realistic/build.mill

Fix doc typo in JavaModule realistic

---

.github/workflows/actions.yml
.github/workflows/run-mill-action.yml
example/javalib/web/5-todo-micronaut/build.mill
example/javalib/web/5-todo-micronaut/src/main/resources/application.properties
main/client/src/mill/main/client/ProxyStream.java
main/util/src/mill/util/CoursierSupport.scala
testkit/src/mill/testkit/ExampleTester.scala

* Remove `-j1` parallelism limit on windows, enable parallelism for windows tests by changing `.test` to `.testCached`
* Clean up coursier retry logic and add more cases
* Two of our example tests were conflicting on port `8088`, moved one of them to `8089`

Parallelize windows CI

---

.github/workflows/publish-artifacts.yml
.github/workflows/publish-docs.yml
.github/workflows/run-tests.yml

By the time things passed tests and land in master, they have already passed tests twice (once on PR, once in master). So no need to run tests a third time when we push a tag or manually trigger a release

Decouple publish/releasing from main CI

---

.github/workflows/dependency-graph.yml
.github/workflows/publish-artifacts.yml
.github/workflows/publish-docs.yml
.github/workflows/run-tests.yml
ci/release-bridge-maven.sh

- Only trigger `Publish Artifacts` on tags and explicit `workflow_dispatch`
- Remove redundant job conditionals
- Don't both running tests on tags since they already run on the commits land in the branch containing the tag

More cleanups for github actions

---

build.mill
contrib/errorprone/readme.adoc
contrib/errorprone/src/mill/contrib/errorprone/ErrorProneModule.scala
contrib/errorprone/test/resources/simple/src/ShortSet.java
contrib/errorprone/test/src/mill/contrib/errorprone/ErrorProneTests.scala
contrib/package.mill
docs/modules/ROOT/pages/Java_Module_Config.adoc
example/javalib/module/14-error-prone/build.mill
example/javalib/module/14-error-prone/src/example/ShortSet.java
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
testkit/src/mill/testkit/ExampleTester.scala

This adds a new `ErrorProne` plugin to the `contrib` section of Mill.
It provides the `ErrorProneModule` `trait`, which can be mixed into `JavaModule`s. Derived modules like `ScalaModule` are also supported, as long as they support the `javacOptions` task to configure the Java compiler.
We use the [Error Prone](https://errorprone.info/index) project as a compiler plugin. Although this is a simple javac compiler plugin, it's usage isn't trivial. Fetching the correct classpath and supplying options can be tricky, since they need to be provided in a special form. Also using with JVMs starting from version 16 requires special options handling due to the new more restrictive module classpath. This plugin is handling all of the known issues and make its use easy for the user.
Additional …

Add ErrorProne plugin

---

.github/workflows/run-tests.yml
scalalib/src/mill/scalalib/Dep.scala
scalalib/test/src/mill/scalalib/ResolveDepsTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3417
We do a best-effort approach where we try to reverse the `Dep.parse` logic, and at the end do a `==` check to see if the round tripped `Dep` is identical to the original. There's some overhead with the round trip comparison - effectively for each write-read of a `Dep` we add an additional `read` - but this isn't a hot code path so it shouldn't be a big deal. In exchange we get a pretty good guarantee of correctness that later on when someone round-trips the same `Dep` off of disk, they get the same result. We do the same for `BoundDep` and re-use most of the `Dep` logic
The sophistication of our `def parse` and `def unparse` logic can be extended over time, but this should work well for 99% of dependencies which are simple without …

Shorten `Dep` serialization format in common cases

---

docs/modules/ROOT/pages/Library_Dependencies.adoc
scalalib/src/mill/scalalib/Dep.scala
scalalib/test/src/mill/scalalib/ResolveDepsTests.scala

You can give exclusions with `;exclude=org:name` or `;exclude=org:*` or `;exclude=*:name`.

Support `exclude` attribute in `Dep` parser

---

build.mill
main/util/src/mill/util/CoursierSupport.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3465

Update coursier to 2.1.11, disable coursier retries

---

contrib/checkstyle/readme.adoc
contrib/checkstyle/src/mill/contrib/checkstyle/CheckstyleArgs.scala
contrib/checkstyle/src/mill/contrib/checkstyle/CheckstyleModule.scala
contrib/checkstyle/src/mill/contrib/checkstyle/CheckstyleXsltModule.scala
contrib/checkstyle/src/mill/contrib/checkstyle/CheckstyleXsltReport.scala
contrib/checkstyle/test/resources/compatible-java/checkstyle-config.xml
contrib/checkstyle/test/resources/compatible-java/src/com/etsy/sbt/TestClass.java
contrib/checkstyle/test/resources/compatible-scala/checkstyle-config.xml
contrib/checkstyle/test/resources/compatible-scala/checkstyle-xslt/html/noframes.xml
contrib/checkstyle/test/resources/compatible-scala/src/com/etsy/sbt/TestClass.java
contrib/checkstyle/test/resources/compatible-scala/src/com/etsy/sbt/TestClass.scala
contrib/checkstyle/test/resources/non-compatible/checkstyle-config.xml
contrib/checkstyle/test/resources/non-compatible/checkstyle-xslt/htm/noframes-copy.xml
contrib/checkstyle/test/resources/non-compatible/checkstyle-xslt/htm/noframes.xml
contrib/checkstyle/test/resources/non-compatible/checkstyle-xslt/htm/readme.txt
contrib/checkstyle/test/resources/non-compatible/checkstyle-xslt/html/noframes-copy.xml
contrib/checkstyle/test/resources/non-compatible/checkstyle-xslt/html/noframes.xml
contrib/checkstyle/test/resources/non-compatible/src/blocks/ArrayTrailingComma.java
contrib/checkstyle/test/resources/non-compatible/src/coding/EmptyStatement.java
contrib/checkstyle/test/src/mill/contrib/checkstyle/CheckstyleModuleTest.scala
contrib/checkstyle/test/src/mill/contrib/checkstyle/CheckstyleXsltModuleTest.scala
contrib/package.mill
main/util/src/mill/util/Jvm.scala

Added plugins
- `CheckstyleModule`, fully compliant with [Checkstyle CLI](https://checkstyle.org/cmdline.html#Command_line_usage)
- `CheckstyleXsltModule`, generates reports by applying XSL Transformations on a Checkstyle output report
Resolves #3332.

Added plugins to run Checkstyle and generate reports

---

docs/modules/ROOT/pages/Mill_Sandboxing.adoc
example/depth/sandbox/2-test/bar/test/src/bar/BarTests.java
example/depth/sandbox/2-test/foo/test/src/foo/FooTests.java
example/depth/sandbox/3-breaking/build.mill
example/depth/sandbox/3-breaking/foo/src/foo/Foo.java
example/depth/sandbox/3-breaking/foo/test/src/foo/FooTests.java
example/javalib/module/5-resources/foo/test/src/FooTests.java
main/client/src/mill/main/client/EnvVars.java
scalalib/backgroundwrapper/src/mill/scalalib/backgroundwrapper/BackgroundWrapper.java
scalalib/src/mill/scalalib/TestModule.scala
scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3510
I decided to try and standardize on a `MILL_WORKSPACE_ROOT` environment variable that is present in both build files and tests, to try and provide a seamless experience to our users. 
`mill.api.WorkspaceRoot.workspaceRoot` and `T.workspace` are still there but perhaps we can get rid of them in 0.13.0 in favor of using `MILL_WORKSPACE_ROOT` everywhere. After all, accessing the workspace root should be inconvenient to discourage people from doing it unnecessarily, so providing short concise helper methods to do so may even be a net negative

Add docs for how to break out of Mill sandbox folder

---

contrib/playlib/src/mill/playlib/PlayModule.scala
contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala
main/define/src/mill/define/Task.scala
scalajslib/src/mill/scalajslib/ScalaJSModule.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/RunModule.scala
scalalib/test/src/mill/scalalib/PublishModuleTests.scala
scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala

`T.command` currently has two overloads, one accepting a `Result` (like most of the other task factories, `T`, `T.input`, `T.task` and so on) and one accepting a `Task`. Because of the second version, command definitions like the following don't do what the user thinks they do, although they seem to work.
```scala
override def publishLocal(localIvyRepo: String): Command[Unit] = T.command {
super.publishLocal(localIvyRepo)
}
```
Instead of creating a new command that depends on another command (the `super`-version) and returns just the result, it returns the `super`-command as-is.
The correct version is:
```scala
override def publishLocal(localIvyRepo: String): Command[Unit] = T.command {
super.publishLocal(localIvyRepo)()
}
```
```diff
override def publishLocal(localIvyRepo: String): …
```

Deprecated `T.command(task)` for removal in Mill 0.13

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.adoc
docs/supplemental-ui/partials/header-content.hbs
example/scalalib/basic/4-builtin-commands/build.mill

This replaces a direct link to the discord channel with an invite to that channel. The invite does not time out. It has the advantage to easily let new users to register to discord.
Fix https://github.com/com-lihaoyi/mill/issues/3541

Fix discord link to be inviting 

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/Java_Builtin_Commands.adoc
docs/modules/ROOT/pages/Kotlin_Builtin_Commands.adoc
docs/modules/ROOT/pages/Kotlin_Installation_IDE_Support.adoc
docs/modules/ROOT/pages/Kotlin_Intro_to_Mill.adoc
docs/modules/ROOT/pages/Scala_Builtin_Commands.adoc
docs/modules/ROOT/partials/Intro_Maven_Gradle_Comparison.adoc
example/package.mill
example/scalalib/basic/4-builtin-commands/build.mill

* Added `Kotlin_Intro_to_Mill.adoc`, `Kotlin_Installation_IDE_Support.adoc`, `Kotlin_Builtin_Commands.adoc` pages
* Fixed an issue with inherited example adoc pages not rendering correctly since https://github.com/com-lihaoyi/mill/pull/3398

Integrate kotlin example into docs

---

docs/modules/ROOT/pages/Case_Study_Mill_vs_Gradle.adoc
example/javalib/testing/3-integration-suite/build.mill
example/javalib/web/4-hello-micronaut/build.mill

Fixed some doc typos in the Java section,
- Maven/Gradle confusion
- Missing closing markdiwn quote
- Dangling sentence
I also rephrased a section on java integration test, emphasizing more on the mill way to do it rather than the usage of Junit5/4, i can drop the commit if it is not suited

Fix some doc typos + slight doc proposal on java integration test section

---

main/src/mill/main/RootModule.scala

IntelliJ/VSCode can't see the generated code so they think that these things are missing, but they're not. Rather than changing IntelliJ/VSCode, for now we just provide dummy definitions that get overriden by the codegen but are enough to make the IDEs happy
Before, we see errors in `extends RootModule` because of the missing implicit `RootModule.Info`, and errors on the `object` as a whole because of the missing `def millDiscover`:
After, those two errors are gone, although the "need override keyword" errors remain:
Eventually we may have dedicated IDE support, but for now this hacks around one of the more visible IDE issues

Provided dummy `def millDiscover` and implicit `RootModule.Info` to make IDEs not display errors

---

scalalib/test/resources/testrunner/scalatest/src/ScalaTestSpec.scala
scalalib/test/src/mill/scalalib/TestRunnerTests.scala
testrunner/src/mill/testrunner/TestRunnerUtils.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3440
The problem is mill defines all the test tasks with `explicitlySpecified` to be `true`. This makes all the tests always be included. [Related code](https://github.com/scalatest/scalatest/blob/main/jvm/core/src/main/scala/org/scalatest/tools/Framework.scala#L267) in Scalatest.

Fix ScalaTest testOnly include option

---

.scalafmt.conf
build.mill

We no longer need to support Java 8, hence we can bump this one.

Update scalafmt from 3.7.15 to 3.8.3

---

docs/modules/ROOT/pages/Thirdparty_Plugins.adoc

Closes https://github.com/sake92/squery/issues/9

Add squery mill plugin

---

contrib/jmh/src/mill/contrib/jmh/JmhModule.scala

I believe this to be  a solution for #3576 . However, I'm unclear how I could effectively test it. Feedback welcomed.

Forward javacOptions to JMH

---

example/thirdparty/mockito/build.mill

It's known to be flaky upstream, no sense suffering the flakes ourselves when there's nothing we can do https://github.com/mockito/mockito/blob/1e337ed703ce2b78ce9ea40ff8b8c645f8219cf2/src/test/java/org/mockitousage/debugging/StubbingLookupListenerCallbackTest.java#L200-L201

Disable flaky mockito unit test

---

example/kotlinlib/publishing/2-publish-module/build.mill
example/kotlinlib/publishing/2-publish-module/foo/src/foo/Foo.kt
example/kotlinlib/testing/1-test-suite/bar/src/bar/Bar.kt
example/kotlinlib/testing/1-test-suite/bar/test/src/bar/BarTests.kt
example/kotlinlib/testing/1-test-suite/build.mill
example/kotlinlib/testing/1-test-suite/foo/src/foo/Foo.kt
example/kotlinlib/testing/1-test-suite/foo/test/src/foo/FooTests.kt
example/kotlinlib/testing/2-test-deps/baz/src/baz/Baz.kt
example/kotlinlib/testing/2-test-deps/baz/test/src/baz/BazTestUtils.kt
example/kotlinlib/testing/2-test-deps/baz/test/src/baz/BazTests.kt
example/kotlinlib/testing/2-test-deps/build.mill
example/kotlinlib/testing/2-test-deps/qux/src/qux/Qux.kt
example/kotlinlib/testing/2-test-deps/qux/test/src/qux/QuxTests.kt
example/kotlinlib/testing/3-integration-suite/build.mill
example/kotlinlib/testing/3-integration-suite/qux/integration/src/qux/QuxIntegrationTests.kt
example/kotlinlib/testing/3-integration-suite/qux/src/qux/Qux.kt
example/kotlinlib/testing/3-integration-suite/qux/test/src/qux/QuxTests.kt
example/package.mill

Another addition for #3451: it adds `publishing` and `testing` examples for Kotlin.
The only thing that needs to be mentioned is test filtering in Kotest: it doesn't have `package.class.method` format to do the filtering, instead it is using `specs` + `classes` parameters (see [here](https://kotest.io/docs/framework/conditional/conditional-tests-with-gradle.html)).
Also `mockito-kotlin` requires JVM bytecode target to be 11.

Add Kotlin publishing and testing examples

---

scalalib/src/mill/scalalib/ScalaModule.scala

while developing Scala 3 port, when using metals as the BSP server then semanticdb files are generated in the same folder as the source file.
With this change, and setting the bootstrapped mill version for BSP server, metals no longer puts semanticdb in the same directory, but instead in `out/../semanticdbData.dest/classes/META-INF/semanticdb/...`

add -sourceroot flag when generating semanticdb with scala 3

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.adoc
docs/supplemental-ui/partials/header-content.hbs
example/scalalib/basic/4-builtin-commands/build.mill

Replaced with a never expiring link, again.
Fix https://github.com/com-lihaoyi/mill/issues/3590

Update Discord Invite link

---

integration/feature/docannotations/resources/build.mill
integration/feature/docannotations/src/DocAnnotationsTests.scala
main/eval/src/mill/eval/GroupEvaluator.scala
main/resolve/src/mill/resolve/Resolve.scala
main/resolve/src/mill/resolve/ResolveCore.scala
main/src/mill/main/RunScript.scala
main/test/src/mill/main/MainModuleTests.scala

This PR generalizes some `Target`-related stuff in `Resolve` to all `NamedTask`s with no arguments (targets and workers), and makes sure `resolve` / `show` / `inspect` work fine with workers. In particular, running `show` on a worker now prints something like
```json
{
"worker": "foo.theWorker",
"toString": "build_.package_$foo$$anon$1@4acbdb44",
"inputsHash": -2075822978
}
```

Show workers in resolve / show / inspect too

---

example/package.mill

Stumbled upon it when diving in the examples internals. It seems to me that this env var is unused (can't find it anywhere else by grepping the whole codebase).

Remove unused env var in examples forkEnv

---

docs/modules/ROOT/pages/Out_Dir.adoc
example/depth/out-dir/1-custom-out/build.mill
example/package.mill
integration/feature/output-directory/resources/build.mill
integration/feature/output-directory/src/OutputDirectoryTests.scala
main/client/src/mill/main/client/EnvVars.java
main/client/src/mill/main/client/OutFiles.java
runner/src/mill/runner/CodeGen.scala
runner/src/mill/runner/FileImportGraph.scala
runner/src/mill/runner/MillBuildBootstrap.scala
runner/src/mill/runner/MillBuildRootModule.scala
runner/src/mill/runner/MillMain.scala
testkit/src/mill/testkit/IntegrationTester.scala
testkit/src/mill/testkit/IntegrationTesterBase.scala

This allows users to change the Mill output directory (by default, `out` under the project root) to a directory of their choice, via the `MILL_OUTPUT_DIR` environment variable.
Fixes https://github.com/com-lihaoyi/mill/issues/3144

Allow users to use a custom output dir via an env var

---

scalalib/src/mill/scalalib/CoursierModule.scala

Using the default global `ExecutionContext`, also used by the BSP server, can lead to deadlocks, as coursier doesn't mark blocking things with `blocking`. (It deadlocks locally for me, during Mill import via BSP in IntelliJ, with 4 threads being spawned and awaiting in the default `ExecutionContext`.)

Use coursier thread pool to run coursier-related task

---

integration/feature/docannotations/resources/build.mill
integration/feature/docannotations/src/DocAnnotationsTests.scala
main/define/src/mill/define/Discover.scala
main/define/src/mill/define/Module.scala
main/resolve/src/mill/resolve/Resolve.scala
main/resolve/test/src/mill/main/ResolveTests.scala
main/src/mill/main/MainModule.scala

Implement inspect for modules:
- Name of module with file/line info
- Scaladoc on module
- Inherited modules
- Module dependencies
- Default task
- Implemented tasks

Issue #2929: implement inspect for modules

---

example/kotlinlib/linting/3-ktfmt/build.mill
example/kotlinlib/linting/3-ktfmt/src/example/FooRight.kt
example/kotlinlib/linting/3-ktfmt/src/example/FooWrong.kt
kotlinlib/src/mill/kotlinlib/contrib/ktfmt/KtfmtArgs.scala
kotlinlib/src/mill/kotlinlib/contrib/ktfmt/KtfmtModule.scala
kotlinlib/test/resources/contrib/ktfmt/after/imports/Example.kt
kotlinlib/test/resources/contrib/ktfmt/after/style/google/Example.kt
kotlinlib/test/resources/contrib/ktfmt/after/style/kotlin/Example.kt
kotlinlib/test/resources/contrib/ktfmt/after/style/meta/Example.kt
kotlinlib/test/resources/contrib/ktfmt/before/src/Example.kt
kotlinlib/test/src/mill/kotlinlib/contrib/ktfmt/KtfmtModuleTests.scala

Fixes #3612.
This PR is based on the logic done in #3531, so it looks quite similar.

Add Ktfmt support

---

.scalafmt.conf
bsp/src/mill/bsp/BspWorker.scala
contrib/buildinfo/src/mill/contrib/buildinfo/BuildInfo.scala
main/util/src/mill/util/PromptLoggerUtil.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Scalafmt needs to be updated to support the latest scala 3 syntax.
according to the now-deleted comment, this version was frozen because of supporting building with JDK 8, but if 0.12.0 will drop JDK 8 support then why not update

use Scalafmt latest version (won't build with Java 8)

---

contrib/playlib/src/mill/playlib/RouterModule.scala
contrib/scalapblib/src/mill/contrib/scalapblib/ScalaPBModule.scala
contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala
contrib/twirllib/src/mill/twirllib/TwirlModule.scala
example/depth/tasks/5-persistent-targets/build.mill
main/define/src/mill/define/NamedParameterOnlyDummy.scala
main/define/src/mill/define/Task.scala
main/define/test/src/mill/define/MacroErrorTests.scala
main/eval/src/mill/eval/EvaluatorCore.scala
main/eval/src/mill/eval/Terminal.scala
main/eval/test/src/mill/eval/TaskTests.scala
main/src/mill/main/MainModule.scala
runner/src/mill/runner/MillBuildRootModule.scala
scalajslib/src/mill/scalajslib/ScalaJSModule.scala
scalalib/src/mill/scalalib/GenIdeaModule.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/ScalaModule.scala
scalalib/src/mill/scalalib/SemanticDbJavaModule.scala
scalalib/src/mill/scalalib/TestModule.scala

fixes https://github.com/com-lihaoyi/mill/issues/3566. Mostly a straightforward implementation of what was discussed.
We use `Task.Command(exclusive = true)` to make `console`/`repl`/`clean`/etc. run serially, all other commands should run in parallel. That includes most `test` commands. The name `exclusive` is taken from the Bazel action/target tag with the same meaning: that the tagged action runs alone with no other actions in parallel
`Task.Persistent` was changed to `Task(persistent = true)` for consistency, and also for other reasons: the new syntax is more composable, e.g. a user can more easily choose whether they want `persistent = true` or `persistent = false` based on a computed `Boolean` value, and Mill can in future extend it such that we can have `Task(exclusive = true, …

Introduce `Task.Command(exclusive = true)` and convert `Task.Persistent` to `Task(persistent = true)`

---

example/depth/tasks/7-forking-futures/build.mill
main/util/src/mill/util/PromptLogger.scala
runner/src/mill/runner/MillMain.scala
runner/src/mill/runner/Watching.scala

Now, if you use `-w`/`--watch` the prompt starts and ends after each evaluation (which is bounded) rather than around the entire watch (which may last forever). This is much more useful so you can see where each run started and ended and how long it took, v.s. previously where it just tells you how long you've been watching for overall which is usually not something you care about
Also fixed a race condition where the `promptUpdaterThread` was still running for one iteration even after `PromptLogger#close()`, causing extra prompts to sometimes be displayed overlapping other logs

Scope PromptLogger to `MillBuildBootstrap#evaluate` call to make prompt more intuitive

---

build.mill
main/api/src/mill/api/Logger.scala
main/eval/src/mill/eval/EvaluatorCore.scala
main/eval/src/mill/eval/EvaluatorImpl.scala
main/eval/src/mill/eval/GroupEvaluator.scala
main/util/src/mill/util/MultiLogger.scala
main/util/src/mill/util/PrefixLogger.scala
main/util/src/mill/util/PromptLogger.scala
main/util/src/mill/util/ProxyLogger.scala
runner/src/mill/runner/MillBuildBootstrap.scala
scalalib/src/mill/scalalib/ScalaModule.scala
testkit/src/mill/testkit/UnitTester.scala

Turns out we still need it for `console` and `repl` commands in order to disable the prompt auto updater thread. But we can limit its use to only within `EvaluatorCore` for every `exclusive` command, rather than letting it be used in any random user-land task
Also refactors it such that `exclusive = true` commands use `SystemStreams.original` by default, allowing `def repl` and `def console` to work without overriding the system streams themselves
Tested manually
```
$ ./mill -i dist.launcher && (cd example/scalalib/basic/1-simple  && ../../../../out/dist/launcher.dest/run -i path compile sources + console + version)
[2579/2579] ========================================================================= dist.launcher =========================================================================== …
```

Put back `withPromptPaused`, but make it `private[mill]`

---

main/eval/src/mill/eval/ExecutionContexts.scala
main/util/src/mill/util/PromptLogger.scala

* Swap from `ForkJoinPool` to `ThreadPoolExecutor`
* `ForkJoinPool` does this weird thing where fork-join-tasks can be re-entrant at `join` points, resulting in weird scenarios where a mill-task that hits a yield point (e.g. inside Zinc / parallel-collections / FJP) can start running a second mill-task even before the first has finished, violating all sorts of invariants (# of running tasks exceeds `--jobs`, `FixSizeCache` semaphores get taken twice by the same thread, all sorts of craziness)
* We replace `ForkJoinPool#ManagedBlocker` with our own manual logic increasing and decreasing the `ThreadPoolExecutor`s `maximumPoolSize` and `corePoolSize` in our `blocking{...}`  wrapper
* We need to `Thread#interrupt()` the `promptUpdaterThread` thread when we close the `PromptLogger`, so we …

Concurrency fixes

---

build.mill

Fix [CVE-2024-7254](https://github.com/advisories/GHSA-735f-pc8j-v9w8)

Update protobuf-java from 4.28.0 to 4.28.2

---

build.mill
kotlinlib/package.mill
kotlinlib/src/mill/kotlinlib/KotlinModule.scala
kotlinlib/src/mill/kotlinlib/detekt/DetektModule.scala
kotlinlib/src/mill/kotlinlib/ktfmt/KtfmtModule.scala
kotlinlib/test/src/mill/kotlinlib/contrib/kover/KoverModuleTests.scala
kotlinlib/test/src/mill/kotlinlib/contrib/ktfmt/KtfmtModuleTests.scala

Some minor cleanup for the previous work on the Kotlin-related modules:
* Read tooling versions from build info (https://github.com/com-lihaoyi/mill/pull/3620#discussion_r1779445633 and https://github.com/com-lihaoyi/mill/pull/3620#discussion_r1779445811)
* Declare versions only once in the unit tests
* Change parent module to `JavaModule` for Ktfmt support, because we don't need the code to be compiled in this module, so declaring Kotlin version there was looking a bit strange. In fact only `sources()` method is needed, which is available in the `JavaModule`. In the future `KotlinModule` may be split into different traits: the one which collects Kotlin+Java files, but doesn't do any compilation (so Kotlin version is not needed) and the one which actually does compilation.

Use build info for versions in kotlinlib

---

idea/src/mill/idea/GenIdeaImpl.scala
integration/ide/gen-idea/resources/hello-idea/idea/libraries/scala_js_SDK_3_3_1.xml

IntelliJ IDEA doesn't have proper Scala.JS support but complains about multiple Scala library jars on the compiler classpath. Users reported that removing the scala3-library_3 fixes the issue. This PR applies this to `GenIdea`.
Hopefully fix https://github.com/com-lihaoyi/mill/issues/3344

GenIdea: Filter out scala3-library_3 for Scala-js-SDK library entry

---

example/kotlinlib/basic/1-simple/build.mill
example/kotlinlib/basic/2-custom-build-logic/build.mill
example/kotlinlib/basic/3-multi-module/build.mill
example/kotlinlib/basic/4-builtin-commands/build.mill
example/kotlinlib/builds/4-realistic/build.mill
example/kotlinlib/linting/4-kover/build.mill
example/kotlinlib/module/15-jni/build.mill
example/kotlinlib/module/7-resources/build.mill
example/kotlinlib/module/8-kotlin-compiler-plugins/build.mill
example/kotlinlib/testing/1-test-suite/build.mill
example/kotlinlib/testing/2-test-deps/build.mill
example/kotlinlib/testing/3-integration-suite/build.mill
example/kotlinlib/testing/4-test-grouping/build.mill
example/kotlinlib/web/1-hello-ktor/build.mill
kotlinlib/src/mill/kotlinlib/KotlinMavenModule.scala
kotlinlib/src/mill/kotlinlib/KotlinModule.scala
kotlinlib/src/mill/kotlinlib/kover/KoverModule.scala
kotlinlib/test/src/mill/kotlinlib/HelloWorldTests.scala
kotlinlib/test/src/mill/kotlinlib/MixedHelloWorldTests.scala
kotlinlib/test/src/mill/kotlinlib/contrib/kover/KoverModuleTests.scala

This brings them in line with where we want to bring the other testing traits, e.g. `JavaModuleTests` -> `JavaTests` and `ScalaModuleTests` -> `ScalaTests`. Since `KotlinModuleTests` hasn't been published yet, we are free to rename it

Rename KotlinModuleTests to KotlinTests

---

main/src/mill/main/RootModule.scala
runner/src/mill/runner/CodeGen.scala

They already get processed as part of the root `build.mill`'s `Discover[T]` macro call, so no need to duplicate the work

Avoid calling `Discover[T]` macro for sub-folder root modules

---

build.sc

Fix  [CVE-2024-7254](https://github.com/advisories/GHSA-735f-pc8j-v9w8)

Update protobuf-java to 3.25.5

---

integration/feature/plugin-classpath/src/MillPluginClasspathTest.scala
runner/src/mill/runner/MillBuildRootModule.scala

When we override `scalacPluginClasspath` we need to remeber to also override `semanticDbPluginClasspath`
Fixes #3666
Pull Request: https://github.com/com-lihaoyi/mill/pull/3673

Fix `semanticDbData` for mill-build

---

integration/feature/output-directory/resources/build.mill
integration/feature/output-directory/src/OutputDirectoryLockTests.scala
main/api/src/mill/api/Logger.scala
main/client/src/mill/main/client/OutFiles.java
main/client/src/mill/main/client/lock/DummyLock.java
main/client/src/mill/main/client/lock/DummyTryLocked.java
main/client/src/mill/main/client/lock/Lock.java
runner/src/mill/runner/MillCliConfig.scala
runner/src/mill/runner/MillMain.scala
testkit/src/mill/testkit/IntegrationTester.scala

First cut at https://github.com/com-lihaoyi/mill/issues/3519
There's no tests yet, but it works fine in manual tests.

Acquire a lock on the out dir in order to run tasks / commands

---

bsp/src/mill/bsp/Constants.scala
build.mill
integration/ide/bsp-server/resources/project/build.mill
integration/ide/bsp-server/resources/snapshots/build-targets-compile-classpaths.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-modules.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-sources.json
integration/ide/bsp-server/resources/snapshots/build-targets-javac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-jvm-run-environments.json
integration/ide/bsp-server/resources/snapshots/build-targets-jvm-test-environments.json
integration/ide/bsp-server/resources/snapshots/build-targets-output-paths.json
integration/ide/bsp-server/resources/snapshots/build-targets-resources.json
integration/ide/bsp-server/resources/snapshots/build-targets-scalac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-sources.json
integration/ide/bsp-server/resources/snapshots/initialize-build-result.json
integration/ide/bsp-server/resources/snapshots/workspace-build-targets.json
integration/ide/bsp-server/src/BspServerTestUtil.scala
integration/ide/bsp-server/src/BspServerTests.scala
integration/package.mill
kotlinlib/src/mill/kotlinlib/KotlinModule.scala
scalalib/src/mill/scalalib/bsp/BspModule.scala

This PR adds non-regression integration tests for Kotlin support via BSP. Kotlin modules are currently advertized as Java ones, and IntelliJ seems to handle fine Kotlin sources in those (using non-experimental BSP support).

Add Kotlin BSP integration test

---

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
integration/ide/bsp-server/resources/snapshots/workspace-build-targets.json
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/ScalaModule.scala

This adds the JVM we use in the Scala details in BSP build targets. I don't think Metals uses that for now, and I don't know about IntelliJ. But they might in the future.

Pass BSP JvmBuildTarget stuff to ScalaBuildTarget

---

docs/modules/ROOT/pages/comparisons/maven.adoc
docs/modules/ROOT/pages/depth/design-principles.adoc
docs/modules/ROOT/partials/Intro_to_Mill_Header.adoc
docs/package.mill
example/fundamentals/cross/1-simple/build.mill
example/fundamentals/cross/10-static-blog/build.mill
example/fundamentals/cross/3-outside-dependency/build.mill
example/fundamentals/cross/4-cross-dependencies/build.mill
example/fundamentals/cross/5-multiple-cross-axes/build.mill
example/fundamentals/cross/7-inner-cross-module/build.mill
example/fundamentals/modules/7-modules/build.mill
example/fundamentals/modules/8-diy-java-modules/build.mill
example/fundamentals/tasks/1-task-graph/build.mill
example/fundamentals/tasks/2-primary-tasks/build.mill
example/scalalib/basic/2-custom-build-logic/build.mill
example/scalalib/basic/4-builtin-commands/build.mill
example/scalalib/module/2-custom-tasks/build.mill
main/graphviz/src/mill/main/graphviz/GraphvizTools.scala
main/package.mill
main/src/mill/main/MainModule.scala
main/src/mill/main/VisualizeModule.scala
mill-build/build.sc

* We cannot do Javet/Node/Graphviz rendering in-process because the native node.js binary necessary to run these things doesn't play well with Mill's classloader juggling, meaning if the `build.mill` gets recompiled in a long-running process it currently fails with a nasty LinkageError. This is an existing problem
```
lihaoyi mill$ ./mill  visualize dist._
...
[ [55/59] =========================================== visualize dist._ =============================================== 8s
"/Users/lihaoyi/Github/mill/out/visualize.dest/out.txt",
"/Users/lihaoyi/Github/mill/out/visualize.dest/out.dot",
"/Users/lihaoyi/Github/mill/out/visualize.dest/out.json",
"/Users/lihaoyi/Github/mill/out/visualize.dest/out.png",
"/Users/lihaoyi/Github/mill/out/visualize.dest/out.svg"
]
[3/3] …
```

Unify `visualize` and doc-site graphviz rendering into Javet subprocess

---

scalalib/src/mill/scalalib/Assembly.scala

Should be basically the same logic, just now we use the version bundled within `os.zip`

Make use of new `os.zip.open` operation to create assemblies

---

kotlinlib/src/mill/kotlinlib/js/KotlinJSModule.scala

These appear to be ADTs - and they need to generate upickle readwriters
makes it easier for the Scala 3 upgrade to get this in now

use case object in KotlinJSModule

---

example/kotlinlib/web/3-hello-kotlinjs/build.mill
example/kotlinlib/web/3-hello-kotlinjs/foo/src/foo/Hello.kt
example/kotlinlib/web/3-hello-kotlinjs/foo/test/src/foo/HelloTests.kt

Takes advantage of the new klib support pulled in by https://github.com/com-lihaoyi/mill/pull/3705
We don't support the `module` file indirection, so for now we have to reference the `-js` version of the artifact directly

Add kotlinx-html to `3-hello-kotlinjs` example

---

main/define/src/mill/define/Discover.scala
runner/src/mill/runner/CodeGen.scala

fixes https://github.com/com-lihaoyi/mill/issues/3385
Somehow the `@nowarn` annotations don't seem to work after we moved the `millDiscover` definition into the main module body (???) so instead of relying on those I try to fix the deprecated warning in the `Discover` macro itself by identifying type annotations and explicitly asking not to dereference them
Manually tested by running the commands below, observed that no deprecation warning was printed
```
rm -rf /Users/lihaoyi/Github/mill/example/javalib/basic/1-simple/out
./mill -i dist.run example/javalib/basic/1-simple -i run -t hello
```

Try to fix deprecated discover warning

---

contrib/proguard/src/mill/contrib/proguard/Proguard.scala

Proguard is a long pole in the windows contrib test job, hopefully this makes it a bit faster
Seems to cut a few minutes; previously it ran in 12-17min, with this PR it ran in 10+ min

Try and speed up proguard contrib module/tests by re-using global java runtime jar

---

main/api/src/mill/api/Logger.scala
main/eval/src/mill/eval/EvaluatorCore.scala
main/util/src/mill/util/MultiLogger.scala
main/util/src/mill/util/PrefixLogger.scala
main/util/src/mill/util/PromptLogger.scala
main/util/src/mill/util/PromptLoggerUtil.scala
main/util/src/mill/util/ProxyLogger.scala
main/util/test/src/mill/util/PromptLoggerTests.scala

* Move more pure logic into `PromptLoggerUtil` static methods
* Make prompt line replacement logic more aggressive, such that even after dead lines finish transitioning they can be replaced, fixing an issue where the prompt height sometimes grew unnecessarily due to blank lines

More cleanups for PromptLogger

---

integration/feature/docannotations/src/DocAnnotationsTests.scala
main/util/src/mill/util/CoursierSupport.scala
scalalib/src/mill/scalalib/CoursierModule.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/Lib.scala
scalalib/src/mill/scalalib/ZincWorkerModule.scala

Allowing users to ask for more artifact types to be fetched and put in the classpath

Add JavaModule.artifactTypes

---

integration/feature/docannotations/src/DocAnnotationsTests.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/test/src/mill/scalalib/ResolveDepsTests.scala

Follow-up of https://github.com/com-lihaoyi/mill/pull/3703 that added `JavaModule.artifactTypes`. `JavaModule` performs two dependency resolutions: one for `compileClasspath`, the other for `runClasspath`. https://github.com/com-lihaoyi/mill/pull/3703 used `artifactTypes` in the `runClasspath` one, but not in the `compileClasspath` one. The PR here fixes that, and adds unit tests for both paths.
This addresses the issues found around https://github.com/com-lihaoyi/mill/pull/3696#issuecomment-2405891608.

Fix JavaModule.artifactTypes

---

example/kotlinlib/web/4-webapp-kotlinjs/build.mill
example/kotlinlib/web/4-webapp-kotlinjs/client/src/ClientApp.kt
example/kotlinlib/web/4-webapp-kotlinjs/resources/webapp/index.css
example/kotlinlib/web/4-webapp-kotlinjs/src/WebApp.kt
example/kotlinlib/web/4-webapp-kotlinjs/test/src/WebAppTests.kt
example/scalalib/web/4-webapp-scalajs/client/src/ClientApp.scala

Point 4 in #3611: add a sample of Kotlin/JS frontend+ Ktor backend.

Add Kotlin/JS webapp example

---

example/kotlinlib/web/5-webapp-kotlinjs-shared/build.mill
example/kotlinlib/web/5-webapp-kotlinjs-shared/client/src/ClientApp.kt
example/kotlinlib/web/5-webapp-kotlinjs-shared/resources/logback.xml
example/kotlinlib/web/5-webapp-kotlinjs-shared/resources/webapp/index.css
example/kotlinlib/web/5-webapp-kotlinjs-shared/shared/src/Shared.kt
example/kotlinlib/web/5-webapp-kotlinjs-shared/src/WebApp.kt
example/kotlinlib/web/5-webapp-kotlinjs-shared/test/src/WebAppTests.kt
kotlinlib/src/mill/kotlinlib/PlatformKotlinModule.scala

This PR addresses task 5 from #3611 by adding and example of code sharing between JVM and JS Kotlin targets.
I also simply copied `PlatformScalaModule` -> `PlatformKotlinModule`, because type aliasing won't work: doc is different (and need to extend from `KotlinModule` still).

Add shared JVM/JS Kotlin code example

---

build.mill
kotlinlib/package.mill
kotlinlib/src/mill/kotlinlib/js/KotlinJSModule.scala
kotlinlib/test/resources/kotlin-js/qux/src/qux/ExternalDependency.kt
kotlinlib/test/src/mill/kotlinlib/js/KotlinJSKotlinVersionsTests.scala

Since `klib` files can be fetched now, it removes the constraint for the Kotlin 2+ version usage (where `stdlib` is now published only as `klib`).
I added a `kotlinVersion` to the build info, but it is not actually used anywhere in the module code (because the default version for the module is never specified), only in the test.

Lift Kotlin 2+ version usage constraint for Kotlin/JS

---

integration/failure/root-module-compile-error/src/RootModuleCompileErrorTests.scala
main/src/mill/main/RootModule.scala
main/src/mill/main/Subfolder.scala
runner/src/mill/runner/CodeGen.scala
runner/src/mill/runner/MillBuildBootstrap.scala
runner/src/mill/runner/MillBuildRootModule.scala

Removed `MillBuildRootModule.Info` and `MillBuildRootModule.MillMiscInfo` and consolidated them into `RootModule.Info` and `SubfolderModule.Info`. Shouldn't affect anything semantically, just removes some unnecessary indirection that wasn't doing anything but packing and unpacking the same few values

Simplify codegen prelude implicits

---

integration/invalidation/codesig-subfolder/src/CodeSigSubfolderTests.scala
integration/invalidation/zinc-build-compilation/resources/build.mill
integration/invalidation/zinc-build-compilation/resources/subfolder/package.mill
integration/invalidation/zinc-build-compilation/src/ZincBuildCompilationTests.scala
main/src/mill/main/MainModule.scala

Seems there's a bug in https://github.com/sbt/zinc/issues/1461 causing over-compilation, for now just assert the misbehavior

Add smoketest for incremental compilation of multi-file build

---

idea/src/mill/idea/GenIdeaImpl.scala

Fix https://github.com/com-lihaoyi/mill/issues/3168

GenIdea: Handle failure when evaluating module sources/resources

---

docs/package.mill
example/fundamentals/tasks/1-task-graph/build.mill
main/api/src/mill/api/SystemStreams.scala
main/client/src/mill/main/client/ProxyStream.java
main/eval/src/mill/eval/EvaluatorCore.scala
main/util/src/mill/util/PromptLogger.scala
main/util/src/mill/util/PromptLoggerUtil.scala
main/util/test/src/mill/util/PromptLoggerTests.scala

1. Make `EvaluatorCore` waits for all non-exclusive tasks to finish before beginning to run exclusive tasks to prevent overlap
2. Re-organize `promptLineState`/`streamManager`/`runningState` to ensure each piece of mutable state is only read by one of them
3. Tweak `PromptLoggerUtil.clearScreenToEndBytes` to prevent the `clearScreen` from mucking up tab-stops in iTerm2
4. Overhaul `PromptLogger'`s synchronization strategy: we now no longer synchronize on child loggers writing to `PromptLogger`'s streams, and only synchronize on `PromptLogger` writing to the parent `systemStreams0` (including the writes coming from `ProxyStream.Pumper`) along with the operations mutating state within `PromptLogger`
5. Ensure we only print the prompt in `preRead` if the previous character was a `\n`, to …

More fixes for prompt logger

---

idea/src/mill/idea/GenIdeaImpl.scala

We simply don't swallow the error but propagate it.
Fix https://github.com/com-lihaoyi/mill/issues/3168
Backport of pull request: https://github.com/com-lihaoyi/mill/pull/3754

GenIdea: Handle failure when evaluating module sources/resources (backport #3754)

---

docs/modules/ROOT/pages/fundamentals/modules.adoc
example/fundamentals/modules/11-module-ref/bar/src/bar/Bar.java
example/fundamentals/modules/11-module-ref/bartest/src/bar/BarTests.java
example/fundamentals/modules/11-module-ref/build.mill
example/fundamentals/modules/11-module-ref/foo/src/foo/Foo.java
example/fundamentals/modules/11-module-ref/footest/src/bar/FooTests.java

Not super thorough, but at least it exists now

Add example documentation for `ModuleRef`

---

build.mill
integration/invalidation/codesig-subfolder/src/CodeSigSubfolderTests.scala
integration/invalidation/zinc-build-compilation/src/ZincBuildCompilationTests.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Pulls in https://github.com/sbt/zinc/releases/tag/v1.10.3 and fixes https://github.com/com-lihaoyi/mill/issues/3748

Pull in Zinc 0.10.3

---

integration/feature/full-run-logs/src/FullRunLogsTests.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/ScalaModule.scala
scalalib/test/src/mill/scalalib/ScalaIvyDepsTests.scala
scalalib/test/src/mill/scalalib/ScalaMultiModuleClasspathsTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3761
* Introduce `runModuleDeps`, the runtime version of `moduleDeps` and `compileModuleDeps`
* We introduce `transitiveRunIvyDeps`, the runtime version of `transitiveIvyDeps`, and use it in most places as a replacement for `runIvyDeps`
* I also flipped the ordering of `transitiveModuleDeps`/`transitiveRunModuleDeps` to put `this` on the right/last, to follow the rest of the module resolution logic where "upstream" things come on the left/first in the classpath ordering
There are some behavioral changes, e.g. the A module's direct `compileModuleDeps` no longer end up on your `runClasspath`, as shown by the change in the test case `mill.scalalib.ScalaMultiModuleClasspathsTests.modCompile`. I think the new behavior is more correct than the …

Make runtime deps transitive

---

main/util/src/mill/util/LinePrefixOutputStream.scala

Previously the `linePrefix` would end with `RESET` and wipe out the colors after each line; now we parse each line and look at the ending color and print that at the start of the next line. There'll be some overhead, but `fansi.Str` is pretty fast so hopefully it's OK
Tested manually, we can see the multi-line ansi colors that were problematic earlier now work, both preserving color, going from color to non-color and color to non-color
Fixes https://github.com/com-lihaoyi/mill/issues/3793

Fix ANSI color sequences that apply to multiple lines in the terminal logs

---

docs/modules/ROOT/partials/Intro_to_Mill_Header.adoc

Fix chart: foo.classpath should be contained in "foo" cluster

---

example/tasks/4-inputs/build.sc
runner/src/mill/runner/MillMain.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3789. We just
accidentally flipped the conditional and didn't have any tests that
verify this behavior, so I added some example tests that also serve to
explain the feature in the docs.
Backport of pull request: https://github.com/com-lihaoyi/mill/pull/3791

Fix property handling and add tests and docs (backport #3791)

---

build.mill

This is a major version change. I haven't tested manually, if it works. There is also PR #3810, which only bump to latest minor update.

Update javet to 4.0.0

---

dist/resources/logback.xml

Since we bundle the logback dependency, it runs with a built-in default config printing all messages with at least DEBUG level on the console. This can be very verbose.
This change includes a default config creating a log file `out/mill.log` in the current workind directory. Since Mill now always runs in a sandbox dir, this should not pollute the users working directory.
If a user wants to change the log configuration, she can provide an alternative config with `-Dlogback.configurationFile=/path/to/config.xml`
We add the config file `logback.xml` to the runtime resources of the `dist` module, so it is only on the classpath of the Mill assembly. Since this assembly isn't expected on the classpath of other tools or libraries, we should avoid accidental downstream logging configurations.
Fix …

Add a default config for logback

---

main/client/src/mill/main/client/ServerLauncher.java
main/server/test/src/mill/main/server/ClientServerTests.scala
runner/client/src/mill/runner/client/MillClientMain.java
runner/client/src/mill/runner/client/MillProcessLauncher.java

Previously we only spawned the terminfo updater when spawning the Mill server process, but that only handles the no-server case and first-time-spawning-server case, without handling the subsequently-re-use-server case. 
This moves the logic into a helper method so we can call it from both server and no-server launchers at the first point at which we have a dedicated `serverDir` available. Since the `serverDIr` is only available deep inside the `ServerLauncher` object, as it needs to do the work of testing different locks to pick a server, we add a `preRun` hook that we can override to start the terminfo updater thread

Fix spawning of terminfo thread in server mode

---

integration/failure/missing-build-file/src/MissingBuildFileTests.scala
runner/src/mill/runner/FileImportGraph.scala
runner/src/mill/runner/MillBuildBootstrap.scala
runner/src/mill/runner/MillMain.scala
runner/src/mill/runner/RunnerState.scala

Instead of always using `build.mill` we now use the actual buildfile name in the progress logger.
```
> mill resolve _
[build.sc-57/61] compile
...
> mv build.sc build.mill.scala
> mill resolve _
[build.mill.scala-57/61] compile
...
```
Fix https://github.com/com-lihaoyi/mill/issues/3831

Show the correct buildfile name in the progress

---

readme.adoc

`os.remove.all` had replaced it accidentally in https://github.com/nafg/mill/commit/bc9dc386625021fec517f2dbf0644ccafe1e32c2#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15

readme.adoc: Restore `rm` command in bash snippet

---

example/javalib/basic/1-simple/build.mill
main/define/src/mill/define/Cacher.scala
main/define/src/mill/define/Ctx.scala
main/define/src/mill/define/Module.scala
main/define/src/mill/define/Task.scala
main/define/test/src/mill/define/MacroErrorTests.scala

Same as https://github.com/com-lihaoyi/mill/pull/3558, but for `mill.define.Ctx` rather than `mill.main.RootModule.Info`. Because it's provided by the enclosing code-generation, we need to trick IntelliJ into thinking there is something it can use, and so I define a low priority implicit to fall back upon if the main `def make` doesn't work (but `@compileTimeOnly` to show an error message if it ends up being needed)
I moved the bulk of the cacher logic from `mill-moduledefs` to `mill.define`. We just need a marker trait in `mill-moduledefs`, and having the rest of the logic in Mill itself simplifies maintenance and evolution of the code
Before
After

Add stub `mill.define.Ctx` to trick IntelliJ into not erroring

---

CONTRIBUTING.adoc
docs/modules/ROOT/pages/index.adoc
docs/supplemental-ui/partials/header-content.hbs

Fixes https://github.com/com-lihaoyi/mill/issues/3864
Somehow the direct channel links always expire even when specifically configured not to

Replace direct discord invite link with link to scala discord and instructions to join channel

---

integration/feature/keyword-module/resources/build.mill
integration/feature/keyword-module/resources/for/package.mill
integration/feature/keyword-module/resources/for/src/Foo.scala
integration/feature/keyword-module/resources/if/package.mill
integration/feature/keyword-module/resources/if/src/Foo.scala
integration/feature/keyword-module/resources/import/package.mill
integration/feature/keyword-module/resources/import/src/Foo.scala
integration/feature/keyword-module/resources/null/package.mill
integration/feature/keyword-module/resources/null/src/Foo.scala
integration/feature/keyword-module/resources/this/package.mill
integration/feature/keyword-module/resources/this/src/Foo.scala
integration/feature/keyword-module/src/KeywordModuleTests.scala
runner/src/mill/runner/FileImportGraph.scala

to allow submodule use scala keyword as name, fix #3863 
I am not sure this is the way we want to match scala keyword though

backtick when path segment is scala keyword

---

docs/package.mill

All currently configured previous versions point to git tags, not branches. Hence editing on Github isn't fruitful.
Fix https://github.com/com-lihaoyi/mill/issues/3858

Docs: disable edit links for previous versions

---

main/resolve/src/mill/resolve/Resolve.scala
main/resolve/src/mill/resolve/ResolveCore.scala
main/resolve/test/src/mill/main/ResolveTests.scala
main/test/src/mill/util/TestGraphs.scala
scalalib/src/mill/scalalib/internal/ModuleUtils.scala

This completes #3715 with all the cycle cases I could think of.
It also touches `resolveDirectChildren` where I made some changes that I would help with readability. I thought I was going to need to build on those but didn't. These can be reverted if it's unwanted.

Detect when `resolve` needs `ModuleRef` when likely cyclic references

---

runner/src/mill/runner/MillBuildRootModule.scala

Mill used various tricks to map build scripts written by users to generated enhanced versions, including package objects and other stuff.
Since some of these techniques may result in Zinc undercompilation, we want avoid downstream issues,
especally in the `methodCodeHashSignatures` task, which is sensitive to inconsistent bytecode.
We trait potentially longer compilation against incorrect or too coarse code change detection, which may invalidate a lot more downstream tasks than needed due to invalid data.
Fix https://github.com/com-lihaoyi/mill/issues/3874

Drop incremental compilation state for Mill modules when version changes

---

integration/feature/full-run-logs/src/FullRunLogsTests.scala
main/eval/src/mill/eval/Evaluator.scala
main/eval/src/mill/eval/EvaluatorCore.scala
main/eval/src/mill/eval/EvaluatorImpl.scala
main/eval/src/mill/eval/JsonArrayLogger.scala
runner/src/mill/runner/MillBuildBootstrap.scala
testkit/src/mill/testkit/IntegrationTester.scala
testkit/src/mill/testkit/UnitTester.scala

We broaden the scope of `profileLogger`/`chromeProfileLogger` from within `def evaluate` to instead last as long as the `Evaluator` itself, and share it with any sub-`Evaluator`s created e.g. to redirect output during `show`
`Evaluator` is now `AutoCloseable`, and needs to be closed after being used in `MillBuildBootstrap` and in `UnitTester`
For now I decided not to share the profilers between different evaluation levels of the meta-build, since they already don't overlap: one goes to `out/`, the parent to `out/mill-build/`, etc. We could do that if we think it would be useful to give people a consolidated profile, but it might be a bit more work (e.g. we would need to properly prefix entries in the profile to distinguish the different meta levels).
Added a unit test to ensure the `show …

Share profile loggers between nested evaluations

---

integration/failure/non-exclusive-depends-on-exclusive/resources/build.mill
integration/failure/non-exclusive-depends-on-exclusive/src/NonExclusiveDependsOnExclusive.scala
main/eval/src/mill/eval/EvaluatorCore.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3875
I placed a check to raise an error when a non-exclusive task depends on an exclusive task. 
We could place this check any time from task instantiation to just before the `NoSuchElementException` gets thrown. I ended up putting it as late as possible, such that the failure is localized, which allows other un-related parts of the build to proceed despite the failure, as well as allowing other errors in the build to be reported in parallel (rather than having to re-run the build over and over after fixing each one to see the next one)
Covered with an integration test that asserts on the error message. Best reviewed with Ignore Whitespace

Add nice error when non-exclusive task depends on exclusive task

---

.github/workflows/publish-artifacts.yml
.github/workflows/run-mill-action.yml

This should avoid duplicated build work.
It also makes sure, we publish identical jars everywhere.
Potentially needed GHA Job retries will be faster too.
This is untested. We should do at least one manual run before we tag the next release.

CI: Reuse built artifacts in publish jobs (sonatype, github)

---

kotlinlib/test/resources/hello-world-kotlin/main/kotest/src/FooTest.kt
kotlinlib/test/src/mill/kotlinlib/HelloWorldTests.scala
testrunner/src/mill/testrunner/TestRunnerUtils.scala

Mitigates https://github.com/com-lihaoyi/mill/issues/3910 by hackily filtering out all anonymous classes, but non-anonymous non-test classes still cause the problem
Added a unit test to check this specific misbehavior

Filter out anonymous classes during test discovery

---

.github/workflows/run-tests.yml
example/package.mill
example/thirdparty/arrow/build.mill
kotlinlib/src/mill/kotlinlib/KotlinModule.scala
kotlinlib/src/mill/kotlinlib/js/KotlinJsModule.scala
kotlinlib/test/src/mill/kotlinlib/js/KotlinJsLinkTests.scala

This PR partially addresses #3670: it contains working example, but doesn't contain any docs.
This example contains compilation and test execution for all the modules of https://github.com/arrow-kt/arrow for the JVM and JS (Node) targets, except [arrow-optics-compose](https://github.com/arrow-kt/arrow/tree/main/arrow-libs/optics/arrow-optics-compose) module (it requires better Android support by Mill).
Full example run takes 6 minutes on my machine, so it is extracted into a dedicated CI job.
The following Gradle plugins are not added to the example build script, because their respective tooling is Gradle-dependent (no raw-jar or CLI):
* https://github.com/xvik/gradle-animalsniffer-plugin (although maybe it is possible to use options from https://www.mojohaus.org/animal-sniffer/)
* …

Add `arrow-kt` example

---

.github/workflows/run-mill-action.yml
.github/workflows/run-tests.yml
scalalib/src/mill/javalib/android/AndroidSdkModule.scala

This PR seeks to improve Android SDK handling approach.
The current issues are:
* Android SDK setup is [limited only to Linux](https://github.com/com-lihaoyi/mill/blob/9d11962eaf529474dd66e095620a97cff66ebcd3/scalalib/src/mill/javalib/android/AndroidSdkModule.scala#L24) and is also using [tooling which may be not available on other platforms](https://github.com/com-lihaoyi/mill/blob/9d11962eaf529474dd66e095620a97cff66ebcd3/scalalib/src/mill/javalib/android/AndroidSdkModule.scala#L102-L109).
* Each module [will have its own copy of SDK](https://github.com/com-lihaoyi/mill/blob/9d11962eaf529474dd66e095620a97cff66ebcd3/scalalib/src/mill/javalib/android/AndroidSdkModule.scala#L114). Imagine a project with 20 Android modules (19 lib modules + 1 app module), it will be 20x space usage than it …

Improve Android SDK handling

---

integration/feature/docannotations/resources/build.mill
integration/feature/docannotations/resources/core3/package.mill
integration/feature/docannotations/src/DocAnnotationsTests.scala
main/src/mill/main/MainModule.scala
main/test/src/mill/main/MainModuleTests.scala
testkit/src/mill/testkit/ExampleTester.scala

* Retain the full source location relative to the project directory.
* Inherited Modules now show the full class names instead of just a short names without the package.
* In debug mode, show all inherited modules, not only the directly declared ones.
* Also show compile and runtime module dependencies
* Reworked formatting for modules to be consistent with inspect for tasks
* Added a test for inspect modules
```
sub(main/test/src/mill/main/MainModuleTests.scala:46)
Sub module
Inherited Modules:    
mill.define.TaskModule
Module Dependencies:
sub.subSub
Default Task: sub.hello
Tasks (re-/defined):
sub.hello
```

Improve `inspect`

---

main/util/src/mill/util/PromptLogger.scala

The logic was incorrect: we still need to re-calculate the prompt even if the statuses don't change, because the wall clock time changes and so the second tickers need to be updated

Remove prompt update hash check

---

contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3857. We were missing one of the necessary flags, which is documented in https://dotty.epfl.ch/docs/internals/coverage.html
Manually tested, reproduced the problem and verified the fix. I'm not sure why the existing unit tests didn't catch it, must be something to do with how the sandbox is set up for unit tests vs in real usage. I'm not sure if it's worth introducing an integration test just for this so just leaving it at manual testing for now

Fix Scoverage report generation in Scala 3

---

build.mill
docs/modules/ROOT/pages/index.adoc
docs/package.mill

* The latest stable version (now 0.12.2) now is the default documentation version linked under `/`
* Older stable versions (e.g. 0.11.12) now are linked under `/0.11.x/`
* The unstable main branch version is now linked under `/main-branch/`
This should ensure people go to the latest stable version of the docs easily, links to older stable versions remain stable, and the main branch docs are available if less convenient

Stabilize links to doc site versions

---

runner/src/mill/runner/MillBuildBootstrap.scala

Seems to be necessary for some of the libraries people `import $ivy`, such as Guardrail

Set context classloader during Mill evaluation

---

build.mill

Not `2.1.17` yet, I'd like to add a way for users to disable the new internal handling of BOMs when bumping to it

Update coursier to 2.1.16

---

scalalib/src/mill/scalalib/JavaModule.scala

I was looking at this file, and it feels `allIvyDeps` was meant to be used in `transitiveIvyDeps `, but isn't. This fixes that. (Unless `allIvyDeps` is somehow scheduled for deletion?)

NIT Use allIvyDeps task where it seems it's meant to be used

---

kotlinlib/src/mill/kotlinlib/ktlint/KtlintModule.scala

For some reason `ktlint` behaves differently if it's config is set vs unset to it's default of `.editorconfig`.
It seems to be unable to disable `ktlint` when not explicitly set, so I think we should set it instead.
Why not bump the version while we're at it?

Default KtlintModule to .editorconfig explicitly

---

docs/modules/ROOT/pages/javalib/publishing.adoc
example/javalib/publishing/3-revapi/bar/conf/logback.xml
example/javalib/publishing/3-revapi/bar/conf/revapi.json
example/javalib/publishing/3-revapi/bar/src/Visibility.java
example/javalib/publishing/3-revapi/build.mill
example/javalib/publishing/3-revapi/dev/src/Visibility.java
scalalib/src/mill/javalib/revapi/RevapiModule.scala
scalalib/test/resources/javalib/revapi/conf/logback.xml
scalalib/test/resources/javalib/revapi/conf/revapi.json
scalalib/test/resources/javalib/revapi/example/v1/src/annotations/InheritedAnnotation.java
scalalib/test/resources/javalib/revapi/example/v1/src/classes/TypeParams.java
scalalib/test/resources/javalib/revapi/example/v1/src/fields/Visibility.java
scalalib/test/resources/javalib/revapi/example/v2/src/annotations/InheritedAnnotation.java
scalalib/test/resources/javalib/revapi/example/v2/src/classes/TypeParams.java
scalalib/test/resources/javalib/revapi/example/v2/src/fields/Visibility.java
scalalib/test/resources/javalib/revapi/example/v2/src/methods/Abstract.java
scalalib/test/resources/javalib/revapi/expected/example.lines
scalalib/test/resources/javalib/revapi/expected/guava.lines
scalalib/test/src/mill/javalib/revapi/RevapiModuleTests.scala

Added [Revapi](https://revapi.org/revapi-site/main/index.html) support for API analysis and change tracking to identify incompatibilities.
Resolves #3929.

Added support for Revapi

---

mill

This is a precaution for cases when the `.mill-version` file can contain a Windows line end `\r\n` instead of the typical Unix line end `\n`. Without this fix, in such situation the script breaks in a spectacular and surprising way.
The error it was giving looked like this:
```sh
$ mill __.compile
curl: (3) URL using bad/illegal format or missing URL
```
Where `mill` is pointing to the wrapper script that I'm changing in this PR

Handle case of .mill-version with Windows line ends

---

scalalib/src/mill/scalalib/TestModule.scala
scalalib/test/resources/junit5/test/src/qux/FooTests.java
scalalib/test/resources/junit5/test/src/qux/QuxTests.java
scalalib/test/src/mill/javalib/junit5/JUnit5Tests.scala

This changes discovery of test classes for Junit5, to be in line with that of sbt-jupiter-interface.
Closes #3910

junit5: override test discovery

---

contrib/sonatypecentral/readme.adoc
contrib/sonatypecentral/src/mill/contrib/sonatypecentral/SonatypeCentralPublishModule.scala

In the current version the SonatypeCentralPublishModule has non intented behaviour with PublishModule.defaultGpgArgs.
It will default to the args without a passphrase and afterwards ignore the passphrase env. var as a gpgarg is already set.
To get the "correct" behaviour one has to override the args with an empty string to then pick up the "PGP_PASSPHRASE" env. arg.
Also changed the env. name to match the one from SonaTypePublisher "PGP_PASSPHRASE" -> "MILL_PGP_PASSPHRASE".
Currently pgp and gpg are getting used both in terms of naming - guessing going for gpg in the future might be more clear.

align SonatypeCentralPublishModule with SonatypePublisher

---

example/extending/typescript/4-npm-deps-bundle/build.mill

Fixes: https://mill-build.org/mill/extending/example-typescript-support.html#_npm_dependencies_and_bundling

Docs nit 1

---

scalalib/src/mill/scalalib/UnidocModule.scala

Needed for https://github.com/com-lihaoyi/mill/pull/3950. It's running into a [scaladoc bug](https://github.com/scala/bug/issues/10028), and would need to exclude an internal dependency of coursier from the class path passed to scaladoc.
Once merged, Mill would need to be rebootstrapped on the latest nightly version, and https://github.com/com-lihaoyi/mill/pull/3950 would override `UnidocModule#unidocCompileClasspath` to exclude the JAR of coursier/dependency from it.

Allow users to override more UnidocModule parameters

---

main/api/src/mill/api/ClassLoader.scala

[Just ran](https://github.com/com-lihaoyi/mill/actions/runs/11955905378/job/33330071633?pr=3924) into a `java.nio.file.FileSystemException: C:\Users\runneradmin\rt-11.0.25.jar: The process cannot access the file because it is being used by another process.` during the attempt to copy this file. So this PR adds a retry around it, in the hope that it can help.

Add retry to the rt.jar copying stuff

---

kotlinlib/test/src/mill/kotlinlib/js/KotlinJsNodeRunTests.scala

Recently ran into one of them being red on the CI, and I couldn't run the failing test locally because of the `{` or `/` in the test names. So that PR simplifies those names.

Rename KotlinJsNodeRunTests tests so that they can be called individually on the command-line

---

docs/modules/ROOT/pages/extending/running-jvm-code.adoc
example/extending/jvmcode/3-worker/build.mill
example/extending/jvmcode/6-module-cached-classloader/bar/src/Bar.java
example/extending/jvmcode/6-module-cached-classloader/build.mill
example/extending/jvmcode/6-module-cached-classloader/foo1/src/Foo.java
example/extending/jvmcode/6-module-cached-classloader/foo2/src/Foo.java
example/extending/jvmcode/6-module-cached-classloader/foo3/src/Foo.java
example/fundamentals/tasks/6-workers/build.mill
main/api/src/mill/api/CacheFactory.scala
main/api/src/mill/api/CachedFactory.scala
main/api/src/mill/api/FixSizedCache.scala
main/api/src/mill/api/KeyedLockedCache.scala
main/api/test/src/mill/api/CachedFactoryTests.scala
main/util/src/mill/util/Jvm.scala
scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala
scalalib/src/mill/scalalib/ZincWorkerModule.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala
scalanativelib/src/mill/scalanativelib/worker/ScalaNativeWorker.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3730
The old `FixSizedCache`/`KeyedLockedCache`/`RandomBoundedCache` were all a bit of a mess, and none of them provided one crucial component to long-lived cache entries: the ability to tear them down after you are done with them. This is necessary for a lot of long-lived components you may want to cache: classloaders, subprocesses, open file handles, etc. all need to be torn down after use. Also, their implementation was weird, probably overly convoluted, and not used consistently throughout Mill
This PR introduces a new `CachedFactory` class meant to replace the old ones. I use it in four places (ZincWorker Scala and Java compilers, ScalaJsWorker, ScalanativeWorker), and added docs so users can discover and use it too. It provides a hook …

Overhaul worker concurrency helpers with `mill.api.CacheFactory`

---

integration/feature/full-run-logs/src/FullRunLogsTests.scala
main/util/src/mill/util/PromptLoggerUtil.scala
main/util/test/src/mill/util/PromptLoggerTests.scala
main/util/test/src/mill/util/PromptLoggerUtilTests.scala
runner/client/src/mill/runner/client/MillProcessLauncher.java

The previous full-width prompt header looks really weird on wide screens, even a full-width laptop screen is enough to make it awkward. This PR replaces it with a variable-width prompt header with some heuristics for shortening the `=` bars and the title text as necessary.
Covered by existing tests, added some more thorough tests in `PromptLoggerUtilTests.scala` to exercise the edge cases in the new shortening heuristics

Replace full-width prompt header with a variable-width-with-max prompt header

---

kotlinlib/src/mill/kotlinlib/detekt/DetektModule.scala

Somehow the `PathRef(T.workspace).path` is causing issues, but it's totally redundant since we can just use `T.workspace`. Walking the `out/` folder filesystem and hashing stuff seems to be causing problems with the file locks we use to ensure mutual exclusion
Seems to make `example.kotlinlib.linting[1-detekt].local.test` pass reliably where previously it was very flaky

Fix Detekt tests

---

kotlinlib/src/mill/kotlinlib/js/KotlinJsModule.scala

The current code passes a class path made for compile time to the Kotlin JS linker. While it's not a problem with the current main branch that doesn't really make a difference between compile and runtime class paths, this will be a problem with https://github.com/com-lihaoyi/mill/pull/4028, that can bring less JARs in `compileClasspath` (while all JARs will be around in runtime targets, like `resolvedRunIvyDeps`, like currently)

Pass a classpath made for runtime to Kotlin JS linker

---

build.mill

Alongside https://github.com/com-lihaoyi/mill/pull/4037, my hope is that this addresses https://github.com/com-lihaoyi/mill/issues/3662 (because both coursier and coursier-interface include https://github.com/coursier/coursier/pull/3171 now)

Update coursier-interface to 1.0.25

---

example/pythonlib/basic/1-simple/build.mill
example/pythonlib/basic/2-custom-build-logic/build.mill
example/pythonlib/basic/2-custom-build-logic/foo/src/foo.py
example/pythonlib/basic/3-multi-module/build.mill

Re-write Docs for First Class Python Support [Basic Example]
Fixes: #4054 
Rewrite Docs for Python `1-simple`, `2-custom-build-logic` and `3-multi-module` Examples
- Link to related issue #4054.
Updated & Require Review!!!

Fixed: #4054 Re-Write Docs for First Class Python Support [Basic Example]

---

bsp/worker/src/mill/bsp/worker/BspCompileProblemReporter.scala
build.mill
main/api/src/mill/api/CompileProblemReporter.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Fixes https://github.com/com-lihaoyi/mill/issues/2816
https://github.com/user-attachments/assets/8ff8f141-f217-40c0-a75f-8f4e87597391
Pull Request: https://github.com/com-lihaoyi/mill/pull/4064

[BSP] Report compilation's completion percentage

---

main/api/src/mill/api/Result.scala

This keeps the original exception as cause of mill.api.Exception, so that its message, stack traces, and those of its causes, are usually printed when a mill.api.Exception gets thrown

Don't swallow exception stack trace in mill.api.Exception

---

scalalib/src/mill/scalalib/JavaModule.scala

With the main task first, the compile-only one second, and the runtime one third
This makes it easier to change these methods, add related ones, etc.
This is already part of https://github.com/com-lihaoyi/mill/pull/4068. Opening the PR here to make it easier to review the changes here, and those of https://github.com/com-lihaoyi/mill/pull/4068 if the one here gets merged

Move scope-related tasks together in JavaModule

---

build.mill
scalalib/src/mill/scalalib/PublishModule.scala
scalalib/src/mill/scalalib/publish/Ivy.scala
scalalib/test/src/mill/scalalib/PublishModuleTests.scala

It seems `runIvyDeps` were not written in `ivy.xml` files, and thus were not resolved when publishing a Mill project locally. This fixes that.

Write runtime dependencies in ivy.xml

---

scalalib/src/mill/scalalib/publish/Pom.scala
scalalib/test/src/mill/scalalib/publish/PomTests.scala

While looking at some Mill-generated POMs, some empty sections looked odd. This PR makes Mill avoid writing them.

Avoid writing some empty sections in POMs

---

build.mill
integration/feature/full-run-logs/src/FullRunLogsTests.scala
main/util/src/mill/util/PromptLogger.scala
main/util/src/mill/util/PromptLoggerUtil.scala
main/util/test/src/mill/util/PromptLoggerTests.scala
main/util/test/src/mill/util/PromptLoggerUtilTests.scala

* Skip the two blank spaces at the left side of the header, since it looks weird on terminates with a line cursor rather than a block cursor (e.g. on Windows Terminal)
* Remove the `===` footer in non-interactive mode, since usually the end of the prompt is clear enough from context and it can be very verbose

More improvements for prompt logger

---

main/util/src/mill/util/Jvm.scala
pythonlib/package.mill
pythonlib/src/mill/pythonlib/PythonModule.scala
pythonlib/test/resources/run-background/foo/src/foo.py
pythonlib/test/src/mill/pythonlib/RunBackgroundTests.scala
scalalib/backgroundwrapper/src/mill/scalalib/backgroundwrapper/MillBackgroundWrapper.java
scalalib/src/mill/scalalib/RunModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/657
We re-use `MillBackgroundWrapper` and extend it to optionally spawn subprocess instead of calling the in-process main method. There's a bit of overhead in the JVM wrapper, but we need some kind of process wrapper to manage the mutex and termination even when the Mill process terminates, and eventually when https://github.com/com-lihaoyi/mill/issues/4007 lands we can use that to provide lighter-weight wrappers. We add a shutdown hook and copy the termination grace-period logic from OS-Lib to try and gently kill the wrapped process when necessary
Integrated this into `PythonModule#runBackground` and added a unit test to verify the asynchronous launch, background existence (by checking that a file lock is taken) and termination on …

Generalize `.runBackground` to work with all kinds of subprocesses

---

main/client/src/mill/main/client/InputPumper.java

Attempts to fix https://github.com/com-lihaoyi/mill/discussions/4092
Instead of checking `src.available() == 0`, we check for `src.read(buffer) == 0`, which should provide a more accurate measure

Always check `available()` in `InputPumper` to avoid burning CPU

---

dist/package.mill

This gives us a chance to manually announce release notifications, e.g. after some sanity checks or after Maven artifacts are available.
For pre-releases this is the right thing anyways.

Create new automatic Github reelases with `prerelease` flag

---

integration/invalidation/codesig-subfolder/src/CodeSigSubfolderTests.scala
main/codesig/src/LocalSummary.scala
runner/src/mill/runner/CodeGen.scala
runner/src/mill/runner/MillBuildRootModule.scala

We tweak the codegen and codesig analysis to avoid unnecessarily invalidating the code signatures when the set of sub-folder `package.mill` files change. Follow up of https://github.com/com-lihaoyi/mill/pull/4113
Covered by additional integration tests

More fixes for codesig stability of multi-file builds

---

example/thirdparty/mockito/build.mill
example/thirdparty/netty/build.mill
integration/ide/bsp-server/resources/snapshots/build-targets-compile-classpaths.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-modules.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-sources.json
integration/ide/bsp-server/resources/snapshots/build-targets-javac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-jvm-run-environments.json
integration/ide/bsp-server/resources/snapshots/build-targets-jvm-test-environments.json
integration/ide/bsp-server/resources/snapshots/build-targets-output-paths.json
integration/ide/bsp-server/resources/snapshots/build-targets-resources.json
integration/ide/bsp-server/resources/snapshots/build-targets-scalac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-sources.json
integration/ide/bsp-server/resources/snapshots/workspace-build-targets.json
integration/invalidation/selective-execution/src/SelectiveExecutionTests.scala
main/define/src/mill/define/Module.scala
main/define/src/mill/define/Reflect.scala
main/define/src/mill/define/Segment.scala
main/define/src/mill/define/Segments.scala
main/eval/src/mill/eval/Plan.scala
main/resolve/src/mill/resolve/ParseArgs.scala
main/resolve/src/mill/resolve/Resolve.scala
main/resolve/src/mill/resolve/ResolveCore.scala
main/src/mill/main/MainModule.scala
main/src/mill/main/SelectiveExecution.scala
main/src/mill/main/SelectiveExecutionModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4129 and https://github.com/com-lihaoyi/mill/issues/4026. We never really looked at performance at this stuff before, but in order to support `selective.prepare __` (the default of `selective.prepare`) we need to improve these bottlenecks 
* Introduces the `ResolveCore#Cache` class that holds mutable dictionaries to memo-ize various expensive parts of the task resolution logic
* Lots of micro-optimizations in various places: cache `Segments#hashCode`, avoid calling `Segments#render` for sorting or `Segments#part` for taking the last part, etc.
Brings down `time ./mill plan __` from ~60s to ~3s

Speed up task resolution and planning logic 

---

main/client/src/mill/main/client/ServerLauncher.java
runner/client/src/mill/runner/client/MillClientMain.java
runner/client/src/mill/runner/client/MillProcessLauncher.java

Fixes https://github.com/com-lihaoyi/mill/issues/4133
The problem was that the cleanup-process-folder logic running in `ServerLauncher#run` was taking place after the `terminfo` file was initially created in `runTermInfoThread`, resulting in it wiping out the `terminfo` file that then never gets re-created until you resize the terminal. 
This PR moves the cleanup logic to always run just before the `terminfo` file is created, renaming `runTermInfoThread` into `prepareMillRunFolder` and making it responsible for both cleanup of the mill process folder as well as initialization with new `terminfo` metadata

Fix Prompt Logger

---

build.mill
scalalib/src/mill/scalalib/CoursierModule.scala
scalalib/src/mill/scalalib/Dep.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/PublishModule.scala
scalalib/src/mill/scalalib/publish/Pom.scala
scalalib/test/src/mill/scalalib/BomTests.scala

Follow-up of https://github.com/com-lihaoyi/mill/pull/3924

Stop using "_" to mean empty version / version to read in BOM

---

main/client/src/mill/main/client/InputPumper.java

Fixes https://github.com/com-lihaoyi/mill/issues/4158
This hits some JVM limitations that significantly slow down the process exit, unnecessarily. Added a comment to the code so we don't forget again

Revert "Always check `available()` in `InputPumper` to avoid burning CPU (#4095)"

---

docs/package.mill

These cause issues once in a while, but in general Scaladoc bugs are outside of our control so it doesn't make sense to block PRs on them

Ignore scaladoc files in broken links checks

---

build.mill
main/client/src/mill/main/client/ServerLauncher.java
main/client/src/mill/main/client/Util.java
main/util/src/mill/util/Util.scala
runner/client/src/mill/runner/client/MillProcessLauncher.java
runner/src/mill/runner/MillMain.scala

JDK 22 introduced some changes to the method `System.console()`:
> In JDK 22, System.console() has been changed to return a Console with enhanced editing features that improve the experience of programs that use the Console API. In addition, System.console() now returns a Console object when the standard streams are redirected or connected to a virtual terminal. Prior to JDK 22, System.console() instead returned null for these cases. This change may impact code that checks the return from System.console() to test if the JVM is connected to a terminal. If required, the -Djdk.console=java.base flag will restore the old behavior where the console is only returned when it is connected to a terminal. Starting JDK 22, one could also use the new Console.isTerminal() method to test if the console …

Universal availability check for an interactive console with JDK >= 22 support

---

main/api/src/mill/api/SystemStreams.scala
main/client/src/mill/main/client/InputPumper.java

Fixes https://github.com/com-lihaoyi/mill/issues/4184
The basic problem is that we are spawning an `PumpedProcessInput` from the Mill server's redirected `stdin` to the stdin of any subprocess we spawn, but the `PumpedProcessInput`'s `InputPumper` thread only terminates on the source stream closing, and we never close the redirected `stdin` of the Mill server.
Reading from the shared `stdin` from multiple tasks/threads concurrently doesn't really make sense, so we should probably not use `PumpedProcessInput` at all and just pass in a `DummyInputStream` with zero data. Interactive use cases like consoles and repl are handled by the `os.InheritRaw` codepath anyway and so won't be affected. `stdout`/`stderr` aren't affected, because having multiple tasks/threads writing lines to the same …

Fix pumper thread leak

---

kotlinlib/src/mill/kotlinlib/ktlint/KtlintModule.scala

This PR improves `ktlint` support: it explicitly specifies the files to process.
Without that current `mill.kotlinlib.ktlint.KtlintModule/checkFormatAll` run, for example, will go through the files under the `out` folder, which is useless and pollutes logs.
Also this PR removes redundant flags from `reformatAll` and `checkFormatAll`: former will always be with `format=true` by definition, the latter will always be with `format=false`.

Specify exact files to process in ktlint run

---

.github/actions/post-build-setup/action.yml
example/cli/builtins/1-builtin-commands/build.mill

https://github.com/com-lihaoyi/mill/commit/b26fb7c346c95379e582f1763d8f33a6845a3e73 removed one of the `chmod`s that was necessary to keep the filesystem permissions consistent, this PR puts it back
Tested using this PR, verified that the touched `example.cli.builtins[1-builtin-commands].local.test` test is the only one picked up by test selection (https://github.com/com-lihaoyi/mill/actions/runs/12545856782/job/34980872995?pr=4205), the rest are all skipped

Fix Selective Test Execution on PRs

---

main/api/src/mill/api/ClassLoader.scala
runner/src/mill/runner/MillMain.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4164
It's been around since we used to use Ammonite to compile scripts, and IIRC was necessary to make the in-memory Scala compiler work. We no longer go through that code path, so maybe we can get rid of it? AFAIK we now only use the Scala compiler through Zinc which manages this stuff itself

Check if rt.jar is still necessary

---

kotlinlib/src/mill/kotlinlib/ktlint/KtlintModule.scala

Fix small typo made in https://github.com/com-lihaoyi/mill/pull/4201 - `checkFormalAll` task should fail in case of formatting violations.

Use `check=true` for ktlint `checkFormatAll` run

---

scalalib/src/mill/scalalib/SemanticDbJavaModule.scala

Fixes https://github.com/joan38/mill-scalafix/issues/213

Don't fail semanticDbData if classes dir does not exist

---

.github/workflows/scala-steward.yml

It does not trigger other actions somehow, so we don't get any feedback if bumps are working. It's also redundant to the Scala Steward runs by https://github.com/scala-steward.
Keep the `workflow_dispatch` setup nevertheless, to be able to run Scala Steward in case the official service fails again, since we see more error message when running it manually.

Disable scala-steward action

---

docs/modules/ROOT/pages/cli/flags.adoc
runner/src/mill/runner/MillCliConfig.scala
runner/src/mill/runner/MillMain.scala

When the NO_COLOR env variable is set,
then avoid coloring the terminal.
--color argument does overrides the env variable
Inspired by https://no-color.org
and asked in discussion: https://github.com/com-lihaoyi/mill/discussions/4170

Honor the NO_COLOR env variable

---

.github/workflows/post-build-selective.yml

Cherry-picked from https://github.com/com-lihaoyi/mill/pull/4188/files, hopefully improves some of the flakiness we've been seeing

Run android CI job without parallelism

---

integration/invalidation/run-background/resources/build.mill
integration/invalidation/run-background/resources/foo/src/foo/Foo.java
integration/invalidation/run-background/src/RunBackgroundTests.scala
main/util/src/mill/util/Jvm.scala

This might have been the cause of a lot of flakiness that seems to have gone away with https://github.com/com-lihaoyi/mill/pull/4254, as the server exiting caused the `runBackground` calls to exit causing the http servers to exit and fail to pick up requests.
Might have been caused by https://github.com/com-lihaoyi/os-lib/pull/324 which made `destroyOnExit` the default for spawned subprocesses. This PR explicitly disables `destroyOnExit` for the subprocesses where `background = true`
Covered by a new `integration.invalidation` test that runs under  both `server` and `fork`, that previously failed when run under `fork`

WIP fix `runBackground` with `-i`/`--no-server` 

---

example/android/javalib/1-hello-world/build.mill
example/android/kotlinlib/1-hello-kotlin/build.mill
scalalib/src/mill/javalib/android/AndroidAppModule.scala

I've tried to replicate why the timeouts related to the android emulator that happen in github actions. It seems that  the `adb wait-for-device` is stuck although I cannot replicate it locally and the kotlin example does not suffer the same issue.
So for now, I added some wait time after start emulator and a call to `adb device` to verify the device is indeed present and it seems to be working.
This should work for the time being and make the job green until we create a better alternative.
Small change included: Since we throw an error if we don't detect the boot notification of start emulator, I changed the `startAndroidEmulator` signature from `Option[String]` to `String`
Linking the green job on my copy for reference: https://github.com/vaslabs-ltd/mill/actions/runs/12651834850/job/3525 …

Replace waiting for android emulator with a sleep and a list device call to verify emulator is running

---

integration/ide/bsp-server/src/BspServerTestUtil.scala

Added some logging and reproduced the failure locally, indicating the flakiness is caused it is a sequence ordering instability in the return value of `workspaceBuildTargets`
```diff
[3387-1] X mill.integration.BspServerTests.requestSnapshots 32882ms 
[3387-1]   os.SubprocessException: Result of git…: 1
[3387-1]   diff --git a/var/folders/rt/f1pd6fz92x3__6jg0cmgdd580000gn/T/2103572287842600910jsonStr b/var/folders/rt/f1pd6fz92x3__6jg0cmgdd580000gn/T/16267358687599680664expectedJsonStr
[3387-1]   index 8935f3ef329..3ac57e39baa 100644
[3387-1]   --- a/var/folders/rt/f1pd6fz92x3__6jg0cmgdd580000gn/T/2103572287842600910jsonStr
[3387-1]   +++ b/var/folders/rt/f1pd6fz92x3__6jg0cmgdd580000gn/T/16267358687599680664expectedJsonStr
[3387-1]   @@ -2,16 +2,17 @@
[3387-1]      "targets": [
[3387-1] …
```

Improve debug logging for `integration.ide[bsp-server].local`

---

build.mill
integration/invalidation/run-background/src/RunBackgroundTests.scala
main/src/mill/main/MainModule.scala

fixes https://github.com/com-lihaoyi/mill/issues/4260
With `ignoreErrors = true`, we ignore the `.mill-background-process-lock` file, and proceed to delete the `.mill-background-process-uuid` file, which is enough to make the process exit even if the un-used lock file is hanging around after

Use `ignoreErrors = true` to make `clean` work on `runBackground` subprocesses on windows

---

integration/ide/bsp-server/resources/snapshots/build-targets-compile-classpaths.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-modules.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-sources.json
integration/ide/bsp-server/resources/snapshots/build-targets-javac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-jvm-run-environments.json
integration/ide/bsp-server/resources/snapshots/build-targets-jvm-test-environments.json
integration/ide/bsp-server/resources/snapshots/build-targets-output-paths.json
integration/ide/bsp-server/resources/snapshots/build-targets-resources.json
integration/ide/bsp-server/resources/snapshots/build-targets-scalac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-sources.json
integration/ide/bsp-server/resources/snapshots/workspace-build-targets.json
integration/ide/bsp-server/src/BspServerTestUtil.scala
main/define/src/mill/define/Reflect.scala

It seems sometimes `reflect` was returning reflected modules in different orders, so we make sure to always sort them before returning

Try and stabilize `integration.invalidation[bsp-server]` tests 

---

integration/ide/bsp-server/resources/project/build.mill
integration/ide/bsp-server/resources/snapshots/build-targets-compile-classpaths.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-modules.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-sources.json
integration/ide/bsp-server/resources/snapshots/build-targets-javac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-jvm-run-environments.json
integration/ide/bsp-server/resources/snapshots/build-targets-jvm-test-environments.json
integration/ide/bsp-server/resources/snapshots/build-targets-output-paths.json
integration/ide/bsp-server/resources/snapshots/build-targets-resources.json
integration/ide/bsp-server/resources/snapshots/build-targets-scalac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-sources.json
integration/ide/bsp-server/resources/snapshots/workspace-build-targets.json

This PR adds multi-module non-regression tests of the BSP support. This is helpful for https://github.com/com-lihaoyi/mill/pull/4145, that touches some BSP things in `MillBuildServer`.

Add multi-module BSP tests

---

.github/workflows/publish-artifacts.yml
dist/package.mill

* We need separate jobs per OS and CPU architecture because Graal cannot cross-build
* For now, I'm only publishing on the default CPU architecture per OS: x64 for linux, ARM for Mac
* Skipping Windows for now

Publishing configuration for Graal native images

---

.github/workflows/post-build-selective.yml
example/android/javalib/1-hello-world/build.mill
example/android/kotlinlib/1-hello-kotlin/build.mill
scalalib/src/mill/javalib/android/AndroidAppBundle.scala
scalalib/src/mill/javalib/android/AndroidAppModule.scala

This should fix the android job back to green and has some improvements on handling the android emulator in the CI (and locally) , part of which eliminates the need for sleep hack in documentation examples.
Job reference on my fork can be found [here](https://github.com/vaslabs-ltd/mill/actions/runs/12688329695/job/35364858469) . ~~Sometimes the device may be stuck in unauthorized, I don't know the reason yet and can't yet replicate it locally .~~
In https://github.com/ReactiveCircus/android-emulator-runner, it seems that the same issue occurs when caching is used. ~~I'm wondering if there's any implicit caching that I have missed in the github actions~~
After experimenting with https://github.com/vaslabs-ltd/test-android-emulator , it seems that the runner avd directory is polluted. …

Eliminate sleep from android emulator doc examples

---

.gitignore
build.mill
ci/test-mill-bootstrap.sh
ci/test-mill-release.sh
dist/package.mill
example/package.mill
integration/invalidation/multi-level-editing/src/MultiLevelBuildTests.scala
integration/invalidation/version-change/resources/build.mill
integration/invalidation/version-change/src/VersionChangeTests.scala
integration/package.mill
main/client/src/mill/main/client/EnvVars.java
main/client/src/mill/main/client/ServerLauncher.java
main/client/src/mill/main/client/Util.java
main/client/test/src/mill/main/client/MillEnvTests.java
main/eval/src/mill/eval/GroupEvaluator.scala
main/server/test/src/mill/main/server/ClientServerTests.scala
mill
readme.adoc
runner/client/src/mill/runner/client/CoursierClient.scala
runner/client/src/mill/runner/client/MillClientMain.java
runner/client/src/mill/runner/client/MillProcessLauncher.java
runner/package.mill
scalalib/src/mill/scalalib/NativeImageModule.scala

* Bootstrap native image JVM using Coursier, rather than just hardcoding `java`
* Allow custom JVMs to be used for Mill server by specifying `.mill-jvm-version`
* Make sure we use separate download paths for `-native` and non`-native` mill executables
* Tidy up `dist/package.mill`
* Remove unnecessary `def fix` overrides now that `.fix` on empty modules no longer crashes

Cleanup after native image

---

.github/workflows/run-tests.yml

Now that we'll have an OS-X publishing job for native image, we need to make sure that some basic smoketests pass on PRs before we merge them

Add OS-X CI smoketest job

---

.github/ISSUE_TEMPLATE.md
.github/workflows/draft-ci.yml
.github/workflows/publish-artifacts.yml
.github/workflows/run-tests.yml

This PR aims to reduce the bottleneck of contributors waiting for CI jobs on the shared Mill repo by moving CI for draft/WIP pull requests to each contributor's own fork, each of which has a separate concurrency budget (~20 concurrent workers) from the `com-lihaoyi` organization. 
Once a PR is marked ready-for-review, `com-lihaoyi` CI begins, so the author effectively has a choice of where they want to run their CI workloads. Mill's main PR validation CI jobs are portable, do not need any special secrets or environment, and can run just fine in contributor's GH Actions environments
To do this:
* Made the upstream `build-linux`/`build-windows`/`test-docs` CI jobs filter on `github.event.pull_request.draft == false`, and 
* Removed the `branches: - main` filter on the `run-tests` jobs so …

Move CI jobs for draft PRs to contributor's personal forks of Mill

---

.github/workflows/draft-ci.yml
.github/workflows/pre-build.yml
.github/workflows/publish-docs.yml
.github/workflows/run-tests.yml
build.mill

* Try to consolidate `Draft CI / link` and `Draft CI / run` statuses
* Remove debug echoes
* Make selective testing work on draft PRs running on user forks
* Make `millLastTag` rely on `MILL_STABLE_VERSION=1`, update `publish-docs` with that env var, and make `mac`  nad `test-docs` jobs do shallow clones
* Consolidate `action == ready_for_review`/`draft == false` checks under a single `main-ci` job that everyone else depends on

Test Draft PR

---

scalalib/src/mill/javalib/android/AndroidAppModule.scala

The following small PR is part of integrating android studio with mill, so it is focused on developer experience. This was already mentioned as a TODO in the androidDebugKeystore method. The screenshot below is with an attempt to hook together android studio and mill and deleting the out directory, then trying to run the bsp test (work pending)
So far, the debug keystore, is stored in the task destination directory, which makes it ephemeral, even for a local development device, as out directory can be wiped frequently.
We followed a similar approach that gradle and android studio use, excluding the lock file. So I'm marking this PR as draft and asking for opinions on:
1. should we handle multi-process access to the debug keystore (i.e. use a file lock)?
2. is it a problem that we break …

Part of Android Studio Integration: Fix apk installation failure

---

example/scalalib/dependencies/1-ivy-deps/build.mill

Please open all PRs as drafts and ensure that your fork of Mill has 
`settings/actions` / `Allow all actions and reusable workflows` enabled to run CI on
your own fork of the Mill repo. Only once CI passes mark the PR as `Ready for review`
and CI will run on the main Mill repo before we merge it.

Dependencies: fix documentation

---

example/extending/jvmcode/3-worker/build.mill
main/api/src/mill/api/ClassLoader.scala
runner/src/mill/runner/MillBuildBootstrap.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4316
This isn't a general solution to make context classloaders behave properly in the presence of long-lived worker objects instantiated from classloaders. Rather, we just hard-code support in the Scala3 docjar callsite to properly set the context classloader there, since these context-classloader-sensitive pieces of code are pretty rare in Mill and so we can just deal with them individually as they pop up
CC @joan38

Fix docjar context classloader conflict in scala 3

---

scalalib/src/mill/scalalib/ZincWorkerModule.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Previously we closed the nested classloaders, but the classloader we used to spawn `ZincWorkerImpl` itself was leaked

Properly close `ZincWorkerImpl` classloader when worker shuts down

---

example/android/javalib/1-hello-world/build.mill
example/android/kotlinlib/1-hello-kotlin/build.mill
scalalib/src/mill/javalib/android/AndroidAppModule.scala
scalalib/src/mill/javalib/android/InstrumentationOutput.scala
scalalib/test/src/mill/javalib/android/InstrumentalOutputReportTest.scala

As part of our testing to integrate Mill with Android Studio, we are experimenting with BSP integration. The stubbed test method is not compatible with the expected BSP interfaces. 
The raw output provided in ADB instrumented testing is translated to TestResults as expected from the test module interface. 
- Handling parallelization 
- Selectors ( e.g for use in test only )
- Test failure scenarios ( with examples )
- Stack traces and test output

Part of Android Studio Integration: Standardize test output

---

main/client/src/mill/main/client/lock/FileLock.java

I've been getting exceptions such as these lately, using Mill `0.12.5`:
```text
An unexpected error occurred java.nio.channels.OverlappingFileLockException
java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1522)
java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1360)
mill.main.client.lock.FileLock.tryLock(FileLock.java:21)
mill.runner.MillMain$.withOutLock(MillMain.scala:447)
mill.runner.MillMain$.$anonfun$main0$9(MillMain.scala:247)
mill.runner.MillMain$.$anonfun$main0$9$adapted(MillMain.scala:225)
mill.runner.Watching$.watchLoop(Watching.scala:29)
mill.runner.MillMain$.$anonfun$main0$8(MillMain.scala:277) …
```

Handle OverlappingFileLockException in FileLock

---

.github/workflows/run-tests.yml
main/util/src/mill/util/Jvm.scala
readme.adoc
scalalib/test/resources/launcher/src/Main.java
scalalib/test/src/mill/scalalib/LauncherTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4302
We largely copy the existing implementation `dist/package.mill`. Once we rebootstrap, we can cut over to the new `Jvm.*` implementation and remove the version in `dist/`. Added some unit tests to exercise the `JAVA_HOME`/`JAVA_OPTS` handling

Upstream Mill's `dist.launcherScript` into `mill.util.Jvm.launcherUniversalScript`

---

build.mill
example/large/selective/9-selective-execution/build.mill
main/codesig/src/ResolvedCalls.scala
main/eval/src/mill/eval/EvaluatorCore.scala
main/eval/src/mill/eval/EvaluatorLogs.scala
main/src/mill/main/MainModule.scala
main/src/mill/main/RunScript.scala
main/src/mill/main/SelectiveExecution.scala
main/src/mill/main/SelectiveExecutionModule.scala
main/util/src/mill/util/SpanningForest.scala
testkit/src/mill/testkit/ExampleTester.scala

Also lots of general refactoring for the SelectiveExecution/SpanningForest logic
I need this myself to help debug https://github.com/com-lihaoyi/mill/issues/4343

Add `selective.resolveTree` task to help debug selective execution misbehaviors

---

example/depth/javahome/1-custom-jvms/build.mill

Zinc modules' names were referring to a different java version than the one they actually defined
**Suggestion**: drop the version number in these names ?

Fix version typos in JVM versions example

---

dist/package.mill

This is a step to moving them off of Github to Maven Central, where we have stronger guarantees (e.g. immutability) and a narrower service dependency list (Mill already depends on maven central anyway, and this removes the dependency on Github). With 0.13.0 I expect to remove these artifacts from Github Releases entirely
We still have some Github release download dependencies, e.g. some JVM downloads come from Github, but at least for things that are within our control it's better for them to be on maven central

Cross-publish example and launcher artifacts to maven central

---

.github/workflows/publish-artifacts.yml
.github/workflows/run-tests.yml
example/kotlinlib/basic/1-simple/build.mill

The mac-latest and mac-13 workers seem significantly slower than the default linux worker, so just run a single thirdparty example as a smoketest on each one

Test PR for intel mac-13 job

---

dist/package.mill

The Mill Client only forwards requests and therefore does not need much memory.
However, Java doesn't know that an allocates a large heap based on the machines memory size.
Therefore, give a way lower heap limit,
creating a leaner client memory wise.
Example on my machine:
- Before: A Mill client reserved ~500MByte
- After: A Mill client reserves the specified 24Mbyte
This is mostly relevant for a long running mill client (examples  `--watch` clients, `-i --no-build-lock` and --bsp`).

Reduce Java Heap for Mill Client

---

example/android/javalib/1-hello-world/app/src/androidTest/java/com/helloworld/app/ExampleInstrumentedTest.java
example/android/javalib/1-hello-world/app/src/main/java/com/helloworld/SampleLogic.java
example/android/javalib/1-hello-world/app/src/test/java/com/helloworld/ExampleUnitTest.java
example/android/javalib/1-hello-world/build.mill
example/android/kotlinlib/1-hello-kotlin/app/src/androidTest/java/com/helloworld/app/ExampleInstrumentedTest.kt
example/android/kotlinlib/1-hello-kotlin/app/src/main/java/com/helloworld/app/MainActivity.kt
example/android/kotlinlib/1-hello-kotlin/build.mill
example/android/kotlinlib/2-compose/build.mill
kotlinlib/src/mill/kotlinlib/android/AndroidAppKotlinModule.scala
scalalib/src/mill/javalib/android/AndroidAppBundle.scala
scalalib/src/mill/javalib/android/AndroidAppModule.scala
scalalib/src/mill/javalib/android/AndroidTestModule.scala
scalalib/src/mill/scalalib/JavaModule.scala

- ability to import a mill android project to android studio via BSP, including sources and generated sources.
- necessary changes to the way sources are resolved (through module dependency instead of class inheritance).
- Changes to tests (e.g. number of sources compiled) reflect these changes
- Compilation still needs to be done from the command line in order for the paths to be resolved inside the IDE.
Note that to make compilation, running, testing and debugging work from android studio, we'll need to develop a plugin for it
This is an early draft and I need to cleanup or review a few rough edges, I submit this as a draft to get some early feedback. 
I've implemented java to get the basics to work, as kotlin has multiple kinds of sources and files that need to be taken care of, so …

Android Studio Integration: Attempt via bsp for Java android apps

---

docs/modules/ROOT/pages/scalalib/publishing.adoc
example/scalalib/publishing/8-native-image-config-scala/build.mill
example/scalalib/publishing/8-native-image-config-scala/foo/src/Foo.scala

We already have an equivalent Java example, so this adds a Scala version. Still missing a Kotlin version but that can come later

Add Scala graal native image example with libraries

---

docs/modules/ROOT/pages/migrating/maven.adoc

This is from reviewing #4363. I couldn't comment on this because it was not part of the changes.

Fix a possible typo in "maven.adoc"

---

kotlinlib/test/src/mill/kotlinlib/HelloWorldTests.scala
kotlinlib/worker/impl/src/mill/kotlinlib/worker/impl/KotlinWorkerImpl.scala

It seems this class was renamed in https://youtrack.jetbrains.com/issue/KT-70221
Updated the unit test to exercise `2.1.0`, fails before this change, passes with. The existing kotlin versions seem to continue working AFAICT

Fix kotlin 2.1.0 support by using  `K2JsCompiler` instead of `K2JsIrCompiler`

---

.github/actions/post-build-selective/action.yml
.github/actions/pre-build-setup/action.yml
.github/workflows/run-tests.yml

Minimized in https://github.com/com-lihaoyi/mill/pull/4357, it appears the difference in behavior comes from different JVM versions being used during `selective.prepare` and `selective.{resolve,run}` phases

Fix selective testing of native example tests by adding jvm version override

---

example/package.mill

The earlier PR defined `ExampleCrossModuleAndroid` but didn't use it

Fix android example test exclusive flag

---

scalalib/src/mill/scalalib/JavaModule.scala

Resolve #4451 
It seems that `transitiveCoursierProjects` is populated with repetitive transitive modules, that's why it only causes problem for large build.

Fix `transitiveCoursierProjects` cause OOM on large build

---

scalalib/src/mill/scalalib/JavaModule.scala

Resolve #4451 
It seems that `transitiveCoursierProjects` is populated with repetitive transitive modules, that's why it only causes problem for large build.
Please open all PRs as drafts and ensure that your fork of Mill has 
`settings/actions` / `Allow all actions and reusable workflows` enabled to run CI on
your own fork of the Mill repo. Only once CI passes mark the PR as `Ready for review`
and CI will run on the main Mill repo before we merge it.

Fix `transitiveCoursierProjects` cause OOM on large build (#4452)

---

integration/feature/inspect/src/InspectTests.scala
integration/feature/scala-3-syntax/resources/sub/package.mill
main/define/src/mill/define/Discover.scala
main/resolve/src/mill/resolve/Resolve.scala
main/src/mill/main/MainModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/3893
- Recurse over all module parent classes, in addition to member return types
- Remove `allNames`, since it can now be derived from the `declaredNames` of every module class
- Make `entryPoints` only store the entrypoints specifically declared for each class, and not those inherited
Reduces the size of `out/mill-build/compile.dest/classes//build_/package_$.class` in the Mill repo from 820K to 73K. Haven't measured but I would expect a decrease in compile times as well

Reduce size of generated code in Discover macro

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/large/multi-language-builds.adoc
example/large/multi/14-multi-language/build.mill
example/large/multi/14-multi-language/client/public/index.html
example/large/multi/14-multi-language/client/src/App.css
example/large/multi/14-multi-language/client/src/app/App.tsx
example/large/multi/14-multi-language/client/src/index.tsx
example/large/multi/14-multi-language/client/src/test/App.test.tsx
example/large/multi/14-multi-language/sentiment-analysis/src/foo.py
example/large/multi/14-multi-language/sentiment-analysis/test/src/test.py
example/large/multi/14-multi-language/server/resources/application.properties
example/large/multi/14-multi-language/server/src/com/example/AnalysisController.java
example/large/multi/14-multi-language/server/src/com/example/Server.java
example/large/multi/14-multi-language/server/src/com/example/StaticPageController.java
example/large/multi/14-multi-language/server/test/src/com/example/ServerTest.java
example/pythonlib/basic/1-simple/build.mill

Back-port PR #4476 into `0.12.x`

[BACKPORT] Write a doc example on multi-language Mill projects

---

example/javalib/linting/3-palantirformat/build.mill
scalalib/src/mill/javalib/palantirformat/PalantirFormatBaseModule.scala
scalalib/src/mill/javalib/palantirformat/PalantirFormatModule.scala
scalalib/src/mill/scalalib/scalafmt/ScalafmtModule.scala

Having a quick quantitative feedback what goes on is always nice and helps spotting issues.
For example, I tried to manually format the code base with two different source selectors, from which I assumed they should have the same effect. But they didn't. After this change, the difference would be obvious.
```
> mill mill.javalib.palantirformat.PalantirFormatModule/formatAll --check __:JavaModule.sources
[437] checking format in 109 java sources ...
> mill mill.javalib.palantirformat.PalantirFormatModule/formatAll --check __.sources
[947] checking format in 259 java sources ...
```
Obviously, there are Java sources in non-Java modules.

Add file count to `PalantirFormatModule` output

---

core/client/src/mill/client/ClientUtil.java
core/client/src/mill/client/Util.java
runner/client/src/mill/runner/client/MillClientMain.java
runner/src/mill/runner/MillBuildBootstrap.scala
runner/src/mill/runner/MillMain.scala
runner/src/mill/runner/worker/ScalaCompilerWorker.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4498
Turns out we were instantiating a new Classloader to hold the Scala 3 compiler worker every run, which is expensive, even though the worker is the same every time. This PR moves the compile worker to a global `lazy val` so it can be reused.
Also replaced `hexArray` with a implementation that avoids `String.format` and `BigInteger`, because they were appearing in the Jprofiler profiles, and replaces a `sha1Hash` call with `md5hex` since the callsite doesn't require a cryptographic hash
Tested manually, makes warm launch times drop back to similar to 0.12.7

Fix launch time regression in Scala 3 upgrade

---

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
core/define/src/mill/define/internal/Applicative.scala
core/exec/src/mill/exec/Execution.scala
core/exec/src/mill/exec/ExecutionCore.scala
core/exec/src/mill/exec/GroupExecution.scala
core/exec/test/src/mill/exec/Checker.scala
core/exec/test/src/mill/exec/EvaluationTests.scala
core/exec/test/src/mill/exec/ModuleTests.scala
core/exec/test/src/mill/exec/OverrideTests.scala
core/exec/test/src/mill/exec/TaskTests.scala
core/src/mill/eval/Evaluator.scala
core/src/mill/eval/SelectiveExecution.scala
idea/src/mill/idea/GenIdeaImpl.scala
main/init/test/src/mill/init/InitModuleTests.scala
main/src/mill/main/MainModule.scala
main/src/mill/main/SelectiveExecutionModule.scala
main/test/src/mill/main/MainModuleTests.scala
runner/src/mill/runner/MillBuildBootstrap.scala
scalalib/src/mill/scalalib/dependency/versions/VersionsFinder.scala
scalalib/test/src/mill/scalalib/giter8/Giter8Tests.scala
testkit/src/mill/testkit/UnitTester.scala

* Fold `evalOrThrow` into normal `evaluate` code path, rename to `evaluateValues`
* Rename the various methods in `exec` from `evaluate` to `execute`
* Fold `MainModule.resolve*` into `Evaluator#resolve*`
* Break out an `mill.exec.Execution` object so that `Evaluator` doesn't need to directly inherit all of `ExecutionCore`/`GroupExecution`

Cleanup `Evaluator` public API

---

.github/workflows/run-tests.yml

Exclude all integration and test modules.

CI: Limit the dependency trees to essential modules

---

example/package.mill

Since we use Scala string intrpolation as a low cost template engine,
we need to avoid `.stripMargin`, as it may over-eager strip margin symbols
from the interpolated variables.
Fix https://github.com/com-lihaoyi/mill/issues/4542

Avoid `.stripMargin` when rendering documentation from example modules

---

website/package.mill

Fixes https://github.com/com-lihaoyi/mill/issues/4547
The original PR https://github.com/com-lihaoyi/mill/pull/4510 was a bit too over-eager at find-replacing `docs/` in the codebase; in this case, it was configuration for old versions of Mill, whose `docs/` folders still have not changed.
Tested via `./mill -w website.githubPages`; fails without this PR, passes with. Was not caught on the PR last time because we only test the `website.fastPages` on PRs to reduce latencies

Fix doc publishing

---

core/define/src/mill/define/Task.scala
core/exec/src/mill/exec/GroupExecution.scala
main/test/src/mill/util/TestUtil.scala

For now mostly superficial cleanups: reducing duplication, extracting helpers, renaming `Target.Internal` to `TaskMacros`, etc. But this should pave the way for more cleanup in follow up PRs

Clean up `Task.scala`

---

contrib/testng/src/mill/testng/ResultEvent.java
contrib/testng/src/mill/testng/TestNGRunner.java

needed for: https://github.com/scalameta/metals/pull/7200
This allows to select and run single tests in Metals using TestNGFramework.
Previously only whole suite selection was possible.
Tested it manually as visible on the GIF above.

feat: support test case selection in TestNG framework

---

core/define/src/mill/define/Task.scala
core/define/src/mill/define/internal/Applicative.scala
core/define/test/src/mill/define/ApplicativeTests.scala
core/define/test/src/mill/define/ApplicativeTestsBase.scala
core/define/test/src/mill/define/Opt.scala

This PR removes some of the divergence between the test implementation `Opt` and the real implementation `Task`, and simplifies the underlying abstraction by dropping unnecessary type parameters and members

Simplify Applicative.scala

---

build.mill
scalalib/package.mill
scalalib/src/mill/javalib/palantirformat/PalantirFormatBaseModule.scala
scalalib/src/mill/javalib/palantirformat/PalantirFormatModule.scala

Instead of a hardcoded version we use one defined in the outer Mill build.

Avoid hardcoded version in PalantirFormatModule

---

contrib/scoverage/test/src/mill/contrib/scoverage/HelloWorldTests.scala
scalalib/src/mill/scalalib/AssemblyModule.scala
scalalib/src/mill/scalalib/JavaModule.scala

Backport of https://github.com/com-lihaoyi/mill/pull/4565

[BACKPORT] Separate resolvedRunIvyDeps and transitiveLocalClasspath into two stages when build assembly jar 

---

scalalib/src/mill/scalalib/TestModuleUtil.scala

Should fix the rebootstrap problems found in https://github.com/com-lihaoyi/mill/pull/4545 and https://github.com/com-lihaoyi/mill/pull/4570 that seems to be caused by a mistake in this backport https://github.com/com-lihaoyi/mill/pull/4504. Not sure why this causes a hang, but for now just fixing it to revert to the previous semantics
Tested manually via
```bash
./mill dist.installLocal
git checkout main
./mill-assembly.jar 'integration.invalidation[selective-execution].local.fork.test' mill.integration.SelectiveExecutionWatchTests.watch.changed-code
```
Doing this manually on `0.12.x` hangs, whereas doing it on this PR succeeds

Fix hang on `mill.integration.invalidation[selective-execution]`

---

build.mill
integration/feature/inspect/resources/core3/package.mill
integration/feature/inspect/src/InspectTests.scala
main/src/mill/main/Inspect.scala
runner/src/mill/runner/CodeGen.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4508
Due to how the codegen works, the scaladoc on `RootModule`s ends up on the generated companion class rather than on the `object`. The mill-moduledefs scaladoc plugin wasn't capturing Scaladoc on `class`s, which was fixed on https://github.com/com-lihaoyi/mill-moduledefs/commit/b0064b61c4e26e7abc155a87eb3bac2ca4477668. I then updated `Inspect.scala` to look for `RootModule` objects by name and try to fetch the scaladoc from the companion class
Tweaked the unit test to exercise this scenario

Fix Scaladoc capture on `RootModule`s

---

.github/workflows/run-tests.yml
core/constants/src/mill/constants/ServerFiles.java
integration/failure/fatal-error/src/FatalErrorTests.scala
integration/invalidation/multi-level-editing/src/MultiLevelBuildTests.scala
integration/invalidation/process-file-deleted-exit/resources/build.mill
integration/invalidation/process-file-deleted-exit/src/ProcessFileDeletedExit.scala
runner/client/src/mill/runner/client/MillProcessLauncher.java
runner/server/src/mill/main/server/Server.scala
runner/server/test/src/mill/main/server/ClientServerTests.scala
runner/src/mill/runner/MillMain.scala
testkit/src/mill/testkit/ExampleTester.scala
testkit/src/mill/testkit/IntegrationTester.scala
testkit/src/mill/testkit/IntegrationTesterBase.scala
testkit/test/resources/example-test-example-project/build.mill
testkit/test/src/mill/testkit/ExampleTesterTests.scala
testkit/test/src/mill/testkit/IntegrationTesterTests.scala
testkit/test/src/mill/testkit/TestkitTestUtils.scala

This attempts to fix some of the residual flakiness encountered in https://github.com/com-lihaoyi/mill/pull/4570
Somehow the recursive process termination we pulled in from upstream https://github.com/com-lihaoyi/os-lib/pull/359 only works some of the time, and other times the processes get leaked. This PR extends the `serverId`-file-deleted shutdown logic we already used for client-server mode and enables it for `--no-server` mode as well. This lets us put an additional guardrail in our `IntegrationTester#close` to delete any such files, to try and force any Mill processes to terminate.
Added an additional integration test to exercise this behavior
Also fixed a bug in `ExampleTester` not honoring the `clientServerMode` flag, and update `testkit.test` to assert on those behaviors

Make `--no-server` mode also terminate on removal of `processId` file, use it in integration test cleanup 

---

mill.bat

Fixes https://github.com/com-lihaoyi/mill/issues/4414
We only need to do this on windows, since on Linux and Mac we support both ARM and Intel

Ignore `-native` suffix on Windows-ARM and fall back to JVM

---

core/define/src/mill/define/Cross.scala
core/define/src/mill/define/Segments.scala
core/resolve/src/mill/resolve/ParseArgs.scala
integration/feature/root-cross-module/resources/bar/package.mill
integration/feature/root-cross-module/resources/build.mill
integration/feature/root-cross-module/src/RootCrossModuleTests.scala

Implements #3693 
These seem to be the minimal changes to allow RootModule and Cross to be applied to the same module. 
it was only necessary to make `Cross` a trait. I did try making `RootModule` also a trait but it proved a little trickier due to it usign the class constructor for `BaseModule` that it extends. 
The main issue I ran into that caused me to have to remove the implicit parameter on `Cross` was the Ctx implicit was not being filled in properly and i was seeing `Modules and Tasks can only be defined within a mill Module` from the dummy being used. There may have been a way around this in the `CrossMacros`, but I couldn't see it, and this solution appears to work, at least for the examples shown in the integration tests added.

feat: RootModule and Cross can be applied to the same module

---

example/scalalib/basic/2-custom-build-logic/build.mill
website/docs/modules/ROOT/nav.adoc
website/docs/modules/ROOT/pages/cli/flags.adoc
website/docs/modules/ROOT/pages/comparisons/gradle.adoc
website/docs/modules/ROOT/pages/comparisons/unique.adoc
website/docs/modules/ROOT/pages/depth/caching.adoc
website/docs/modules/ROOT/pages/depth/evaluation-model.adoc
website/docs/modules/ROOT/pages/depth/parallelism.adoc
website/docs/modules/ROOT/pages/depth/process-architecture.adoc
website/docs/modules/ROOT/pages/fundamentals/tasks.adoc
website/docs/modules/ROOT/pages/index.adoc

First step to fix https://github.com/com-lihaoyi/mill/issues/4603.
The pages are pretty thin, but can be fleshed out over time

Break out separate `Caching in Mill` and `Parallelism in Mill` pages

---

website/docs/modules/ROOT/pages/depth/caching.adoc
website/docs/modules/ROOT/pages/depth/evaluation-model.adoc
website/docs/modules/ROOT/pages/depth/parallelism.adoc

Mostly adding cross-references to relevant builtin commands and out-dir files

More documentation improvements for Mill parallelism and caching

---

scalalib/src/mill/scalalib/ScalaModule.scala
scalalib/test/resources/hello-world-mixed/core/src/Foo.scala
scalalib/test/resources/hello-world-mixed/core/src/JFoo.java
scalalib/test/src/mill/scalalib/ScalaMixedProjectSemanticDbTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/2981
The approach taken is the first one suggested by @Lefou in the issue, namely detect whether the project is mixed, and avoid stopping the compilation after the semanticdb phase when it is the case.

[ISSUE-2981] Fix `semanticdbData` for mixed scala/java projects

---

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala

Prevents having to iteratively querying the location of each artifact's resolved files. This makes a big difference in large mill projects.

Improve performances of `Bloop/install`

---

.github/actions/post-build-selective/action.yml
core/exec/src/mill/exec/CodeSigUtils.scala
core/exec/src/mill/exec/Execution.scala
core/exec/src/mill/exec/GroupExecution.scala
core/src/mill/eval/Evaluator.scala
core/src/mill/eval/SelectiveExecution.scala
example/fundamentals/out-dir/1-out-files/build.mill
runner/src/mill/runner/MillBuildBootstrap.scala
runner/src/mill/runner/MillBuildRootModule.scala
runner/src/mill/runner/RunnerState.scala
testkit/src/mill/testkit/UnitTester.scala
website/docs/modules/ROOT/pages/depth/caching.adoc

This simplifies the name and brings it inline with the internal terminology of the `codesig` module

Rename `methodCodeHashSignatures` to `codeSignatures`

---

ci/mill-bootstrap.patch

Seems the bootstrap job on CI consistently fails, like [here](https://github.com/com-lihaoyi/mill/actions/runs/13409951292/job/37459400148). This should fix it.

Fix 0.12.x branch bootstrap job

---

build.mill
contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
scalalib/src/mill/scalalib/JsonFormatters.scala
scalalib/test/src/mill/scalalib/BomTests.scala

Report of #4591 against `0.12.x`

Update coursier to 2.1.25-M2 (adds early Gradle Module support) - 0.12.x

---

contrib/bloop/src/mill/contrib/bloop/Bloop.scala
contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
developer.adoc
integration/ide/bloop/src/BloopTests.scala
integration/package.mill
main/package.mill
main/util/src/mill/util/CoursierSupport.scala
runner/src/mill/runner/MillBuildRootModule.scala
scalalib/src/mill/scalalib/CoursierModule.scala
testkit/src/mill/testkit/UtestIntegrationTestSuite.scala

The goal of this PR is to pass source JARs corresponding to the Mill class path to Bloop. These are added in the root modules, where they're needed to get go-to-source to work for Mill build files.

Pass Mill source JARs to Bloop

---

scalalib/src/mill/scalalib/NativeImageModule.scala

Update Scaladocs to reflect that `nativeImage` is not a command.

Update Scaladocs for NativeImageModule

---

mill.bat

The curl check in the `mill.bat` wrapper script is actually broken:
```batch
if not exist "%MILL%" (
...
where /Q curl
if %ERRORLEVEL% EQU 0 (
curl -f -L "!DOWNLOAD_URL!" -o "!DOWNLOAD_FILE!"
)
```
The `%ERRORLEVEL%` is inside of nested `if`, so it will be the value of `ERRORLEVEL` when `if not exist "%MILL%"` is executed, not the result of `where /Q curl`. It should be replaced with `!ERRORLEVEL!` to get the correct result.
Some minor indentation fixes are also included.

Fix curl check in Windows wrapper script

---

bsp/src/mill/bsp/BspContext.scala
bsp/worker/src/mill/bsp/worker/MillBspLogger.scala
core/api/src/mill/api/Logger.scala
core/exec/src/mill/exec/ExecutionContexts.scala
core/exec/src/mill/exec/GroupExecution.scala
core/internal/src/mill/internal/FileLogger.scala
core/internal/src/mill/internal/MultiLogger.scala
core/internal/src/mill/internal/PrefixLogger.scala
core/internal/src/mill/internal/PrintLogger.scala
core/internal/src/mill/internal/PromptLogger.scala
core/internal/src/mill/internal/ProxyLogger.scala
pythonlib/src/mill/pythonlib/PythonModule.scala
scalalib/src/mill/scalalib/TestModule.scala
scalalib/src/mill/scalalib/TestModuleUtil.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Another part of https://github.com/com-lihaoyi/mill/issues/3603
More narrowing of the `Logger` interface so we can figure out what really needs to be there
- Moved `colored`, `infoColor`, `errorColor` to the `prompt` object since it's not typically overriden
- Inlined the `subLogger` calls at its one call-site

More logger cleanups

---

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
example/fundamentals/out-dir/1-out-files/build.mill
idea/src/mill/idea/GenIdeaImpl.scala
integration/ide/bsp-server/resources/project/build.mill
integration/ide/bsp-server/resources/snapshots/build-targets-compile-classpaths.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-modules.json
integration/ide/bsp-server/resources/snapshots/build-targets-dependency-sources.json
integration/ide/bsp-server/resources/snapshots/build-targets-javac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-output-paths.json
integration/ide/bsp-server/resources/snapshots/build-targets-resources.json
integration/ide/bsp-server/resources/snapshots/build-targets-scalac-options.json
integration/ide/bsp-server/resources/snapshots/build-targets-sources.json
integration/ide/bsp-server/resources/snapshots/workspace-build-targets.json
integration/ide/gen-idea/resources/hello-idea/build.mill
integration/ide/gen-idea/resources/hello-idea/idea/mill_modules/helloideasourcegen.iml
integration/ide/gen-idea/resources/hello-idea/idea/modules.xml
main/api/src/mill/api/Ctx.scala
main/define/src/mill/define/Task.scala
scalalib/src/mill/scalalib/DeferredGeneratedSourcesModule.scala
scalalib/src/mill/scalalib/JavaModule.scala

Context : https://github.com/com-lihaoyi/mill/discussions/4530
* Adds a `DeferredGeneratedSourcesModule` that extends `JavaModule`, providing a `def deferredGeneratedSourceTasks` alternative to `generatedSources`. This allows BSP/GenIdea/Bloop to predict source roots without actually running the code generation logic. 
* Adds a `def out` to the `Ctx` class, allowing to query the location `out` folder within tasks. 
* Adds unit tests / integration tests where relevant 
@lihaoyi, I want to open this PR to continue the discussion. At the time of writing this, this adds a `generatedSourceRoots` parameter for tasks, as you've described, and uses it to compute the source directories for the bloop configuration, as opposed to actually running the `allSources` task. A similar change would need to …

Add a `sourceGenerators` task to help out IDE config generation

---

bsp/package.mill
build.mill
contrib/package.mill
example/javalib/module/2-custom-tasks/build.mill
example/kotlinlib/module/2-custom-tasks/build.mill
example/scalalib/module/2-custom-tasks/build.mill
integration/package.mill
runner/src/mill/runner/MillMain.scala
scalajslib/package.mill
scalalib/package.mill
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/publish/settings.scala
website/package.mill

Replace deeper calls into deprecated coursier API.

Use `Dep.version` where appropriate

---

bsp/src/mill/bsp/BspContext.scala
contrib/scoverage/api/src/mill/contrib/scoverage/api/ScoverageReportWorkerApi2.java
contrib/scoverage/src/mill/contrib/scoverage/ScoverageReportWorker.scala
core/api/src/mill/api/Logger.scala
core/internal/src/mill/internal/Colors.scala
core/internal/src/mill/internal/DummyLogger.scala
core/internal/src/mill/internal/FileLogger.scala
core/internal/src/mill/internal/MultiLogger.scala
core/internal/src/mill/internal/PrefixLogger.scala
core/internal/src/mill/internal/PromptLogger.scala
core/internal/src/mill/internal/ProxyLogger.scala
core/internal/test/src/mill/internal/PromptLoggerTests.scala
runner/src/mill/runner/MillMain.scala
testkit/src/mill/testkit/UnitTester.scala

Add `def warn(s: String): Unit` to `Logger`

---

bsp/src/mill/bsp/BSP.scala
contrib/docker/src/mill/contrib/docker/DockerModule.scala
contrib/scalapblib/src/mill/contrib/scalapblib/ScalaPBModule.scala
contrib/scoverage/api/src/mill/contrib/scoverage/api/ScoverageReportWorkerApi2.java
contrib/scoverage/src/mill/contrib/scoverage/ScoverageReportWorker.scala
contrib/scoverage/worker2/src/mill/contrib/scoverage/worker/ScoverageReportWorkerImpl.scala
kotlinlib/src/mill/kotlinlib/KotlinWorkerManagerImpl.scala
kotlinlib/src/mill/kotlinlib/js/KotlinJsModule.scala
scalajslib/src/mill/scalajslib/ScalaJSModule.scala
scalalib/src/mill/scalalib/ScalaModule.scala

See also https://github.com/com-lihaoyi/mill/issues/3603

Use the new warn log level in various places

---

build.mill
website/docs/modules/ROOT/pages/cli/installation-ide.adoc
website/package.mill

Fixes https://github.com/com-lihaoyi/mill/issues/4668
We were incorrectly using `build.millDownloadUrl()` which contains the unstable current last tag, rather than the last stable version from `docTags.last`
Tested manually via ` MILL_STABLE_VERSION=1 ./mill -i -w website.githubPages`, verified the generated links point at the right place
Also did some cleanups to try and make this area of the code less confusing

Fix down download URLs to use stable versions

---

core/api/src/mill/api/SystemStreams.scala
core/constants/src/mill/constants/InputPumper.java
scalajslib/worker/1/src/mill/scalajslib/worker/ScalaJSWorkerImpl.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4097
Seems like `checkAvailable` is still used, so we can't remove it

Remove `InputPumper#runningCheck`

---

core/internal/src/mill/internal/PromptLogger.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4683
#4653 moved a bunch of methods into a nested `object`, but that makes the `synchronized` blocks have a different receiver than before, possibly resulting in race conditions. This PR explicitly qualifies the synchronized blocks to restore the old behavior.

Try and fix synchronization problems in prompt logger

---

core/internal/src/mill/internal/PromptLogger.scala

Otherwise previously viewing raw logs on github actions would show noisy `[0k`s everywhere

Avoid printing `AnsiNav.clearLine` in non-interactive PromptLogger to clean up CI logs

---

main/util/src/mill/util/PromptLogger.scala

Backport of https://github.com/com-lihaoyi/mill/pull/4709

Backport "Avoid printing `AnsiNav.clearLine` in non-interactive PromptLogger to clean up CI logs" to 0.12.x

---

core/api/src/mill/api/Ctx.scala
core/exec/src/mill/exec/ExecutionContexts.scala
example/fundamentals/tasks/7-forking-futures/build.mill
scalalib/src/mill/scalalib/TestModuleUtil.scala

This is a follow up improvement to https://github.com/com-lihaoyi/mill/pull/4701 which uses an explicit priority queue rather than relying on ad-hoc LIFO ordering. By prioritizing the first async task and de-prioritizing subsequent async tasks, this encourages Mill to re-use the same async task JVM to do more work, minimizing JVM startup overhead
When testing this out on the Netty example, `testParallelism` prioritizing the first testrunner JVM over all others does seem to make a material difference. I manually performed did ad-hoc benchmarks of the time taken to run the following command, basically running all the tests that we run in the example integration test:
```
/Users/lihaoyi/Github/mill/out/dist/launcher.dest/run 'codec-{dns,haproxy,http,http2,memcache,mqtt,redis,smtp,socks,stomp, …
```

Use priority queue to run Mill executor tasks, prioritizing first async task and de-prioritizing subsequent ones

---

main/api/src/mill/api/Ctx.scala
main/eval/src/mill/eval/ExecutionContexts.scala
scalalib/src/mill/scalalib/TestModuleUtil.scala
testrunner/src/mill/testrunner/Model.scala
testrunner/src/mill/testrunner/TestRunnerMain0.scala
testrunner/src/mill/testrunner/TestRunnerUtils.scala

This PR improves the precision on how the parent `test` tasks and child `fork.async` tasks are created and terminated
* We allow the parent test task to terminate even when the child async tasks are still running, as long as all test classes are accounted for. 
* That means that the remaining child tasks have no more work to do, and will anyway just immediately terminate when it's their turn to run
* We pre-claim the first test class in the parent Mill process before spawning the child process. This provides:
* A smoother UI since the user won't see empty worker lines in the prompt that get filled in later: now all test worker lines immediately get a label of what test class they will run
*  Faster feedback to `TestModuleUtild` that no more processes. Previously we would spawn a bunch of …

(0.12.x) Improvements precision of `testParallelism` scheduler lifetime management

---

scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala
scalanativelib/worker-api/src/mill/scalanativelib/worker/api/ScalaNativeWorkerApi.scala
scalanativelib/worker/0.5/src/mill/scalanativelib/worker/ScalaNativeWorkerImpl.scala

Scala Native supports `ServiceProvider` which allows loading implementations for interfaces using reflection. To avoid bloating binaries with all available implementations, Scala Native requires to set at build time the implementations that are used.
This PR adds support for it in Mill.
Pull Request: https://github.com/com-lihaoyi/mill/pull/4736

Support `nativeServiceProviders` in `ScalaNativeModule`

---

.gitignore

It seems some files used to be written there when running `./mill -i dist.installLocal` I think, but that's not the case anymore (unless I'm mistaken?). So there's no need to keep that entry there.
Having it there makes the global search of VSCode ignore that directory and its `package.mill` file, which can be a problem sometimes.

Remove dist/ from .gitignore

---

dist/package.mill
testkit/src/mill/testkit/ExampleTester.scala

This makes some example test failures be ignored on CI. The examples are still run, their stacktrace when they fail is still printed, but this doesn't make the CI job fail.
Whether the errors of an example tests are ignored or not is controled by an `ignoreErrorsOnCI` file at its root. If this file exists, then the test errors are printed but ignored. Only so on CI, not locally.

Ignore some example tests that consistently fail on CI

---

website/docs/modules/ROOT/pages/comparisons/gradle.adoc
website/docs/modules/ROOT/pages/comparisons/maven.adoc

Fixes https://github.com/com-lihaoyi/mill/issues/4030
I left the Maven/Gradle numbers unchanged since I'm running on the same code/OS/hardware/JVM, and just updated the Mill numbers to use the newest version. Mostly unchanged for larger builds, though smaller builds benefit a lot from the new `-native` launcher

Update benchmarks for Mill 0.12.9-native

---

scalalib/api/src/mill/scalalib/api/ZincWorkerApi.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/RunModule.scala

This PR removes the task definitions from `JavaModule` that have already been moved into `RunModule`, encapsulating the difference between `JavaModule` and other `RunModule`s that do not use Zinc (e.g. `KotlinModule`) in the `def allLocalMainClasses` task.
This should be semantically identical as before, just with a bit less indirection

Clean up main method discovery logic

---

core/internal/src/mill/internal/PromptLoggerUtil.scala
core/internal/src/mill/internal/Util.scala
scalalib/src/mill/scalalib/TestModule.scala
scalalib/src/mill/scalalib/TestModuleUtil.scala
scalalib/test/src/mill/scalalib/TestRunnerScalatestTests.scala
scalalib/test/src/mill/scalalib/TestRunnerUtestTests.scala
testrunner/src/mill/testrunner/Model.scala
testrunner/src/mill/testrunner/TestRunnerMain0.scala
testrunner/src/mill/testrunner/TestRunnerUtils.scala

/claim #4735
This PR add some calculation to add test progress & failure indicator for each test runner while `testParallelism` is set to `true`
To add progress indicators, this pull request introduces a new file within each worker's claim folder. This file is overwritten every time `runClaimedTestClass` is called. The parent process will checks these files in each worker, accumulates their contents, and outputs them via a `ticker`.
For test timing, this pull request uses a separate map, similar to `workerStatusMap`, to store the starting time. The time calculation is then straightforward, and the result is output via a `ticker` alongside the test class name.

Add test runner indicators

---

main/util/src/mill/util/PromptLoggerUtil.scala
main/util/src/mill/util/Util.scala
scalalib/src/mill/scalalib/TestModule.scala
scalalib/src/mill/scalalib/TestModuleUtil.scala
scalalib/test/src/mill/scalalib/TestRunnerScalatestTests.scala
scalalib/test/src/mill/scalalib/TestRunnerUtestTests.scala
testrunner/src/mill/testrunner/Model.scala
testrunner/src/mill/testrunner/TestRunnerMain0.scala
testrunner/src/mill/testrunner/TestRunnerUtils.scala

Test runner indicators backport

---

core/internal/src/mill/internal/LinePrefixOutputStream.scala

Fix https://github.com/com-lihaoyi/mill/issues/4768
Ensure we don't use a negative index in case a string is empty.

Fix potential ArrayIndexOutOfBoundsException

---

contrib/buildinfo/readme.adoc
contrib/buildinfo/src/mill/contrib/buildinfo/BuildInfo.scala
contrib/buildinfo/test/resources/buildinfo/kotlin/src/Main.kt
contrib/buildinfo/test/src/mill/contrib/buildinfo/BuildInfoTests.scala
contrib/package.mill

Add support for Kotlin source file generator in `BuildInfo` module.
In addition to Java and Scala, `BuildInfo` now also supports a Kotlin source generator.
The default generator is selected based on the module type, but can now also be configured to a specific type. E.g. users of `ScalaModule` or `KotlinModule` might want to generate a Java source file. 
```scala
// Always generate a Java file
def buildInfoLanguage = BuildInfo.Language.Java
```
Or modules implementing `ScalaModule` and `KotlinModule` might want to generate a Kotlin file instead of a Scala file.

Add Kotlin support for BuildInfo module

---

contrib/buildinfo/readme.adoc
contrib/buildinfo/src/mill/contrib/buildinfo/BuildInfo.scala
contrib/buildinfo/test/resources/buildinfo/kotlin/src/Main.kt
contrib/buildinfo/test/src/mill/contrib/buildinfo/BuildInfoTests.scala
contrib/package.mill

Add support for Kotlin source file generator in `BuildInfo` module.
In addition to Java and Scala, `BuildInfo` now also supports a Kotlin
source generator.
The default generator is selected based on the module type, but can now
also be configured to a specific type. E.g. users of `ScalaModule` or
`KotlinModule` might want to generate a Java source file.
```scala
// Always generate a Java file
def buildInfoLanguage = BuildInfo.Language.Java
```
Or modules implementing `ScalaModule` and `KotlinModule` might want to
generate a Kotlin file instead of a Scala file.
Original pull request: https://github.com/com-lihaoyi/mill/pull/4771

Add Kotlin support for BuildInfo module (backport #4771)

---

build.mill
contrib/proguard/src/mill/contrib/proguard/Proguard.scala
contrib/proguard/test/resources/proguard/src/Main.scala
contrib/proguard/test/src/mill/contrib/proguard/ProguardTests.scala

Removed hardcoded `proguardVersion`.
Re-enabled and overhauled tests.
Manage versions used in tests from Mill build.

Review and fix proguard contrib plugin

---

integration/failure/module-outside-top-level-module/src/ModuleOutsideTopLevelModuleTests.scala
integration/failure/no-modules-in-helper-file/src/NoModulesInHelperFileTests.scala
main/define/src/mill/define/Ctx.scala

Original Pull request: https://github.com/com-lihaoyi/mill/pull/4789

Less confusing error message (backport #4789)

---

bsp/src/mill/bsp/BSP.scala
contrib/playlib/src/mill/playlib/RouterModule.scala
contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala
contrib/testng/test/src/mill/testng/TestNGTests.scala
kotlinlib/src/mill/kotlinlib/KotlinModule.scala
main/init/src/mill/init/BuildGenException.scala
main/init/src/mill/init/BuildGenModule.scala
main/init/src/mill/init/InitGradleModule.scala
main/init/src/mill/init/InitMavenModule.scala
main/init/src/mill/init/InitSbtModule.scala
main/src/mill/main/VisualizeModule.scala
main/util/src/mill/util/MillModuleUtil.scala
scalajslib/src/mill/scalajslib/ScalaJSModule.scala
scalalib/src/mill/scalalib/CoursierModule.scala
scalalib/src/mill/scalalib/Dep.scala
scalalib/src/mill/scalalib/ZincWorkerModule.scala
scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala

This is meant as a replacement for `mill.util.ModuleUtils.millProjectModule`.
The main motivation for this change is to handle mill module dependencies more regular. Since they can be resolved together with other dependencies, this should result in better conflict resolution. The older API rather forces us to concat two potential redundant or conflicting classpaths. 
There is one last usage of the older `ModuleUtils.millProjectModule` from `VisualizeModule`, which resides in `mill.main` and can't access `CoursierModule` or `Dep`. Don't know how to best handle it.

Add `Dep.millProjectModule` to refer to mill project modules

---

main/util/src/mill/util/Retry.scala
main/util/test/src/mill/util/RetryTests.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
testkit/src/mill/testkit/IntegrationTestSuite.scala
testkit/src/mill/testkit/IntegrationTesterBase.scala
testkit/src/mill/testkit/UtestExampleTestSuite.scala
testkit/src/mill/testkit/UtestIntegrationTestSuite.scala

This adds a `logger: String => Unit` argument to `Retry`, so that we can know in the logs (CI logs say) if a retry did happen. Two helpers are added to help users pass that new argument: `Retry.ctxLogger` that uses `Task.ctx`, and `Retry.printStream` if one wants to log with `System.err` for example.
Also, this moves the `Retry` of integration tests from `UtestIntegrationTestSuite` to `IntegrationTestSuite#integrationTest`. In the former location, it was wrapping a `Future`, which `Retry` doesn't handle, so that the retry actually had no effect I think.
Lastly, this ignores `TimeoutException`s for example tests that have a `ignoreErrorsOnCI` file (introduced in https://github.com/com-lihaoyi/mill/pull/4751).

Add a logger to Retry, and make the integration tests Retry effective

---

example/kotlinlib/basic/1-simple/build.mill
example/kotlinlib/basic/3-multi-module/build.mill
example/kotlinlib/basic/6-realistic/build.mill
example/kotlinlib/dependencies/1-ivy-deps/build.mill
example/kotlinlib/dependencies/3-unmanaged-jars/build.mill
example/kotlinlib/dependencies/4-downloading-unmanaged-jars/build.mill
example/kotlinlib/dependencies/5-repository-config/build.mill
example/kotlinlib/module/2-custom-tasks/build.mill
example/kotlinlib/module/3-override-tasks/build.mill
example/kotlinlib/module/4-compilation-execution-flags/build.mill
example/kotlinlib/publishing/1-assembly-config/build.mill
example/kotlinlib/publishing/2-publish-module/build.mill
example/kotlinlib/publishing/8-native-image-libs/build.mill
example/kotlinlib/testing/1-test-suite/build.mill
example/kotlinlib/testing/4-test-parallel/build.mill
example/kotlinlib/testing/5-test-grouping/build.mill
example/kotlinlib/testing/6-test-group-parallel/build.mill
kotlinlib/src/mill/kotlinlib/KotlinModule.scala
scalalib/src/mill/scalalib/RunModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4772
Previously it inherited the Zinc-based main class discovery via `JavaModule`, which overrode the generic classpath-scanning approach from `RunModule`. This PR adjusts the overrides such the `KotlinModule` uses the disk-based discovery API.
Removed all the now-unnecessary `def mainClass` annotations in the kotlinlib example tests, except for the one in `example/kotlinlib/module/1-common-config` that is useful for educational purposes.
@lefou do you know what the difference between the two implementations is? I'm wondering what the Zinc-based approach gives us, or whether we can just standardize on the disk-based approach that seems like it should work for all JVM languages

Fix main class discovery for `KotlinModule`

---

dist/package.mill

Backport Pull request: https://github.com/com-lihaoyi/mill/pull/4808

Use a `-native` suffix when installing a native image into the local cache (backport #4808)

---

example/scalalib/web/3-todo-http4s/src/WebApp.scala

Backport of https://github.com/com-lihaoyi/mill/pull/4798
Otherwise it hangs for 30s when you try to kill the process, which slows down iterative development considerably

Backport Set `WebApp.scala` shutdown timeout to zero

---

main/api/src/mill/api/JarManifest.scala
main/util/src/mill/util/package.scala

JarManifest will be moved from mill.api.JarManifest in Mill 0.12 to mill.util.JarManifest in Mill 0.13.
This change already adds the new (by delegating to the old) and deprecates the old API, to assist in migration.
Tracker issue: https://github.com/com-lihaoyi/mill/issues/4716

Add Mill 0.13 forward compatibility: `mill.util.JarManifest`

---

example/kotlinlib/basic/1-simple/build.mill
example/kotlinlib/basic/3-multi-module/build.mill
example/kotlinlib/basic/6-realistic/build.mill
example/kotlinlib/dependencies/1-ivy-deps/build.mill
example/kotlinlib/dependencies/3-unmanaged-jars/build.mill
example/kotlinlib/dependencies/4-downloading-unmanaged-jars/build.mill
example/kotlinlib/dependencies/5-repository-config/build.mill
example/kotlinlib/module/2-custom-tasks/build.mill
example/kotlinlib/module/3-override-tasks/build.mill
example/kotlinlib/module/4-compilation-execution-flags/build.mill
example/kotlinlib/publishing/1-assembly-config/build.mill
example/kotlinlib/publishing/2-publish-module/build.mill
example/kotlinlib/publishing/8-native-image-libs/build.mill
example/kotlinlib/testing/1-test-suite/build.mill
example/kotlinlib/testing/4-test-parallel/build.mill
example/kotlinlib/testing/5-test-grouping/build.mill
example/kotlinlib/testing/6-test-group-parallel/build.mill
kotlinlib/src/mill/kotlinlib/KotlinModule.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/RunModule.scala

Backports https://github.com/com-lihaoyi/mill/pull/4797
Fixes https://github.com/com-lihaoyi/mill/issues/4772
Previously it inherited the Zinc-based main class discovery via JavaModule, which overrode the generic classpath-scanning approach from RunModule. This PR adjusts the overrides such the KotlinModule uses the disk-based discovery API.
Removed all the now-unnecessary def mainClass annotations in the kotlinlib example tests, except for the one in example/kotlinlib/module/1-common-config that is useful for educational purposes.

Backport "Fix main class discovery for `KotlinModule`"

---

dist/package.mill
main/package.mill

* Exclude  the `j2v8` binary since we don't use it in the main classpath, brings the native dist from 106M to 100M
* Turn on `-Os` in the graal config to try and optimize for size, bringing the native dist from 100M to 97M
Probably a lot more we can improve, but this is a start. Current breakdown is
* ~50mb for the main assembly jar
* ~20mb from Graal native image overhead
* ~30mb from Coursier compiled to Graal native, from the dependency on `courser-jvm` that pulls in all of coursier's various modules
```
[1-5997] Build resources:
[1-5997]  - 24.18GB of memory (75.6% of 32.00GB system memory, determined at start)
[1-5997]  - 10 thread(s) (100.0% of 10 available processor(s), determined at start)
[1-5997] [2/8] Performing analysis...  [*****] …
```

Minor improvements to native distribution size

---

integration/migrating/init/src/MillInitMavenTests.scala

This makes a test in `MillInitMavenTests` test local publishing by writing to a throw away directory, rather than the user's `~/.ivy2/local`, where the written files might be a problem.

Don't publish jansi in ~/.ivy2/local in integration test

---

dist/package.mill
main/package.mill

Backport of  #4825
* Exclude  the `j2v8` binary since we don't use it in the main classpath, brings the native dist from 106M to 100M
* Turn on `-Os` in the graal config to try and optimize for size, bringing the native dist from 100M to 97M
Probably a lot more we can improve, but this is a start. Current breakdown is
* ~50mb for the main assembly jar
* ~20mb from Graal native image overhead
* ~30mb from Coursier compiled to Graal native, from the dependency on `courser-jvm` that pulls in all of coursier's various modules
```
[1-5997] Build resources:
[1-5997]  - 24.18GB of memory (75.6% of 32.00GB system memory, determined at start)
[1-5997]  - 10 thread(s) (100.0% of 10 available processor(s), determined at start)
[1-5997] [2/8] Performing analysis...  [*****] …
```

Backport "Minor improvements to native distribution size"

---

bsp/src/mill/bsp/BSP.scala
contrib/playlib/src/mill/playlib/RouterModule.scala
contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala
contrib/testng/test/src/mill/testng/TestNGTests.scala
kotlinlib/src/mill/kotlinlib/KotlinModule.scala
main/init/src/mill/init/BuildGenException.scala
main/init/src/mill/init/BuildGenModule.scala
main/init/src/mill/init/InitGradleModule.scala
main/init/src/mill/init/InitMavenModule.scala
main/init/src/mill/init/InitSbtModule.scala
main/src/mill/main/VisualizeModule.scala
main/util/src/mill/util/MillModuleUtil.scala
scalajslib/src/mill/scalajslib/ScalaJSModule.scala
scalalib/src/mill/scalalib/CoursierModule.scala
scalalib/src/mill/scalalib/Dep.scala
scalalib/src/mill/scalalib/ZincWorkerModule.scala
scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala

This is meant as a replacement for
`mill.util.ModuleUtils.millProjectModule`, which I annotated as deprecated.
The main motivation for this change is to handle mill module
dependencies more regular. Since they can be resolved together with
other dependencies, this should result in better conflict resolution.
The older API rather forces us to concat two potential redundant or
conflicting classpaths.
There is one last usage of the older `ModuleUtils.millProjectModule`
from `VisualizeModule`, which resides in `mill.main` and can't access
`CoursierModule` or `Dep`. Don't know how to best handle it.
Original pull request: https://github.com/com-lihaoyi/mill/pull/4790

Add `Dep.millProjectModule` to refer to mill project modules (backport #4790)

---

javascriptlib/src/mill/javascriptlib/PublishModule.scala
javascriptlib/src/mill/javascriptlib/TypeScriptModule.scala
main/src/mill/main/VcsVersion.scala
pythonlib/src/mill/pythonlib/PublishModule.scala
pythonlib/src/mill/pythonlib/PythonModule.scala
scalalib/src/mill/javalib/android/AndroidModule.scala

- Use Task.Sources with sub path
- Added correct license version number
- Use relative source dir
- formatting
- Ignore test example.android.javalib[1-hello-world] on CI (again)

Minor changes

---

integration/feature/java-opts/resources/build.mill
integration/feature/java-opts/src/JavaOptsTests.scala
runner/client/src/mill/runner/client/MillProcessLauncher.java

Fix #4826
Propagate options specified in `JAVA_OPTS` to mill subprocess by appending them to `JDK_JAVA_OPTIONS` and setting `JDK_JAVA_OPTIONS` in the process env. Related discussion in the [APE PR](https://github.com/com-lihaoyi/mill/pull/4503#issuecomment-2665620418). The JVM will print `NOTE: Picked up JDK_JAVA_OPTIONS: ...` to stderr though.

Propagate JAVA_OPTS to mill subprocess

---

main/resolve/src/mill/resolve/ResolveCore.scala
main/resolve/test/src/mill/main/ResolveTests.scala

Backports https://github.com/com-lihaoyi/mill/pull/4861
Fixes https://github.com/com-lihaoyi/mill/issues/4536 and https://github.com/com-lihaoyi/mill/issues/4514 and https://github.com/com-lihaoyi/mill/issues/3618
- `__` was incorrectly adding the current module to `seenModules`, which causes problems when it recurses on the current module. This PR skips updating `seenModules` when recursing on the current module. There are probably other edge cases we haven't noticed in this cycling module graph detection logic, but for now this just fixes the reported issue and the test suite should give confidence we didn't regress anything
- `typePatterns` was incorrectly being resolved only on modules during the `__` wildcard resolution, and allowing tasks to pass through without filtering. This PR …

Backport "Fix wildcard and type selector query bugs"

---

core/resolve/src/mill/resolve/ResolveCore.scala
core/resolve/test/src/mill/resolve/ResolveTests.scala
core/resolve/test/src/mill/resolve/TypeSelectorTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4536 and https://github.com/com-lihaoyi/mill/issues/4514 and https://github.com/com-lihaoyi/mill/issues/3618
- `__` was incorrectly adding the current module to `seenModules`, which causes problems when it recurses on the current module. This PR skips updating `seenModules` when recursing on the current module. There are probably other edge cases we haven't noticed in this cycling module graph detection logic, but for now this just fixes the reported issue and the test suite should give confidence we didn't regress anything
- `typePatterns` was incorrectly being resolved only on modules during the `__` wildcard resolution, and allowing tasks to pass through without filtering. This PR moves the filtering to after …

Fix wildcard and type selector query bugs

---

scalalib/src/mill/scalalib/TestModule.scala

We couldn't removed in 0.12 due to bin-compat. Later we overlooked it.
Turns out, it is still used in the `JUnit5` case. I tried to come up with a alternative implementation, without inspecting whether there is a better way.

Remove TestModule.compile

---

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
bsp/worker/src/mill/bsp/worker/MillJavaBuildServer.scala
bsp/worker/src/mill/bsp/worker/MillJvmBuildServer.scala
bsp/worker/src/mill/bsp/worker/MillScalaBuildServer.scala
mill-bsp.trace
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/RunModule.scala
scalalib/src/mill/scalalib/TestModule.scala
scalalib/src/mill/scalalib/bsp/BspModule.scala

This is a requirement to split up the BSP server classpath from the evaluator classpath, since they may each have their own `Task` classes and transitive dependencies. It's generally straightforward to move the logic into `BspModule`

[WIP] avoid usage of `Task.Anon` in Mill BSP server

---

example/thirdparty/netty/build.mill
runner/api/src/BuildReporter.scala
scalalib/src/mill/scalalib/JsonFormatters.scala
scalalib/src/mill/scalalib/TestModule.scala
scalalib/src/mill/scalalib/TestModuleUtil.scala
testrunner/src/mill/testrunner/Model.scala
testrunner/src/mill/testrunner/TestRunnerMain0.scala
testrunner/src/mill/testrunner/TestRunnerUtils.scala

This adds a new `testLogLevel` task on `TestModule`, that allows users to silence test debug output. It's useful to make the netty tests less verbose, which is what the second commit does.
My goal here is to make the netty tests, that fail from time to time, stop unnecessarily flooding the CI output, like [they do sometimes](https://github.com/alexarchambault/mill/actions/runs/14306280494/job/40092395363).

Add TestModule#testLogLevel, make netty tests less verbose

---

scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/classgraph/ClassgraphWorkerModule.scala

#4822 introduced `ClassgraphWorkerModule` and the corresponding package `classgraph-worker`, but `prepareOffline` does not install it, causing offline build to fail. This PR fixes that problem.

Implement prepareOffline for ClassgraphWorkerModule

---

dist/package.mill

Fixes https://github.com/com-lihaoyi/mill/issues/4863
Seems like it was broken by #4837 which replaced `Jvm.runSubprocess` with `os.call`, which unfortunately had different stream forwarding defaults. This class of problem should be impossible in future thanks to https://github.com/com-lihaoyi/mill/pull/4456 from @sake92 which standardizing the stream forwarding defaults of `Jvm.*Process` APIs with `os.*`

Fix `dist.run` stdout forwarding

---

bsp/src/mill/bsp/BSP.scala
core/api/src/mill/api/internal/EvaluatorApi.scala
core/api/src/mill/api/internal/SemanticDbJavaModuleApi.scala
core/api/src/mill/api/internal/api.scala
core/define/src/mill/define/Discover.scala
core/define/src/mill/define/Evaluator.scala
core/define/src/mill/define/ExecutionResults.scala
integration/ide/bsp-server/src/BspServerTestUtil.scala
scalalib/src/mill/scalalib/JavaModule.scala
scalalib/src/mill/scalalib/RunModule.scala
scalalib/src/mill/scalalib/SemanticDbJavaModule.scala
scalalib/src/mill/scalalib/TestModule.scala
scalalib/src/mill/scalalib/bsp/BspModule.scala

I don't know if we want these to be exposed/override-able by users, but until we make a decision on that it's easiest just to make them all `private[mill]` for now

Privatize `mill.internal`-specific BSP methods, remove unused `upickle.default.ReadWriter[BspServerResult]`

---

bsp/src/mill/bsp/BSP.scala
bsp/src/mill/bsp/package.scala
contrib/artifactory/src/mill/contrib/artifactory/ArtifactoryPublishModule.scala
contrib/artifactory/src/mill/contrib/artifactory/package.scala
contrib/bintray/src/mill/contrib/bintray/BintrayPublishModule.scala
contrib/bintray/src/mill/contrib/bintray/package.scala
contrib/codeartifact/src/mill/contrib/codeartifact/CodeartifactPublishModule.scala
contrib/codeartifact/src/mill/contrib/codeartifact/package.scala
contrib/gitlab/src/mill/contrib/gitlab/GitlabPublishModule.scala
contrib/gitlab/src/mill/contrib/gitlab/package.scala
contrib/sonatypecentral/src/mill/contrib/sonatypecentral/SonatypeCentralPublishModule.scala
contrib/sonatypecentral/src/mill/contrib/sonatypecentral/package.scala
contrib/versionfile/src/mill/contrib/versionfile/VersionFileModule.scala
core/exec/test/src/mill/exec/ModuleTests.scala
core/resolve/src/mill/resolve/Resolve.scala
idea/src/mill/idea/GenIdea.scala
idea/src/mill/idea/package.scala
kotlinlib/src/mill/kotlinlib/kover/KoverModule.scala
kotlinlib/src/mill/kotlinlib/kover/package.scala
kotlinlib/src/mill/kotlinlib/ktfmt/KtfmtModule.scala
kotlinlib/src/mill/kotlinlib/ktfmt/package.scala
kotlinlib/src/mill/kotlinlib/ktlint/KtlintModule.scala
kotlinlib/src/mill/kotlinlib/ktlint/package.scala
scalalib/src/mill/javalib/palantirformat/PalantirFormatModule.scala
scalalib/src/mill/javalib/palantirformat/package.scala
scalalib/src/mill/scalalib/scalafmt/ScalafmtModule.scala
scalalib/src/mill/scalalib/scalafmt/package.scala

This allows the shorter syntax e.g. `mill.scalalib.scalafmt.scalafmt` to be called programmatically, and brings them in line with Scala `package object`s and Mill's existing `RootModule`s

Rename `PackageDefaultExternalObject` to the `package` objects

---

bsp/src/mill/bsp/BSP.scala
bsp/src/mill/bsp/package.scala
contrib/artifactory/src/mill/contrib/artifactory/ArtifactoryPublishModule.scala
contrib/artifactory/src/mill/contrib/artifactory/package.scala
contrib/bintray/src/mill/contrib/bintray/BintrayPublishModule.scala
contrib/bintray/src/mill/contrib/bintray/package.scala
contrib/codeartifact/src/mill/contrib/codeartifact/CodeartifactPublishModule.scala
contrib/codeartifact/src/mill/contrib/codeartifact/package.scala
contrib/gitlab/src/mill/contrib/gitlab/GitlabPublishModule.scala
contrib/gitlab/src/mill/contrib/gitlab/package.scala
contrib/sonatypecentral/src/mill/contrib/sonatypecentral/SonatypeCentralPublishModule.scala
contrib/sonatypecentral/src/mill/contrib/sonatypecentral/package.scala
contrib/versionfile/src/mill/contrib/versionfile/VersionFileModule.scala
idea/src/mill/idea/GenIdea.scala
idea/src/mill/idea/package.scala
kotlinlib/src/mill/kotlinlib/kover/KoverModule.scala
kotlinlib/src/mill/kotlinlib/kover/package.scala
kotlinlib/src/mill/kotlinlib/ktfmt/KtfmtModule.scala
kotlinlib/src/mill/kotlinlib/ktfmt/package.scala
kotlinlib/src/mill/kotlinlib/ktlint/KtlintModule.scala
kotlinlib/src/mill/kotlinlib/ktlint/package.scala
main/eval/test/src/mill/eval/ModuleTests.scala
main/resolve/src/mill/resolve/Resolve.scala
scalalib/src/mill/javalib/palantirformat/PalantirFormatModule.scala
scalalib/src/mill/javalib/palantirformat/package.scala
scalalib/src/mill/scalalib/scalafmt/ScalafmtModule.scala
scalalib/src/mill/scalalib/scalafmt/package.scala

Backport of https://github.com/com-lihaoyi/mill/pull/4922
This allows the shorter syntax e.g. `mill.scalalib.scalafmt.scalafmt` to be called programmatically, and brings them in line with Scala `package object`s and Mill's existing `RootModule`s

(Backport) Rename `PackageDefaultExternalObject` to the `package` objects

---

.github/actions/setup-android/action.yml
example/android/javalib/3-linting/build.mill
example/android/kotlinlib/4-sum-lib-kotlin/build.mill

- It seems like, github actions has already installed an old version of the android tools, so the android-setup action was running and trying to install in the same locations as the pre-installed tools ( android-setup couldn't override the locations but instead it created a new folder and installed it there )
- The old pre-exsisting android tools doesn't have the R8 tool 
Change the location of where android home is located and change the cmd-line tools version to latest

fix android cmd-line tools on CI

---

bsp/src/mill/bsp/BspClasspathWorker.scala
bsp/worker/src/mill/bsp/worker/BspWorkerImpl.scala
bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
build.mill
core/constants/src/mill/constants/EnvVars.java
core/define/src/mill/define/Evaluator.scala
dist/package.mill
main/src/mill/main/Inspect.scala
runner/src/mill/runner/MillMain.scala
runner/src/mill/runner/MillServerMain.scala

* Remove unused MILL_BUILD_LIBRARIES, seems we don't need it now since we only run the IDE integration tests in `.packaged` mode
* Need to move the `os.checker` inside the `EvaluatorImpl` so it runs in the right classloader
* Simplify logging in BSP server and make it work again. Fixes https://github.com/com-lihaoyi/mill/issues/4430, now we log more consistently to `out/mill-bsp/out.log` and `err.log`. Seems the previous assumption that `--bsp` was always the first argument stopped being true in IntelliJ at some point
Enough to import `example/scalalib/basic/1-simple`, as well `mill` itself. I'm able to run `mill.util.JvmTests` from the IntelliJ UI

Fixes for BSP import

---

bsp/worker/src/mill/bsp/worker/BspWorkerImpl.scala
bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
bsp/worker/src/mill/bsp/worker/MillJavaBuildServer.scala
bsp/worker/src/mill/bsp/worker/MillJvmBuildServer.scala
bsp/worker/src/mill/bsp/worker/MillScalaBuildServer.scala

1. Use the existing `Executor` rather than `ExecutionContexts.global`
2. Consolidate `completable` and `completableNoState` into using the same shared helper
3. Rename all the `completable*` methods to `handler*` 
4. Remove explicit `hint` strings and use `sourcecode.Name` instead

Cleanup MillBuildServer

---

core/internal/src/mill/internal/LinePrefixOutputStream.scala
core/internal/test/src/mill/internal/LinePrefixOutputStreamTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/4115
The problem was that we were only re-applying the Ansi colors after printing the `LinePrefixOutputStream` prefix. This misses the case where a single log line is broken into multiple `writeOutBuffer` calls, e.g. if it arrives at `LinePrefixOutputStream` as multiple separate `write` calls due to the vagaries of upstream buffering:
1. The first call will correctly set the `endOfLastLineColor`
2. The second call will not include the `endOfLastLineColor` when rendering its own `bufferString`, and thus when it calculates the next `endOfLastLineColor` it will find it to be the 0 (no colors)
3. The third call, perhaps on the following line, will find `endOfLastLineColor` to be 0 and render without colors
This PR fixes it by rendering the …

Fix color prompt logging for broken log lines

---

integration/ide/gen-idea/resources/hello-idea/idea/mill_modules/mill-build.iml
scalalib/package.mill
scalalib/src/mill/scalalib/scalafmt/ScalafmtWorker.scala

Cuts `mill-assembly.jar` from 55mb to 53mb, so ~2mb of savings, with a somewhat cleaner classpath. the `scalafmt-dynamic` code will be downloaded on-demand

Move `ScalaFmt` into its own classloader

---

integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.iml
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.mill-build.iml
runner/package.mill

Also enabled assertions for the meta-build in the `GenIdeaExtended` tests, so we have some test coverage of what's on the classpath for the meta-build

Tighten up `mill-runner-meta` dependencies

---

scalajslib/package.mill

Not sure why these dependencies were listed as `compileMvnDeps` rather than just `mvnDeps`, but that seems to be the cause of the `java.lang.NoSuchMethodError`s that were plaguing CI since we removed scalafmt/parallel-collections from the classpath. Hopefully this helps make things work again
Seems like the `compile` prefix was added in https://github.com/com-lihaoyi/mill/pull/4162

Fix `main` build and CI

---

example/javalib/dependencies/4-downloading-unmanaged-jars/build.mill
example/kotlinlib/dependencies/4-downloading-unmanaged-jars/build.mill
example/pythonlib/dependencies/4-downloading-unmanaged-wheels/build.mill
example/scalalib/dependencies/4-downloading-unmanaged-jars/build.mill

Show case how to respect the `Task.offline` state before downloading remote resources.

Use `Task.offline` in dependency download examples

---

libs/androidlib/src/mill/androidlib/AndroidAppKotlinModule.scala

Screenshot tests stopped running after some commits
After pair programming with @vaslabs we used git bisect and found that the problem was on the commit c58cb616fd35c93e89f5cec55a7b70443f827c52  Turn on `testEnableWorkStrealing` by default (#4681)
For now, we disabled the testParallel for the screenshotTests

fix the screenshot tests problem

---

core/constants/package.mill
core/constants/src/mill/constants/Util.java
core/exec/src/mill/exec/GroupExecution.scala
runner/client/src/mill/runner/client/MillProcessLauncher.java
runner/server/client/src/mill/client/ClientUtil.java
runner/server/client/test/src/mill/client/MillEnvTests.java

Interpolating missing variable to the empty string (`""`) is error prone, possibly dangerous and hard to debug. Hence, this change makes it a hard failure when a variable is missing.

Fail on missing interpolatable variables

---

contrib/artifactory/readme.adoc
contrib/bintray/readme.adoc
contrib/bloop/readme.adoc
contrib/buildinfo/readme.adoc
contrib/codeartifact/readme.adoc
contrib/docker/readme.adoc
contrib/flyway/readme.adoc
contrib/gitlab/readme.adoc
contrib/jmh/readme.adoc
contrib/playlib/readme.adoc
contrib/proguard/readme.adoc
contrib/scalapblib/readme.adoc
contrib/scoverage/readme.adoc
contrib/sonatypecentral/readme.adoc
contrib/twirllib/readme.adoc
contrib/versionfile/readme.adoc
core/constants/src/mill/constants/Util.java
example/extending/imports/1-mvn-deps/build.mill
example/extending/imports/2-mvn-deps-scala/build.mill
example/extending/plugins/7-writing-mill-plugins/myplugin/test/resources/example-test-project/build.mill
example/extending/plugins/7-writing-mill-plugins/myplugin/test/resources/integration-test-project/build.mill
example/fundamentals/cross/10-static-blog/build.mill
example/package.mill
example/scalalib/linting/2-contrib-scoverage/build.mill
example/thirdparty/commons-io/build.mill
example/thirdparty/netty/build.mill
integration/feature/header-mvn-deps-worker-invalidation/resources/build.mill
integration/feature/scoverage/resources/build.mill
integration/ide/bloop/resources/build.mill
mill-build/src-testkit/mill/testkit/ExampleParser.scala

Adapt `ExampleParser` to also capture the YAML frontmatter.
Defer rendering of YAML frontmatter until the first Scala code block is rendered.
Revise all contrib plugin examples to use YAML frontmatter to load the plugin.
This supersedes https://github.com/com-lihaoyi/mill/pull/4984

Parse YAML frontmatter only from file head

---

example/large/selective/9-selective-execution/build.mill
libs/main/src/mill/main/MainModule.scala
libs/main/src/mill/main/SelectiveExecutionModule.scala

The hope is, to have some meaningfull `mill inspect selective` output, but it seems, inspect does not output the Scaladoc for modules yet.
Fixed some typos along the way.

Added module docs for selective execution

---

runner/client/src/mill/runner/client/JLineNativeLoader.java

Comes from https://github.com/com-lihaoyi/mill/pull/4917, but shouldn't be a problem

Respect XDG_CACHE_HOME in JLineNativeLoader

---

runner/src/mill/runner/MillBuildRootModule.scala
runner/src/mill/runner/MillCliConfig.scala
scalalib/src/mill/scalalib/package.scala

Fix https://github.com/com-lihaoyi/mill/issues/5004
This also backports https://github.com/com-lihaoyi/mill/pull/5006 ands support for the `mvn:` prefix in the `--import` CLI option.

Mill 1.0 compat: Add `mvn` string interpolator for `ivy` dependencies

---

build.mill
ci/mill-bootstrap.patch
core/util/src/mill/util/Jvm.scala
dist/package.mill
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.iml
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.mill-build.iml
integration/ide/gen-idea/resources/hello-idea/idea/mill_modules/mill-build.iml
libs/scalalib/src/mill/scalalib/JvmWorkerModule.scala

New attempt at https://github.com/com-lihaoyi/mill/pull/4917
It seems the too long paths are being an issue as soon as we bump the coursier version ([this job](https://github.com/alexarchambault/mill/actions/runs/14705154651/attempts/1) only bumps the coursier version, and results in issues with too long GraalVM paths).
Unlike https://github.com/com-lihaoyi/mill/pull/4917, this not only uses short paths in examples and integration tests, but also in the Mill build itself. It seems this makes `dist.native.nativeImage` happy.

Update coursier to 2.1.25-M11 and use short paths for GraalVM distributions (new attempt)

---

core/define/src/mill/define/SelectiveExecution.scala
core/eval/src/mill/eval/EvaluatorImpl.scala
core/eval/src/mill/eval/SelectiveExecutionImpl.scala
integration/invalidation/selective-execution/src/SelectiveExecutionTests.scala
libs/main/src/mill/main/SelectiveExecutionModule.scala

Forward port to `main` of https://github.com/com-lihaoyi/mill/pull/5032
If you have two modules and run `--watch {moduleA.fooCommand,moduleB.fooCommand}`, mill will run `moduleB.fooCommand` every 2nd change to `moduleA`, even if there is no changes to `moduleB`.
The problem stems from the fact that when we save the changed inputs in selective execution, we did not store the inputs from `moduleB` and when selective execution runs again (the 2nd time), it thinks that *everything* in `moduleB` changed.
This fix correctly saves the state of all modules when storing the selective execution state.

Fix selective execution when multiple changes are made to one module under --watch (main branch)

---

integration/invalidation/selective-execution/src/SelectiveExecutionTests.scala
main/src/mill/main/RunScript.scala
main/src/mill/main/SelectiveExecution.scala
main/src/mill/main/SelectiveExecutionModule.scala

If you have two modules and run `--watch {moduleA.fooCommand,moduleB.fooCommand}`, mill will run `moduleB.fooCommand` every 2nd change to `moduleA`, even if there is no changes to `moduleB`.
The problem stems from the fact that when we save the changed inputs in selective execution, we did not store the inputs from `moduleB` and when selective execution runs again (the 2nd time), it thinks that *everything* in `moduleB` changed.
This fix correctly saves the state of all modules when storing the selective execution state.

Fix selective execution when multiple changes are made to one module under --watch

---

runner/client/src/mill/runner/client/MillProcessLauncher.java

This was lost in the churn of https://github.com/com-lihaoyi/mill/pull/5025, and re-implementing it should fix the re-bootstrapping problems we hit in https://github.com/com-lihaoyi/mill/pull/5050

Re-implement cached JVM existence check in Mill client

---

runner/client/src/mill/runner/client/MillProcessLauncher.java

Same as https://github.com/com-lihaoyi/mill/pull/5051 but for the runner jars instead of the JVM itself. Similarly, we want to make sure the cached metadata refers to files that actually exist, and if not we should re-run the resolution

Add bootstrapped runner jars existence check

---

.github/workflows/run-tests.yml
example/package.mill
example/thirdparty/android-endless-tunnel/build.mill
libs/androidlib/src/mill/androidlib/AndroidAppModule.scala

Following the work on https://github.com/com-lihaoyi/mill/pull/5013 I've added a third party example for Android native. I included an `androidRun` command as a testing motivation . (which we can connect to run and subsequently to IDE BSP run in the future) 
The example increases confidence on building android native apps with mill and it is another milestone for Mill's android support .
https://github.com/user-attachments/assets/a442a185-4b45-4342-9d78-3c1fe726873b

Third party example for android native: endless-tunnel

---

example/extending/metabuild/4-meta-build/mill-build/build.mill
example/extending/metabuild/5-meta-shared-sources/mill-build/build.mill
integration/failure/root-module-compile-error/src/RootModuleCompileErrorTests.scala
integration/feature/scala-3-syntax/resources/mill-build/build.mill
integration/ide/build-classpath-contents/resources/mill-build/build.mill
integration/ide/gen-idea/resources/extended/mill-build/build.mill
integration/invalidation/multi-level-editing/resources/mill-build/build.mill
integration/invalidation/multi-level-editing/resources/mill-build/mill-build/build.mill
runner/meta/src/mill/runner/meta/CodeGen.scala
runner/meta/src/mill/runner/meta/MillBuildRootModule.scala

* Now that we are on Scala 3, `MillBuildRootModule` can be a `trait` like most other modules and still take implicit parameters
* That allows us to remove the special casing of `MillBuildRootModule` in codegen, since it can now stack with the default `MainRootModule` that non-meta-build root modules inherit from
* We can also remove the synthetic `import _root_.mill.runner.meta.MillBuildRootModule` that we were previously injecting into the scope, since now it is just another stackable trait like any other
* Also tidied up `CodeGen.scala` a bit to reduce duplication

Simplify handling of `MillBuildRootModule` in `CodeGen`

---

main/define/src/mill/define/Discover.scala

without this in case there is another mill package (which is often the case for [plugins](https://github.com/disneystreaming/smithy4s/blob/series/0.18/modules/mill-codegen-plugin/src/smithy4s/codegen/mill/Smithy4sModule.scala#L17)) following error occurs during macro expansion:
```
[error] [millCodegenPlugin0_12] /home/kghost/workspace/smithy4s/modules/mill-codegen-plugin/src/smithy4s/codegen/LSP.scala:30:32: object define is not a member of package smithy4s.codegen.mill
[error] [millCodegenPlugin0_12]   lazy val millDiscover = mill.define.Discover[this.type]
[error] [millCodegenPlugin0_12]                                ^
[error] [millCodegenPlugin0_12] one error found
[error] [millCodegenPlugin0_12] (millCodegenPlugin0_12 / Compile / compileIncremental) Compilation failed
[error] Total …
```

fix: Use root qualifier in Discover macro

---

core/constants/src/mill/constants/OutFiles.java
core/constants/src/mill/constants/ProxyStream.java
core/constants/src/mill/constants/ServerFiles.java
example/fundamentals/out-dir/1-out-files/build.mill
runner/bsp/worker/src/mill/bsp/worker/BspWorkerImpl.scala
runner/bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
runner/client/src/mill/client/ServerLauncher.java
runner/client/src/mill/client/lock/DoubleLock.java
runner/client/src/mill/client/lock/DoubleLocked.java
runner/client/src/mill/client/lock/DoubleTryLocked.java
runner/client/src/mill/client/lock/FileLock.java
runner/client/src/mill/client/lock/Locks.java
runner/daemon/src/mill/daemon/MillMain.scala
runner/daemon/src/mill/daemon/MillServerMain.scala
runner/launcher/src/mill/launcher/MillLauncherMain.java
runner/launcher/src/mill/launcher/MillProcessLauncher.java
runner/server/src/mill/server/Server.scala
runner/server/test/src/mill/server/ClientServerTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5031
* We now only have a single server process running at a time, and no longer keep up to 5 separate `serverDir-1` to `serverDir-5` folders. Essentially we are migrating from the style of concurrency used by `gradle` and `mvnd` to the style of concurrency used by `bazel`
* We now only hold the `clientLock` until the server process is initialized (and has taken it's `processLock`) to avoid redundant initialization, and after that we release it to allow multiple clients to connect
* Since there is only one server and one `serverDir`, we have to remove several per-server files since there is no way to ensure they are unique in the presence of multiple clients
* `runArgs` can no longer be a file, and instead we send its contents over the …

Use a single Mill server process

---

runner/client/src/mill/client/ServerCouldNotBeStarted.java
runner/client/src/mill/client/ServerLauncher.java
runner/client/src/mill/client/lock/DoubleLock.java
runner/client/src/mill/client/lock/MemoryLock.java
runner/launcher/src/mill/launcher/MillLauncherMain.java
runner/launcher/src/mill/launcher/MillProcessLauncher.java
runner/server/test/src/mill/server/ClientServerTests.scala

* Fix `DoubleLock` hierarchical locking discipline. This makes the locking/unlocking order correct, and seems to make some non-deterministic `OverlappingFileLockException`s stop happening in my manual testing
* Re-organize `ServerLauncher.run`, folding in `acquireLocksAndRun` into the main `run` body and breaking out parts of it into helper methods. It could be greatly simplified since we no longer need to loop over the possible server dirs to claim one
* Remove `setJnaNoSys` handling, which I *think* is not necessary anymore now that we have cleaner classpath/process isolation between the Mill client and server

Cleanups for `ServerLauncher.scala`

---

ci/mill.ps1
mill
mill.bat
scripts/package.mill
scripts/src/mill.bat
scripts/src/mill.sh

Fix https://github.com/com-lihaoyi/mill/issues/5076
Although this property is no longer in use,
we still need it for older Mill versions,
including the latest available stable Mill release `0.12.10`.
This reverts some changes from PR https://github.com/com-lihaoyi/mill/pull/5061

Fix support for older Mill version in bootstrap scripts

---

build.mill

Recently published in https://github.com/com-lihaoyi/mill/actions/runs/14896055766/job/41838705072
This speeds up our test suite considerably from not constantly re-compiling these scala sources

Use pre-published 2.13.16 zinc compiler bridge

---

integration/feature/leak-hygiene/src/LeakHygieneTests.scala
libs/kotlinlib/src/mill/kotlinlib/KotlinModule.scala
libs/kotlinlib/src/mill/kotlinlib/KotlinWorkerManager.scala
libs/kotlinlib/src/mill/kotlinlib/js/KotlinJsModule.scala
libs/kotlinlib/src/mill/kotlinlib/ksp/KspModule.scala

This lets us re-use classloaders between modules while being safe w.r.t. parallelism and teardown
CC @lefou

Move `KotlinWorker` over to `CachedFactory`

---

integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.iml
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.mill-build.iml
integration/ide/gen-idea/resources/hello-idea/idea/mill_modules/mill-build.iml
libs/androidlib/src/mill/androidlib/AndroidAppModule.scala
mill-build/src/millbuild/Deps.scala

Split out from https://github.com/com-lihaoyi/mill/pull/5043 due to apparent breakage in the upgrade

Bump OS-Lib

---

core/api/src/mill/api/internal/api.scala
core/constants/src/mill/constants/Profiler.java
core/define/src/mill/define/PathRef.scala
integration/invalidation/multi-level-editing/src/MultiLevelBuildTests.scala
runner/daemon/src/mill/daemon/MillBuildBootstrap.scala
runner/daemon/src/mill/daemon/RunnerState.scala
runner/launcher/src/mill/launcher/MillProcessLauncher.java
runner/meta/src/mill/meta/MillBuildRootModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5010, brings `./mill version` JVM launcher times down from ~400ms to ~100-150ms, and native launcher times down to ~50ms, in line with the 0.12.10 numbers. Still more optimization we can do, but this will do for now to close the original ticket.
1. Avoid redundantly hashing files to create `PathRef`s in `MillBuildBootstrap`, which was also expensively creating them all with `quick=false` even for expensive external jars. Instead, we make `PathRef` extend a shared `mill.api.internal.PathRefApi` trait that we can share across the classloader boundary (unlike `PathRef` itself which cannot be shared due to a dependencies on OS-Lib/uPickle), and use the existing `PathRef#sig` directly. This was the main culprit adding 250+ms every run on an …

Re-optimize Mill launch times

---

core/eval/package.mill
core/exec/package.mill
core/resolve/package.mill

These are no longer on the `build.mill` classpath since https://github.com/com-lihaoyi/mill/pull/4879 so they can evolve freely without backwards compatibility concerns

Tag `core.eval`, `resolve`, and `exec` as non-stable `MillPublishScalaModule`s

---

libs/main/src/mill/main/VcsVersion.scala

When mill `out/` directory was moved out of srctree by MILL_OUTPUT_DIR env, all git cmds w/o `cwd` set to `vcsBasePath` will be failed.

bugfix: All git cmds should be run with cwd=vcsBasePath

---

build.mill
dist/scripts/src/mill.bat
dist/scripts/src/mill.sh
mill
mill.bat

File extension for the download URL needed to change, because the new sonatype central publishing pipeline doesn't accept shell-prefixed assemblies or native image binaries with the `.jar` prefix, so I instead suffixed it with `.exe`

Rebootstrap on top of sonatype central published artifacts

---

libs/scalalib/src/mill/scalalib/Lib.scala

It seems these `forceVersion` calls are unnecessary, these versions are either already forced via `ScalaModule#mapDependencies` (and if its branch's CI is happy, an upcoming PR of mine should move that to `ScalaModule#resolutionParams`), or don't need to be forced apparently (for the scaladoc stuff).

Don't unnecessarily force versions

---

build.mill

This ought to make Scala Steward send updates for the [coursier jvm-index version](https://github.com/com-lihaoyi/mill/blob/a5c41ce47643f8f3630fb220d0d659cf8c20e9ab/mill-build/src/millbuild/Deps.scala#L182) we're using

Add coursier jvm-index version to dummy dep list for updates

---

example/depth/sandbox/1-task/build.mill
integration/invalidation/multi-level-editing/src/MultiLevelBuildTests.scala
integration/invalidation/process-file-deleted-exit/src/ProcessFileDeletedExit.scala
runner/client/src/mill/client/ServerLauncher.java
runner/launcher/src/mill/launcher/MillLauncherMain.java
runner/server/src/mill/server/Server.scala
runner/server/test/src/mill/server/ClientServerTests.scala
testkit/src/mill/testkit/IntegrationTesterBase.scala
testkit/test/src/mill/testkit/ExampleTesterTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5112
This PR also makes us take the lock when checking the Mill version, so when we exit we can be sure we are not interrupting any other concurrent launcher connected to the same daemon, and extends it to also exit when the Java home changes
We still maintain support for multiple processes in `--no-server` mode, since in that case you may have multiple clients running at the same time (e.g. waiting on `--watch`) and each client needs it's own corresponding server process

Remove per-mill-version server dir 

---

core/util/package.mill
libs/scalalib/package.mill
libs/scalalib/src/mill/javalib/revapi/RevapiModule.scala
libs/scalalib/src/mill/scalalib/PublishModule.scala
runner/bsp/package.mill

* Remove `PublishModule.publishSelfDependency`. It is identical to `artifactMetadata`, which has the arguably better name.
* Don't use deprecated task in build script.
* Fix https://github.com/com-lihaoyi/mill/issues/5116
* To prepare the removal, we deprecated it in for Mill 0.12.12 to prepare the removal. See https://github.com/com-lihaoyi/mill/pull/5117

Remove `PublishModule.publishSelfDependency` in favor of `artifactMetadata`

---

build.mill
mill
mill.bat

Backport of https://github.com/com-lihaoyi/mill/pull/5124, and pulls in all the other changes in the `mill` and `mill.bat` file from the `main` branch

(Backport) Update `mill` and `mill.bat` to download 0.12.12 and above from the `.exe` URL

---

build.mill
core/define/src/mill/define/Task.scala
runner/bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
runner/daemon/src/mill/daemon/MillMain.scala
runner/server/src/mill/server/Server.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5038
Adding the `sourcecode.Enclosing` is not pretty, but it's better than what it was before, as at least the `Task.Anon(...)` parens contain some useful information (albeit a bit verbosely):
```
Another Mill process is running 'Task.Anon@8a58691(mill.scalalib.ScalaModule#bspBuildTargetData) Task.Anon@637be5e2(mill.scalalib.ScalaModule#bspBuildTargetData) Task.Anon@18e95310(mill.scalalib.ScalaModule#bspBuildTargetData) Task.Anon@1df556d4(mill.scalalib.ScalaModule#bspBuildTargetData) Task.Anon@39c0caf5(mill.scalalib.ScalaModule#bspBuildTargetData) Task.Anon@5a87cda(mill.scalalib.ScalaModule#bspBuildTargetData) Task.Anon@578bceac(mill.scalalib.ScalaModule#bspBuildTargetData) 
... 
Task.Anon@33d116e7(mill.scalalib.ScalaModule#bspBuildTargetDat …
```

Add `sourcecode.Enclosing` to `Task.Anon#toString` and `sourcecode.Name` to BSP `mill-active-command`s

---

core/define/package.mill
integration/feature/scala-3-syntax/resources/build.mill
integration/feature/scala-3-syntax/src/Scala3SyntaxTests.scala
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.iml
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.mill-build.iml
integration/ide/gen-idea/resources/hello-idea/idea/mill_modules/mill-build.iml
mill-build/src/millbuild/Deps.scala

Pulls in @bishabosha's work in https://github.com/com-lihaoyi/upickle/pull/662, which gives us an opt-in implicit for Scala >=3.7.0 that lets us serialize named tuples as JSON dictionaries
CC @lefou

Bump uPickle to 4.2.1, test namedtuple integration

---

dist/package.mill
libs/init/package.mill

We were using the `lastTag` rather than the current `millVersion`, which made the `./mill` launcher use the last stable version rather than the example version, and the download URLs have an extra `mill-dist-` prefix

Fixes for `mill init` example zip version and urls

---

build.mill
website/docs/modules/ROOT/pages/index.adoc
website/package.mill

This isn't stored in any tag in the Git repo, so we need to fetch it from Maven Central's `maven-metadata.xml` in an input task
I also broke up the `oldDocSources` into multiple smaller tasks using a `Cross` module, so we can get some parallelism on what is typically a pretty slow code path

Add latest unstable release to docsite

---

.editorconfig
core/define/src/mill/define/Task.scala
integration/invalidation/run-background/src/RunBackgroundTests.scala
libs/pythonlib/src/mill/pythonlib/PythonModule.scala
libs/scalalib/backgroundwrapper/src/mill/scalalib/backgroundwrapper/MillBackgroundWrapper.java
libs/scalalib/src/mill/scalalib/RunModule.scala
mill-build/src/millbuild/MillPublishJavaModule.scala
website/docs/modules/ROOT/pages/cli/flags.adoc

Currently the `runBackground` uses file locks and generated UUIDs for coordination.
This sometimes leads to the cases where a new background process is launched while the old one is still running because the JVM seems to release file locks before network sockets.
Because Mill now uses JDK 11, we can use it's APIs to transition to process id based watching, which should alleviate this problem.
`0.12.x` branch backport: https://github.com/com-lihaoyi/mill/pull/5120

Make `runBackground` use process IDs

---

runner/client/src/mill/client/ClientUtil.java
runner/client/test/src/mill/client/ClientTests.java

Fixes https://github.com/com-lihaoyi/mill/issues/5149
Someone I can't get a reliably repro of that failure, but this PR should theoretically fix the mechanism through which the failure happens by making the launcher-daemon protocol robust against null strings

Fix NullPointerException when java home not provided

---

runner/client/src/mill/client/lock/DoubleLock.java
runner/client/src/mill/client/lock/DoubleLocked.java
runner/daemon/src/mill/daemon/MillDaemonMain.scala
runner/daemon/src/mill/daemon/MillMain.scala

This PR makes some uses of `DoubleLock` safer, and fixes a race condition with it.
`DoubleLock` is basically used as a wrapper around a file lock (second lock), using it alongside a memory lock (first lock), that acts as a mutex for it. That way, the same JVM process doesn't try to acquire the file lock twice at the same time in a given JVM, which `java.nio.channels.FileChannel` doesn't allow (it throws an `OverlappingFileLockException` in that case).
This PR makes sure `MillMain` and `MillDaemonMain` use the same `Lock.memory()` instance as a guard when trying to acquire a lock for the output directory. This doesn't solve the issue I was running into (see below), but seems to be safer nonetheless.
It also tries to dispose of locks in `DoubleLock` in case calls to `Lock#{lock,tryLock}` …

Fix race condition in DoubleLocked#release

---

scalalib/src/mill/scalalib/JavaModule.scala
scalalib/test/src/mill/scalalib/CrossVersionTests.scala

Before, some `:0+mill-internal` were not properly removed, e.g. when on the last line of the rendered tree.

Fix internal names mangling in `mvnDepsTree`

---

core/api/src/mill/api/SystemStreams.scala
core/api/src/mill/api/internal/api.scala
core/define/src/mill/define/SystemStreams.scala
core/internal/src/mill/internal/PrefixLogger.scala
core/internal/src/mill/internal/SimpleLogger.scala
integration/ide/bsp-server/resources/project/build.mill
integration/ide/bsp-server/resources/snapshots/logging
integration/ide/bsp-server/resources/snapshots/workspace-build-targets.json
integration/ide/bsp-server/src/BspServerTestUtil.scala
integration/ide/bsp-server/src/BspServerTests.scala
libs/scalalib/src/mill/scalalib/JavaModule.scala
libs/testrunner/src/mill/testrunner/TestRunnerUtils.scala
runner/bsp/package.mill
runner/bsp/worker/src/mill/bsp/worker/BspWorkerImpl.scala
runner/bsp/worker/src/mill/bsp/worker/MillBspLogger.scala
runner/bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
runner/bsp/worker/src/mill/bsp/worker/MillJavaBuildServer.scala
runner/bsp/worker/src/mill/bsp/worker/MillJvmBuildServer.scala
runner/bsp/worker/src/mill/bsp/worker/MillScalaBuildServer.scala
runner/daemon/src/mill/daemon/MillMain0.scala
runner/daemon/src/mill/daemon/RunnerState.scala
runner/launcher/src/mill/launcher/MillProcessLauncher.java

Same as https://github.com/com-lihaoyi/mill/pull/5154, with a cleaner git history to ease review
---
When Mill runs as a BSP server, this makes it log in a similar way as when running Mill from the command-line, with `[…] ` prefixes.
For example, the small BSP session run in the test added in this PR logs the following to stderr:
```text
[bsp] Trying to load BSP server...
[bsp] BSP server started
[1-buildInitialize] Entered buildInitialize
[1-buildInitialize] buildInitialize took 2 msec
[2-workspaceBuildTargets] Entered workspaceBuildTargets
[bsp-init-build.mill-61] [info] compiling 3 Scala sources to /Users/alexandre/projects/mill/mill-class-loading/out/integration/ide/bsp-server/local/daemon/testForked.dest/sandbox/run-1/out/mill-build/compile.dest/classes ...
[bsp-init-build.mill-61] …
```

Prefix logging for BSP

---

integration/feature/leak-hygiene/src/LeakHygieneTests.scala
libs/scalalib/worker/src/mill/scalalib/worker/JvmWorkerImpl.scala
runner/launcher/src/mill/launcher/MillProcessLauncher.java

IIUC, in order to cache opened zip files, scalac delays the closing of those with [a timer](https://github.com/scala/scala/blob/6d0b1346d645ea79ad6aaedba90a098b4af5b01f/src/compiler/scala/tools/nsc/classpath/ZipAndJarFileLookupFactory.scala#L326C15-L326C20). The thread created by this timer keeps hanging around, making Mill leak threads. So https://github.com/com-lihaoyi/mill/pull/5082 disabled that timer. It seems disabling that timer creates new issues: https://github.com/com-lihaoyi/mill/issues/5159 (which look like scalac bugs to me).
So that PR handles those timers another way: it uses reflection to get the timers created by scalac, and stops them manually, when we dispose of the scala compiler.

Manually stop scalac timers

---

core/util/package.mill
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.iml
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.mill-build.iml
integration/ide/gen-idea/resources/hello-idea/idea/mill_modules/mill-build.iml
libs/main/package.mill
libs/scalalib/package.mill
mill-build/src/millbuild/Deps.scala
runner/idea/package.mill
runner/launcher/package.mill

Fixes https://github.com/com-lihaoyi/mill/issues/5183. Also moved `sonatype-central-client`, `graphviz-java`, and `jgrapht` off the compile classpath. All in all removes ~91 jars from the compile classpath, cleaning it up considerably
It might be worth defining a new `def privateMvnDeps` task to automate the tedious work of duplicating the same deps in `runMvnDeps` and `compileMvnDeps`
CC @alexarchambault

Exclude coursier dependencies from compile time classpath by default

---

core/exec/src/mill/exec/Execution.scala
core/exec/src/mill/exec/ExecutionContexts.scala
core/exec/src/mill/exec/GroupExecution.scala
integration/feature/leak-hygiene/resources/build.mill
integration/feature/leak-hygiene/src/LeakHygieneTests.scala
runner/daemon/src/mill/daemon/MillBuildBootstrap.scala
runner/daemon/src/mill/daemon/MillMain0.scala
testkit/src/mill/testkit/UnitTester.scala

This makes `mill.exec.Execution` accept a thread pool in its constructor, rather than creating one every time tasks need to be run. In BSP and in watch mode, this should save the thread pool creation across task runs. I don't have numbers to back the impact of this change, but factoring the thread pool was part of [a bunch of optimizations](https://github.com/coursier/sbt-coursier/pull/256) in the coursier integration in sbt a few years ago. Plus given we follow more of a single-execution-at-a-time model, there's no reason not to re-use the thread pool across executions.

Factor thread pool used to run tasks

---

example/thirdparty/androidtodo/build.mill
libs/androidlib/src/mill/androidlib/AndroidAppModule.scala
libs/androidlib/src/mill/androidlib/AndroidModule.scala
libs/androidlib/src/mill/androidlib/AndroidSdkModule.scala

This PR standardises the use of application id and namespace. It is also one of the pre-requisites of making hilt instrumented tests to work.
The application id is a unique id for every android app , so the android manifest package depends on it.
The android manifest package is also used whenever there's a relative path for Applications and activities so
```xml
<manifest package="com.foo">
<application android:name=".TodoApplication"/>
</manifest>
```
Becomes 
```xml
<manifest package="com.foo">
<application android:name="com.foo.TodoApplication"/>
</manifest>
```
During manifest merging. Because this happens when the manifest is loaded (before everything is merged) we start with the manifest package being the android namespace. We then pass the package property to the merger to be the …

Android: Standardize the use of application id and namespace

---

dist/scripts/src/mill.sh
mill

Fixes https://github.com/com-lihaoyi/mill/issues/5231 with the bash bootstrap script. Seems like it was broken by https://github.com/com-lihaoyi/mill/pull/4052
Doesn't fix the `.bat` script which has the same bug, but that one has had the bug since forever, whereas the bash bug was a recent regression
Tested manually on my laptop, now commands like `./mill -ikj1 version` work where previously they didn't

Fix grouped `-i` handling in bootstrap script

---

core/api/src/mill/api/internal/MillScalaParser.scala
integration/failure/compile-error/resources/build.mill
integration/failure/compile-error/src/CompileErrorTests.scala
integration/feature/leak-hygiene/src/LeakHygieneTests.scala
runner/daemon/src/mill/daemon/MillScalaParserImpl.scala
runner/launcher/src/mill/launcher/CoursierClient.scala
runner/meta/src/mill/meta/FileImportGraph.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5223
Previously the script parser would look for the `package build` line and then discard anything before it. Now, we explicitly keep the `prefix: String` of any code before the `package`, which can basically only be line comments or block comments, and prepend it back onto the script code before passing it further down the pipeline to keep the line numbers the same as they were before

Fix line numbers of files with yaml predefs

---

build.mill
scalalib/src/mill/scalalib/JsonFormatters.scala

Same version as the one used in `main`

Update coursier to 2.1.25-M13 (0.12.x)

---

libs/androidlib/src/mill/androidlib/AndroidAppModule.scala
libs/androidlib/src/mill/androidlib/AndroidModule.scala
libs/androidlib/src/mill/androidlib/manifestmerger/AndroidManifestMerger.scala

During testing more android samples (compose-sample) it became apparent that the merger can conflict in 2 situations:
1. Dependency resolution: AndroidAppModule uses a separate strategy for resolving android dependencies (e.g. environment android etc) while the merger is a jvm app, running on the host machine.
2. Classpath conflicts, picking up wrong classes from the shared classloader.
I've separated the merger into its own external module, which allows it to have an independent dependency resolution strategy.
Classpath issues are also resolved with this approach.
I've noticed while experimenting for compose-samples that runClasspath is not properly evaluated (due to caching) as I've missed to make it Task.Anon, fixed in this PR

Separate android manifest merger to avoid classpath conflicts

---

core/exec/src/mill/exec/Execution.scala
core/exec/src/mill/exec/GroupExecution.scala
example/depth/sandbox/1-task/build.mill
integration/failure/os-checker/src/OsCheckerTests.scala

Prints the name of the task in the error message, so it's more clear what the problem is.
Noticed when investigating https://github.com/com-lihaoyi/mill/issues/5248

Improve error reporting for OS checker errors

---

integration/ide/bsp-server/resources/project/build.mill
integration/ide/bsp-server/resources/project/errored/compilation-error/src/Thing.scala
integration/ide/bsp-server/resources/snapshots/logging
integration/ide/bsp-server/resources/snapshots/workspace-build-targets.json
integration/ide/bsp-server/src/BspServerTests.scala
runner/bsp/worker/src/mill/bsp/worker/BspCompileProblemReporter.scala
runner/bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
runner/bsp/worker/src/mill/bsp/worker/Utils.scala

This fixes a regression from #5200. Since #5200, if the code base doesn't compile, an error notification was shown to users via `onBuildShowMessage` (dismiss-able notification in the lower right corner of the window in VSCode). This PR makes Mill stop doing that, but keeps showing such a notification if the compile request goes wrong for another reason (like a failing intermediate task - behavior introduced in #5200).

Don't send onBuildShowMessage upon simple compilation errors

---

core/resolve/src/mill/resolve/Resolve.scala
core/resolve/src/mill/resolve/ResolveCore.scala
core/resolve/test/src/mill/resolve/ErrorTests.scala
libs/main/src/mill/main/MainModule.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5280
We can improve the pretty-printing out `resolve` output later, but this at least gives some kind of meaningful ordering so e.g. `resolve _` shows the stuff you probably care most about at the top

Sort resolve output with modules first, then commands, then other tasks

---

build.mill
libs/tabcomplete/src/mill/tabcomplete/TabCompleteModule.scala
libs/tabcomplete/test/src/mill/tabcomplete/TabCompleteTests.scala

```
> ./mill bar<TAB>
bar
bar.task2
> ./mill qux<TAB>
qux
qux[12]
qux[34]
qux[56]
```
Implementing this involved looking for the case where the first `resolve` returns an exact match for the current token, and if so perform a second `resolve` with `._` appended to the current token.
Tested manually in Zsh on Mac, also updated the unit tests to consider these cases

Tab complete nested modules and tasks when token is exact match for module

---

integration/ide/bsp-server/src/BspServerTestUtil.scala
integration/ide/bsp-server/src/BspServerTests.scala
integration/package.mill

The current way of changing the code and then changing it back is error prone, as witnessed in https://github.com/com-lihaoyi/mill/pull/5265#discussion_r2140429333 .
I changed it to use an environment variable, which has no chance of being committed to the codebase.

Update BSP test snapshots via MILL_TESTS_BSP_UPDATE_SNAPSHOTS env var

---

core/define/package.mill
core/define/test/src/mill/define/BasePathTests.scala
core/define/test/src/mill/define/DiscoverTests.scala
core/define/test/src/mill/define/ModuleTests.scala
core/define/test/src/mill/define/TestGraphs.scala
core/define/test/src/mill/define/UTestFramework.scala
core/exec/test/src/mill/exec/CrossTests.scala
core/exec/test/src/mill/exec/ExecutionTests.scala
core/exec/test/src/mill/exec/PlanTests.scala
core/resolve/test/src/mill/resolve/ModuleTests.scala
core/resolve/test/src/mill/resolve/ResolveTests.scala
libs/main/package.mill
libs/main/test/src/mill/TestMain.scala
mill-build/src/millbuild/MillBaseTestsModule.scala
mill-build/src/millbuild/MillJavaModule.scala

It only really requires stuff in `core` anyway, so no sense pulling in stuff in `main`
After this PR, ` ./mill plan core.define.test | grep main.` no longer returns any results

Move `TestGraphs` from `libs.main` to `core.define` modules

---

.github/workflows/run-tests.yml
ci/mill-bootstrap.patch
core/define/src/mill/define/SubfolderModule.scala
integration/failure/root-module-compile-error/src/RootModuleCompileErrorTests.scala
integration/ide/build-classpath-contents/src/BuildClasspathContentsTests.scala
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.iml
integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.mill-build.iml
integration/ide/gen-idea/resources/hello-idea/idea/mill_modules/mill-build.iml
libs/init/buildgen/src/mill/main/buildgen/BuildGenUtil.scala
libs/init/gradle/src/mill/main/gradle/GradleBuildGenMain.scala
libs/init/maven/src/mill/main/maven/MavenBuildGenMain.scala
libs/init/sbt/src/mill/main/sbt/SbtBuildGenMain.scala
libs/main/package.mill
libs/package.mill
libs/vcs/package.mill
libs/vcs/src/mill/vcs/VcsVersion.scala
libs/vcs/test/src/mill/vcs/VcsVersionTests.scala
runner/meta/src/mill/meta/CodeGen.scala

This makes the purpose of each module much cleaner and easier to document and understand
Also re-enabled some module test suites we forgot to enable before in CI

Move `VcsVersion` and `SubfolderModule` out of `mill.main` into its own module, re-enable forgotten tests

---

ci/mill-bootstrap.patch
libs/main/src/mill/main/package.scala

People should use `mill.util.Tasks` instead

Remove leftover `mill.main.Tasks` alias

---

libs/init/buildgen/src/mill/main/buildgen/BuildGenUtil.scala
libs/init/maven/test/resources/expected/misc/build.mill

We no longer allow calling upstream tasks in `Task.Sources`, and thus have to split it into a standalone `Task.Sources` and a normal `Task` that aggregates the `Task.Sources` with the `super`

Fix `Task.Sources` override in `./mill init`

---

core/resolve/src/mill/resolve/Resolve.scala

Hopefully this will make failures easier to debug than the status quo error:
```
java.util.NoSuchElementException: head of empty list
scala.collection.immutable.Nil$.head(List.scala:663)
scala.collection.immutable.Nil$.head(List.scala:662)
mill.resolve.Resolve$.instantiateCommand$$anonfun$1)Resolve.scala:202)
```

Improve error message for command instantiation failure

---

dist/package.mill
main/init/package.mill

Fixes https://github.com/com-lihaoyi/mill/issues/5238
Backport of https://github.com/com-lihaoyi/mill/commit/0d8285e215951fb7b0869d2af8ec3c423e72dace

Fix `./mill init` example download in 0.12.x

---

.github/actions/post-build-selective/action.yml

This should hopefully mitigate the risk of `no space left on device` that sometimes happens

Try to free up space on github actions workers.

---

core/define/src/mill/define/Module.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5345
The basic problem was that `import build._` pulled in the `build.moduleNestedCtx` implicit, which depending on scoping could over-ride the lexical `moduleNestedCtx`. This fix makes `moduleNestedCtx` `protected`, so it is available in the nested scope but cannot be imported
Tested manually, seems to fix the reported problem

Protect `moduleNestedCtx` to prevent it from being imported by `import build._`

---

.github/workflows/run-tests.yml
example/androidlib/kotlin/2-compose/build.mill
example/package.mill
example/thirdparty/android-compose-samples/build.mill
example/thirdparty/androidtodo/build.mill
libs/androidlib/src/mill/androidlib/AndroidAppBundle.scala
libs/androidlib/src/mill/androidlib/AndroidAppKotlinModule.scala
libs/androidlib/src/mill/androidlib/AndroidAppModule.scala
libs/androidlib/src/mill/androidlib/AndroidModule.scala
libs/androidlib/src/mill/androidlib/AndroidR8AppModule.scala

This PR builds on top of https://github.com/com-lihaoyi/mill/pull/5285 and https://github.com/com-lihaoyi/mill/pull/5285 , and extends the work by creating a new linking android resources method that triggers the merging algorithm (with flat files instead of zips and auto overlay, with -R to add each library resource)
- New configuration parameters were needed to include "common" dependencies otherwise some of them were failing to be resolved for android
This is the major change that allows for [JetLagged](https://github.com/android/compose-samples/tree/main/JetLagged) from compose samples to work (only to run the App for now). The key change was to overlay the flat files of the libraries (with `-R` parameter) instead of linking them together as command inputs (without -R)
This allows for …

Android compose samples: Jet Lagged

---

core/util/src/mill/util/Jvm.scala
integration/bootstrap/no-java-bootstrap/src/NoJavaBootstrapTests.scala
libs/androidlib/src/mill/androidlib/AndroidSdkModule.scala
libs/scalalib/src/mill/scalalib/dependency/metadata/MavenMetadataLoader.scala
runner/launcher/src/mill/launcher/CoursierClient.scala

This fixes https://github.com/com-lihaoyi/mill/issues/5358 by ensuring the coursier cache logger is initialized and then stopped around calls that might download things.
Fixes https://github.com/com-lihaoyi/mill/issues/5358

Ensure the coursier cache logger is properly initialized / stopped

---

core/define/src/mill/define/Discover.scala
core/exec/test/src/mill/exec/ExecutionTests.scala

Fixes  https://github.com/com-lihaoyi/mill/issues/5281
The previous code already collected all command overloads in the `Discover` data structure, but it returned one arbitrarily when queried. This PR makes it return the one with the longer argument list, which supports `@unroll`-style signature evolution of adding parameters with default values to the right side of a parameter list.
Added a unit test that fails on main, passes on this PR

Support command overloading in a binary compatible fashion

---

integration/invalidation/watch-source-input/src/WatchSourceInputTests.scala
testkit/src/mill/testkit/IntegrationTester.scala
testkit/src/mill/testkit/UtestIntegrationTestSuite.scala
testkit/src/mill/testkit/helpers.scala

While debugging https://github.com/com-lihaoyi/os-lib/pull/398 I encountered a lackluster developer experience when running `WatchTests`.
- It took ages for the tests to fail.
- When the tests failed, the amount of context was very low.
This PR improves on both of those areas:
- `WatchTests` timeout is now `15s` instead of `120s` when running not on CI.
- If the test fails the `eval` context (things like working directory, the command line for eval and environment variables) is printed out.
To achieve that, I introduced:
- `prepEval` - as `eval` but doesn't actually execute immediatelly.
- `withTestClues` - enhances `utest.AssertionError` thrown in the block with the given `TestValues`

`IntegrationTester.prepEval` and improved `WatchTests`

---

example/thirdparty/android-compose-samples/build.mill

Following https://github.com/com-lihaoyi/mill/pull/5341, this PR also adds the androidTest in the JetLagged example
No changes were required on mill.

Android tests included for jetlagged example

---

libs/kotlinlib/package.mill
libs/scalajslib/package.mill
libs/scalanativelib/package.mill
libs/tabcomplete/package.mill
libs/vcs/package.mill

- `mill.vcs` needs to be stable
- `mill.tabcomplete` does not need to be stable
- `mill.scalanativelib`, `mill.scalajslib`, `mill.kotlinlib` can probably be stable by now

Stableize various modules

---

dist/package.mill
libs/init/package.mill

Previously, any change to any example folder would invalidate all of them via
```json
{
"dist.examplePathsWithArtifactName0": {
"dist.examplePathsWithArtifactName": {
"libs.init.exampleList": {
"libs.init.resources": {
"libs.init.localRunClasspath": {
"libs.init.localClasspath": {
"libs.main.test.transitiveLocalClasspath": {
"libs.main.test.runClasspath": {
"example.javalib.module[9-docjar].runClasspath": {
"example.javalib.module[9-docjar].local.daemon.runClasspath": {
"example.javalib.module[9-docjar].local.daemon.testForked": {}
}
},
```
This PR splits up `examplePathsWithArtifactNames` into `examplePaths`, `examplePathRefs`, and `exampleArtifactNames`. This allows `libs.init.exampleList` to avoid depending on the contents of the example folders, which should avoid invalidation of all …

Improve selective testing precision in Mill's example tests

---

.github/actions/setup-android/action.yml
example/androidlib/java/5-R8/build.mill
libs/androidlib/src/mill/androidlib/AndroidSdkModule.scala

Running the android tests on a vanilla setup lead to the error of not having `proguard` and provided `proguard` default configurations which the `r8` third party examples rely on.
Added `tools` to the sdk packages that get installed automatically and removed it from the setup android action
I think the future goal could be for mill to setup everything (with automatic license accept on CI) and we can slowly remove the setup android steps on the CI.
For example `cmdline-tools`'s manual installation seems necessary for now since sdkmanager comes with it.

Android: added `tools` sdk package to install automatically

---

.github/workflows/run-tests.yml
runner/client/src/mill/client/ClientUtil.java
runner/client/src/mill/client/ServerLauncher.java
runner/launcher/src/mill/launcher/MillLauncherMain.java
runner/launcher/src/mill/launcher/MillProcessLauncher.java
runner/server/src/mill/server/Server.scala
runner/server/test/src/mill/server/ClientServerTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5209
When using Graal Native Image, the launcher receives any `-D` properties as system properties rather than command-line flags. Thus we try to identify any system properties that are set by the user so we can propagate them to the Mill daemon process appropriately.
Testing this in CI is kind of annoying because there are 3 different dataflows that properties can go through: 
1. JVM launcher: the properties get passed through application-level flags and handled by mainargs
2. Native launcher daemon: the properties get picked up as system-props in the launcher, and passed over the socket at the start of a new connection
3. Native launcher nodaemon: the properties get picked up as system-props in the launcher, and passed as `-D` JVM flags …

Fix `-D` property passing with graal native launcher

---

integration/feature/mill-jvm-property/resources/build.mill
integration/feature/mill-jvm-property/src/MillJvmPropertyTests.scala

Integration test to reproduce https://github.com/com-lihaoyi/mill/issues/5416
Backport of https://github.com/com-lihaoyi/mill/pull/5212
It shows, that current `0.12.x` branch is not passing the test for `native` builds.
```console
> mill -j1 integration.feature[mill-jvm-property].native.__.test
...
[5956/5974] integration.feature[mill-jvm-property].native.fork.test
[5956] -------------------------------- Running Tests --------------------------------
[5956] Copying integration test sources from /home/lefou/work/opensource/mill-0.12/integration/feature/mill-jvm-property/resources to /home/lefou/work/opensource/mill-0.12/out/integration/feature/mill-jvm-property/native/fork/test.dest/sandbox/run-1
[5956] X mill.integration.MillJvmPropertyTests.simple 12660ms 
[5956]   utest.AssertionError: …
```

Add integration test ensuring `-D` property passing works (backport #5212)

---

libs/main/src/mill/main/MainModule.scala
runner/daemon/src/mill/daemon/MillMain0.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5448
`Task.Anon`s cannot call `Task.Command`s, so we move the `clean` logic into a separate `def cleanTask: Task.Anon` that can be shared between both

Fix bsp clean

---

runner/meta/src/mill/meta/CodeGen.scala

This might fix the issue with indentation of the generated code
```scala
object package_ extends package_ {
final lazy val x: _root_.build_.x.package_.type = _root_.build_.x.package_ // subfolder module reference
final lazy val y: _root_.build_.y.package_.type = _root_.build_.y.package_ // subfolder module reference
export build_.dependencies_.*
export build_.versions_.*
override lazy val millDiscover: _root_.mill.define.Discover = _root_.mill.define.Discover[this.type]
}
```
```scala
object package_ extends package_ {
final lazy val x: _root_.build_.x.package_.type = _root_.build_.x.package_ // subfolder module reference
final lazy val y: _root_.build_.y.package_.type = _root_.build_.y.package_ // subfolder module reference
export build_.dependencies_.*
export build_.versions_.*
override …
```

Fixed indentation issue with exportSiblingScripts

---

core/internal/src/mill/internal/PromptLogger.scala
core/internal/src/mill/internal/PromptLoggerUtil.scala
core/internal/test/src/mill/internal/PromptLoggerTests.scala

This would allow the prompt to continue to be shown after using `Ctrl-C` to interrupt a command, and avoid messing up the prompt in terminals like Windows Terminal which do not clear the screen after `Ctrl-C`
Instead of bundling the `up` codes immediately after every prompt and of the same height, we instead print the `up` codes before each prompt equal to the height of the _previously rendered_ prompt, which we track in a `lastPromptHeight` variable. This leaves the cursor after the prompt in between prints, so on interruption the prompt remains visible above.
Updated the unit tests to account for the cursor being on a new blank line, and manually tested it using `rm -rf out && ./mill-assembly.jar -i __.compile` on the Mill repo

Park cursor after the multiline prompt rather than at the start

---

contrib/sonatypecentral/readme.adoc
libs/javalib/src/mill/javalib/PublishModule.scala
libs/javalib/src/mill/javalib/SonatypeCentralPublishModule.scala
website/docs/modules/ROOT/partials/Publishing_Footer.adoc

Mill's artifact signing for publishing needs `gpg` to import the signing keys. However, the current implementation naively assumes that the key it imports is the only key.
If you have other keys in your keychain, a couple of things could happen:
- `gpg` by default signs using the first key in your keychain, which isn't necessarily the key you just imported, so your artifact can be signed using the wrong key.
- If the key `gpg` picks has a passphrase, `gpg` will hang indefinitely waiting for you to enter the passphrase to stdin, which will never happen, as it's mill handling the stdin.
This PR ensures that when the key is imported into GPG, its ID is extracted and then used in the signing commands to specify which key to use.
Tested manually on Linux and Mac.

Fix `gpg` hanging waiting for input when more than one key is present in keychain

---

core/api/src/mill/api/internal/Applicative.scala
core/api/test/src/mill/api/MacroErrorTests.scala

Returning a `Task[_]` from a `Task[_]` (for example, `Task[Task[Int]]`) should be always an error because the inner task is never detected as a dependency in the task graph and thus never executed.
Fixes https://github.com/com-lihaoyi/mill/issues/5263

Let `Task`-macros fail if their return value has a `Task`-type

---

.github/workflows/run-tests.yml
core/constants/package.mill
libs/javalib/src/mill/javalib/pmd/PmdArgs.scala
mill-build/build.mill
mill-build/src/millbuild/MillStableJavaModule.scala
mill-build/src/millbuild/MillStableScalaModule.scala
runner/daemon/src/mill/daemon/MillBuildBootstrap.scala
runner/daemon/src/mill/daemon/MillMain0.scala
runner/daemon/src/mill/daemon/Watching.scala

Turns on MIMA for `mill.constants` as well
Tested manually by breaking bincompat in `core.constants` and `libs.javalib` and making sure `__.mimaReportBinaryIssues` fails

Enable mima for Mill 1.0.0 series

---

runner/daemon/src/mill/daemon/MillMain0.scala

Fixes https://github.com/com-lihaoyi/mill/pull/5510
The version mismatch checker should strip trailing `-jvm` suffixes, just like it already strips trailing `-native`

Fix spurious version mismatch error when using `-jvm` launcher

---

libs/scalalib/src/mill/scalalib/CrossSbtModule.scala

They were pointing to src/main instead of src/test.
I was about to file an issue but the fix is easy enough. Of course this probably needs a test.

Fix version sources in CrossSbtTests

---

libs/javalib/src/mill/javalib/RunModule.scala

I think the existing logic in RunModule accidentally fails to give effect to user settings for `useCpPassingJar`, whether provided directly when running or via overriding `runUseArgsFile`. Currently, a temporary CLASSPATH-passing jar file will be created unconditionally, on any platform, if `runClasspath` is nonempty. 
This PR attempts to complete logic I think left accidentally not-quite-complete in RunModule.

Give effect to useCpPassingJar settings in RunModule

---

libs/androidlib/src/mill/androidlib/AndroidLibModule.scala
libs/javalib/src/mill/javalib/PublishModule.scala

While working on sonatype central snapshot publishing I noticed that `AndroidLibModule` is overriding `publishArtifacts` Task while copying a lot of code from the parent's `PublishModule.publishArtifacts` task.
For example, if you compare these two:
https://github.com/com-lihaoyi/mill/blob/8d6bbf562cbda3f5e730433d7d0e94f484681288/libs/javalib/src/mill/javalib/PublishModule.scala#L452-L480
https://github.com/com-lihaoyi/mill/blob/8d6bbf562cbda3f5e730433d7d0e94f484681288/libs/androidlib/src/mill/androidlib/AndroidLibModule.scala#L52-L78
You can see that most of the code is copy-pasted and only a few bits differ.
This leads to two problems:
1. If `PublishModule.publishArtifacts` logic is changed, people can forget to update the `AndroidLibModule.publishArtifacts`.
2. When changing either of …

Refactor publishing tasks into more granular blocks

---

example/thirdparty/android-compose-samples/build.mill
website/docs/modules/ROOT/nav.adoc
website/docs/modules/ROOT/pages/android/compose-samples.adoc
website/docs/modules/ROOT/pages/android/hilt-sample.adoc

Added [JetNews](https://github.com/android/compose-samples/tree/main/JetNews) to the compose samples.
The object structure is similar to the JetLagged sample. R8 still currently throws some errors but converting them to warnings allows the app to function and the tests to pass successfully. 
This expands the test coverage and will be useful for detecting regressions in the future

Android compose samples: JetNews

---

integration/feature/publish-sonatype-central-snapshots/src/PublishSonatypeCentralSnapshotTests.scala
integration/feature/publish-sonatype-central/resources/build.mill
integration/feature/publish-sonatype-central/resources/testProject/src/Foo.scala
integration/feature/publish-sonatype-central/src/PublishSonatypeCentralTests.scala
scalalib/maven-worker/src/mill/scalalib/maven/worker/impl/WorkerImpl.scala
scalalib/maven-worker/src/mill/scalalib/maven/worker/impl/WorkerRemoteM2Publisher.scala
scalalib/src/mill/scalalib/MavenWorkerSupport.scala
scalalib/src/mill/scalalib/SonatypeCentralPublishModule.scala
scalalib/src/mill/scalalib/SonatypeCentralPublisher.scala
scalalib/src/mill/scalalib/internal/MavenWorkerSupport.scala
testkit/src/mill/testkit/IntegrationTester.scala

Adds tests that run in CI that publish to a local directory for sonatype central release and snapshot publishing.
Backport of https://github.com/com-lihaoyi/mill/pull/5525

Add tests to sonatype snapshot publishing (0.12.x)

---

runner/launcher/src/mill/launcher/CoursierClient.scala

This can avoid useless error message like 
```
Either.right.get on Left
```

Avoid use .right.get.

---

.github/workflows/pre-build.yml
.github/workflows/run-tests.yml
example/migrating/javalib/3-maven-complete-large/build.mill
example/thirdparty/jimfs/build.mill
libs/scalajslib/test/src/mill/scalajslib/CompileLinkTests.scala
libs/scalajslib/test/src/mill/scalajslib/JarPublishRunTests.scala
libs/scalalib/test/src/mill/scalalib/CoursierMirrorTests.scala
libs/scalalib/test/src/mill/scalalib/spotless/SpotlessTests.scala
libs/scalanativelib/test/src/mill/scalanativelib/CompileRunTests.scala

* `libs.scalalib` was accidentally disabled during the `javalib`/`scalalib` split, so some tests bitrotted and were failing. Just disabled them for now so I can get the test suite running again
* Reduced test matrix size for scala-js/scala-native unit tests
* Reduce test matrix size across linux/windows, so each test only runs once on one OS or the other
* Consolidated CI into a smaller number of jobs to reduce per-job overhead (typically around a minute)
* Reduced the amount compiled in `build-linux`/`build-windows` jobs, to allow test-specific compilation to happen in parallel on each corresponding test job

More CI optimizations

---

libs/pythonlib/src/mill/pythonlib/PythonModule.scala

Hopefully this will fix the flakiness we've been seeing where the `scie` step in PEX gets rate limited by github
```
[6546] pex: Zipping PEX file.
[6546] pex: Zipping PEX file.: 347.5ms
[6546] pex: Building scie(s)
[6546] pex: Building scie(s): 3358.7ms
[6546] Traceback (most recent call last):
[6546]   File "/home/runner/work/mill/mill/out/integration/localOutFolder.dest/local-0/out/out/foo/pythonExe.dest/venv/lib/python3.12/site-packages/pex/result.py", line 105, in catch
[6546]     return func(*args, **kwargs)
[6546]            ^^^^^^^^^^^^^^^^^^^^^
[6546]   File "/home/runner/work/mill/mill/out/integration/localOutFolder.dest/local-0/out/out/foo/pythonExe.dest/venv/lib/python3.12/site-packages/pex/bin/pex.py", line 1379, in do_main
[6546]     for scie_info in scie.build(
[6546]   File …
```

Avoid configuring `scie` when building PEX files

---

libs/javalib/src/mill/javalib/JavaModule.scala
libs/kotlinlib/src/mill/kotlinlib/KotlinModule.scala
libs/scalalib/src/mill/scalalib/ScalaModule.scala
libs/scalalib/test/src/mill/scalalib/DottyDocTests.scala
libs/scalalib/test/src/mill/scalalib/ScalaDoc3Tests.scala
libs/scalalib/test/src/mill/scalalib/ScalaScaladocTests.scala

`JavaModule`, `ScalaModule` and `KoltinModule` currently implement the `docJar` task to produce an Javadoc-compatible JAR ready for publishing and consumption by IDEs. Unfortunately, this JAR is rather unsuited for direct consumption by a browser, e.g. to read the API documentation directly. It either needs to be extracted (Mill doesn't provide any convenience task for that) or users can use the implementation detail like the `javadoc` directory in the `javaDoc.dest`  directory, which is not documented and can change at any time.
This PR splits the generation of the API documentation from the `docJar` packaging. As a result, users can use the result of `javadocGenerated`, `scalaDocGenerated` and `dokkaGenerated` tasks to directly access the exploded API documentation. The names were …

Split up `docJar` into javadoc/scaladoc generation and jar creation

---

website/docs/modules/ROOT/partials/Publishing_Footer.adoc

This adds documentation on how to publish snapshots to Sonatype Central and how to consume these published snapshots.

Improve documentation for Sonatype Central snapshot publishing

---

libs/javalib/src/mill/javalib/PublishModule.scala

This was causing `docjar` to run every time tests were run locally, which likely surfaced the misbehavior mentioned in https://github.com/com-lihaoyi/mill/pull/5580 (though it's not the root cause) and also greatly slows down iterative development on this repo

Skip docjars and sourcejars when using `publishLocalTestRepo`

---

example/javalib/basic/4-compat-modules/bar/src/main/java/bar/Bar.java
example/javalib/basic/4-compat-modules/build.mill
example/javalib/basic/4-compat-modules/foo/src/integration/java/foo/FooIntegrationTests.java
example/kotlinlib/basic/4-compat-modules/build.mill
example/kotlinlib/basic/4-compat-modules/foo/src/integration/java/foo/FooIntegrationTests.kt
example/scalalib/basic/4-compat-modules/build.mill
example/scalalib/basic/4-compat-modules/foo/src/integration/scala/FooIntegrationTests.scala
libs/javalib/src/mill/javalib/MavenModule.scala
libs/kotlinlib/src/mill/kotlinlib/KotlinMavenModule.scala
libs/scalalib/src/mill/scalalib/SbtModule.scala

So an `object integration` automatically gets `src/integration/java/` as their sources, and `src/integration/` as their `intellijModulePathJava`, without the user needing to specifically configure it.
Update the three `4-compat-modules` example tests to exercise and document this

Make `MavenTests`/`SbtTests`/`KotlinMavenTests` modules take their folder path from their module name

---

libs/javalib/package.mill
libs/javalib/src/mill/javalib/MavenWorkerSupport.scala
libs/javalib/src/mill/javalib/publish/PublishInfo.scala
libs/javalib/test/src/mill/javalib/publish/PublishInfoTests.scala

This PR fixes parsing of strings like "chisel-plugin_3.3.4-7.0.0-RC3+5-c4ca27e5-SNAPSHOT.pom". Previously `chisel-plugin_2.13.14-7.0.0-RC3+4-4815de48-SNAPSHOT` would be identified as a `classifier`.
This happened because when constructing a regular expression we did not escape the id/version parts and thus symbols like + were interpreted as regex instructions instead of literals, which made the regex never match.
Additionally, a small refactoring has been done where `PublishInfo.parseFromFile` is now `PublishInfo.IvyMetadata.parseFromFile`, as it's actually the metadata we are parsing.

Fixes incorrect parsing of `PublishInfo` from string when artifact id or version contains regex-sensitive characters

---

libs/javalib/src/mill/javalib/SemanticDbJavaModule.scala
libs/javalib/test/src/mill/javalib/HelloJavaTests.scala
libs/scalalib/src/mill/scalalib/ScalaModule.scala
runner/daemon/src/mill/daemon/MillDaemonMain.scala

- Remove the code the cleans out the `classes/` folder or `zinc` file in between runs
- Add some custom code to remove old `.semanticdb` files when their originating `.java` or `.scala` files are not present
Tested by the existing unit tests, which seem pretty rigorous at failing if I didn't get the implementation quite right

Turn on incremental compilation for `semanticDbData` task

---

example/scalalib/module/9-docjar/build.mill
website/docs/modules/ROOT/pages/javalib/module-config.adoc
website/docs/modules/ROOT/pages/kotlinlib/module-config.adoc
website/docs/modules/ROOT/pages/scalalib/module-config.adoc

Unlike `scaladocOptions` and `javadocOptions`, `dokkaOptions` does not follow the `{language-small}docOptions` pattern, so we needed to add a new `{language-doc}` configuration for our docsite

Fix docs for `dokkaOptions`

---

core/exec/src/mill/exec/CodeSigUtils.scala

- Make `resolveTransitiveParents` an imperative breadth-first-search with seen-set, rather than the clever lazy-recursive iterator that would need to be de-duplicated later
- Call `.distinct` on the `enclosingCls`s before running `resolveTransitiveParents`, to avoid doing it more than once on each class
Seems to speed up `while true; do time ./mill-assembly.jar __.compile; done` from ~4.5s to ~2.5s per iteration, and makes this particular method drop off the JProfiler report

Optimize `precomputeMethodNamesPerClass` to speed up large mostly-cached builds

---

core/api/daemon/src/mill/api/daemon/Logger.scala
core/api/src/mill/api/MultiBiMap.scala
core/api/src/mill/api/TopoSorted.scala
core/api/src/mill/api/internal/Reflect.scala
core/eval/src/mill/eval/EvaluatorImpl.scala
core/exec/src/mill/exec/Execution.scala
core/exec/src/mill/exec/GroupExecution.scala
core/exec/src/mill/exec/PlanImpl.scala
core/internal/src/mill/internal/JsonArrayLogger.scala
core/internal/src/mill/internal/MultiLogger.scala
core/internal/src/mill/internal/PromptLogger.scala
core/internal/src/mill/internal/Tarjans.scala
core/internal/src/mill/internal/ThreadNumberer.scala
core/internal/test/src/mill/internal/PromptLoggerTests.scala
integration/feature/full-run-logs/src/FullRunLogsTests.scala
integration/feature/leak-hygiene/src/LeakHygieneTests.scala
libs/javalib/src/mill/javalib/JavaModule.scala
runner/daemon/src/mill/daemon/MillBuildBootstrap.scala
runner/daemon/src/mill/daemon/MillMain0.scala
testkit/src/mill/testkit/UnitTester.scala

- Move chrome profile handling from `Execution` into `PromptLogger`, so it can be used outside of the execution phase
- Consolidate chrome-profiling handling into `withPromptLine` to keep it consistent with the terminal UI
- Make chrome-profile logging use separate `begin` and `end` events, so that in-progress tasks can be properly displayed on the profile
- Move chrome-profile logging onto a separate thread to avoid blocking the main execution codepaths
- Add some ad-hoc profile logging for Mill lifecycle phases, to give an approximate view of where non-execution-related time is going. 
- This also makes `[resolve]` and `[planning]` visible in the terminal UI giving the user some indication of what is happening
- Added some minor micro-optimizations to hot code paths surfaced by this …

Overhaul chrome profile management

---

build.mill
integration/package.mill

Pulls in https://github.com/com-lihaoyi/mill/pull/5617, which means we shouldn't need to manually propagate environment variables from our build.mill into our integration tests

Rebootstrap

---

example/scalalib/testing/5-test-grouping/build.mill
libs/javalib/src/mill/javalib/TestModuleUtil.scala
libs/scalalib/test/src/mill/scalalib/TestRunnerScalatestTests.scala
libs/scalalib/test/src/mill/scalalib/TestRunnerUtestTests.scala

We can consolidate the desired behavior into `runTestQueueScheduler` (e.g. avoiding parallelizing via `async`, avoiding the extra `worker-$n/` folder) to avoid duplication and make it easier to maintain and extend with new features (e.g. https://github.com/com-lihaoyi/mill/issues/5558). There's some minor overhead in maintaining the `claim`/`claim.log`/`test-classes` folders, but overall it's probably negligible

Consolidate old `TestModuleUtil#runTestDefault` code path into `runTestQueueScheduler`

---

core/api/src/mill/api/internal/ResolveChecker.scala
core/exec/src/mill/exec/GroupExecution.scala
example/depth/sandbox/1-task/build.mill

Rather than just saying what is not allowed, we should suggest what the user does instead

Flesh out `os.Checker` error messages to make them more actionable

---

.github/workflows/run-tests.yml
build.mill
core/internal/src/mill/internal/MillCliConfig.scala
libs/tabcomplete/package.mill
libs/tabcomplete/src/mill/tabcomplete/TabCompleteModule.scala
libs/tabcomplete/test/src/mill/tabcomplete/TabCompleteTests.scala
runner/daemon/src/mill/daemon/MillMain0.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5300
- Only use `resolve` to tab-complete the task selector being run - the first token in `leftoverArgs` - and not tokens before or after
- If the first token in `leftoverArgs` begins with `-` or `--`, it's actually a not-yet-fully-typed flag so autocomplete using the list of short or long flags
- If the autocomplete is on anything else, it's probably not a task or a flag, so delegate to the default bash completion list using `bash -c "compgen -f -- "`. This should work in both bash and zsh since we're just using bash to give us a list to print
Moved `mill.daemon.MillCliConfig` to `mill.internal` so `mill.tabcomplete` can use it. It's all still private so it shouldn't affect anything
Covered with additional unit tests, also tested locally …

tab-complete flags like `-j` or `--jobs`, and forward non-task tab completion to bash

---

libs/tabcomplete/src/mill/tabcomplete/TabCompleteModule.scala
libs/tabcomplete/test/src/mill/tabcomplete/TabCompleteTests.scala

- Skip positional params
- Consolidate `Success` and `MismatchedArguments` logic when handling command parameters
- When handling failed parses of command params, use the index location when determining autocomplete, not the token at which the parse failed
Tested via additional unit tests

More tweaks to tab-completion logic

---

build.mill
libs/tabcomplete/resources/mill/tabcomplete/complete.sh
libs/tabcomplete/src/mill/tabcomplete/TabCompleteModule.scala
libs/tabcomplete/test/src/mill/tabcomplete/TabCompleteTests.scala

* Uses the hack described at https://stackoverflow.com/a/10130007/871202, where we place the descriptions in-line in the completion tokens but trim them off when there's only one token to prevent them from being inserted
* Refactored `complete.sh` to share the line-truncation-ellipses-insertion logic between bash and zsh completers

Add completion descriptions to bash tab completion

---

libs/scalalib/test/src/mill/scalalib/spotless/SpotlessTests.scala

This fixes the local issue on my machine that some tests hang if the gpg agent has currently no unlocked key to use.

Disable git gpg signing in automated tests

---

build.mill

Not sure when it broke, but we have to make sure `millVersion` doesn't depend on upstream `Task.Input`s and ignore their values, because despite ignoring their values the graph still gets traversed during selective testing causing all tests to run when `millVersionTruth` changes every commit

Fix selective testing again

---

libs/androidlib/src/mill/androidlib/AndroidAppModule.scala
libs/androidlib/src/mill/androidlib/AndroidModule.scala

Fixes some issues of ManifestMerger as mentioned in https://github.com/com-lihaoyi/mill/issues/5654.
> - Android manifest merge cache does not seem to be invalidated when the manifest file changes
> - Android manifest merge fails if `xmlns:android="http://schemas.android.com/apk/res/android"` property already exists
>

Android: ManifestMerger bugfixes

---

build.mill
dist/scripts/package.mill
dist/scripts/src/mill.bat
dist/scripts/src/mill.sh

* We shouldn't use `millVersionTruth` because that causes selective testing invalidation regardless of code changes, instead we should use `millVersion`
* We don't need separate `mill-version` and `mill-best-version` substitute, just have a single `mill-version`

Improve selective testing for `dist.scripts` and  use current version as default

---

changelog.adoc
website/blog/modules/ROOT/pages/12-direct-style-build-tool.adoc
website/blog/modules/ROOT/pages/13-mill-build-tool-v1-0-0.adoc
website/blog/modules/ROOT/pages/14-bash-zsh-completion.adoc
website/blog/modules/ROOT/pages/5-executable-jars.adoc
website/docs/modules/ROOT/pages/android/android-initial-setup.adoc
website/docs/modules/ROOT/pages/cli/installation-ide.adoc
website/docs/modules/ROOT/pages/comparisons/why-mill.adoc
website/docs/modules/ROOT/pages/extending/thirdparty-plugins.adoc
website/docs/modules/ROOT/partials/Publishing_Footer.adoc

Most notably, mark console snippets as `console`, not `bash`.

Slight format fixes for latest blog post and other pages

---

core/exec/test/src/mill/exec/ModuleTests.scala

Not sure why that `os.remove.all` is failing, but also not sure why it is necessary. So just trying to remove it
Fixes  https://github.com/com-lihaoyi/mill/issues/5680

Try to fix flakiness in `externalModuleTargetsAreNamespacedByModulePackagePath`

---

mill-build/src/millbuild/Deps.scala

Now that https://github.com/com-lihaoyi/mill/issues/5706 is fixed, we can start depending on the updated JVM index with newer JVM versions available

Bump coursier index version

---

libs/androidlib/src/mill/androidlib/AndroidAppModule.scala
libs/kotlinlib/src/mill/kotlinlib/ksp/Ksp2Module.scala
libs/kotlinlib/src/mill/kotlinlib/ksp/KspModule.scala

This PR resolves an issue found [during integration](https://github.com/com-lihaoyi/mill/issues/5758) where we were missing the functionality to include in the apk, native deps provided by dependencies 
I have also renamed the kspDeps as suggested from https://github.com/com-lihaoyi/mill/pull/5727

Android: Package jnis provided by dependencies

---

.github/workflows/run-tests.yml
example/thirdparty/androidtodo/build.mill

This was broken accidentally since [the ksp 2 work](https://github.com/com-lihaoyi/mill/pull/5727) , I didn't realise it wasn't running in the CI.
I'd prefer to have androidtodo over jetnews, as jetnews doesn't use Hilt, and androidtodo uses both compose and hilt (and KSP), so if I may choose one I prefer androidtodo.

Android: Fix androidtodo and replace compose samples in ci with it

---

build.mill
scalalib/api/src/mill/scalalib/api/ZincWorkerUtil.scala
scalalib/test/src/mill/scalalib/Scala38NightlyTests.scala
scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala

Backports https://github.com/com-lihaoyi/mill/pull/5751 to 0.12.x branch

Implement support for Scala 3.8 (backport of #5751)

---

core/exec/src/mill/exec/GroupExecution.scala
integration/bootstrap/no-java-bootstrap/src/NoJavaBootstrapTests.scala
integration/feature/cs-env-vars/resources/build.mill
integration/feature/cs-env-vars/src/CsEnvVarsTests.scala
integration/ide/bsp-server/resources/snapshots/logging
libs/init/gradle/src/mill/main/gradle/GradleBuildGenMain.scala
libs/javalib/src/mill/javalib/CoursierConfigModule.scala
libs/javalib/src/mill/javalib/CoursierModule.scala
libs/javalib/src/mill/javalib/Dependency.scala
libs/javalib/src/mill/javalib/JavaHomeModule.scala
libs/javalib/src/mill/javalib/JavaModule.scala
libs/javalib/src/mill/javalib/Lib.scala
libs/javalib/src/mill/javalib/dependency/DependencyUpdatesImpl.scala
libs/javalib/src/mill/javalib/dependency/versions/VersionsFinder.scala
libs/javalib/src/mill/javalib/internal/ZincCompilerBridgeProvider.scala
libs/javalib/test/src/mill/javalib/ResolveDepsTests.scala
libs/scalalib/test/src/mill/scalalib/CoursierMirrorTests.scala
libs/util/src/mill/util/CoursierConfig.scala
libs/util/src/mill/util/Jvm.scala
runner/daemon/src/mill/daemon/MillBuildBootstrap.scala
runner/launcher/src/mill/launcher/CoursierClient.scala
website/docs/modules/ROOT/pages/cli/installation-ide.adoc

This is a new attempt at fixing https://github.com/com-lihaoyi/mill/issues/5134. Turns out setting the context class loader when evaluating user code addresses the issue while not running into https://github.com/com-lihaoyi/mill/issues/5398 again.
---
Description from https://github.com/com-lihaoyi/mill/pull/5350 that still applies:
This makes Mill read all environment variables and Java properties used by coursier via a `Task.Input`.
In more detail, this adds a `CoursierConfigModule` external module in scalalib. It contains a single `Task.Input`, that reads all environment variables used by coursier via `Task.env` and all Java properties used by coursier via `sys.props`.
Helper tasks compute default values for various parameters (repositories, cache location, etc.). …

Read coursier env vars and Java properties via input tasks

---

core/api/daemon/src/mill/api/daemon/MillURLClassLoader.scala

Follow up to https://github.com/com-lihaoyi/mill/pull/5791
With the help of the `@static` annotation, we can hook the caller-sensitive static registration of the classloader on a static variable.
Deleted all workaround code.

Simplify MillURLClassLoader parallel registration with `@static`

---

website/docs/modules/ROOT/pages/extending/thirdparty-plugins.adoc

This just updates the documentation to third-party plugin `mill-daemon` (and adds a note distinguishing it from mill's internal daemon).

Update documentation of mill-daemon plugin

---

contrib/scalapblib/src/mill/contrib/scalapblib/ScalaPBModule.scala
integration/feature/inspect/src/InspectTests.scala
libs/javalib/src/mill/javalib/CoursierModule.scala
libs/javalib/src/mill/javalib/JavaModule.scala
libs/javalib/src/mill/javalib/PublishModule.scala
libs/javalib/src/mill/javalib/bsp/BspJavaModule.scala
libs/javalib/src/mill/javalib/eclipse/GenEclipseModule.scala
libs/javalib/src/mill/javalib/idea/GenIdeaModule.scala
libs/javalib/src/mill/javalib/revapi/RevapiModule.scala
libs/javalib/test/src/mill/javalib/ResolveDepsTests.scala
libs/scalalib/src/mill/scalalib/ScalaModule.scala

This fixes https://github.com/com-lihaoyi/mill/issues/5796 (forced versions not enforced) by taking them into account in `JavaModule#coursierDependency`, so that they're being enforced during dependency resolution, and are taken into account in other modules if needed.
In order to get forced versions from `mvnDeps`, `JavaModule#coursierDependency` needs to be a task. So in more detail, the current `coursierDependency` is deprecated, and a new `coursierDependencyTask` is used instead.

Fix forced versions

---

core/constants/src/mill/constants/CodeGenConstants.java
dist/scripts/src/mill.sh
example/package.mill
integration/failure/missing-build-file/src/MissingBuildFileTests.scala
mill
mill-build/src-testkit/mill/testkit/ExampleParser.scala
mill.bat
runner/daemon/test/src/mill/daemon/MillMainTests.scala
runner/meta/src/mill/meta/FileImportGraph.scala
runner/meta/src/mill/meta/MillBuildRootModule.scala

`.sc` was fine as a migration bridge and `.mill.scala` was a good stopgap measure when `.mill` file support in tools wasn't there, but IntelliJ/VSCode/ScalaFmt now have support for `.mill` files so we can consider standardizing on it.
This is a breaking change for local builds but not plugins, so would go into 1.1.0

Cut down the number of Mill file suffixes to just `.mill`

---

runner/client/src/mill/client/MillServerLauncher.java
runner/launcher/src/mill/launcher/MillLauncherMain.java
runner/launcher/src/mill/launcher/MillProcessLauncher.java
runner/server/test/src/mill/server/ClientServerTests.scala

Fixes https://github.com/com-lihaoyi/mill/issues/5637
The basic problem was that `prepareMillRunFolder` gets called via `MillServerLauncher#run` and `prepareDaemonDir`, which can end up calling it twice when the daemon restarts since we call `.run` twice in `MillLauncherMain`. But `memoizedTerminalDims` gets set the first time and not cleared, and so the second time `prepareMillRunFolder` gets run it deletes the old `terminfo` file but thinks the dimensions are unchanged (v.s. the `memoizedTerminalDims`) and so does not write a new one
The fix is to move `prepareMillRunFolder` into `configureRunMillProcess`, so it only gets called when we actually spawn the Mill daemon process, which should only happen once per launcher. This also lets us remove `prepareDaemonDir` and simplify things …

Fix prompt when server restarts

---

example/kotlinlib/basic/7-dependency-injection/build.mill
example/thirdparty/arrow/build.mill
libs/javalib/src/mill/javalib/JavaHomeModule.scala
libs/javalib/src/mill/javalib/JavaModule.scala
libs/javalib/src/mill/javalib/SemanticDbJavaModule.scala
libs/kotlinlib/api/src/mill/kotlinlib/worker/api/KotlinWorker.scala
libs/kotlinlib/api/src/mill/kotlinlib/worker/api/KotlinWorkerTarget.scala
libs/kotlinlib/package.mill
libs/kotlinlib/src/mill/kotlinlib/KotlinModule.scala
libs/kotlinlib/src/mill/kotlinlib/js/KotlinJsModule.scala
libs/kotlinlib/src/mill/kotlinlib/ksp/KspModule.scala
libs/kotlinlib/test/src/mill/kotlinlib/HelloKotlinTests.scala
libs/kotlinlib/test/src/mill/kotlinlib/js/KotlinJsKotlinVersionsTests.scala
libs/kotlinlib/worker/src/mill/kotlinlib/worker/impl/Compiler.scala
libs/kotlinlib/worker/src/mill/kotlinlib/worker/impl/JsCompileImpl.scala
libs/kotlinlib/worker/src/mill/kotlinlib/worker/impl/JvmCompileBtApiImpl.scala
libs/kotlinlib/worker/src/mill/kotlinlib/worker/impl/JvmCompileImpl.scala
libs/kotlinlib/worker/src/mill/kotlinlib/worker/impl/KotlinInterop.java
libs/kotlinlib/worker/src/mill/kotlinlib/worker/impl/KotlinWorkerImpl.scala
libs/scalalib/test/src/mill/scalalib/ScalaValidatedPathRefTests.scala
mill-build/src/millbuild/Deps.scala
mill-build/src/millbuild/MillPublishJavaModule.scala

With Kotlin 2.2, there is a new beta build tools api (BT API) which should be used by build tools to integrate the Kotlin compiler. This PR adds support for this API and uses it by default if the module is using Kotlin 2.0+ for JVM.
Related to https://github.com/com-lihaoyi/mill/issues/5788

Use Kotlin build-tools-api to compile Kotlin code

---

example/thirdparty/arrow/build.mill
libs/kotlinlib/src/mill/kotlinlib/KotlinModule.scala

Follow up on #5785 to fix the failing `arrow` test.

Enabled Kotlin BT API only for modules using Kotlin 2.1+

---

integration/failure/invalid-build-header-no-space/src/InvalidBuildHeaderNoSpaceTests.scala
integration/failure/invalid-build-header/src/InvalidBuildHeaderTests.scala
libs/daemon/client/src/mill/client/ServerLauncher.java
runner/launcher/src/mill/launcher/MillLauncherMain.java
runner/launcher/src/mill/launcher/MillProcessLauncher.java
testkit/src/mill/testkit/ExampleTester.scala
testkit/src/mill/testkit/IntegrationTestSuite.scala
testkit/src/mill/testkit/IntegrationTester.scala
testkit/src/mill/testkit/IntegrationTesterBase.scala

Previously we needed a `retryWithTimeout` around the reading of the port because the initial process launch could take >10s, which would make the outer `retryWithTimeout` not take effect. This is because we were performing the coursier runner classpath resolution as part of that launch, which can take arbitrarily long, overshooting the retry timeout.
This PR fixes it by moving the coursier runner classpath resolution out of the retry loop, so the retry loop only contains the logic around launching the process. This should help keep the time of each attempt to a more reasonable amount, allowing the outer retries to work and avoiding the need for nested retries around the individual steps of the process launch workflow

Simplify `launchOrConnectToServer` to eliminate nested retries

---

website/blog/modules/ROOT/pages/15-android-build-flow.adoc

Fixes publish docs by removing the link reference to the android native docs that was introduced on the same PR

Blog: Remove link not referenced in stable

---

libs/androidlib/src/mill/androidlib/AndroidModule.scala
libs/androidlib/src/mill/androidlib/AndroidR8AppModule.scala

Resolves https://github.com/com-lihaoyi/mill/issues/5875
Now no errors are thrown when using R8 for XR applications, thus `override def androidR8Args = Seq("--map-diagnostics", "error", "warning")` is not needed anymore.

Android: pass compileMvnDeps as classpaths to R8

---

runner/daemon/src/mill/daemon/MillBspMain.scala
runner/launcher/src/mill/launcher/MillLauncherMain.java
runner/launcher/src/mill/launcher/MillProcessLauncher.java

This should make the `MillBspMain` processes easier to distinguish from the command line from the `MillDaemonMain` or `MillNoDaemonMain` processes launched by users when you run `jps`.
Tested manually via `./mill dist.installLocalCache` and using the new version in a Mill project I load into Intellij. `jps` then shows the `MillBspMain` clearly separate from the other user-created Mill processes:
```console
$ jps
4930 MillNoDaemonMain
1717 
7063 MillLauncherMain
7080 Jps
5835 MillDaemonMain
749 Main
7070 MillBspMain
4927 NailgunRunner
```

Make `--bsp` Mill process launch from `MillBspMain` class

---

.github/actions/post-build-selective/action.yml
.github/workflows/post-build-selective.yml
.github/workflows/publish-artifacts.yml
.github/workflows/publish-bridges.yaml
.github/workflows/run-tests.yml

Inconsistent application of this environment variable seems to be the cause of https://github.com/com-lihaoyi/mill/issues/5910. Before applying it everywhere, first let's try removing it to see if it's still needed at all

Try to remove `COURSIER_ARCHIVE_CACHE` configuration

---

libs/scalajslib/api/src/mill/scalajslib/worker/api/ScalaJSWorkerApi.scala
libs/scalajslib/package.mill
libs/scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala
libs/scalajslib/worker/1/src/mill/scalajslib/worker/ScalaJSWorkerImpl.scala

This is a smaller step compared to #5931. Still doesn't fix all the problems with linkers, but it's enough to guarantee teardown happens correctly and Scala.js linker caches are cleaned.
Pull Request: https://github.com/com-lihaoyi/mill/pull/5933

Clean Linker caches when ScalaJSWorker is closed

---

example/thirdparty/android-compose-samples/build.mill
example/thirdparty/androidtodo/build.mill
libs/androidlib/src/mill/androidlib/AndroidBuildTypeSettings.scala
libs/androidlib/src/mill/androidlib/AndroidR8AppModule.scala

Generate keep rules for user defined classes in order to improve the minification. Relevant Issue: https://github.com/com-lihaoyi/mill/issues/5893
Implementation is the same as Gradle's: ([Task](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/GenerateLibraryProguardRulesTask.kt), [Impl](https://android.googlesource.com/platform/tools/base/+/refs/tags/studio-2025.1.3/sdk-common/src/main/java/com/android/ide/common/symbols/SymbolUtils.kt#235)):
- Extract `name` tags from the merged Manifest
- Extract tags from `res/layout*.xml` files
Release APK with Mill:
Release APK with Gradle:

Android: Generate MinifyKeepRules for Proguard 

---

example/thirdparty/commons-io/build.mill
website/blog/modules/ROOT/pages/7-graal-native-executables.adoc

With the move of `jvmId` from `JvmWorkerModule` to `JavaModule` in PR #5327 a few examples were not updated.

Update remaining examples still referencing `JvmWorkerModule.jvmId`
