project/build.properties
The compilation fails with sbt v0.13.15 on some terminals:
```
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
```
=> Build: Bump sbt version

core/src/main/scala/mill/main/RunScript.scala
Currently, mill fails with match error when the selector is empty:
```
➜  mill-zinc git:(master) ✗ mill
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Compiling /Users/rockjam/projects/mill-zinc/build.sc
Exception in thread "main" scala.MatchError: List() (of class scala.collection.immutable.Nil$)
at mill.main.RunScript$.evaluateTarget(RunScript.scala:97)
at mill.main.RunScript$.$anonfun$runScript$2(RunScript.scala:44)
at ammonite.util.Res$Success.flatMap(Res.scala:61)
at mill.main.RunScript$.runScript(RunScript.scala:41)
at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:36)
at ammonite.MainRunner.watchLoop(Main.scala:350)
at mill.main.MainRunner.runScript(MainRunner.scala:28)
at mill.Main$.main(Main.scala:63)
at …
```
=> don't fail with match error on empty selector

core/src/main/scala/mill/main/ParseArgs.scala, core/src/main/scala/mill/main/RunScript.scala, core/src/main/scala/mill/util/EitherOps.scala, core/src/test/scala/mill/main/MainTests.scala, core/src/test/scala/mill/main/ParseArgsTest.scala
This PR allows mill users to run multiple task via command line. This implementation uses brace [expansion](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html) for bash and zsh.
For other shells, that doesn't support brace expansion there is internal implementation of brace expansion in mill's command line parsing code, so all users should expect same behavior.
What works now:
1. Running one task in different modules
```
mill --all {Application,Core}.compile
```
2. Running different tasks in one module
```
mill --all Core.{jar,docsJar,sourcesJar}
``` 
3. Running multiple totally unrelated tasks
```
mill --all Core.jar Application.compile
```
4. Running multiple tasks on multiple modules
```
mill --show --all {Core,Application}.{scalaVersion,scalaBinaryVersion}
```
5. …
=> ability to run multiple tasks via bash/zsh braces expansion

scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/src/mill/scalalib/ScalaWorkerApi.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala, scalaworker/src/mill/scalaworker/ScalaWorker.scala
Main methods are discovered using zinc (like sbt). All discovered main methods can be found with `discoverMainClasses`. `mainClass` now defaults if there is exactly one discovered main class.
=> Discover main class(es) via zinc #124

docs/pages/2 - Configuring Mill.md
_.isFile Filter was missing:
def lineCount = T{
import ammonite.ops._
foo.sources().flatMap( r =>  ls.rec(r.path)).filter(_.isFile).flatMap(read.lines).size
}
=> Fixed small bug in example

docs/pages/1 - Intro to Mill.md, scalalib/src/mill/scalalib/publish/SonatypeHttpApi.scala, scalalib/src/mill/scalalib/publish/SonatypePublisher.scala
Now you get an exception:
dgraph.publish scalaj.http.HttpStatusException: 401 Error: HTTP/1.1 401 Unauthorized
scalaj.http.HttpResponse.throwIf(Http.scala:156)
....
instead of a upickle error
=> Better error messages when publishing to Sonatype

scalalib/src/mill/scalalib/Dep.scala, scalalib/test/src/mill/scalalib/ResolveDepsTests.scala
Syntax:
```scala
ivy"org.lwjgl:lwjgl:3.1.1;classifier=natives-macos"
```
or:
```scala
ivy"org.lwjgl:lwjgl:3.1.1".configure(attributes = coursier.Attributes(classifier = "natives-macos"))
```
I wasn't sure what the best way to test the parser was, let me know if I can write a narrower test!
=> Allow specifying classifiers in ivy deps

main/src/mill/Main.scala
* Mill's default home folder is now $HOME/.mill/ammonite
This lets users provide global settings by defining a predef.sc file
in that home folder.
* Re-enabled the --home cli param to manually set the home folder
=> Changed the default home location

scalaworker/src/mill/scalaworker/ScalaWorker.scala
This should fix color output for scalatest and other testing frameworks
=> use outputStream for test logs

build.sc, docs/example-2/build.sc, docs/pages/1 - Intro to Mill.md, docs/pages/3 - Common Project Layouts.md, integration/test/resources/acyclic/build.sc, integration/test/resources/upickle/build.sc, scalajslib/test/src/mill/scalajslib/HelloJSWorldTests.scala, scalalib/src/mill/scalalib/publish/JsonFormatters.scala, scalalib/src/mill/scalalib/publish/Pom.scala, scalalib/src/mill/scalalib/publish/settings.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala
The scm url syntax is a source of confusion for developper. I added VersionControl.github() to simplify this process. We can add other common VersionControl url scheme like Git, Bazar, etc.
=> Add dsl for SCM (now called VersionControl)

build.sc
The `mill show gitHead` and dependent tasks fail on systems with case sensitive filesystem:
> fatal: ambiguous argument 'head': unknown revision or path not in the working tree.
because the default git ref name for current head is "HEAD", in upper case.
This fix should not affect users with case insensitive filesystems.
=> Fix invalid git HEAD ref name in build.sc#gitHead

scalaworker/src/mill/scalaworker/ScalaWorker.scala
A recurrent thing that confuses users is when mill is compiling and
warnings such as "there were 5 deprecation warnings in total; re-run
with -deprecation for details" pop up.
@lihaoyi suggested to add a `println` call when this happens, so
users know the error does not come from their code.
=> Add message to inform users mill is compiling

docs/pages/1 - Intro to Mill.md
I have just added an Arch Linux package for mill [here](https://aur.archlinux.org/packages/mill/), which I included in the docs. I have also added some headers to distinguish the different installation methods. Feel free to change the headers if you don't like them as is.
=> adds Arch Linux package to doc/install

scalajslib/jsbridges/0.6/src/mill/scalajslib/bridge/ScalaJSBridge.scala, scalajslib/jsbridges/1.0/src/mill/scalajslib/bridge/ScalaJSBridge.scala, scalajslib/src/mill/scalajslib/NodeJSConfig.scala, scalajslib/src/mill/scalajslib/ScalaJSBridge.scala, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/test/src/mill/scalajslib/NodeJSConfigTests.scala
This pull request allows users to configure Node.js in ScalaJSModule such as for passing arguments to increase heap memory, executable, etc., as allowed in Scala.js NodeJSEnv.
=> Allows users to customize Node.js (Scala.js' NodeJSEnv) in ScalaJSModule

scalalib/src/mill/scalalib/GenIdea.scala, scalalib/test/resources/gen-idea/idea_modules/iml
The "/.." thing here feels janky to me, but I wasn't sure how to better obtain the "out/{module_name}" dir.
Without this, IntelliJ doesn't notice generated sources, presumably because they are not beneath any "content root", but I'm not sure exactly what the format of these .iml files are because I couldn't find any documentation 😕
=> Add out/{module_name} as a content root in generated IntelliJ project

scalajslib/jsbridges/0.6/src/mill/scalajslib/bridge/ScalaJSBridge.scala, scalajslib/jsbridges/1.0/src/mill/scalajslib/bridge/ScalaJSBridge.scala
Specifically, fix 2 issues in order to better mirror the behavior of "sbt fullOptJS"
- Invoke the Google Closure Compiler after generating the optimized Javascript output
- Set scala.scalajs.LinkingInfo.developmentMode = false (and productionMode = true) when
building fullOpt in order to allow Scala.js code to distinguish between development
and production mode.
Fixes #189
=> Improve fullOpt behavior

main/src/mill/modules/Jvm.scala, scalaworker/src/mill/scalaworker/ScalaWorker.scala
This pull request addresses #157. 
**Note:** mill interactive mode (`-i`) should always be used in Windows.
I've tested this only on Windows 10 (with MSYS2) to compile and run JVM and JS tests for my project.  It would be great if someone can help setup the "official" mill tests on Windows platform (perhaps using AppVeyor).
=> Fixes for Windows (tested on Windows 10 with MSYS2)

.appveyor.yml, main/test/src/mill/eval/JavaCompileJarTests.scala
[Some tests are still failing](https://ci.appveyor.com/project/robby-phd/mill/build/1.0.13) (due to long filename/extension):
```
scalalib.test.test java.io.IOException: Cannot run program "java" (in directory "C:\mill"): CreateProcess error=206, The filename or extension is too long
java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
mill.modules.Jvm$.subprocess(Jvm.scala:153)
mill.scalalib.TestModule.$anonfun$test$1(ScalaModule.scala:355)
mill.define.ApplyerGenerated.$anonfun$zipMap$5(ApplicativeGenerated.scala:13)
mill.define.Task$MappedDest.evaluate(Task.scala:358)
```
=> Added AppVeyor configuration and made JavaCompilerJarTests compatible with Windows

scalalib/src/mill/scalalib/ScalaModule.scala
Trying to fix #199 
```
@ core.ivyDepsTree()() 
[4/4] core.ivyDepsTree 
├─ com.lihaoyi:sourcecode_2.12:0.1.4
│  └─ org.scala-lang:scala-library:2.12.2 -> 2.12.4
├─ com.lihaoyi:ammonite_2.12.4:1.0.5
│  ├─ com.github.scopt:scopt_2.12:3.5.0
│  │  └─ org.scala-lang:scala-library:2.12.0 -> 2.12.4
│  ├─ com.lihaoyi:ammonite-compiler_2.12.4:1.0.5
│  │  ├─ com.lihaoyi:ammonite-ops_2.12:1.0.5
│  │  │  ├─ com.lihaoyi:geny_2.12:0.1.2
│  │  │  │  └─ org.scala-lang:scala-library:2.12.0 -> 2.12.4
│  │  │  └─ org.scala-lang:scala-library:2.12.4
│  │  ├─ com.lihaoyi:ammonite-runtime_2.12:1.0.5
│  │  │  ├─ com.lihaoyi:ammonite-ops_2.12:1.0.5
│  │  │  │  ├─ com.lihaoyi:geny_2.12:0.1.2
│  │  │  │  │  └─ org.scala-lang:scala-library:2.12.0 -> 2.12.4
│  │  │  │  └─ org.scala-lang:scala-library:2.12.4
│  │  │ …
```
=> ScalaModule: Added ivyDepsTree command

scalajslib/jsbridges/0.6/src/mill/scalajslib/bridge/ScalaJSBridge.scala, scalajslib/jsbridges/1.0/src/mill/scalajslib/bridge/ScalaJSBridge.scala, scalajslib/src/mill/scalajslib/ScalaJSBridge.scala, scalajslib/src/mill/scalajslib/ScalaJSModule.scala
ScalaJS can generate CommonJS modules to use with bundlers like [Browserify](http://browserify.org) and [WebPack](https://webpack.js.org).
Now you can select the `CommonJSModule` mode in a `ScalaJSModule`:
```scala
object Foo extends ScalaJSModule {
def scalaJSVersion = "0.6.22"
def scalaVersion = "2.12.4"
def moduleKind = ModuleKind.CommonJSModule
}
```
The default is `ModuleKind.NoModule` which exports to the global scope.
=> Support to switch between NoModule and CommonJSModule ModuleKinds

build.sc
This pull request addresses #156 by upgrading ammonite to (at least) [1.0.5-1-819bc80](https://github.com/lihaoyi/Ammonite/commit/819bc803fd0b95993246560a2a4a595998545c73).
Integrating this pull request builds a mill release that's compatible with Java 9 and 10, which can be used, for example, to include tests in travis using oraclejdk9 (in a separate pull request).
=> Support for Java 9 (and 10)

core/src/mill/util/ClassLoader.scala, main/src/mill/modules/Jvm.scala, main/test/src/mill/util/TestUtil.scala, scalajslib/src/mill/scalajslib/ScalaJSBridge.scala, scalajslib/test/src/mill/scalajslib/HelloJSWorldTests.scala, scalajslib/test/src/mill/scalajslib/MultiModuleTests.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala, scalaworker/src/mill/scalaworker/ScalaWorker.scala
While pull request #215 enables mill to run under Java 9 and 10, it turns out more changes are needed to make `{clientserver,main,scalalib,scalajslib}.test` work under Java 9-10.
Basically, creation of `URLClassLoader` has to take into account "exported rt.jar" (see lihaoyi/Ammonite#761); a helper object method is added to facilitate this.
Note that the following tests are disabled under Java 9 or above (require further investigations):
* Tests using Scala 2.10 and 2.11 (cannot find xsbt.CompilerInterface)
* Tests using ScalaJsUtil.runJs (null when retrieving nashorn script engine)
Integrating this pull request builds a mill release that can be used to run `test-mill-0.sh` using oraclejdk9 in travis.
=> Changes to make {clientserver,main,scalalib,scalajslib}.test work under Java 9

.appveyor.yml, clientserver/src/mill/clientserver/Client.java
Set `jna.nosys` to `true` if unspecified to avoid JNA incompatibility (see java-native-access/jna#384).
Test mill non-interactive on Windows.
=> Test mill (client/server) non-interactive on Windows and set jna.nosys=true as default

main/src/mill/modules/Jvm.scala
This PR fixes #231
If the fat jar produced by `assembly` contains signature files (see: https://docs.oracle.com/javase/tutorial/deployment/jar/signing.html), running it will throw a `SecurityException`.
The solution (copied by [what sbt-assembly does](https://github.com/sbt/sbt-assembly/blob/2ff7635afc27a7d2255167dedf1d56a58fb8d651/src/main/scala/sbtassembly/MergeStrategy.scala#L137)) is to explicitly skip those files (which end in `.sf`, `.rsa` and `.dsa`).
I've tested this locally (with `mill dev`) on a project which has a signed jar (bouncycastle) and now the exception is not thrown anymore 🎉
=> Skip signature files in assembly

docs/pages/1 - Intro to Mill.md, docs/pages/6 - Extending Mill.md
This PR updates the documentation to reflect the changes introduced by 6336860
=>  Rename 'describe' to 'inspect' in the docs

docs/pages/6 - Extending Mill.md
=> Add closing backtick to `java.lang.Process` in doc

scalalib/src/mill/scalalib/ScalaModule.scala
This PR adds propagation of these settings from the outer `ScalaModule` to the `Tests` module:
- repositories
- scalacPluginIvyDeps
- scalacOptions
- javacOptions
For these values, I think it's reasonable that they are the same as the parent module by default. If the tests have specific needs, they can be easily overridden.
=> Propagate more properties into Tests module

build.sc, main/src/mill/Main.scala, main/src/mill/modules/Jvm.scala, scalalib/src/mill/scalalib/ScalaModule.scala
This PR adds batch file generation for Windows, thus, enabling Window users to run mill without a sh environment (no repl support at the moment; see below). The resulting assembly and release .bat files are similar to the sh version where their corresponding jar file is embedded in it.
Notes:
* Shifting of command line argument for interactive mode is moved to Main.main because it's difficult to do in batch for arguments with special characters 
* Support for ANSI color is disabled by default in Windows 10 Console; it requires a native API call to enable it. It's best to use terminal replacement such as [ConEmu](https://conemu.github.io).
* mill repl does not work because Ammonite repl assumes [sh/Unix environment](https://github.com/lihaoyi/Ammonite/blob/ac754ee65a2760bf6c442ab9d5a3077775 …
=> Batch (.bat) file generation for assembly, launcher, and release

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalalib/src/mill/scalalib/Lib.scala, scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/src/mill/scalalib/ScalaWorkerApi.scala, scalalib/test/resources/hello-world/core/src-2.13/Shim.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala, scalaworker/src/mill/scalaworker/ScalaWorker.scala
This PR lets us use scala milestone releases, like `2.13.0-M3` in mill. Didn't work before
=> Support scala milestone releases (with fixes for 2.13.0-M3)

build.sc, core/src/mill/util/ClassLoader.scala, main/src/mill/modules/Jvm.scala, scalalib/test/resources/hello-world/core/src/Main.scala
This PR changes the behavior of mill.util.Classloader for jdk 9 and above. We use `ClassLoader.getPlatformClassLoader` as parent classloader if parent class loader is null (https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-A868D0B9-026F-4D46-B979-901834343F9E). Also we always add rt.jar in class loader.
fixes #251
=> try to fix classloading issues on runLocal and test with java 9

docs/pages/2 - Configuring Mill.md, scalalib/src/mill/scalalib/Dep.scala, scalalib/src/mill/scalalib/publish/Ivy.scala, scalalib/src/mill/scalalib/publish/Pom.scala, scalalib/src/mill/scalalib/publish/settings.scala, scalalib/test/src/mill/scalalib/ResolveDepsTests.scala, scalalib/test/src/mill/scalalib/publish/IvyTests.scala, scalalib/test/src/mill/scalalib/publish/PomTests.scala
partly borrow the idea from #214, but also reflect the exclusions in ivy and pom generation.
=> add exclusions and custom configuration to dependencies

clientserver/src/mill/clientserver/Client.java, clientserver/src/mill/clientserver/ClientServer.java, core/src/mill/util/ClassLoader.scala, main/src/mill/Main.scala, scalalib/src/mill/scalalib/ScalaModule.scala
This PR attempts to fix a couple of issues with Windows client/server:
1. Failure to connect to server manifested as IOException (first commit)
This is addressed by ~~re-attempting the connection and~~ hard shutdown using 
System.exit ~~after several attempts~~ (currently, the client exits with code 1
without printing any message).
2. The more pressing issue is the unpredictable performance under Java 9 when starting mill client/server for the first time (second commit)
Unfortunately, mill client/server under Windows with Java 9 (or above) runs unpredictably
when run for the first time. This is because exporting rt.jar on the server side can somehow
be non-deterministically slow after displaying:
```
Compiling (synthetic)/ammonite/predef/interpBridge.sc
```
This can take a minute (or …
=> Windows client/server improvements

build.sc, main/src/mill/modules/Jvm.scala, scalalib/src/mill/scalalib/ScalaModule.scala
As a follow-up to lihaoyi/Ammonite#781 this pr generates scripts that can run on linux shell and windows cmd.
It merges the shell and batch scripts introduced in #243.
Feedback is always welcome!
=> universal script generation for assembly, launcher, and release that run on linux and windows

scalalib/src/mill/scalalib/Dep.scala, scalalib/test/src/mill/scalalib/ResolveDepsTests.scala
This PR fixes https://github.com/lihaoyi/mill/issues/173 by setting default dependency configuration to `default(compile)`. That's what coursier does in it's CLI: https://github.com/coursier/coursier/blob/master/cli/src/main/scala-2.12/coursier/cli/options/CommonOptions.scala#L69 and also advised by coursier's author here: https://github.com/coursier/coursier/issues/552#issuecomment-310133532
=> fixes #173; use default(compile) configuration for deps as default

clientserver/src/mill/clientserver/Client.java, clientserver/src/mill/clientserver/ClientServer.java, clientserver/src/mill/clientserver/Server.scala, clientserver/test/src/mill/clientserver/ClientServerTests.scala, core/src/mill/eval/Evaluator.scala, core/src/mill/util/Ctx.scala, docs/pages/3 - Tasks.md, main/src/mill/Main.scala, main/src/mill/main/MainRunner.scala, main/src/mill/main/RunScript.scala, main/test/src/mill/util/ScriptTestSuite.scala
Since Mill now executes in a long-lived JVM, the builds do not have a chance to use environment variables as inputs (ie `System.getEnv` returns the same result across several runs). 
This PR allows to propagate the environment variables from the client all the way down to the context and makes them available as a `Map[String, String]` so that they can be used as inputs should the user choose to do so.
Example of usage : 
`def envVar = T.input { T.ctx().env.get("ENV_VAR") } `
https://github.com/lihaoyi/mill/issues/257
=> Adds envVars propagation client -> server

docs/pages/1 - Intro to Mill.md, readme.md
Mill unstable releases should be used for bootstrapping.
This is from discussion in #293.
=> Add some documentation regarding bootstrapping.

docs/pages/1 - Intro to Mill.md, docs/pages/5 - Modules.md, readme.md
I found that the module name has changed, but the docs still refer to `GenIdeaModule`
=> Fix docs re: GenIdea/idea command

scalalib/src/mill/scalalib/GenIdeaImpl.scala, scalalib/src/mill/scalalib/JavaModule.scala, scalalib/src/mill/scalalib/MiscModule.scala, scalalib/test/resources/gen-idea/idea/modules.xml, scalalib/test/resources/gen-idea/idea_modules/test.iml, scalalib/test/src/mill/scalalib/GenIdeaTests.scala
This PR fixes #201
It's achieved by introducing `intellijModulePath`, which is different from `millSourcePath` for sbt/maven module's tests.
For instance:
module path in Intellij is: `module`
module's test path in Intellij is: `module/src/test`.
Meanwhile `millSourcePath` didn't change
=> Mark test module as test sources; change sbt module root

main/test/src/mill/eval/JavaCompileJarTests.scala
Otherwise we cannot rely on the exception message because the error returned by the java command line will be localized.
=> Resolves #305, use an English locale when excuting java command line

scalalib/src/mill/scalalib/GenIdeaImpl.scala, scalalib/test/resources/gen-idea/idea_modules/iml, scalalib/test/resources/gen-idea/idea_modules/test.iml
Se issue #311; the fix is base on what I see in the .iml files after manually editing the modules in Intellij IDEA.
=> Fix #311: sources and resources paths for Intellij test modules

build.sc
Instead of count all commits back to the beginning of time twice, and
then subtracting, just make one call to let git figure it out.
This is my first time trying to contribute, so any comments are very welcome.
=> Optimize calculation of commit count

scalalib/src/mill/scalalib/ScalaModule.scala
Related to #301 
It simplify use case described in this issue #301
instead of overriding whole `repl` function
you just need override one `replOptions` on your choice.
=> Add configurable repl options

scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/test/resources/hello-world-flags/core/src/Main.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala
Added a test (akin to #287 which was insuffcient for my particular case - publishing locally a module with cats in it, that required partial unification)
=> Fixes #336: pass scalac options to ScalaDoc during docJar stage

main/src/mill/modules/Jvm.scala
This is needed to fix https://github.com/lihaoyi/Ammonite/issues/813
Basically it allows us to specify whether to use `shebang` for `launcherUniversalScript`
=> Allow shebang with launcherUniversalScript

build.sc, ci/test-mill-0.sh, ci/test-mill-dev.sh, main/test/src/mill/define/CacherTests.scala, twirllib/src/mill/twirllib/TwirlModule.scala, twirllib/src/mill/twirllib/TwirlWorker.scala, twirllib/test/resources/hello-world/core/views/hello.scala.html, twirllib/test/src/mill/twirllib/HelloWorldTests.scala
Based on @pleira implementation
This is a work in progress:
For now the main issue is that an exception is thrown when `TwirlCompiler.compile` is invoked.
Oddly tests are running fine in Intellij IDEA. In this case the reflection is calling `JavaMirrors.JavaVanillaMethodMirror.apply(args: Any*)`. But when I run the tests using `mill twirllib.test`, the reflection is calling `JavaMirrors.JavaTransformingMethodMirror.apply(args: Any*)`.
I've also tried to use Java reflection but without success:
```scala
val clt = cl.loadClass("play.twirl.compiler.TwirlCompiler")
val module = cl.loadClass("play.twirl.compiler.TwirlCompiler$").getField("MODULE$")
val compileMethod = clt.getMethods.find(_.getName == "compile").get
compileMethod.invoke(module, 
source,
sourceDirectory,
generatedDirectory, …
```
=> Add a TwirlModule to compile Twirl templates

scalalib/src/mill/scalalib/Lib.scala
Throws an exception with a sensible error message when the Java compiler
is not available.
I spent some time trying to figure out where that NullPointerException was coming from, so I added a check for that case.
=> Check for availability of Java compiler

build.sc, main/client/src/mill/main/client/MillClientMain.java
Use MILL_CLASSPATH system property for Windows. It looks like it was an oversight when it was originally introduced. Also, since this make the command line arguments exceed the limit for Windows, use a vm options file for starting the server.
=> Fix MILL_CLASSPATH for Windows

core/src/mill/define/Module.scala, core/src/mill/util/ParseArgs.scala, docs/pages/2 - Configuring Mill.md, main/src/mill/main/ReplApplyHandler.scala, main/src/mill/main/Resolve.scala, main/test/src/mill/define/BasePathTests.scala, main/test/src/mill/define/DiscoverTests.scala, main/test/src/mill/define/GraphTests.scala, main/test/src/mill/eval/EvaluationTests.scala, main/test/src/mill/eval/FailureTests.scala, main/test/src/mill/main/MainTests.scala, main/test/src/mill/util/TestGraphs.scala
This solves issue #166 .
I decided to be conservative, and only allow hyphens in names. Any other characters could be added very easily, but I am not sure if there is a need for them, especially since many of them are not normally used in file names.
Please give me any thoughts about how I constructed the tests.
=> Allow hyphens in module and task names

scalalib/src/mill/scalalib/JavaModule.scala, scalalib/src/mill/scalalib/ScalaModule.scala
Hi,
My environment proxies everything and has some internal repositories that we're mandated to use. We can currently compile (thanks to this issue's resolution: https://github.com/lihaoyi/mill/issues/246) but we can't run tests.
=> Allow configuration of TestRunner's ScalaWorkerModule

docs/pages/1 - Intro to Mill.md, docs/pages/2 - Configuring Mill.md, docs/pages/3 - Common Project Layouts.md, docs/pages/4 - Tasks.md, docs/pages/5 - Modules.md, docs/pages/6 - Cross Builds.md, docs/pages/7 - Extending Mill.md, docs/pages/8 - Mill Internals.md
While reading the docs, I noticed some minor inconsistencies, which are fixed in this PR:
- use same import syntax in examples
- fixed code formatting (missing space after class name or `T` target def)
- using "its" for possessive, instead of "it's" 
- inheritance instead of inherit**e**nce
- inserted/changed some words to have more meaningful description
=> Fixed typos, wordings, formatted examples

scalalib/src/mill/scalalib/JavaModule.scala, scalalib/src/mill/scalalib/scalafmt/ScalafmtModule.scala
I missed 2 hard-coded ScalaWorkerModules in my prior PR: https://github.com/lihaoyi/mill/pull/364
I did a grep this time and didn't find any others.
=> Allow configuration of JavaModule and ScalafmtModule scala workers

scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/src/mill/scalalib/publish/settings.scala
When compiling a JS library, the platform suffix (e.g., `_sjs0.6`) is correctly appended before the scala version to dependencies during resolution. However, when publishing, the artifact ID listed in the published `ixy.xml` is missing the suffix, causing dependency resolution to fail for downstream clients using the published JS library.
Maybe in the longer term it'd be good to just have one code path producing the artifact names so they wouldn't ever end up disagreeing like this.
But anyway, this super simple patch works for me for now.
=> Add scala JS version suffix to ivy deps for published JS ivy.xml

docs/pages/1 - Intro to Mill.md
I just [added Mill to scoop](https://github.com/lukesampson/scoop/pull/2333) (with excellent support from the maintainers) and added the corresponding documentation to the Windows installation instructions.
Btw, it would be nice to have `0.2.4` released sometime soon 😃
=> Add scoop as installation option for Windows

core/src/mill/util/Logger.scala, main/src/mill/MillMain.scala, main/src/mill/main/MainModule.scala, main/src/mill/main/MainRunner.scala, main/src/mill/main/ReplApplyHandler.scala, main/test/src/mill/util/ScriptTestSuite.scala, main/test/src/mill/util/TestEvaluator.scala, scalalib/src/mill/scalalib/TestRunner.scala, scalalib/worker/src/mill/scalalib/worker/ScalaWorker.scala
Follow up from a [question on Gitter](https://gitter.im/lihaoyi/mill?at=5b3c8932f166440661184b95) 
- Correctly¹ handles `--color false` (instead of ignoring it)
- Allows disabling ticker logs.
¹ - I'm not sure if current logic was intentional or not
Example:
```bash
➜  mill git:(disable-ticker) ✗ mill --color false show __.version
[1/1] show # those are coloured
[1/1] version
0.2.2
"0.2.2"
➜  mill git:(disable-ticker) ✗ ./out/dev/assembly/dest/mill --color false show __.version
ill version changed (0.2.2 -> 0.2.3-17637010), re-starting s%                                                                                                                        ➜  mill git:(disable-ticker) ✗ ./out/dev/assembly/dest/mill --color false show __.version
[1/1] show # no colour
[1/1] version …
```
=> Add --disable-ticker, handle --color correctly

docs/pages/2 - Configuring Mill.md
Really a small thing, but the bullets do not show correctly in my addition to the Mill manual with regard to Module/Task Names.
@lihaoyi: Is there any way to preview the manual? Looking at the Markdown on Github shows correctly without this change. See [2 - Configuring Mill.md](https://github.com/lihaoyi/mill/blob/master/docs/pages/2%20-%20Configuring%20Mill.md).
I would like to make sure that my change actually corrects the problem. Right now, I am just imitating what I see elsewhere, i.e., empty line before the bullets, and no indentation.
=> Fix bullets in manual

main/src/mill/MillMain.scala
This fixes  #378 
I forced this error for testing purposes by applying the following patch on Windows:
diff --git a/core/src/mill/util/Ctx.scala b/core/src/mill/util/Ctx.scala
index 6c8b2af..ce3fe0c 100644
--- a/core/src/mill/util/Ctx.scala
+++ b/core/src/mill/util/Ctx.scala
@@ -33,7 +33,7 @@ object Ctx{
def args: IndexedSeq[_]
}
-  def defaultHome = ammonite.ops.home / ".mill" / "ammonite"
+  def defaultHome = ammonite.ops.home / ".mill" / "uammonite"
}
class Ctx(val args: IndexedSeq[_],
=> Fix bug with 'u' at the beginning of path

scalalib/src/mill/scalalib/TestRunner.scala
I am trying to convert a sbt/scalatest project to mill.
We have various tagged tests which I am trying to run with
`mill foo.test -l MyTagHere`
unfortunately it seems that mill reuses the sbt test runners and passes in the args for both `remoteArgs` and `args`, when I only want to set `args`.
This is because for scalatest `remoteArgs` activates remote connect and the first two params are supposed to be a host name and port number, wheras `args` is the ones documented that you might want to pass in for normal running as mill would be doing.
The documentation for the sbt interface is just that it's test framework specific https://github.com/scala-native/scala-native/blob/master/test-interface-sbt-defs/src/main/scala/sbt/testing/Framework.scala#L22 Therefore I'm not sure if the real solution …
=> don't pass in sbt scalatest test args as remoteArgs too

docs/VisualizePlan.svg, docs/pages/1 - Intro to Mill.md, main/graphviz/src/mill/main/graphviz/GraphvizTools.scala, main/src/mill/main/MainModule.scala, main/src/mill/main/VisualizeModule.scala
The purpose of this PR is too visualize all tasks that would be resolved by "plan", and not just the tasks returned by "resolve", which is what "visualize" does.
However, it will still not work if any external modules are returned by plan, and I cannot figure out how to either filter them out, or better yet, resolve them.
Any suggestions are welcome.
=> Visualize Plan

main/src/mill/main/ReplApplyHandler.scala
This makes it easier to hack on Mill using Mill itself, the evaluator is
available using `replApplyHandler.evaluator`
=> Make the REPL evaluator accessible from the REPL itself

build.sc, docs/VisualizePlan.svg, docs/pages/2 - Configuring Mill.md, docs/pages/5 - Modules.md, integration/test/resources/caffeine/build.sc, main/src/mill/modules/Jvm.scala, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalalib/src/mill/scalalib/JavaModule.scala, scalalib/src/mill/scalalib/Lib.scala, scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/src/mill/scalalib/Versions.scala, scalalib/src/mill/scalalib/ZincWorkerApi.scala, scalalib/src/mill/scalalib/dependency/metadata/MavenMetadataLoader.scala, scalalib/src/mill/scalalib/scalafmt/ScalafmtModule.scala, scalalib/test/src/mill/scalalib/dependency/metadata/MetadataLoaderFactoryTests.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala, scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala
This PR depends on https://github.com/lihaoyi/mill/pull/411
---
Before this PR, JavaModule#compile simply called javac
unconditionally, thus generating new classfiles every time. But if a
Scala project depends on a Java project, this will throw off the
incremental compilation algorithm which will unnecessarily recompile
files. To avoid this we now use Zinc to compile Java projects too (as a
bonus this means that Java compilation becomes incremental). This
required some refactoring in ZincWorkerImpl to be able to compile stuff
without having to pass Scala-specific options.
The issue solved by this commit could be reproduced by running in the
Mill repository:
```shell
$ mill main.compile
$ mill -i
@ main.compile()
```
and observing that before this commit, the `main.compile()` call ended
up …
=> Fix incremental compilation when a Scala project depends on a Java project

main/core/src/mill/eval/PathRef.scala
Mill was trying to read all files found under the source directory to
create a digest for each of them. This was causing an error for broken
symlinks.
At first I believed temporary files should be ignored to avoid this problem,
and asked at the gitter channel how to go about this, but overriding the `sources`
task as [suggested](https://gitter.im/lihaoyi/mill?at=5ad6cd801130fe3d36eb7655)
by @lihaoyi  didn't actually help, because it was `T.sources` macro who was actually
triggering the exception.
So, on a simple scala project, editing a file with Emacs, creates a link file, like:
```
vic@oeiuwq ~/h/foo> ls -la foo/src/
total 8
drwxr-xr-x  4 vic  staff  128 Sep  1 12:23 .
lrwxr-xr-x  1 vic  staff   22 Sep  1 12:23 .#hello.scala -> vic@oeiuwq.local.10748
drwxr-xr-x  3 vic  staff   96 Sep  1 …
```
=> Make sure files are readable when traversing source files.

scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala
Add dedicated functions to define documentation options and plugins used by the `docJar` task during the scaladoc generation:
> Documentation Options
–doc-title <title>
Define the overall title of the documentation, typically the name of the library being documented.
–doc-version <version>
Define the overall version number of the documentation, typically the version of the library being documented.
–doc-source-url <url>
Define a URL to be concatenated with source locations for link to source files. 
Source: https://www.scala-lang.org/old/sites/default/files/linuxsoft_archives/docu/files/tools/scaladoc.html
This feature is backward compatible, by default:
* `scalaDocPluginIvyDeps` resolves to `scalacPluginIvyDeps`
* `scalaDocOptions` resolves to `scalacOptions`
In other words it's not …
=> Dedicated scalaDoc plugins and options

scalalib/src/mill/scalalib/publish/SonatypeHttpApi.scala
Probably due to my raging cold, but I had it backwards in the issue.
=> Fixes #440: fix for allowing subgroups of a given staging profile

scalalib/src/mill/scalalib/GenIdeaImpl.scala, scalalib/src/mill/scalalib/JavaModule.scala
This PR is a first sketch how to skip some modules in Idea project generator.
The motivation is simple:
* Idea cannot handle multiple projects with the same base directory
* When working with Cross to enable cross compile projects of any kind, Idea selects one of the cross versions (almost) randomly per directory, which is undesired
This is a quickly hacked PR to sketch one possible solution to tackle the need to customize project generation. I'm open for input / change requests. If we can reach a consensus about the general direction, we can beautify, e.g. move the `IdeaConfigModule` into it's own file. Also tests would be nice, but I'm not familiar with the integration test setup of mill yet.
=> Configure Idea project generator per module

docs/pages/4 - Tasks.md, main/core/src/mill/eval/Evaluator.scala, main/core/src/mill/util/Logger.scala, main/src/mill/MillMain.scala, main/src/mill/main/MainModule.scala, main/src/mill/main/MainRunner.scala, main/src/mill/main/ReplApplyHandler.scala, main/test/src/mill/util/ScriptTestSuite.scala, main/test/src/mill/util/TestEvaluator.scala, readme.md, scalalib/src/mill/scalalib/TestRunner.scala
Use it to add additional debug messages when executing a task/target. By default, those message will only land in the log file under `out/`, but they can also be enabled via the `--debug` cmdline option.
Usage:
```scala
def complexTask(): T.command {
T.ctx().log.debug("About to process bla bla bla")
}
```
=> Added additional debug log channel (default: log-file only)

contrib/twirllib/src/mill/twirllib/TwirlModule.scala, contrib/twirllib/src/mill/twirllib/TwirlWorker.scala, contrib/twirllib/test/resources/hello-world/core/views/wrapper.scala.html, contrib/twirllib/test/src/mill/twirllib/HelloWorldTests.scala, docs/pages/9 - Contrib Modules.md
This is to address the caveats described in the doc (and removing the caveats from the docs).
* support for twirls default additional imports
* support for user-provided additional imports
=> improving twirl

integration/test/resources/large-project/build.sc, integration/test/resources/large-project/conf.sc, integration/test/resources/large-project/foo/common/one/src/main/scala/foo/common/one/Main.scala, integration/test/src/LargeProjectTests.scala, integration/test/src/forked/Tests.scala, integration/test/src/local/Tests.scala, main/core/src/define/Discover.scala
I now did try to tackle #508 - as I said before I have not too much experience in scala macros so there might be a much nicer solution to this problem.
However this change successfully builds the example I posted before.
=> Discover - break overridesRoutes into fixed size chunks

scalalib/src/GenIdeaImpl.scala
GenIdea is broken as it is no longer creating the required folder structure when needed.
=> fix GenIdea to create required folders

main/core/src/eval/Evaluator.scala, main/core/src/util/Loggers.scala, main/src/modules/Jvm.scala, scalajslib/src/ScalaJSModule.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/JavaModule.scala, scalalib/src/Lib.scala, scalalib/src/ZincWorkerModule.scala, scalalib/test/src/GenIdeaTests.scala, scalanativelib/src/ScalaNativeModule.scala
Also adds basic ticker logging to indicate when they are downloading.
=> Avoid unnecessary dependency downloading by providing fetches per cache policy

scalalib/worker/src/ZincWorkerImpl.scala
This is to better support non-Mill build tools like Bazel or Make who might do their own file hashing/mtiming for change-detection
=> Allow usage of ZincWorkerImpl without hashing files

build.sc, scalalib/src/ZincWorkerModule.scala, scalalib/worker/src/ZincWorkerImpl.scala
- Cache classloaders separately from `ScalaInstance`s
- Pre-compute `analysisMap` to speed up lookups
- Allow compile-to-jar using sbt/zinc 1.3.0-m1
=> More improvements to ZincWorkerImpl

docs/pages/1 - Intro to Mill.md, scalalib/src/PublishModule.scala, scalalib/src/publish/SonatypePublisher.scala
PR for #529 
Add ```--gpgKeyName``` flag to ```.publish``` & ```.publishAll```
I was not modify any test cases because I cannot find any related with ```PublishModule```.
New flag has been manually executed & verified on my local machine.
=> PublishModule: add --gpgKeyName flag

scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea/idea/libraries/scala-library-2.12.4.jar.xml
Fixes #512 
Simple implementation that adds entries from`module.scalaCompilerClasspath` to `scala-library`'s Idea XML file.
=> Added compiler-classpath properties to generated IntelliJ xml files

readme.md, scalalib/src/PublishModule.scala
=> Publish compileIvyDeps as provided scope

scalalib/src/JavaModule.scala
E.g. disabling picky JavaDoc linter with `-Xdoclint:none`.
The method is called `docOptions` instead of `javadocOptions` so that other modules like `ScalaModule` can reuse it.
=> Introduced JavaModule.docOptions to add extra procesing options

docs/pages/1 - Intro to Mill.md, scalalib/src/JavaModule.scala
Added a line to the documentation on how to change the artifact id.  
Updated the scaladoc on JavaModule to explain the difference between artifactName and artifactId.
=> Documentation around artifact name for publishing

docs/pages/9 - Contrib Modules.md
The markdown parser for lihaoyi.com requires an empty line before lists.
=> Quick formatting fixes for Play module documentation

contrib/buildinfo/src/BuildInfo.scala, contrib/buildinfo/test/src/BuildInfoTests.scala
generatedSources must be a folder,
but till now it was a reference to a generated file
This commit fixes this issue.
There are 2 reasons for this fix:
(1) Because generatedSources must be folders by the definition:
Folders containing source files that are generated
(2) If you use intellij IDEA and build your project from the IDE,
building module, which includes BuildInfo plugin, fails saying:
Error:scalac: Error: /home/vitalii/risk42/repo/risk42-workspace2/out/infinity/foundations/buildInfo/dest/BuildInfo.scala does not exist or is not a directory
scala.reflect.internal.FatalError: /home/vitalii/risk42/repo/risk42-workspace2/out/infinity/foundations/buildInfo/dest/BuildInfo.scala does not exist or is not a directory
at scala.tools.nsc.settings.MutableSettings$OutputDirs.checkDir(MutableSet …
=> contrib BuildInfo plugin: fix generatedSources, it must be a folder

scalalib/src/GenIdeaImpl.scala
Projects which are imported from other files and used as module dependencies are not found by GenIdea and this causes an exception. This PR transitively adds all the modules to the lookup map.
=> GenIdea - handle projects not in the main build.sc file

build.sc, docs/pages/2 - Configuring Mill.md, scalalib/src/scalafmt/ScalafmtModule.scala, scalalib/src/scalafmt/ScalafmtWorker.scala
This could replace pull request #590.
I completely removed the `scalafmtVersion` key because it can now be configured directly in the `.scalafmt.conf` configuration file. If a version isn't provided in the configuration file, the fallback is the default value provided by the `scalafmt-dynamic` library (which is the same as the version of the library). Alternatively, we could keep the `scalafmtVersion` key to allow specifying a different fallback version, but then we should probably make it optional to avoid hardcoding our own default when there is already one in `scalafmt-dynamic`?
I have added an empty configuration file in the resources,  used if the project doesn't include one, because `scalafmt-dynamic` requires providing an actual config file even though Scalafmt has a reasonable set …
=> [Fixes #442] Switch from scalafmt-cli to scalafmt-dynamic

main/src/main/MainModule.scala
Never got any response in gitter so I just went through the codebase and found a place to put that `System.exit(1)` in :smiley: 
Rationale for this is: in a Jenkins pipeline (and also when working locally on several projects at once) one would like to be able to manage lifetimes of mill servers manually. For instance first Jenkins pipeline stage would implicitly spawn server, then other stages would reuse existing server and reap the benefit of running in warm jvm and after that in pipeline's finally block one would issue `mill shutdown` to prevent resource leaks.
Give me a shout if you see this functionality in any other way. It would help a lot in my attempt to migrate build to mill. Thanks!
=> Add a shutdown target which allows user to kill background server

contrib/scoverage/test/resources/hello-world-sbt/core/src/main/java/Baz.java, contrib/scoverage/test/resources/hello-world-sbt/core/src/main/scala/Foo.scala, contrib/scoverage/test/resources/hello-world-sbt/core/src/test/FooTest.scala, contrib/scoverage/test/resources/hello-world/core/test/src/GreetSpec.scala, contrib/scoverage/test/src/HelloWorldTests.scala, contrib/scoverage/worker/1.3.1/src/ScoverageReportWorkerImpl.scala
Previously, the scoverage report worker would fail on a match error if more than one source directory existed, as found in #613 by @nh13.
=> Scoverage multiple source folders

contrib/scoverage/api/src/ScoverageReportWorkerApi.scala, contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/test/src/HelloWorldTests.scala, contrib/scoverage/worker/1.3.1/src/ScoverageReportWorkerImpl.scala, docs/pages/9 - Contrib Modules.md
* use the _.scoverage.xmlReport task
@nvander1 and @lefou thank-you again for the solution in #615.  
This adds the task to output an XML report, which is required by [codecov for upload](https://docs.codecov.io/reference#section-acceptable-report-formats).  This will work with only a single module, whereas if we have multiple modules in a repo, we will need to add another PR to utilize `scoverage.report.CoverageAggregator`.  I may get to that when I need it, but for now, this is a good start.
=> Scoverage can output an XML report

contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/test/resources/hello-world/core/src/Greet.scala, contrib/scoverage/test/resources/hello-world/other/src/Foo.scala, contrib/scoverage/test/src/HelloWorldTests.scala
Thanks to @kag0 for finding this bug! Fixes #622. @lefou @lihaoyi
=> Inherit moduleDeps from outer in Scoverage

scalalib/src/PublishModule.scala, scalalib/src/publish/SonatypeHttpApi.scala, scalalib/src/publish/SonatypePublisher.scala
As mentioned on gitter right now it never succeeds because the default timeouts for the first part `getStagingProfileUri` are too short.
I can't really test it properly because you have to publish a non-SNAPSHOT for this path to be hit..
=> Configurable read and connect timeouts for Sonatype publishing

scalanativelib/src/ScalaNativeModule.scala
Otherwise testing native modules don't work when you have zero `ivyDeps` (e.g. for uTest's test suite)
=> Replace testFrameworksJvmClasspath and testClasspathJvm with just runClasspath

build.sc, contrib/bloop/src/mill.contrib.bloop/BloopImpl.scala, scalajslib/api/src/ScalaJSWorkerApi.scala, scalajslib/src/ScalaJSModule.scala, scalajslib/src/ScalaJSWorkerApi.scala, scalajslib/test/src/NodeJSConfigTests.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1.0/src/ScalaJSWorkerImpl.scala
This is required to port Scalatags to Mill, since Scalatags needs a PhantomJSEnv to run its tests
=> Allow configuration of JSEnv used for Scala.js tests and runs

contrib/bloop/src/mill.contrib.bloop/BloopImpl.scala
The list is updated according to https://mvnrepository.com/artifact/org.scalameta/semanticdb-scalac
=> Upgrade SemanticDB and Bloop supported versions

contrib/scoverage/src/ScoverageModule.scala
`ScoverageModule` submodule inherits `ivyDeps` from the outer project, not inheriting `repositories`, which creates problems with resolving when package is in custom repository (#620).
=> Fix scoverage: inherit repositories from outer project

build.sc, contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/test/resources/hello-world/core/src/Greet.scala, contrib/scoverage/test/src/HelloWorldTests.scala
Fixes #640. @lefou 
@krcz your idea about taking `generatedSources` from outer was correct. I also had to modify the `xmlReport` and `htmlReport` to pass `allSources` instead of just `sources` to the report builder so it can instrument the generated source files.
This should also fix any other tools that generate source files as part of the mill build.
=> Scoverage buildinfo

docs/pages/9 - Contrib Modules.md
The example on the documentation page imported the buildinfo package instead of scoverage.
=> Fix typo on scoverage docs

build.sc, docs/pages/9 - Contrib Modules.md, main/core/src/util/Compat.scala, main/core/src/util/Router.scala, main/core/src/util/Scripts.scala, main/src/main/MainRunner.scala, main/src/main/MillIvyHook.scala, scalalib/src/ScalaModule.scala, scalalib/src/Versions.scala, scalalib/test/src/HelloWorldTests.scala
This overrides the default $ivy magic import by replacing the `$MILL_VERSION` string with mill's version, in order to facilitate the loading/update of contrib modules.
Ammonite had to be bumped to 1.6.9
NB : I've given it a manual test to see in the logs that coursier attempts to resolve the correct version (and fails, since the version is not yet published). It'd feel a bit weird to add that particular test, which would mean that pulling the latest master and running the tests on it would be red, since the version would then be published and coursier would be able to resolve it ... 
EDIT : apologies for the accidental whitespace removal in the readme. You can read the diff there without the whitespaces https://github.com/lihaoyi/mill/pull/649/files?w=1
=> Interpolates $MILL_VERSION in ivy imports

ci/release.sh, scalalib/src/PublishModule.scala, scalalib/src/publish/SonatypePublisher.scala
Somehow it seems sonatype has gotten slower recently and no longer completes operations in the same 60s timeout that it used to
=> Bump sonatype "wait for something to happen" timeout, make it configurable

.travis.yml, ci/test-mill-bootstrap-0.sh, ci/test-mill-bootstrap-1.sh, ci/test-mill-dev.sh
This makes the travis UI print what script is being run, making it easier to trace than having to look up a name mapping
Also broke up `test-mill-bootstrap` into two jobs since it's kinda slow, and added more JDK versions to the matrix
=> Swap back to CI_SCRIPT env var in travis.yml

main/src/main/MainRunner.scala
Here is an extremely small PR for `MainRunner.CustomCodeWrapper`.
It seems to work with the scratch project, but there might be some other wrapping logic that need to be fixed and that I haven't found yet.
=> Newline before closing the wrapped code (#545)

scalalib/src/Dep.scala, scalalib/src/publish/Ivy.scala, scalalib/src/publish/Pom.scala, scalalib/src/publish/settings.scala
Usage (see #603):
```scala
ivy"org.slf4j:slf4j-api:1.7.25".optional() // or .optional(true)
```
Regarding the publications:
- Optional dependencies are added to the `optional` ivy group. Is more work necessary here?
- `<optional>true</optional>` is added to optional maven dependencies
=> Ease the declaration of optional dependencies + handle them in maven and ivy publications

scalalib/api/src/ZincWorkerApi.scala, scalalib/src/ZincWorkerModule.scala, scalalib/test/resources/hello-dotty/boo/src/Main.scala, scalalib/test/src/HelloWorldTests.scala, scalalib/worker/src/ZincWorkerImpl.scala
Implement #591: for Dotty 0.13.0-RC1 or more recent, use the normal (non-src) compiler bridge jar.
I've checked that no sources are unpacked/compiled with Dotty `0.16.0-RC3`.
=> Use the binary version of the compiler bridge when available

contrib/bloop/src/mill.contrib.bloop/BloopImpl.scala
This allows Metals to support 2.12.9 on Mill builds
=> Update semanticDBVersion and semanticDBSupported

build.sc, scalalib/src/Versions.scala
Currently, it needs to be kept manually in sync with the versions used in the build.
=> Generate Versions.scala file

scalalib/api/src/ZincWorkerApi.scala, scalalib/src/Dep.scala, scalalib/test/resources/dotty213/foo/src/Main.scala, scalalib/test/src/HelloWorldTests.scala
Dotty now uses the 2.13 standard library, so `withDottyCompat` needs to
use the correct suffix depending on the Dotty version.
=> Properly support Dotty >= 0.18.1

scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/mill-build.iml, scalalib/test/resources/gen-idea-hello-world/idea_modules/mill-build.iml
This fixes issues with missing generated sources in IntelliJ IDEA after a rebuild.
It completes #694
=>  Use dedicated output dir for mill-build module in IntelliJ IDEA

contrib/bloop/src/mill.contrib.bloop/BloopImpl.scala
This enables using Mill with Metals and Scala 2.13.1, which in turn is required under Java 1.13
=> Bloop: upgrade semantic db and support scala 2.13.1

contrib/bloop/src/mill.contrib.bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
Bloop 1.3.3 can assume the responsibility of finding the semanticdb plugin and setting the relevant options in the compiler, which means we don't have to do it ourselves anymore to accommodate metals users.
See https://github.com/scalameta/metals/pull/852
=> Remove semanticdb settings

build.sc
They're bloating things up to an unacceptable degree, with the main jar size up to 50mb from 37mb not too long ago.
The whole point of contrib modules is that they're not part of the main distribution, but can be `import $ivy`ed in, so let's make them follow that convention
=> Remove contrib modules from main distribution

contrib/scalapblib/src/ScalaPBModule.scala, contrib/scalapblib/src/ScalaPBWorker.scala, contrib/scalapblib/test/src/TutorialTests.scala, docs/pages/9 - Contrib Modules.md
Add an option to ScalaPBModule to allow setting the protoc compiler. This is useful for systems that can't run the jar embedded protoc.
=> Add `scalaPBProtocPath` option to scalapblib

main/core/src/util/Loggers.scala
Fixes #665 and #605 which caused by `FileLogger`s in loggers surrounding task evaluation holding the log file and clean task attempts to delete log file. While Windows implementation of `FileOutputStream` does not allow open and delete file at the same time, `Files.newOutputStream` does (JDK only set the FILE_SHARE_DELETE flag in latter version).
=> Make FileLogger use Files.newOutputStream from nio

docs/pages/2 - Configuring Mill.md, scalalib/src/scalafmt/ScalafmtModule.scala, scalalib/src/scalafmt/ScalafmtWorker.scala
Adds a new task 'checkFormat' to the scalafmt module that only checks if all files are formatted. It is basically equivalent to the `--test` flag that can be passed to scalafmt on the command line, and can come in very handy in CI scripts.
Caching is preserved wrt to the 'reformat' action, so that only unformatted or changed files are checked.
=> Add task to only check formatting of Scala files

scalalib/src/CoursierModule.scala, scalalib/src/JavaModule.scala
This enables the user to resolve dependencies without defining a Java/Scala module, e.g. in assembly modules.
Fixes https://github.com/lihaoyi/mill/issues/722
=> Added CoursierModule as parent of JavaModule

build.sc, scalajslib/api/src/ScalaJSWorkerApi.scala, scalajslib/src/ScalaJSModule.scala, scalajslib/src/ScalaJSWorkerApi.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/test/src/ScalaJsUtils.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1.0/src/Run.scala, scalajslib/worker/1.0/src/ScalaJSWorkerImpl.scala, scalalib/api/src/ZincWorkerApi.scala
Drop support for the obsolete Scala.js 1.0.0-M2.
Starting from Scala.js 0.6.29, test artifacts must depend on `scalajs-test-bridge` instead of `scalajs-test-interface`, as the JS bridge has been moved to that artifact. This is the only change required for 0.6.29+.
In Scala.js 1.x, in addition to depending on `scalajs-test-bridge`, test artifacts must include a module initializer that initializes the bridge. This required the addition of a `testBridgeInit: Boolean` parameter to the `link` methods scattered here and there. The parameter is ignored in 0.6.
The support for 1.0.0-RC1 is suboptimal: we need to force emitting ECMAScript 5.1 code instead of the new default ES 2015. The only reason is that the tests of Mill itself rely on Nashorn to execute some Scala.js outputs, and Nashorn does …
=> Add support for Scala.js 0.6.29+ and 1.0.0-RC1.

contrib/bsp/src/mill/contrib/bsp/MillBuildServer.scala
Before this PR, invoking bsp won't download sources from maven center, since `resolveDeps` is set to `false` by default, this PR will ask mill to download all sources(including mill sources) to fix this issue.
I think this should also be handled by Intellij too, since sbt has configurations to let user decide downloading source or not, bsp in Intellij didn't give this option to user.
=> make coursier download dependency sources

main/core/src/define/BaseModule.scala, main/core/src/define/Ctx.scala, main/core/src/eval/Evaluator.scala, main/src/main/MainRunner.scala, main/test/resources/examples/foreign/outer/build.sc, main/test/resources/examples/foreign/project/build.sc
Calculates foreign modules paths so that they do not overlap when millSourcePath is overridden
Precalculates `Ctx.foreign` which is now a Option[Segments] based on relative path to the foreign module rather than using `millSourcePath` which would not be unique where `millSourcePath`is overridden (eg when have have `commonlib.js` & `commonlib.jvm` which share a root source path)
Fixes #743
=> Non overlapping foreign module paths for #743

build.sc, contrib/bloop/src/mill.contrib.bloop/BloopImpl.scala, contrib/playlib/api/src/RouteCompilerWorkerApi.scala, contrib/playlib/src/mill/playlib/RouteCompilerWorkerApi.scala, contrib/playlib/worker/2.6/src/RouteCompilerWorker.scala, contrib/playlib/worker/2.7/src/RouteCompilerWorker.scala, contrib/scalapblib/test/src/TutorialTests.scala, contrib/twirllib/test/src/HelloWorldTests.scala, integration/test/resources/better-files/build.sc, main/api/src/mill/api/IO.scala, main/core/src/util/JsonFormatters.scala, main/src/modules/Jvm.scala, main/src/modules/Util.scala, main/test/src/eval/JavaCompileJarTests.scala, main/test/src/main/ForeignBuildsTest.scala, main/test/src/main/ForeignConflictTest.scala, main/test/src/util/ScriptTestSuite.scala, scalalib/src/Dep.scala, scalalib/src/ScalaModule.scala, scalalib/test/src/HelloWorldTests.scala, scalalib/test/src/dependency/metadata/MetadataLoaderFactoryTests.scala
This attempts to do so without bumping the Scala version, since that might take more work and/or more time to wait for third-party libraries to upgrade
Ammonite, Coursier, uPickle, OS-Lib, FastParse/Requests/Geny (transitively)
=> Bump library versions

main/core/src/define/Task.scala, main/test/src/eval/JavaCompileJarTests.scala
https://github.com/lihaoyi/mill/issues/546
Largely copy-pasted from `T.sources`, with all the `Seq`-related stuff removed
Not super heavily tested, but I stuffed a single usage into `JavacCompileJavaTests` to make sure it at least gets some coverage. Seems to work.
Review by @lefou
=> Add T.source to listen to a single source file/folder

docs/pages/9 - Contrib Modules.md
With the new stable release of Metals, 0.8.0, there is no need for a user to include the plugin in order to generate the necessary files. It will all happen automatically.
=> update docs related to Metals

contrib/scoverage/api/src/ScoverageReportWorkerApi.scala, contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/test/src/HelloWorldTests.scala, contrib/scoverage/worker/src/ScoverageReportWorkerImpl.scala
Fixes lihaoyi/mill#763
This just outputs a coverage summary report. Useful for CI systems which don't support HTML/XML reports but have support for parsing stdout.
=> scoverage: Add console reporter

scalajslib/src/ScalaJSModule.scala, scalajslib/test/src/HelloJSWorldTests.scala
Starting from Scala.js 1.0.0, the Scala.js binary version is "1" instead of "1.0". The match was not ready to accept this value.
Moreover, after 1.0.0, the JS env artifacts will evolve independently from the core, hence we should always use version 1.0.0, even when the Scala.js version becomes 1.0.1 or later.
---
This is a blocker for all libraries built with mill to be published for Scala.js 1.0.0, including [uTest, itself a blocker for the GA announcement of Scala.js 1.0.0](https://github.com/lihaoyi/utest/pull/218). A release with this fix would be very welcome, if one of the maintainers can spare the time. :-)
=> Fix #769: Handle Scala.js binary version "1".

build.sc
Fixes https://github.com/lihaoyi/mill/issues/754
Bump upickle to 1.0.0
=> Fix open file handle leak by upgrading upstream dependency upickle

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
See https://github.com/scalacenter/bloop/issues/1167
This will make programs that run via bloop respect the same pwd they
see when the same programs get run via mill.
=> Force -Duser.dir on bloop config

main/test/src/util/TestEvaluator.scala
Allows me to easier spot where a mill ticker message comes from
=> Added prefix to test evaluator logger

scalalib/src/PublishModule.scala, scalalib/src/publish/LocalPublisher.scala
With the new `PublishModule.extraPublish` you can add additional artifacts/files to be published. 
Use cases: 
* Publish a jar with dependencies
* Publish a distribution archive
* Publish a native binary
=> Support publishing of extra artifacts

scalalib/src/Dependency.scala, scalalib/src/dependency/DependencyUpdatesImpl.scala, scalalib/src/dependency/updates/ModuleDependenciesUpdates.scala, scalalib/src/dependency/updates/UpdatesFinder.scala, scalalib/src/dependency/versions/ModuleDependenciesVersions.scala, scalalib/src/dependency/versions/Version.scala, scalalib/src/dependency/versions/VersionsFinder.scala
Mill has a convenient task to check for the availability of newer versions of dependencies `mill.scalalib.Dependency/updates`.
Unfortunately this task only prints the output (in human readable form), but does not persist it in a machine-readable format. This makes it very difficult to reuse the output in other tasks, essentially requiring regex parsing of strings.
The changes proposed here change the `updates` task to expose the underlying data structures representing the upgrade path. An additional task, `showUpdates` is added, implementing the original, human readable, output of updates.
=> Auto-update dependencies: output info in machine-readable format

scalanativelib/api/src/ScalaNativeWorkerApi.scala
These modes where introduced in scala-native 0.4.0
release == release-full
release-fast prioritizes link optimization time and executable size
=> Add release-fast and release-full modes to scala-native

contrib/versionfile/src/mill/contrib/versionfile/Version.scala, contrib/versionfile/src/mill/contrib/versionfile/VersionFileModule.scala, contrib/versionfile/test/src/mill/contrib/versionfile/VersionFileModuleTests.scala, contrib/versionfile/test/src/mill/contrib/versionfile/VersionTests.scala, docs/pages/9 - Contrib Modules.md
Refactored the module, to make it more testable. As a result, it's more modular than the previous iteration. The git tagging/pushing and writing the versions to file are now separated into different tasks, making it easier to use just the parts you want and extend as you want.
Most likely all the git related stuff here will be moved to its own module at some point. Will probably do that when adding the support for pure git tagging that was mentioned in the previous pull request, as that seems like a better place for that stuff to reside.
=> Refactoring of the version file module

scalanativelib/src/ScalaNativeModule.scala
- Pass nativeLinkingOptions and nativeCompileOptions from testOuter to test
- Substitute platformSuffix with `::` in ScalaNativeModule
With current mill if you need native linking or compile options they are not passed to the Scala Native test and it fails to link.
I'm not testing this because it would mean to add link-time dependencies to test mill
=> Pass linking and compile options to test in Scala Native

build.sc, contrib/bsp/src/mill/contrib/BSP.scala, main/client/src/mill/main/client/MillClientMain.java, main/src/modules/Jvm.scala, main/src/modules/Util.scala, scalalib/src/GenIdeaImpl.scala
There are 2 problems this PR tries to fix:
1. production version of Mill, built by `assembly` task
2. development version of Mill, built by `dev.launcher` task
These problems manifest with java 1.8.  
In Hotspots 9+ there exists an option `-XX:VMOptionsFile`...
- Download latest Mill (0.6.1-25-360107-assembly) and rename it to `mill.bat`
- unzip "example-1.zip" project from docs
- run it with downloaded Mill as `mill foo.compile`
First time you run it you'll get this message:
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> Unrecognized VM option 'VMOptionsFile=C:\projects\TODO\mill\winfix\example-1\out\mill-worker-+9h7erhXUQxlj6SW7zBIF3jvnFg=-1\vmoptions'
If you kill it and **try again, it just hangs**...  
I couldnt attach …
=> Fix Windows launcher

build.sc
I ran into problems while trying `mill.bat` from various folders..  
This ensures you can use it from e.g. "C:\New folder\mill.bat" (notice the space)
=> More robust MILL_CLASSPATH on Windows

docs/pages/2 - Configuring Mill.md
The custom task code `foo.sources().flatMap(ref => os.walk(ref.path)).filter(_.isFile).flatMap(read.lines).size` generates the following errros:
```text
build.sc:13: value isFile is not a member of os.Path
.filter(_.isFile)
^
build.sc:14: not found: value read
.flatMap(read.lines)
^
build.sc:9: `T.command` definitions must have 1 parameter list
def lineCount = T {
^
Compilation Failed
```
Change the code to use the correct os methods.
=> fix the Configuring Mill doc lineCount task to use correct os methods

docs/pages/2 - Configuring Mill.md, docs/pages/4 - Tasks.md
Fix  doc Tasks code to make it workable
- import broken/missing packages
-  use `os.proc` to run subprocess
Improve  Custom Tasks code by removing redundant placeholder `_` in `os.isFile` and `os.read.lines`
=> fix doc Tasks  code

build.sc
JNA folks made some break changes in JNA 5.0. Without this, running under windows without `-i` will throws:
```
F:\repos\test>mill clean
Exception in thread "main" java.lang.NoSuchFieldError: SIZE
at com.sun.jna.platform.win32.WinBase.<clinit>(WinBase.java:52)
at com.sun.jna.platform.win32.WinNT$HANDLE.fromNative(WinNT.java:1366)
at com.sun.jna.NativeMappedConverter.fromNative(NativeMappedConverter.java:78)
at com.sun.jna.Function.invoke(Function.java:369)
at com.sun.jna.Library$Handler.invoke(Library.java:244)
at com.sun.proxy.$Proxy0.CreateNamedPipe(Unknown Source)
at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:92)
at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:61)
at …
```
=> Align JNA API/platform version

docs/VisualizeCompile.svg, docs/pages/1 - Intro to Mill.md
`mill show visualizePlan _.compile` diagrams the relationships between the compile tasks of two modules. The old command `mill show visualize __.compile` was wrong and its diagram was deleted in previous doc PR #826. Now add the correct command and its output:
- add a sample `build.sc` file  with two modules. 
- add description.
- ddd the generated diagram.
=> add doc for visualizePlan of two modules

docs/pages/1 - Intro to Mill.md, docs/pages/2 - Configuring Mill.md, docs/pages/4 - Tasks.md, docs/pages/7 - Extending Mill.md
Improve task description and use OS-Lib in code example
- Use `os` instead of `ammonite.ops` for two reasons: 
- no need to `import ammonite.ops._`
- the `%` or `%%` requires implicit values to be imported and the results may not be JSON serializable.
- Improve the description of tasks, especially the anonymous tasks
- fix several code errors
- user `override` in overriding methods to help the compiler find errors
=> improve task doc and use OS-Lib code

docs/pages/8 - Mill Internals.md, integration/test/resources/ammonite/build.sc, integration/test/src/AmmoniteTests.scala, integration/test/src/BetterFilesTests.scala, integration/test/src/PlayJsonTests.scala, integration/test/src/UpickleTests.scala, main/src/main/MainRunner.scala, scalajslib/src/ScalaJSModule.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/test/src/MultiModuleTests.scala, scalajslib/test/src/NodeJSConfigTests.scala, scalalib/src/JavaModule.scala, scalalib/test/src/HelloJavaTests.scala, scalalib/test/src/HelloWorldTests.scala, scalanativelib/src/ScalaNativeModule.scala, scalanativelib/test/src/HelloNativeWorldTests.scala
This should avoid the problem with `__.test` running the `.test.test()` command twice
=> Rename .test with .testUncached to avoid duplicate resolution

contrib/scalapblib/src/ScalaPBModule.scala
This fixes #846, although it is not a long-term solution.
=> Use Scala 2.13.1 for default ScalaPB compiler classpath

scalalib/src/PublishModule.scala, scalalib/src/publish/SonatypePublisher.scala
Not sure if we are ok to break the interface here. If not I can probably add back `gpgPassphrase` and `gpgKeyName` with a `@deprecated` and wire that to `gpgArgs`.
=> Ability to pass GPG arguments to publish

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
When a project has a large amount of cross-compilation and bloop is
only used as a gateway to metals, one might want to skip the generation
of the configuration for some specific scala versions or target
platforms
=> Adds a way to skip bloop configuration

scalalib/api/src/ZincWorkerApi.scala, scalalib/worker/src/ZincWorkerImpl.scala
+ build.sc
```scala
import mill._, scalalib._
object foo extends Cross[FooModule]("0.24.0-RC1", "2.13.2")
class FooModule(val crossScalaVersion: String) extends CrossSbtModule
```
+ output
<details>
```scala
% cat .mill-version 
0.6.2-35-7d1144
% mill 'foo[0.24.0-RC1]'.compile
Compiling /Users/thanhbv/ohze/oss/mill-example/build.sc
[26/26] foo[0.24.0-RC1].compile 
java.lang.Exception: Cannot find scala-library-2.13.0.jar or 2.13.0/jars/scala-library.jar in [/Users/thanhbv/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/epfl/lamp/scala-library/0.24.0-RC1/scala-library-0.24.0-RC1.jar, /Users/thanhbv/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/epfl/lamp/dotty-interfaces/0.24.0-RC1/dotty-interfaces-0.24.0-RC1.jar, /Users/thanhbv/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/epfl …
```
=> fix `Cannot find scala-library-2.13.0.jar ..` Exception when compile dotty project

build.sc
The newer version of coursier has deterministic ordering (see coursier/coursier#1546, thanks for the pointer @smarter), which in turn fixes #853.
=> Upgrade coursier to 2.0.0-RC6-15

build.sc
I'm gonna spend a bit of time trying to investigate why WSL causes client-daemon mode to hang, but if I can't figure out we can just disable it in the launcher
=> Disable client-daemon mode in WSL

scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/helloworld.iml, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/helloworld.test.iml, scalalib/test/resources/gen-idea-hello-world/idea_modules/helloworld.iml, scalalib/test/resources/gen-idea-hello-world/idea_modules/helloworld.test.iml
This makes sure we also use the right content dir for source folders outside our module dir, which is most probably the case when you have "shared" sources in e.g. cross JVM/JS projects.
=> GenIdea: Use new content element for each source path

build.sc
A small fix, suppressing unnecessary outputs on systems that do not use bash as their default shell.
See also gitter discussion https://gitter.im/lihaoyi/mill?at=5ebe5e726675d830b1a91081
=> launcher: fix output redirect to work correctly on non-bash shells

build.sc, integration/test/src/IntegrationTestSuite.scala, main/test/src/util/ScriptTestSuite.scala, scalalib/src/GenIdeaImpl.scala, scalalib/test/src/GenIdeaExtendedTests.scala, scalalib/test/src/GenIdeaTests.scala
This should allow the GenIdea output XML files to be usable cross-platform, e.g. we could resolve them on a WSL-Ubuntu environment and load them into Intellij on the host Windows machine
Tested locally on OS-X, seems to work, and tested on WSL2 as well. IntelliJ seems to be able to load the config successfully, even across the Ubuntu/Windows boundary
=> Relative library paths in GenIdea, and a relative COURSIER_CACHE on WSL2

docs/pages/1 - Intro to Mill.md
New to here, looked through the introduction doc and one typo found.
=> fix typo in intro to mill doc

build.sc, contrib/bsp/src/mill/contrib/BSP.scala, contrib/bsp/src/mill/contrib/bsp/MillBuildServer.scala, contrib/bsp/src/mill/contrib/bsp/ModuleUtils.scala, contrib/bsp/src/mill/contrib/bsp/Utils.scala, main/src/modules/Util.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/ScalaModule.scala
This is fixing:
- Some source file considered as directories.
- A workaround [SCL-17551](https://youtrack.jetbrains.com/issue/SCL-17551) that doesn't manage well 2 modules with the same base directory. This is mitigating https://github.com/lihaoyi/mill/issues/864 just like how SBT does 1 version only.
I'm also trying to fix it on the client side https://github.com/JetBrains/intellij-scala/pull/534
- Partially fixing https://github.com/lihaoyi/mill/issues/863. It's resolving `$ivy` imports but missing the `$file` resolutions.
- Removes the weird `/build` root project so that in the future we will be able to support actual root project.
Thanks
=> BSP fixes and workaround for cross projects

scalalib/src/JavaModule.scala, scalalib/src/Lib.scala, scalalib/src/ScalaModule.scala, scalalib/test/resources/dottydoc/empty/src/Main.scala, scalalib/test/resources/dottydoc/multidocs/docs1/index.md, scalalib/test/resources/dottydoc/multidocs/docs1/nested/original.md, scalalib/test/resources/dottydoc/multidocs/docs1/sidebar.yml, scalalib/test/resources/dottydoc/multidocs/docs2/index.md, scalalib/test/resources/dottydoc/multidocs/docs2/nested/extra.md, scalalib/test/resources/dottydoc/multidocs/src/Main.scala, scalalib/test/resources/dottydoc/static/docs/index.md, scalalib/test/resources/dottydoc/static/docs/nested/extra.md, scalalib/test/resources/dottydoc/static/docs/sidebar.yml, scalalib/test/resources/dottydoc/static/src/Main.scala, scalalib/test/src/DottyDocTests.scala, scalalib/worker/src/ZincWorkerImpl.scala
This is a rebase of #787 on master with some added tests.
In the last commit I added one additional change however: the scaladoc tool now has distinct classpath and ivydeps from the compiler. In Scala <= 2.13 this is not necessary, as the doc tool is included in the compiler artifact, however in dotty this is no longer the case. Feel free to drop that last commit if you'd rather not have the split.
=> Dottydoc fix

main/core/src/eval/Evaluator.scala, main/src/main/RunScript.scala
A tiny fix resolving miss of appropriate destination directory for foreign modules that causes following error:
```
Exception in thread "main" java.nio.file.NoSuchFileException: /Users/goodfella/dev/out/baz/compile/meta.json
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
at …
```
=> Fixed destination path for foreign-module setup

contrib/bsp/src/mill/contrib/bsp/MillBuildServer.scala
Due to an Intellij workaround (shared modules) to support cross compiled code we are receiving multiple times the same target.
=> BSP: Deduplicate targets to compile

scalalib/src/Lib.scala
This change is a "symptomatic treatment" to fix bloop config generation, which is currently broken for dotty projects.
In particular, [this issue](https://github.com/scalameta/metals/issues/1768) describes the error observed, and also hints to the fix.
The gist of it seems to be that Dotty publishes an empty jar named "scala-library" (not sure why?), but the actual standard library is published in the artifact "dotty-library". While the former is empty and isn't strictly a problem when compiling, it does cause bloop to crash if included in the classpath.
~Note that I am not exactly sure what the root cause is, and I'm also not sure what the future plans are regarding the naming of artifacts. It would be great to get feedback from someone more knowledgeable in this area before accepting …
=> Replace scala-library artifact with dotty-library

scalalib/src/publish/Pom.scala
This is just to include the url set in the Developer case class in the pom that is generated when publishing to Sonatype or to the local maven repo.
=> Adding url to generated developer setting in published pom.

main/src/modules/Jvm.scala
Quotes classnames to that bash doesn't interpret any `$` contained within them (as can happen with dotty's top-level main functions).
=> Wrap class names in single quotes in launcher script

scalalib/worker/src/ZincWorkerImpl.scala
JavaOptionConverter.convertInt overflowed the stack, probably because there is no Optional#isEmpty
=> ZincProblemPosition: fix infinite loops

build.sc, docs/pages/1 - Intro to Mill.md, docs/pages/2 - Configuring Mill.md, main/src/MillMain.scala
This adds `--repl` and `--no-server` as options, and makes `-i` with no targets produce a warning message.
* `--repl` starts a build REPL, but fails if a target is given
* `--no-server` fails unless targets are given
* `-i`/`--interactive` is the same as `--no-server`, but emits a warning and starts a build REPL if no targets are given
Giving any of these arguments as the first option on the command-line causes `mill.MillMain` to run (interactive mode). Giving none of them as the first argument causes `mill.client.MillClientMain` to run. It is an error to give more than one of these options.
The only possible undesirable feature is that It is now possible to give one of these options more than once, with the first occurrence being as the first argument and another occurrence later in the …
=> Added --repl and --no-server and changed behavior of -i/--interactive for #926

contrib/bsp/src/mill/contrib/BSP.scala, contrib/bsp/src/mill/contrib/bsp/MillBuildServer.scala, contrib/bsp/src/mill/contrib/bsp/ModuleUtils.scala
This fixes:
- Some redness with the .sc files because if the missing Scala lib as dependency.
- The BSP server boot command to forward the env vars. That's useful when you set env vars like `JAVA_OPTS` or `COURSIER_REPOSITORIES`.
Thanks
=> BSP: Mill build Scala lib dep and forward env vars to server start

scalalib/src/scalafmt/ScalafmtModule.scala, scalalib/test/resources/scalafmt/core/util.sc, scalalib/test/src/scalafmt/ScalafmtTests.scala
This allows that the MillScalafmtModule can be utilised to format the mill build sources (such as build.sc) as well.
Here is an example how a command can be created to trigger the formatting:
```
def buildSources: Sources = T.sources(os.pwd / "build.sc")
def fmtBuild(): Command[Unit] =
T.command {
MillScalafmtModule.reformatAll(Tasks(Seq(buildSources)))
}
```
=> Allows the ScalafmtModule to format build sources

scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
Sourcemaps were only being generated when using
`scalajs 0.6` but not for `scalajs 1`.
This changeset makes sure that we test that both
`fastOpt` and `fullOpt` will generate correct sourcemaps on all
scalajs supported versions.
Closes #884 
Context from gitter channel: https://gitter.im/lihaoyi/mill?at=5efcf211405be935cdd4e4c6
=> Generate sourcemaps on scalajs 1.

build.sc, scalajslib/src/ScalaJSModule.scala, scalajslib/test/src/HelloJSWorldTests.scala
I noticed that the ScalaJS build doesn't work with ScalaJS 1.0.1.
This is because it derives the `scalajs-env-nodejs` and `scalajs-env-jsdom-nodejs` dependencies from the ScalaJS version instead of using fixed versions, since they are not tied to the ScalaJS version.
=> Fix ScalaJS dependencies versions

docs/pages/1 - Intro to Mill.md
Previous update changed the entry point for this command.  Not sure how PR was accepted without documentation updates.
=> Fix showUpdates documentation

build.sc, docs/pages/1 - Intro to Mill.md, main/client/src/mill/main/client/MillClientMain.java
Hi. I'm trying to fix https://github.com/lihaoyi/mill/issues/577. The pull request is still in progress. I want to verify my solution before full implementation.
I propose to pass extra JVM arguments to the launcher through `.mill-args` file in the root of the project. sbt using the same approach with `.sbtopts` file.
At the current moment, only mill server on linux/macos could recognize `.mill-args` file. Support for windows and interactive mode is needed for full feature implementation.
What do you think about this solution?
=> Passing args to launcher

build.sc, docs/pages/2 - Configuring Mill.md, main/src/modules/Assembly.scala, main/src/modules/Jvm.scala, scalalib/test/resources/hello-world-deps/core/src/Main.scala, scalalib/test/resources/hello-world/core/src/Main.scala, scalalib/test/src/HelloWorldTests.scala
Resolves https://github.com/lihaoyi/mill/issues/355
This gives the ability to relocate/shade in assembly on a global level.
This is a good first step but we might want later to provide the ability to shade only for a given lib. This is currently not possible because at the time we get the class path we lost the information of the dependency tree.
Example of usage:
```scala
override def assemblyRules =
Assembly.defaultRules ++ Seq(Assembly.Rule.Relocate("shapeless.**", "com.netflix.data.playback.shade.shapless.@1"))
```
=> Ability to relocate/shade in assembly

contrib/playlib/src/mill/playlib/Twirl.scala, contrib/twirllib/src/TwirlModule.scala, contrib/twirllib/src/TwirlWorker.scala, contrib/twirllib/test/resources/hello-world-inclusive-dot/core/views/test.scala.svg, contrib/twirllib/test/resources/hello-world/core/views/test.scala.svg, contrib/twirllib/test/src/HelloWorldTests.scala, docs/pages/9 - Contrib Modules.md
This aims to bring the twirl module closer to parity with the twirl SBT plugin. It adds support for:
- Overriding full set of twirl template imports rather than just appending additional imports onto the default set
- Renames `twirlAdditionalImports` to `twirlImports`
- Sets the default value to `play.japi.twirl.compiler.TwirlCompiler.DEFAULT_IMPORTS`
- Overriding set of twirl extensions/formats that will be compiled
- Adds `def twirlFormats: T[Map[String, String]]` to define a mapping from extension to class name
- Sets the default value to
```scala
Map(
"html" -> "play.twirl.api.HtmlFormat",
"xml" -> "play.twirl.api.XmlFormat",
"js" -> "play.twirl.api.JavaScriptFormat",
"txt" -> "play.twirl.api.TxtFormat")
```
=> Twirl enhancements

contrib/buildinfo/src/BuildInfo.scala, contrib/buildinfo/test/src/BuildInfoTests.scala
JSON is done via `ujson-circe` as this is what's already being used in the project itself
=> Add toMap and toJson methods to BuildInfo

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/bsp/src/mill/contrib/bsp/MillBuildServer.scala, contrib/scalapblib/src/ScalaPBModule.scala, contrib/scoverage/src/ScoverageModule.scala, contrib/tut/src/TutModule.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/JavaModule.scala, scalalib/src/PublishModule.scala, scalalib/src/ScalaModule.scala
Support compile-only module dependencies with added target `compileModuleDeps`.
Added target `showModuleDeps` to let the user inspect module dependencies on the cmdline.
Fixes https://github.com/lihaoyi/mill/issues/877
Fixes https://github.com/lihaoyi/mill/issues/828
=> Give more control over module dependencies

build.sc
This version of coursier API includes access to licensing information of dependencies.
=> Bump coursier to 2.0.0-RC6-25

scalalib/api/src/ZincWorkerApi.scala, scalalib/src/Dep.scala, scalalib/src/Lib.scala, scalalib/src/ScalaModule.scala, scalalib/src/ZincWorkerModule.scala, scalalib/worker/src/ZincWorkerImpl.scala
This PR is a blocker for lampepfl/dotty#9917. We have a bunch of libraries compiled with Mill in the Dotty community build, and we'd rather not disable them during the artefacts naming change.
@lihaoyi what's the policy on the Mill nightly builds? How soon will we be able to use this change in a nightly build once this is merged?
=> Add support for Scala 3

scalalib/src/MiscModule.scala, scalalib/test/src/HelloWorldTests.scala
Users of mill (including me) struggle with publishing artifacts as soon as they start cross compiling between multiple Scala versions.
By default it will publish `Artifact(org,myproject-2.12.10_2.12,0.0.1-SNAPSHOT)` where we expect something like `Artifact(org,myproject_2.12,0.0.1-SNAPSHOT)`.
Here is an example: https://gitter.im/lihaoyi/mill?at=5f404a975580fa092b15a821
The usual fix is to override the `artifactName` as follows:
```
def artifactName = "myproject"
```
I personally get caught every time I start to cross compile a project and believe that doesn't look reasonable to ask the user to course correct the artifact name.
This proposal removes the added segment part in `artifactName` for `CrossModuleBase`.
cc @davesmith00000
=> Omit the suffix in artifactName for cross modules

.gitignore, scalalib/src/Lib.scala
This PR removes a filter from the test discovery that ignores classes that have parameters in their constructor. I think this is problematic as it is perfectly valid for tests to have constructor parameters depending on the test framework, and so this should be a decision made by the testing framework rather than the build tool.
Here's an example where I encountered this issue recently: https://github.com/disneystreaming/weaver-test/issues/113. After running these tests again with the changes made in this PR the example tests shown in that issue now pass.
I've attempted to verify that these changes are compatible with other test frameworks. With some fairly basic examples uTest and Scalatest both seem to continue to work as expected. I'd be happy to verify the changes against other test …
=> Allow test classes with constructor parameters

scalalib/worker/src/ZincWorkerImpl.scala
The compiler output is a diagnostic message and should hence be printed to stderr.
This also allows users to redirect output when running applications directly from mill, without including any diagnostic information. E.g.
```
mill foo.run > out.txt
```
=> Redirect zinc log output to stderr

build.sc, contrib/proguard/src/Proguard.scala, contrib/proguard/test/resources/proguard/src/Main.scala, contrib/proguard/test/src/ProguardTests.scala, docs/pages/9 - Contrib Modules.md, scratch/build.sc
Create Proguard contrib module
This module will run `proguard` on the normal `assembly` output jar to shrink it. By default all steps - shrink, optimize, obfuscate, and preverify - are run though this can be configured. The default entrypoint is `finalMainClass`. Any additional options can be specified freely with `additionalOptions` (proguard has many).
=> Proguard contrib module

build.sc
The reason for doing this is to ensure that the version of
trees that mill wants is indeeed used instead of the newer
version that is being pulled in by ammonite-interp. Before
this was using `forceVersion()`, which was added https://github.com/lihaoyi/mill/compare/438ebc...6b492a, but by doing this the forced
version doesn't end up in the POM meaning that when someone
bootstraps/uses mill via coursier, they are getting the newer
trees, which is causing issues with how the main class is detected.
You can see we are getting `4.3.20` here instead of the _forced_ `4.3.7`:
```
❯ cs resolve mill | grep trees
org.scalameta:trees_2.13:4.3.20:default
```
This is coming from ammonite-interp:
```
❯ cs resolve mill --what-depends-on org.scalameta:trees_2.13
Result:
└─ org.scalameta:trees_2.13:4.3.20 …
```
=> Exclude trees from ammonite dep.

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
Attempt to fix https://github.com/lihaoyi/mill/issues/990
=> Bloop: Also use compileModuleDeps to calc transitive classpath

build.sc, contrib/codeartifact/src/mill/contrib/codeartifact/CodeArtifactPublisher.scala, contrib/codeartifact/src/mill/contrib/codeartifact/CodeartifactHttpApi.scala, contrib/codeartifact/src/mill/contrib/codeartifact/CodeartifactPublishModule.scala, docs/pages/9 - Contrib Modules.md
This allows Mill projects to deploy to AWS Codeartifact. It functions similarly to the Artifactory PublishModule. Its credentials value is a Codeartifact auth token.
=> Add AWS Codeartifact contrib module

bsp/src/mill/bsp/BSP.scala
The argv attribute needs to hold each argument in a separate element.
This fixes loading issues in latest IntelliJ IDEA.
Suggested reviewer: @joan38 , @m-a-t
=> BSP: Fixed generated `.bsp/mill.json` file.

main/core/src/eval/Evaluator.scala, main/core/src/util/Loggers.scala
This avoids the confusion regarding the jumping overall target count.
Now, we can see clearly that the jumping overall target count is a sub-count.
This result in an output like this:
```
$ mill mill.scalalib.GenIdea/idea
[1/1] mill.scalalib.GenIdea/idea
Analyzing modules ...
[1/1] mill.scalalib.GenIdea/idea > [1270/1271] app.headless.test.ideaCompileOutput
```
I also fixed the ticker progress for parallel builds, which was 0-based,
resulting is some (incorrect) output like this:
```
$ dev-mill -j 0 mill.scalalib.GenIdea/idea
Using experimental parallel evaluator with 4 threads
[#0] [0/1] mill.scalalib.GenIdea/idea
[#0] Analyzing modules ...
[#3] [0/1] mill.scalalib.GenIdea/idea > [1188/1271] module.contract.test.ideaConfigFiles
```
=> Prefix the ticker of evaluator targets with the caller target

bsp/src/mill/bsp/BSP.scala, main/core/src/eval/Evaluator.scala, main/core/src/util/LinePrefixOutputStream.scala, main/core/src/util/Loggers.scala, main/src/main/MainRunner.scala
Some use cases need to be able to emit exact strings to stdout, e.g. BSP.
For those cases, we need to be able to skip log decoration, e.g. colors and prefixes.
I don't know if this is the most elegant solution, but I think emitting logs without decoration is something third party tasks may also need to be able to do, so I added the capability to Logger. For Mill itself, the BSP server needs to be able to do it.
=> Fix BSP,  avoid assumptions about Logger implementation

contrib/scoverage/src/ScoverageReport.scala, docs/pages/9 - Contrib Modules.md
This is a module we've been using for a couple of months now that's been working well, originally suggested by @lefou on Gitter [here](https://gitter.im/lihaoyi/mill?at=5f5f7d8df969413294e55466). It allows scoverage to be run across multiple modules and then aggregated into a single report. This is particularly useful if you need a single report for SonarQube or other analysis tools and so contributing it back here.
Thanks @lefou for the help!
=> Adds ScoverageReport for multi-module projects

build.sc, scalajslib/api/src/ScalaJSWorkerApi.scala, scalajslib/src/ScalaJSModule.scala, scalajslib/src/ScalaJSWorkerApi.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/test/src/MultiModuleTests.scala, scalajslib/test/src/ScalaJsUtils.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
- Support ESModule ModuleKind
- Update Scala.js 0.6 to 0.6.33
- Update Scala.js 1 to 1.3.1
- Add useECMAScript215 to test matrix just for last version
- Update Scala versions it tests
- Update ScalaJsUtils to use node.js instead of nashorn
The initial idea was to use the NodeJSEnv from Scala.js to run the
tests. But this created a problem since adding a particular NodeJSEnv
to the classpath broke the other version of Scala.js linking. For example
using NodeJSEnv from Scala.js 1.3.1 made fastOpt in Scala.js 0.6 break.
So at the end the function is just calling "node" using `os.proc`
=> Support useECMAScript2015 option in ScalaJSModule

scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
Originated from [this message on gitter.im](https://gitter.im/scala-native/scala-native?at=5fb274fd2a354407152b54f3).
This should solve the problem.
This PR caches all the linkers separately. For now there are 12 combinations. But adding new parameters could explode the possibilities even more.
I did this so you can jump between different settings of fastOpt/fullOpt, ModuleKind without losing the incremental linking.
=> Cache Scala.js Linker to enable incremental linking

main/api/src/mill/api/PathRef.scala, main/test/src/api/PathRefTests.scala
This adds the ability for `PathRef` to detects changes on file permissions.
Previously, a change to a file permission was not detected when using `T.source` and the depending tasks were not executed.
=> PathRef: detect permissions change

contrib/bloop/src/mill/contrib/Bloop.scala, contrib/bloop/src/mill/contrib/bloop/Bloop.scala, contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, docs/pages/9 - Contrib Modules.md
We want to avoid package split situations.
=> Move `Bloop` object into mill.contrib.bloop package

contrib/scalapblib/src/ScalaPBModule.scala, contrib/scalapblib/src/ScalaPBWorker.scala, contrib/scalapblib/test/src/TutorialTests.scala, docs/pages/9 - Contrib Modules.md
@lefou can you please review, and let me know if I'm missing something?
The plan with this change is to allow additional args for scalaPBC, this means I can just do this in my code for zio-grpc to work:
```
object example extends ScalaPBModule {
def scalaVersion = "2.12.6"
def scalaPBVersion = "0.7.4"
override def scalaPBAdditionalArgs = Seq(
s"--zio_out=${T.dest.toIO.getCanonicalPath}"
)
}
```
=> ScalaPB additional args

bsp/src/mill/bsp/MillBuildServer.scala, bsp/src/mill/bsp/ModuleUtils.scala, build.sc, main/src/main/MillServerMain.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/Lib.scala
Not sure why the following does not bring in the dependencies anymore since `0.9.x`:
```
val classpath = Try(evaluator.rootModule.getClass.getClassLoader.asInstanceOf[SpecialClassLoader]).fold(
_ => Seq.empty,
_.allJars
)
```
So this is resolving the source files directly. Let me know if you have a better idea.
=> BSP: Provide mill source files

contrib/scalapblib/src/ScalaPBModule.scala, contrib/scalapblib/src/ScalaPBWorker.scala, contrib/scalapblib/test/src/TutorialTests.scala
* fix destination path issue mentioned in https://github.com/lihaoyi/mill/pull/1002#issuecomment-737769495
* isolated classloader as #1026
* use T.worker
=> ScalaPB: various fix and improves

scalanativelib/test/src/HelloNativeWorldTests.scala
Also fixed some inconsistencies in test matrix setup.
=> scala-native: Run test with release-fast as release-full sometimes hangs

main/api/src/mill/api/PathRef.scala, main/test/src/api/PathRefTests.scala
There's no guarantee that the symlink is actually valid. Note that this is called in a loop that itself follows valid symlinks, so there should not be any files missed.
=> Don't follow symlinks when checking permissions of files

build.sc, contrib/proguard/test/src/ProguardTests.scala, scalalib/src/ZincWorkerModule.scala, scalalib/worker/src/ZincWorkerImpl.scala
Unblock https://github.com/lampepfl/dotty/issues/10816
=> Bump zinc to 1.4.4

build.sc
This reverts commit 058479d8f2f794a1e536a170d31b5bc332b8d7c5.
We have various issue with failing CI builds, and I suspect this commit the culprit
Here is a typical output:
```
-------------------------------- Running Tests --------------------------------
java.io.IOException: Error closing -1 for /tmp/398711886632860139/io
at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.read(UnixDomainSocket.java:144)
at mill.main.client.ProxyStreamPumper.run(ProxyStreamPumper.java:29)
at java.lang.Thread.run(Thread.java:748)
main.test.test java.lang.Exception: Interactive Subprocess Failed (exit code 1)
mill.modules.Jvm$.runSubprocess(Jvm.scala:102)
mill.modules.Jvm$.runSubprocess(Jvm.scala:66)
mill.scalalib.TestModule.$anonfun$testTask$1(JavaModule.scala:660) …
```
=> Revert "Update ipcsocket to 1.3.0 (#1057)"

scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
After #1007 got merged, it generated an annoying bug: if you use `-j number` to use multiple parallel workers, multiple workers would try to use the same Scala.js linker, failing with: `java.lang.IllegalStateException: Linker used concurrently`.
This uses separate linkers per generated files so that doing `__.test` or `__.fastOpt` can't give the same linker to two different projects ( they generate different js files )
=> Fix linker used concurrently

docs/pages/2 - Configuring Mill.md
While following the instructions to use a custom `ZincWorkerModule`, things didn't compile until `CoursierModule` was added too. (It seems it's a self type of `ZincWorkerModule` now.) This PR updates the documentation accordingly.
=> Add missing trait in custom ZincWorkerModule example

scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea-hello-world/build.sc, scalalib/test/resources/gen-idea-hello-world/idea_modules/helloworld.test.iml
Fixes the case where runtime dependencies, which are also compile-time dependencies, are only mapped to RUNTIME scope in IntelliJ IDEA.
=> GenIdea: fine-tuned scope calculation for dependencies

.github/workflows/actions.yml, main/client/src/mill/main/client/Util.java, main/client/test/src/mill/main/client/ClientTests.java, main/src/modules/Jvm.scala
Various fixes only shown on Windows, probably also elsewhere.
* Fixed string stream writer/reader used for mill client-server communication, by using an explicit charset for byte conversion
* Avoid `java.nio.file.Paths.get(url.getFile())` in favour of `java.nio.file.Paths.get(url.toURI())` as the latter handles windows paths with leading drive letters well
* Improved CI setup for Windows
* Better run/spawn of Java sub-processes by selecting the same Java executable which is used by mill
We still have some CI failures on Windows, as we need some of these fixed in mill before we can benefit from it. Expect more PRs.
Probably related issues:
* https://github.com/lihaoyi/mill/issues/781
* https://github.com/lihaoyi/mill/issues/874
* https://github.com/lihaoyi/mill/issues/646
* …
=> Various Fixed for Windows

contrib/proguard/src/Proguard.scala, docs/pages/3 - Common Project Layouts.md, docs/pages/5 - Modules.md, docs/pages/9 - Contrib Modules.md, main/api/src/mill/api/IO.scala, main/test/src/eval/EvaluationTests.scala, readme.md, scalalib/src/JavaModule.scala
All changes should be non-semantic.
=> DOC: Fix typos

scalalib/api/src/ZincWorkerApi.scala, scalalib/src/Lib.scala, scalalib/src/ScalaModule.scala, scalalib/test/resources/scaladoc3/empty/src/Main.scala, scalalib/test/resources/scaladoc3/multidocs/docs1/docs/nested/original.md, scalalib/test/resources/scaladoc3/multidocs/docs1/index.md, scalalib/test/resources/scaladoc3/multidocs/docs1/sidebar.yml, scalalib/test/resources/scaladoc3/multidocs/docs2/docs/nested/extra.md, scalalib/test/resources/scaladoc3/multidocs/docs2/index.md, scalalib/test/resources/scaladoc3/multidocs/src/Main.scala, scalalib/test/resources/scaladoc3/static/docs/index.md, scalalib/test/resources/scaladoc3/static/docs/nested/extra.md, scalalib/test/resources/scaladoc3/static/docs/sidebar.yml, scalalib/test/resources/scaladoc3/static/src/Main.scala, scalalib/test/src/HelloWorldTests.scala, scalalib/test/src/ScalaDoc3Tests.scala, scalalib/worker/src/ZincWorkerImpl.scala
This adds support for docJar generation under Scala 3.0.0-RC1, which is currently broken[1].
I've tried to keep backwards compatibility as much as I could. However, there is one sort-of-breaking change with this: `docJar` now has a dependency on the `compile` task (because Scaladoc 3 uses tasty files, not source files anymore). This dependency prevents generating documentation for projects that would previously not compile but could still generate documentation.
[1]: See the [discussion on Gitter](https://gitter.im/lampepfl/dotty?at=603e29b5823b6654d27ad28b) if you're interested, but the gist of it is that Scaladoc 3 is really not compatible with dottydoc, yet dottydoc is no longer available for Scala >= 3.0.0-RC1.
=> Add support for Scaladoc 3

main/client/src/mill/main/client/InputPumper.java, main/client/src/mill/main/client/Lock.java, main/client/src/mill/main/client/Locked.java, main/client/src/mill/main/client/Locks.java, main/client/src/mill/main/client/MillClientMain.java, main/client/src/mill/main/client/ProxyStreamPumper.java, main/src/main/MillServerMain.scala, main/test/src/main/ClientServerTests.scala
Only one thing in `ClientServerTests` doesn't work currently.  
Maybe someone will find a fix in the future... 😄 
I tried many things, even reimplementing the whole named pipes thing with JNA...  
But it boils down to `read/write` throwing an exception instead of returning `-1`...  
Since the read is done infinitely in a separate thread, it doesn't know when the output from server is done.  
So when a connection breaks, we should just ignore it, and not `System.exit(1);` as currently.
=> Windows client-server fixes

.github/workflows/actions.yml
I specifically try to avoid the "Resource amm-dependencies.txt not found" error.
=> Disabled JawnTest to work around CI failures

scalanativelib/api/src/mill/scalanativelib/api/ScalaNativeWorkerApi.java, scalanativelib/src/ScalaNativeModule.scala, scalanativelib/worker/0.4/src/ScalaNativeWorkerImpl.scala
- Make `nativeOptimize` configurable
- Env variables are proper `T.input`s and are evaluated every time
=> Read default Scala Native env variables

scalanativelib/src/ScalaNativeModule.scala
- https://github.com/com-lihaoyi/mill/pull/1253 used `valueOf` which
given a Java `enum` it matches the name of the classes and not
the string values that match the official Scala Native env variables
values. This PR uses instead `.values` which returns all the values
then matches based on the `String value` the enums define.
=> Fix Scala Native env variables values to match sbt

scalalib/api/src/ZincWorkerApi.scala, scalalib/src/Dep.scala, scalalib/test/src/dependency/versions/ScalaVersionTests.scala
Continuation of #1139 
- Add more test on Scala 3 nightly versions.
- Fix `isBinaryBridgeAvailable`
- Fix `withDottyCompat`
@lefou this is ready for review
=> Fix binary version computation of Scala nightly versions

integration/test/resources/hygiene/build.sc, integration/test/src/HygieneTests.scala, integration/test/src/local/Tests.scala, main/core/src/util/Router.scala
By prefixing its `scala` references with `_root_.`, so that users can name some of their own variables `scala`.
=> Fix macro-hygiene in Discover macro

main/core/src/eval/Evaluator.scala, main/core/src/eval/package.scala, main/core/src/util/package.scala, main/test/src/eval/FailureTests.scala
Also deprecated some more type aliases.
See also discussion: https://gitter.im/lihaoyi/mill?at=6051223bd71b6554cd4bf600
> Tobias Roeser @lefou März 16 22:25
> @lihaoyi I find the "dest can only be used in one place within each Target[T]" restriction when calling anonymous tasks quite limiting. Is there a good motivation for it ?
> Li Haoyi @lihaoyi März 17 02:08
> @lefou it was somewhat arbitrary, if we don't think the limitation is pulling its own weight we can probably remove it
> Tobias Roeser @lefou März 17 09:14
> @lihaoyi I'm all for it. I can clearly see that it allows me to better split my work into tasks, or let tasks better interact. But I haven't really thought about any downside of removing that limitation. But I assume there are none, as Tasks run per definition in the …
=> Loosened the restriction to use T.dest only in one T.task

bsp/src/mill/bsp/ModuleUtils.scala
… - cannot import into IDE
There is a PR already (#1092) but I am wary of dealing with Strings directly. Here is my approach.
On Windows, File URLs follow an peculiar representation in Java
```
scala> java.nio.file.Paths.get(".").toAbsolutePath.toUri.toURL
java.net.URL = file:/C:/Users/Developer/mill/./
```
From this, we wish to get a `Path` back, and the way to do this is:
```
scala> java.nio.file.Paths.get((java.nio.file.Paths.get(".").toAbsolutePath.toUri.toURL).toURI)
java.nio.file.Path = C:\Users\Developer\mill\.
```
Unit testing for this is more challenging because the `WindowsFileSystem` instance is a `sun.nio.fs` package, rather than a standard package.
The solution here, compared to the previous code, is to reduce the number of conversions; the key loss happens when you do …
=> Fix #1283, #1021: Windows BSP: request failed: buildTarget/dependencySources

main/src/modules/Jvm.scala, scalalib/src/CoursierModule.scala, scalalib/src/JavaModule.scala, scalalib/src/Lib.scala, scalalib/src/dependency/versions/VersionsFinder.scala
This should fix #767.
TBH, I'm not sure we want this in mill. So I encourage a review and/or discussion.
On one side this fixes an issue with resolving transitive dependencies with os-specific classifiers (#767). But on the other side it makes dependency resolution less reproducible.
So a perfect outcome of this PR for me is also a rejection paired with some documentation how to deal with such situations.
=> Support customizing coursier dependency resolution (make OS specific classifiers work)

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
Metals with VS Code uses the Bloop contrib module to extract the project setup. However when it does it only sees modules directly included in the build file. If you have a foreign-module (internally or externally) then it won't be picked up by bloop.
This has been bugging me for a while as it makes it difficult to modify external libraries without having a separate compile / publish cycle.
The PR fixes this problem by fully enumerating the list of `Modules` (`JavaModue` subclasses) using both the list of modules present in the build file but also the transitive `moduleDeps`.
It also creates better names for the bloop `out` directory for each module so that there is no danger of a clash with a foreign-module / sub-module name
=> let bloop detect foreign modules included via moduleDeps

contrib/versionfile/src/mill/contrib/versionfile/VersionFileModule.scala, contrib/versionfile/test/src/mill/contrib/versionfile/VersionFileModuleTests.scala
strip whitespace to avoid MatchError in `Version.of` when version file ends with newline character.
This fix #1294
=> strip whitespace from version file

build.sc, main/src/MillMain.scala
This fixes https://github.com/com-lihaoyi/mill/issues/1284 by enabling ["console virtual terminal sequences"](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) in the Windows console, which are basically ANSI escape codes. This is done using some JNI bindings of jline, via [windows-ansi](https://github.com/alexarchambault/windows-ansi).
=> Enable ANSI output on Windows upon start-up

.github/workflows/actions.yml, main/src/modules/Assembly.scala, main/src/modules/Jvm.scala, scalalib/test/src/HelloWorldTests.scala
All scalalib tests now pass on Windows, so I moved them back into the mandatory test set of GitHub Actions CI.
Fix #1158
=> Properly close resources to fix assembly on Windows

scalajslib/src/ScalaJSModule.scala, scalalib/src/TestModule.scala, scalalib/src/TestRunner.scala, scalalib/test/resources/testrunner/test/src/BarTests.scala, scalalib/test/resources/testrunner/test/src/FooTests.scala, scalalib/test/resources/testrunner/test/src/FoobarTests.scala, scalalib/test/src/TestRunnerTests.scala, scalanativelib/src/ScalaNativeModule.scala
this is to support test class selection for frameworks do not support selection through runner arguments (for example, ScalaTest does not support class selection when running from sbt runner interface)
=> TestModule: add testOnly to select test suites in mill

contrib/playlib/src/mill/playlib/RouteCompilerWorkerApi.scala, contrib/playlib/src/mill/playlib/RouterModule.scala
Fixed use of mills utility classloader by settings the correct parent classloader.
Using the classloader of the module as parent makes the shared API modules (which need to be already loaded by the mill build) visible.
The previously used default was using the classloader which loaded the mill build (and the ammonite script), which misses the play API module (loaded via `$ivy` import).
Fixed dependency resolution of worker classpath.
The collected classpath of the worker module was limited to only use the worker module.
But this misses all transitive dependencies of the worker.
This is probably because of older limitiations in mill builds, which also included the mill API itself.
Now, mill uses `compileModuleDeps` for the mill API and we have clean and usable transitive module and worker …
=> play-contrib: Fixed classloading of worker module and cleanups

build.sc
This update hopefully fixes binary incompatibilities for external mill plugins.
=> Update os-lib to 0.7.8

bsp/src/mill/bsp/MillBuildServer.scala
due to hardcode `sourceItem(evaluator.rootModule.millSourcePath / "src", generated = false)`,
Metals not recognize build.sc as source file when user choose mill-bsp build server,
no auto-complete and hover tooltips available
This commit fix #1159
=> fix sourceItem for mill-build

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
Compilation of a module and its upstreams should be avoided at all cost when generating bloop configuration. 
https://github.com/com-lihaoyi/mill/pull/1086 adds a reference to a task that depends on `compile`. This PR prevents that from happening, and adds a test to ensure that compilation isn't triggered by `Bloop/install` 
@tgodzik 
@lolgab
=> Prevent compilation during bloop config generation

build.sc, ci/mill-bootstrap.patch, ci/patch-mill-bootstrap.sh, ci/test-mill-bootstrap-0.sh, ci/test-mill-bootstrap-1.sh, ci/test-mill-dev.sh, ci/test-mill-release.sh
Warning: This update introduces binary incompatibilities!
While bootstrap testing, we have the issue, that because of binary incompatibilities, the `build.sc` will no longer work as is. This is in this case, because we use external plugins. So when testing, we apply a temporary patch to `build.sc` to allow building with bootstrapped mill. This allows us to succeed in CI and continue to automatically release snapshot builds, which is needed, to update external plugins later.
=> Update Ammonite and upickle to support newer Scala versions

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, scalajslib/src/ScalaJSModule.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/ScalaModule.scala
It's easy to override scalacOptions in a Scala.js + Scala 3 module.
When you do so, the compiler silently fails to compile Scala.js files.
This is a source of errors for Mill users that can be mitigated by
defining a separate list of compile options which is used internally
to add these mandatory flags.
=> Introduce `mandatoryScalacOptions` to keep system `scalacOptions`

docs/antora/modules/ROOT/pages/Intro_to_Mill.adoc
Found some formatting issues with asciidoc, it considered `_` as a start of an italic word.  
It needs to be escaped in some cases, like this: `\_`
Also, I ran some bigger sentences through https://hemingwayapp.com/, and the text was a bit complicated, so I split some of them into 2 simpler ones...
=> Fix formatting and wording in intro docs

main/client/src/mill/main/client/MillClientMain.java, main/src/main/MillServerMain.scala
Closes #1447 
Now the pipe name takes the *full absolute path* of the project.  
Previously 2 server instances (for different projects) would use *same pipe name* and that would cause an issue...
https://docs.microsoft.com/en-us/windows/win32/ipc/pipe-names
> The pipe name string specified by PipeName can include any character other than a backslash, including numbers and special characters. The entire pipe name string can be up to 256 characters long. Pipe names are not case-sensitive.
=> Use unique pipe for each project

.github/workflows/actions.yml, build.sc
On Windows, this should fix some issues where trying to access the coursier cache blocks indefinitely.
=> Update coursier to 2.0.16+73-gddc6d9cc9

contrib/playlib/src/mill/playlib/RouterModule.scala, contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/src/ScoverageReport.scala, scalajslib/src/ScalaJSModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/916
=> Deprecated toolsClasspath targets in favor of uniquely named new ones

build.sc, ci/mill-bootstrap.patch
This version is also released for mill 0.10.0-M2.
=> Version bump mill-vcs-version to 0.1.1-27-b3a696

build.sc, contrib/docker/src/DockerModule.scala, contrib/docker/test/resources/docker/src/Main.scala, contrib/docker/test/src/DockerModuleTest.scala, docs/antora/modules/ROOT/pages/Contrib_Modules.adoc
Hi!  This PR adds some more options (pretty much correspond 1-1 with Dockerfile instructions) that can be used in `DockerConfig`.  It's not totally comprehensive, but hopefully it catches the most common ones so there's less of a need to override `DockerConfig.build`.
I've added some tests which validate the new options by calling `docker build` - I could possibly replace these with tests against the generated `Dockerfile` strings if you think this is too much.
Thanks, I hope this is helpful.
=> Add More Config Options to Docker Contrib Module

contrib/scalapblib/src/ScalaPBModule.scala
The steps to reproduce the problem are as follows.
1. Parallel execution is enabled.
2. Targets that use `scalaPBUnpackProto` will be executed in parallel.
3. `FileSystemAlreadyExistsException` will be thrown.
This is because FileSystems does not allow multiple instances of the same URI to be created.
Therefore, I have changed the implementation to use ZipInputStream.
=> replace FileSystems with ZipInputStream for parallel execution

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, integration/test/resources/ammonite/build.sc, readme.adoc, scalajslib/src/ScalaJSModule.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/JavaModule.scala, scalalib/src/PublishModule.scala, scalalib/src/ScalaModule.scala, scalalib/test/src/HelloWorldTests.scala, scalanativelib/src/ScalaNativeModule.scala
Add `JavaModule.mandatoryIvyDeps` target to contain typical required ivy dependencies without the need to override and include `super.ivyDeps`.
This fixes #1487 and streamlines platform dependency handling for downstream modules like `ScalaModule`, `ScalaJSModule`, `ScalaNativeModule`. It's probably also useful for other modules which need to bring-in additional dependencies.
This PR includes and refines PR #1489.
=> Refined mandatory ivy libs handling

contrib/scalapblib/src/ScalaPBModule.scala
ScalaJS can be supported if gRPC is not used.
=> scalapblib: support scalajs by default

build.sc, docs/antora/modules/ROOT/nav.adoc, docs/antora/modules/ROOT/pages/Contrib_Plugins.adoc, docs/antora/modules/ROOT/pages/Extending_Mill.adoc, docs/antora/modules/ROOT/pages/Thirdparty_Plugins.adoc, main/src/main/MillIvyHook.scala
Support $MILL_BIN_PLATFORM placeholder and new $ivy.`g::a::v` syntax (borrowed from Scala JS/Native dependency notation)
Also updated Documentation and renamed two pages (Modules => Plugins).
With this PR I also try to establish the convention for mill plugins, to keep the mill binary platform version in the artrifact name as suffix: e.g. for Mill 0.9.x the suffix is `_mill0.9` and for Mill 0.10.x the suffix is `_mill0.10`.
Note: I plan to enforce binary compatibility in mill with the [mill-mima plugin](https://github.com/lolgab/mill-mima). This is come as separate PR.
=> Support more mill-specifics in $ivy-import

build.sc, ci/test-mill-bootstrap-0.sh, ci/test-mill-bootstrap-1.sh, ci/test-mill-dev.sh, ci/test-mill-release.sh, scalalib/src/ScalaModule.scala
We need to use the assembly instead of the script.
If we use the script, it will read the `.mill-version` file and run with the wrong version.
Fix an potential issue with non-existant paths in `ScalaModule.docJar` target.
=> Fixed bootstrap tests

mill
Mill milestone releases have an additional milestone part in the version, so that current version parser fails to get the right download URL (based on git tag).
This fixes #1503 and supersedes #1496.
FIx initially developed for millw: https://github.com/lefou/millw/pull/20
=> mill script: Support milestone versions in download URL

docs/antora/modules/ROOT/pages/Configuring_Mill.adoc
After fixing the documentation, we can also close #818
=> Removed incorrect example about excluding scala-lib from assembly

scalalib/src/JavaModule.scala
sys.env is probably incorrect, as it reflects the state at mill server start.
Fix https://github.com/com-lihaoyi/mill/issues/1554
Thanks to @lolgab who detected it (https://gitter.im/lihaoyi/mill?at=6188e730a41fd206992ed911).
=> Use T.env instead of sys.env to capture actual env values

build.sc, docs/antora/modules/ROOT/nav.adoc, docs/antora/modules/ROOT/pages/Contrib_Plugins.adoc, docs/antora/modules/ROOT/pages/Extending_Mill.adoc, docs/antora/modules/ROOT/pages/Thirdparty_Plugins.adoc, main/src/main/MillIvyHook.scala
Support $MILL_BIN_PLATFORM placeholder and new $ivy.`g::a::v` syntax (borrowed from Scala JS/Native dependency notation)
Also updated Documentation and renamed two pages (Modules => Plugins).
See pull request: #1485
=> Backported support for more mill-specifics in $ivy-import

docs/antora/modules/ROOT/pages/Contrib_Plugins.adoc, docs/antora/modules/ROOT/pages/Extending_Mill.adoc, main/src/MillMain.scala, main/src/main/MillIvyHook.scala, main/test/src/main/MillIvyHookTest.scala
With this PR applied, you can run targets from external modules from the command-line without touching the `build.sc`.
Example:
```
dev-mill --plugin ivy:de.tototec::de.tobiasroeser.mill.vcs.version_mill0.10.0-M2:0.1.2 show de.tobiasroeser.mill.vcs.version.VcsVersion/vcsState
```
This PR also add support for empty versions in $ivy-imports, which will get expanded to the exact mill version. This makes consuming mill contrib plugins even more easy.
Example: Generating Bloop Config without modifying the `build.sc`
```
mill --plugin ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.bloop.Bloop/install
```
See pull request: https://github.com/com-lihaoyi/mill/pull/1526
=> Backported --import cli option and support empty plugin versions

contrib/scoverage/src/ScoverageReport.scala, main/core/src/eval/Evaluator.scala, main/core/src/util/ParseArgs.scala, main/src/main/MainModule.scala, main/src/main/MainScopts.scala, main/src/main/Resolve.scala, main/src/main/RunScript.scala, main/test/src/util/ParseArgsTest.scala
This adds support to specify arbitrary targets and target arguments in one mill run.
__Motivation:__ Current mill only supports the selection of one or multiple targets followed by an argument list which is applied to all targets. Providing different arguments is currently not supported.
__Solution:__ We introduce a new separator `+` which separates the target arguments from the next target. To pass the `+` as argument to a target, masking with `\+` is supported.
Example:
```bash
mill __.compile + core.testCached + itest.test fastTest slowTests + __.publishLocal
```
This command will:
* run `compile` for all modules
* run `testCached` for module `core`
* run `itest.test` command with arguments ` fastTest` and `slowTests`
* run `publishLocal` for all modules
The limitation, that a command …
=> Backported support for a target separator (`+`) in the argument parser

scalalib/src/GenIdeaImpl.scala
PR fixes artifacts resolving from private repos for GenIdea command.
**Problem description**:
Coursier caches private repos under the `.../user@organization/...` path, for unix systems it translates to `.../user%40organization/...` path, and in turn `java.net.URL` translates it to `.../user%2540organization/...`, so when GenIdea constructs `buildDepsPaths` with OS independent `java.net.URL#getFile` call, double escaping breaks pathes for private repos.
**Fix description**:
OS idependent URL to file path conversion `java.net.URL#getFile` was replaced with OS dependent `java.nio.file.Paths#get(java.net.URI)`
=> Fix URL to file path conversion for GenIdea command

docs/antora/modules/ROOT/pages/Intro_to_Mill.adoc
Now that https://github.com/scalameta/metals/pull/3308 is merged Metals can actually detect (based on mill version) if the current workspace can use Mill as a BSP server even if there is no `.bsp/mill-bsp.json` created yet. If the users selects this, it will automatically create the `.bsp/mill-bsp.json` file and then connect to mill. This pr just clarifies this in the docs and mentions the "Switch Build Server" command they'll need to use.
Just to show an example, you can see here there is no bsp entry, but it's still shown as an option:
=> Add note about "Switch Build Server" in Metals.

scalalib/src/mill/scalalib/bsp/ScalaMetalsSupport.scala
For Scala 3 semanticdb is produced natively by the compiler behind the
`-Xsemanticdb` flag, so the plugin isn't necessary. This change ensures
the correct scalacOptions are set when using Scala 3 with
ScalaMetalsSupport.
=> Don't add semanticdb plugin for Scala 3.

scalalib/src/JavaModule.scala, scalalib/src/ScalaModule.scala, scalalib/src/ZincWorkerModule.scala, scalalib/src/mill/scalalib/OfflineSupportModule.scala
This should support more control in inheriting modules.
Also, fetch only essential dependencies in Java and Scala modules,
and keep the full fetch behind a `all` flag, which can be set as parameter.
This is a binary-incompatible change and I have no idea how to preserve compatibility.
Although I could keep the old signature and just forward to the newer,
Loading plugins that also inherit older `OfflineSupportModule`s seem to fail nevertheless.
Also I think Mill isn't checking for multiple commands with the same name, 
so I fear just because it works on my machine, it may still lead to some failures for others.
Only fix would be to invent a new name for the command (and deprecate the old).
As Mill 0.10.x is binary-incompatible anyways, I think this one should be ok.
Fix …
=> Let prepareOffline accept a `all` flag

build.sc, main/core/src/mill/define/Router.scala, main/src/mill/MillMain.scala
Also re-enabled the acyclic plugin, manually created a dependency cycle, and verified the error was reasonable:
```
[info] compiling 7 Scala sources to /Users/lihaoyi/Github/mill/out/main/util/compile/dest/classes ...
[error] Unwanted cyclic dependency
[info] /Users/lihaoyi/Github/mill/main/util/src/mill/util/Jvm.scala:6:11:
[info]   val y = EitherOps
[info]           ^
[info] symbol: object EitherOps
[info] /Users/lihaoyi/Github/mill/main/util/src/mill/util/EitherOps.scala:19:11:
[info]   val x = Jvm
[info]           ^
[info] symbol: object Jvm
[error] one error found
```
Probably not gonna fix all the dependency cycles and re-enable the acyclic enforcement in this PR, maybe in a follow up
=> Upgrade Ammonite to 2.5.0, fansi to 0.3.0, acyclic to 0.3.0

build.sc
Backport of https://github.com/com-lihaoyi/mill/pull/1620
=> Add a newer log4j2 dependency to avoid a critical vulnerability in zinc

main/client/src/mill/main/client/InputPumper.java, main/src/mill/main/MainRunner.scala, main/src/mill/main/MillServerMain.scala, main/src/mill/modules/Jvm.scala, scratch/foo/src/Foo.scala
This gets rid of our custom `watchAndWait` logic, standardizing it with what's upstream in Ammonite and allowing Mill to use the "Enter to re-run" functionality that was introduced in Ammonite 2.5.0.
While this worked for `./mill -i` out of the box, some work was necessary to get it working for Mill's client-server mode. This fixes the wiring for the socket's stdin to ensure it gets plumbed through, and works around the broken `available()` implementation in the `UnixDomainSocketInputStream` by proxying it via an `InputPumper`.
Tested manually:
```
lihaoyi mill$ ./mill -i dev.run scratch -w foo.run
[90/647] de.tobiasroeser.mill.vcs.version.VcsVersion.vcsState
[647/647] dev.run
[44/44] foo.run
false
Watching for changes to 4 paths... (Enter to re-run, Ctrl-C to exit)
<ENTER>
[44/44] …
```
=> Properly wire stdin in client-server mode and enable "Enter to Re-run" for mill -w

build.sc, ci/shared.sc, main/core/src/mill/define/Applicative.scala, main/core/src/mill/define/Task.scala, main/src/mill/main/ReplApplyHandler.scala, main/test/src/define/ApplicativeTests.scala, main/test/src/eval/EvaluationTests.scala
Fixes https://github.com/com-lihaoyi/mill/issues/910
Basically we avoid using the statically typed `zipMap` methods which cap out at 22, and instead use an untyped `zipMapLong` method that works with `IndexedSeq[T[Any]]` and `IndexedSeq[Any]`s. This could conceivably result in runtime errors if the macro has bugs, but assuming the macro is correct then it's as safe for the user as the existing macro is
By removing the old implementation, we are able to cut out a considerable amount of complexity from the codebase while still maintaining the existing semantics. Performance is probably better after, since we're just removing a layer of indirection: previously we ended up going through this dynamic `Seq[Any]` anyway, we just had a statically-typed facade wrapping it
Tested with a unit test, …
=> Tweak macro to allow more than 22 inputs

mill
These are both mostly trivial changes.
The first one makes it so that the script works on systems where Bash is not symlinked to /bin/sh like Alpine Linux and FreeBSD. I'm not 100% sure what that line is trying to do. I read the commit (a41c632291b017b47e2c40979ffc49b279442f3c) that added it and I couldn't make sense of it. Either way, `BASH_SOURCE == BASH_SOURCE[0]` which is equal to `$0` when the script isn't getting sourced. The script is meant to be run, not sourced, so the change should be fine.
The second change just quotes the path in case someone's `XDG_CACHE_HOME` has a space in it. And it's good for consistency.
=> mill script is POSIX-compliant and has quoted paths.

contrib/scalapblib/src/ScalaPBWorker.scala
fixes related issue #1625 
It was easy to resolve the missing package context file by passing all files that need to be generated to protoc at once.
This is similar how sbt and gradle use protoc to compile the sources.
=> #1625 fix transformer not picked up

docs/antora/modules/ROOT/pages/Configuring_Mill.adoc, docs/antora/modules/ROOT/pages/Modules.adoc, main/core/src/mill/define/Ctx.scala, main/core/src/mill/eval/Evaluator.scala, main/test/src/define/BasePathTests.scala, main/test/src/define/CacherTests.scala, main/test/src/eval/EvaluationTests.scala
To be more consistent with the changes from PR
https://github.com/com-lihaoyi/mill/pull/1588
which re-layouted the log, meta, and dest path for targets.
This change touches the path of overriden target results.
It replaces the `../target/overriden/..` part with
`../target.overriden/..`.
There is a catch though, to make this work I had to remove one
`require` assertion, which guarded the presence of dots (`.`) in
labels. TBH, I previously stubled upon this require
and also added the FIXME comment to it, as it is unclear why it
even exists. Probably, because labels with dots can't be properly
parsed when given on cli. More details and hisory can be found in
issue https://github.com/com-lihaoyi/mill/issues/820.
Fix #820.
Review by @lihaoyi.
=> Changed out path for overridden targets for consistency

main/src/mill/modules/Jvm.scala
I noticed that sometimes when I have a bunch of zombie `MillServerMain` processes laying around, their `jstack` indicates that the only non-daemon threads are as follows:
```
"Thread-5" #32 prio=5 os_prio=31 cpu=193.46ms elapsed=4037.87s tid=0x00007fb64eba7000 nid=0x8303 in Object.wait()  [0x0000700002e98000]
java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(java.base@11.0.7/Native Method)
- waiting on <no object reference available>
at java.io.PipedInputStream.read(java.base@11.0.7/PipedInputStream.java:326)
- waiting to re-lock in wait() <0x0000000701a001c0> (a java.io.PipedInputStream)
at java.io.PipedInputStream.read(java.base@11.0.7/PipedInputStream.java:377)
- waiting to re-lock in wait() <0x0000000701a001c0> (a java.io.PipedInputStream)
at …
```
=> Set Jvm.spawnSubprocess input pumper thread to daemon mode.

main/client/src/mill/main/client/InputPumper.java, main/client/src/mill/main/client/MillClientMain.java, main/src/mill/main/MillServerMain.scala, main/src/mill/modules/Jvm.scala
The basic issue here is that we were not properly closing the input streams generated by spawnSubprocess when `-i` is not passed, in particular the one that pumps input from the proxied stdin to the subprocess. Thus it would survive long past the lifetime of the subprocess, try to pump the proxied stdin into the subprocess's closed stdin, and fail while consuming bytes from the proxied stdin so that other consumers couldn't get at it.
The fix is twofold:
1. Pass in `checkAvailable = true` for the proxied-stdin-to-subprocess-inputstream pumper so it doesn't block on trying to read from stdin, and instead polls regularly at 2ms intervals
2. Pass a `java.util.function.BooleanSupplier runningCheck` into the pumper that can be used to abort its polling at any point, and configure it so it …
=> Make -w and enter-to-rerun work with subprocess spawning tasks

scalalib/src/PublishModule.scala, scalalib/src/publish/Pom.scala, scalalib/src/publish/settings.scala, scalalib/test/src/publish/IvyTests.scala, scalalib/test/src/publish/PomTests.scala
Also added a packaging attribute to PomSettings.
=> Added support to add properties to generated Maven pom

build.sc
Fixes #1664
Fix error with NodeJS 17
Tested manually with NodeJS 17 and it doesn't fail.
=> Bump scalajs-env-nodejs to 1.2.1

build.sc, scalanativelib/test/src/HelloNativeWorldTests.scala, scalanativelib/worker/0.4/src/ScalaNativeWorkerImpl.scala
Workers in Mill work (pun not intended) by compiling to a base version and then substitute the classloader with the dependencies from the project they are compiling.
Before this PR, the Scala Native worker dependency was a uberjar created with `assembly` so it was depending on the Scala Native version defined in Mill's `build.sc`.
Now worker contains only the Worker classes and all the other dependencies are injected by Mill using the `scalaNativeVersion` from the `ScalaNativeModule` it is compiling.
=> Fix Scala Native for versions `> 0.4.2`

scalajslib/api/src/ScalaJSWorkerApi.scala, scalajslib/src/ScalaJSModule.scala, scalajslib/src/ScalaJSWorkerApi.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
`ScalaJSModule` currently supports the `useECMAScript2015` settings.
Nowadays Scala.js offers support for multiple `ESVersion`.
In the official Sbt plugin they are set inside an object called `ESFeatures` that contains other settings.
This PR tries to mimic the Scala.js API.
It is a breaking change, since overriding the old `useECMAScript2015` doesn't have any effect anymore.
Since we can't derive `ESFeatures` from `useECMAScript2015`, I can't use the same deprecation mechanism as `testFrameworks`. What I did instead is to define a private boolean `var` in ScalaJSModule called `overriddenUseECMAScript2015` that is first set to `true`. It is then set to `false` by the default implementation of `useECMAScript2015` which calls back the new `esFeatures`. Before `fastOpt` and `fullOpt` I call …
=> Support ESFeatures in Scala.js

build.sc, ci/upload.sc
Removed support for shortening URLs. `git.io` no longer accepts new URLs.
=> Fix GitHub asset upload

docs/antora/modules/ROOT/pages/Intro_to_Mill.adoc, main/client/src/mill/main/client/MillClientMain.java
Resolves #1682 by allowing mill to be configured to work with incubator modules and other uncommon builds.
=> Accepts all args in .mill-jvm-opts now

build.sc
- Introduce MillInternalModule in build
- Make workers extend MillInternalModule
Workers are internal components that shouldn't give any binary compatibility guaranties.
This removes Mima from them so we are free to change them whenever we want.
=> Skip Mima checks in worker modules

bsp/src/mill/bsp/MillScalaBuildServer.scala, build.sc, contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, scalalib/src/ScalaModule.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
We no longer generate an enablement option for each transitively resolved plugin jar, but instead, only generated one `-Xplugin:` option for each explicitly given plugin. This will fix previously seen warnings for the scalac compiler.
I took the opportunity to clean things up on the go.
I removed the handling of `-Xplugin:` from the ZincWorker into the ScalaModule.
This fixes the issue that both the BSP server implementation and the Bloop Config exporter needed to handle this on their own.
Now, this is handled in the IMHO right place, is properly shared and still overrideable by the user if the situation calls for it.
I recognized, that we don't support scalac plugin dependencies from in-project modules at the moment, but this can be added later if needed. Previously, it was enough to add …
=> Explicit handling of scalac plugins and related enablement options

scalalib/src/PublishModule.scala
It seems the default argument for gpgArgs in publish cannot ever resolve to anything but empty. So, if the argument is an empty Seq, replace it with the default gpgArgs. 
This allows projects like mine to publish easily.
=> Fixes the default args for publish

build.sc, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala, scalanativelib/src/ScalaNativeModule.scala, scalanativelib/src/ScalaNativeWorkerApi.scala, scalanativelib/test/src/HelloNativeWorldTests.scala, scalanativelib/worker/0.4/src/ScalaNativeWorkerImpl.scala
- Consistency with `ScalaJSModule`
- Not resolving Scala 2.12 if not needed (imagining a Scala 2.13 only project) could make the build faster
- Not loading a new classloader from scratch and populating it with a brand new scala-library for Scala 2.12 could be faster (I have no data to prove this theory)
=> Make ScalaNativeModule use Scala 2.13 toolchain when available

scalajslib/src/ScalaJSModule.scala, scalajslib/test/resources/top-level-exports/src/App.scala, scalajslib/test/src/TopLevelExportsTests.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
This doesn't change any API but makes the Scala.js emit top level
exports.
Thinking about APIs is hard, so I tried to make the process of support the new `faskLinkJS` a two step approach. For now I migrated only the implementation to the new api using `DirectoryOutputPath` (in Scala. js 1.3+ only) but maintaed the `out.js` output path. It doesn't fail anymore if you try to export a module from the Scala.js code. At the same time it is not optimal since the ausiliary files are not returned by the `fastOpt` task, so are not considered for the tasks cache purposes.
=> Link Scala.js using Directory path when available

scalalib/src/dependency/versions/Version.scala, scalalib/test/src/dependency/versions/VersionTests.scala
This is in preparation to use Version in various module to make version checks without reinventing regexes over and over.
=> Fixed Version handling of short versions and made API public

scalalib/src/JavaModule.scala, scalanativelib/src/ScalaNativeModule.scala, scalanativelib/test/src/ExclusionsTests.scala
Port of the workaround Scala Native is doing for Sbt in this PR: https://github.com/scala-native/scala-native/pull/2553
=> Fix withDottyCompat in Scala Native

bsp/src/mill/bsp/BSP.scala, main/core/src/mill/eval/Evaluator.scala, main/src/mill/main/EvaluatorState.scala, main/src/mill/main/MainModule.scala, main/src/mill/main/ReplApplyHandler.scala, main/src/mill/main/RunScript.scala, main/test/src/util/TestEvaluator.scala
Extracted from https://github.com/com-lihaoyi/mill/pull/1663 to allow introducing new fields in the Evaluator and EvaluatorState classes without breaking the binary compatibility.
=> Make Evaluator and EvaluatorState normal classes

main/core/src/mill/eval/Evaluator.scala, main/src/mill/main/RunScript.scala
- Remove extra comma in Evaluator toString
=> Follow up refactor of importTree in RunScript

build.sc
Compared to `2.0.16-200-ge888c6dea`, this version fixes issues with snapshot artifacts, and also adds new APIs (`ArchiveCache`, that can be useful from Mill tasks).
=> Update coursier to 2.1.0-M2

main/src/mill/modules/Assembly.scala, main/src/mill/modules/Jvm.scala, scalalib/test/resources/hello-world-multi/core/resources/without-new-line.conf, scalalib/test/resources/hello-world-multi/model/resources/without-new-line.conf, scalalib/test/src/HelloWorldTests.scala
PR adds separator to AppendPattern assembly rule.
Implementation and motivation are identical to `mill.modules.Assembly.Rule.Append#separator`
=> Add separator to AppendPattern assembly rule

build.sc
Follow up of https://github.com/com-lihaoyi/mill/pull/1752. Just realized it should have been `2.1.0-M5` rather than `2.1.0-M2` 😅
=> Update coursier to 2.1.0-M5

build.sc, scalalib/src/scalafmt/ScalafmtModule.scala, scalalib/src/scalafmt/ScalafmtWorker.scala, scalalib/test/src/scalafmt/ScalafmtTests.scala
Removed deprecated API calls.
Version bump scalafmt-dynamic to 3.4.3.
Removed support to read a `default.scalafmt.conf` from classpath.
=> Support newer scalafmt versions which require a config file

ci/publish-local.sh, ci/test-mill-bootstrap-0.sh, ci/test-mill-bootstrap-1.sh, ci/test-mill-dev.sh, ci/test-mill-release.sh, main/test/src/util/ScriptTestSuite.scala, readme.adoc
Instead, we now create that file locally under `target/mill-release`.
Also, it is no longer hard coded into the (forked) test suite, but instead
read from the `MILL_TEST_RELEASE` system environment variable.
=> Do not clutter user home directory with `mill-release` binary

main/src/mill/modules/Jvm.scala, scalalib/src/CoursierModule.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/JavaModule.scala, scalalib/src/Lib.scala, scalalib/src/dependency/versions/VersionsFinder.scala
Currently loading a Coursier plugin is not possible, because the `ClassLoaders` that are used by Mill's Coursier cannot be changed. I ran into this when trying to use [my plugin](https://github.com/ActionIQ/coursier-s3) which adds support for a [new protocol](https://get-coursier.io/docs/extra#extra-protocols). Loading via `$ivy.` or anything else doesn't work because Mill uses the `default` Coursier [cache](https://github.com/com-lihaoyi/mill/blob/246e92411c874ae8a33655dec7937af8c4041509/main/src/mill/modules/Jvm.scala#L571-L570)
This PR adds a hook to allow altering the `FileCache` used. With this, I can put the following in my build module:
```
override def cacheCustomizer: Task[Option[FileCache[coursier.util.Task] => FileCache[coursier.util.Task]]] = T.task {
Some( (fc: …
```
=> Support Coursier plugins via customizing FileCache used (with classloaders)

docs/antora/modules/ROOT/pages/Intro_to_Mill.adoc, main/src/mill/main/MainModule.scala, main/src/mill/main/MainRunner.scala, main/src/mill/main/RunScript.scala, main/test/src/main/MainModuleTests.scala
Currently, show invoked with more than one target returns invalid JSON, as it is only concatenating multiple JSON values.
Example:
```
$ mill show __.artifactMetdata
[1/1] show
{
"group": "com.acme",
"id": "pkg1",
"version": "1.0.0"
}
{
"group": "com.acme",
"id": "pkg2",
"version": "1.0.0"
}
```
This PR makes its output valid JSON by outputting a proper JSON array when there is more than one task result. 
Example: 
```
$ mill show __.artifactMetdata
[1/1] show
[
{
"group": "com.acme",
"id": "pkg1",
"version": "1.0.0"
},
{
"group": "com.acme",
"id": "pkg2",
"version": "1.0.0"
}
]
```
Also it introduces a new `showNamed` command, which puts each task result in a JSON dictionary. The keys are reflecting the task names. 
Example:
```
mill showNamed __.artifactMetadata
[1/1] show
{ …
```
=> Improved `show` output to be valid JSON and added `showNamed`

docs/antora/modules/ROOT/pages/Tasks.adoc, main/core/src/mill/eval/Evaluator.scala, main/test/src/eval/TaskTests.scala, main/test/src/util/TestEvaluator.scala
This PR implements this idea:
*  https://github.com/com-lihaoyi/mill/discussions/1780
The idea is, to automatically call the `java.lang.AutoCloseable.close()` method on workers than gets dropped, to provide a chance to clean up and free resources.
I also applied some minor improvements on the go. E.g. synchronized access to `Evaluator.workerCache` now synchronizes on the `workerCache`, not on the `Evaluator` instance.
I also added tests cases to test `AutoCloseable` workers, sequentially and parallel.
Updated documentation.
=> Implemented `AutoCloseable` Workers

bsp/test/resources/bsp-install/build.sc, bsp/test/src/BspInstallTests.scala, main/test/src/util/ScriptTestSuite.scala, scalalib/src/JavaModule.scala, scalalib/src/ScalaModule.scala, scalalib/test/src/mill/scalalib/bsp/BspModuleTests.scala
Issue reported in #1792 by @abernardi597.
=> Fix incorrect module traversal for BSP classpath retrieval

bsp/src/mill/bsp/MillBuildServer.scala, bsp/test/resources/bsp-modules/build.sc, bsp/test/resources/bsp-modules/proj1/build.sc, bsp/test/resources/bsp-modules/proj2/build.sc, bsp/test/resources/bsp-modules/proj3/build.sc, bsp/test/src/BspModulesTests.scala, contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, scalalib/src/internal/ModuleUtils.scala, scalalib/src/mill/scalalib/internal/ModuleUtils.scala
Fixes #1800 
Extracted the method used by `BloopImpl` to get the transitive modules from `rootModule` in a `internal` module and make BSP use it as well.
=> Add transitive moduleDeps to BSP evaluated modules

main/src/mill/main/MainModule.scala
We now separate the output for multiple targets with a blank line.
Before:
```
± mill inspect main.compile main.compileClasspath
Compiling /home/lefou/work/opensource/mill/build.sc
[1/1] inspect 
main.compile(ScalaModule.scala:195)
Compiles the current module to generate compiled classfiles/bytecode
Inputs:
main.scalaVersion
main.upstreamCompileOutput
main.allSourceFiles
main.compileClasspath
main.javacOptions
main.scalaOrganization
main.allScalacOptions
main.scalaCompilerClasspath
main.scalacPluginClasspath
main.compileClasspath(JavaModule.scala:306)
All classfiles and resources from upstream modules and dependencies
necessary to compile this module
Inputs:
main.transitiveLocalClasspath
main.unmanagedClasspath
main.resolvedIvyDeps
```
After:
```
± dev-mill -i inspect main.compile …
```
=> Nicer format of inspect for multiple targets

.github/workflows/actions.yml, integration/test/resources/invalidation/-#+&%.sc, integration/test/resources/invalidation/build.sc, integration/test/src/ScriptsInvalidationTests.scala, main/core/src/mill/internal/AmmoniteUtils.scala, main/core/test/src/mill/internal/AmmoniteUtilsTests.scala
Fixes #1798
The idea of `normalizeAmmoniteImportPath` is to have a single entry per file.
An ammonite file can have multiple classes inside its object.
The previous version was deduplicating all the classes by removing everything starting from the first `$`.
`ammonite.$file.build$module$` would become `ammonite.$file.build`
When a file contains symbols this doesn't work since  `` import $file.`with-symbols` `` generates  `ammonite.$file.with$minussymbols` which the old algorithm would change to `ammonite.$file.with`, which is wrong.
The new algorithm skips the special symbols mappings (`$minus`, `$plus`, etc.) from this removal.
=> Handle Ammonite build scripts with symbols

bsp/src/mill/bsp/MillJavaBuildServer.scala, bsp/src/mill/bsp/MillScalaBuildServer.scala, build.sc, contrib/scoverage/test/src/HelloWorldTests.scala, main/core/src/mill/eval/EvaluatorPaths.scala, scalalib/src/JavaModule.scala, scalalib/src/ScalaModule.scala, scalalib/src/mill/scalalib/UnresolvedPath.scala, scalalib/test/src/mill/scalalib/bsp/BspModuleTests.scala
This should improve (fix) performance and OOM issues with large multi module projects where modules depend heavily on each other.
`bspCompileClassesPath` and `bspCompileClasspath` are now Targets instead of Tasks. This makes them cacheable and also easier to override in derived modules. I also changed the logic in some `transitiveXXX` targets from a recursive call to all dependencies to just calling the non-recursive target on a transitive modules list. This should mitigate OOM issue as reported here: https://github.com/com-lihaoyi/mill/issues/1792#issuecomment-1078815626
Fix https://github.com/com-lihaoyi/mill/issues/1792
Supersedes https://github.com/com-lihaoyi/mill/pull/1794
=> Reworked some BSP module inspection tasks

scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea-extended-hello-world/idea/mill_modules/helloworld.test.iml, scalalib/test/resources/gen-idea-hello-world/idea/mill_modules/helloworld.test.iml
PR fixes dependency priority for GenIdea command.
**Problem description:**
When multiple dependencies have a class with the same name, Mill takes first one from the classpath, as well as Intellij takes first one from the iml file. If some dependencies are modules, Mill put them higher in the classpath, so module classes always take precedence over libraries. But GenIdea put modules after the libraries and therefore Intellij resolves different than Mill class versions. Example of generated iml file:
```
...
<orderEntry type="inheritedJdk"/>
<orderEntry type="sourceFolder" forTests="false"/>
<orderEntry type="library" name="..." level="project"/>
...
<orderEntry type="module" module-name="..." exported=""/>
...
```
**Fix description:**
I swapped libraries and modules in the iml file, so …
=> Put modules before libraries in Intellij iml files

bsp/src/mill/bsp/MillBuildServer.scala, bsp/src/mill/bsp/MillScalaBuildServer.scala, build.sc
I've added `[skip ci]` because for now I only want to see what do you folks think about this PR.
This PR will stay as a draft until changes in `bsp4j` are merged, for now I've used locally published `bsp4j` version.
It is an implementation of the BSP proposal which is described [here](https://github.com/build-server-protocol/build-server-protocol/issues/296#issuecomment-1041525725). This proposal adds an optional framework field to the returned class.
There's already implementation for [bloop](https://github.com/scalacenter/bloop/pull/1695).
=> feat: add framework name to the test classes BSP request

bsp/src/mill/bsp/BSP.scala, bsp/src/mill/bsp/MillBuildServer.scala, bsp/src/mill/bsp/MillJvmBuildServer.scala
Add support for [BSP JVM Extension](https://build-server-protocol.github.io/docs/extensions/jvm.html) methods `buildTarget/jvmTestEnvironment` and `buildTarget/jvmRunEnvironment`. This will correctly set the classpath for execution and testing from IntelliJ IDEA.
Without this addition, IntelliJ IDEA determines the classpath when executing and testing in a BSP Imported project, but the order of precedence when multiple version Jars exist seems to be different than in Mill. Therefore, binary incompatibility error may occur at runtime.
With this addition, IntelliJ IDEA will add the classpath resolved by Mill to the beginning of the classpath, which is the same behavior as Mill.
* https://github.com/JetBrains/intellij-scala/blob/a3f19b5967c87d0e9f3ca49b2278ddf709dd798b/bsp/src/org/jetbrains/bs …
=> Added BSP JVM Extension support

contrib/scoverage/test/src/HelloWorldTests.scala, integration/thirdparty/local/resources/ammonite/build.sc, integration/thirdparty/local/src/AcyclicTests.scala, integration/thirdparty/local/src/AmmoniteTests.scala, integration/thirdparty/local/src/JawnTests.scala, integration/thirdparty/local/src/UpickleTests.scala, main/test/src/util/TestUtil.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/test/src/MultiModuleTests.scala, scalalib/test/src/HelloWorldTests.scala, scalanativelib/test/src/HelloNativeWorldTests.scala
Reviewed and removed some disablements of tests under Java 9+.
Also added some thread context classloader tweak to integration test in the hope it fixes the issues in CI. As I could not reproduce, these fixes are just wild guesses, as Ammonite tries to load the `amm-dependencies.txt` file via the thread context classloader and this failed sometimes in CI.
=> Reviewed tests under Java 9

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
At the moment, mill generates bloop configurations without setting the runtime classpath of Java modules. This makes bloop fall back to `project.classpath` which corresponds with required compile-time classpath. It makes sense to put stuff like slf4j-adapters, postgres-drivers and such—dependencies that are only required during runtime—in the JVM-configuration.
The following discussion on the bloop issue tracker highlights the requirements and the accepted solution: https://github.com/scalacenter/bloop/issues/1233
https://github.com/scalacenter/bloop/pull/1244
This pull-request simply outputs the `runClasspath` target to `BloopConfig.Platform.Jvm#classpath`. I'm not a 100 % sure this is the correct approach, but it corresponds to what gets put on the classpath when having mill run a …
=> make bloop aware of runtime dependencies

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/src/mill/scalajslib/ScalaJSWorkerApi.scala, scalajslib/src/mill/scalajslib/api/Report.scala, scalajslib/src/mill/scalajslib/internal/ScalaJSUtils.scala, scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/test/src/SmallModulesForTests.scala, scalajslib/test/src/TopLevelExportsTests.scala, scalajslib/worker-api/src/ScalaJSWorkerApi.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
Report doesn't contain all linked js files but only the public
ones. Using that as Target return type breaks the cache invalidation.
This adds the dest folder PathRef as a safer cache invalidation input.
It changes jsFile to jsFileName as in official Scala.js API
=> Add dest to report and change jsFile to jsFileName

build.sc
Turns out, it causes instable caches when switching mill server mode, which results in perceived full cache invalidations.
This reverts pull request: https://github.com/com-lihaoyi/mill/pull/1854
Reported by @lolgab, see https://gitter.im/lihaoyi/mill?at=62741f02949ae94006917596
=> Downgrade upickle to 1.6.0

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/src/mill/scalajslib/ScalaJSWorkerApi.scala, scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala, scalajslib/worker-api/src/ScalaJSWorkerApi.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
Introduce `scalaJSOptimizer: T[Boolean] = true` target
to make it configurable.
Set the default to `true` since it is what ScalaJS suggests and
uses in the official Sbt plugin
=> Enable ScalaJS optimizer by default

main/client/src/mill/main/client/MillClientMain.java
Fixes #1795  
In the stacktrace of that issue you can see that `MillServerMain` was (wrongly) used.
=> Fix universal-main args handling

build.sc
Fixes #1652
1. use graphviz-java-all-j2v8 instead of graphviz-java (now as transitive dependency)
Following instructions from graphviz-java [docs](https://github.com/nidi3/graphviz-java#maven
) they say:
> gradle does not support this way of defining a dependency
> Instead of graphviz-java there are two alternative dependencies that can be used:
> - graphviz-java-all-j2v8 additionally contains dependencies to all J2V8 platforms. So the same application can run on Linux, Mac OS X and Windows.
> - graphviz-java-min-deps contains only dependencies that are absolutely necessary. All other dependencies are marked as optional and must added manually. See the [pom.xml](https://github.com/nidi3/graphviz-java/blob/master/graphviz-java-min-deps/pom.xml#L64-L90) for details.
2. downgrade jgrapht …
=> Fix visualize command

bsp/src/mill/bsp/MillBuildServer.scala, scalalib/src/mill/scalalib/bsp/BspModule.scala
* `sub` is interpreted as a package.
* `Source Folders` is `.`.
This creates a problem where IntelliJ may interpret `root.Foo` class as  `sub.foo.src.root.Foo` class.
* `sub` is interpreted as a directory.
* `Source Folders` is `.bsp`.
Everything works well. `build.sc` can also be edited correctly.
If IntelliJ supports [per-file source configuration](https://youtrack.jetbrains.com/issue/SCL-19717), this change would not be necessary.
=> BSP: fix mill-build module interpretation in IntelliJ IDEA

build.sc
Seems like newer version of `lunr-extension` broke the search.  
The version is now fixed to `v1.0.0-alpha.6` (at least for now), which we know works properly.
=> Fix lunr-extension version

build.sc
Second attempt at landing https://github.com/com-lihaoyi/mill/pull/1854. Let's see if keeping the uPickle version consistent between Ammonite and Mill helps
I tried to repro the original problem using the locally-built `target/mill-release` binary, and am able to reproduce the problem (unwanted re-compilation of build.sc) without the Ammonite update, and am unable to reproduce the problem with the Ammonite update. I don't know what the problem is, but I can only conclude that the Ammonite update fixed it.
@lolgab could you help try this out see if it works properly for you too?
=> Bump uPickle to 2.0.0 together with Ammonite 2.5.4

scalanativelib/api/src/mill/scalanativelib/api/ScalaNativeWorkerApi.java, scalanativelib/src/ScalaNativeModule.scala, scalanativelib/worker/0.4/src/ScalaNativeWorkerImpl.scala
This adds support for `nativeEmbedResources` (available in Scala Native 0.4.4+)
Since we support Scala Native 0.4.0+ this uses the same mechanism `scalajslib` uses to execute methods only on versions a certain feature is available.
=> Support Scala Native `nativeEmbedResources`

scalalib/test/src/HelloJavaTests.scala
We saw CI failures lately in this specific test.
As test cases are picked up from class files which order may depend on the used filesystem and other factors like creation time, inode number, ..., we better always try to avoid any ordering assumptions in tests.
=> Fixed ordering-sensitive test

scalalib/worker/src/mill/scalalib/worker/MockedLookup.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
Fix #1901 
Sbt use a `MappedFileConverter`, it will converter `jdk` internal classes like `/module/java.base/java.lang.String` associated with a dummpy `rt.jar`.
https://github.com/sbt/zinc/blob/57d03412abe3810be5762a8c8e8c55cbf622ed03/internal/zinc-core/src/main/scala/sbt/internal/inc/MappedVirtualFile.scala#L56
```scala
def toVirtualFile(path: Path): VirtualFile = {
rootPaths2.find { case (_, rootPath) => path.startsWith(rootPath) } match {
case Some((key, rootPath)) =>
MappedVirtualFile(s"$${$key}/${rootPath.relativize(path)}".replace('\\', '/'), rootPaths)
case _ =>
def isCtSym =
path.getFileSystem
.provider()
.getScheme == "jar" && path.getFileSystem.toString.endsWith("ct.sym")
def isJrt = path.getFileSystem.provider().getScheme == "jrt"
if (isJrt || path.getFileName.toString == …
```
=> fix zinc binary dependencies

build.sc, integration/forked-server/src/forked-server-tests.scala, integration/forked/src/forked-tests.scala, integration/local/resources/mill-jvm-opts/.mill-jvm-opts, integration/local/resources/mill-jvm-opts/build.sc, integration/local/src/MillJvmOptsTests.scala, main/client/src/mill/main/client/MillEnv.java
* Fixes #1908 
* This also completes PR #1683, which forgot to also change the logic in the start script.
* Added a test case
=> Fixed reading of .mill-jvm-opts file

docs/antora/modules/ROOT/pages/Common_Project_Layouts.adoc
Improve Scala.js module config docs adding test and dependency descriptions.
=> Improve Scala.js module config docs

docs/antora/modules/ROOT/pages/Common_Project_Layouts.adoc
As the docs say, if you created your sontaype account any time after Feb
2021 you'll need to chance your URIs in order to correctly publish.
=> docs: add in a note about s01 for new users

build.sc, contrib/flyway/src/ConsoleLog.scala
This was one of the version updates scala steward has missed for a while.
I guess this is because scala steward couldn't add the required NOTICE log code change.
=> update: flyway-core 8.0.2 -> 8.5.13, requires NOTICE log level

build.sc
I can't guess why scala steward missed this update.
In my [mega-dep-update-PR](https://github.com/com-lihaoyi/mill/pull/1933), this dependency only needed a change in build.sc
=> update: scalafmt-dynamic 3.4.3 -> 3.5.8

scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
`SoftReference`s are [better suited to implement memory-sensitive caches](https://docs.oracle.com/javase/8/docs/api/java/lang/ref/SoftReference.html).
Suggested in a code review in bloop: https://github.com/scalacenter/bloop/pull/1761#discussion_r925512643
=> Use SoftReference instead of WeakReference for caches

integration/local/resources/mill-jvm-opts/.mill-jvm-opts, integration/local/resources/mill-jvm-opts/build.sc, integration/local/src/IntegrationTestSuite.scala
I've been having problems with my .mill-jvm-opts file not being applied while in client-server mode.  I was doing some testing and realized the integration tests were always using `--no-server`.
I found that the clientServer parameter was not being passed down.  This is a small one line PR to fix that.
Regarding my original issue, it doesn't seem to happen as of c81ac64ee91b8d85074ff373df1c01f8bd91b06e
=> Pass clientServer parameter to the IntegrationTestSuite constructor

build.sc, main/test/src/eval/ModuleTests.scala, main/test/src/util/TestEvaluator.scala, main/test/src/util/TestUtil.scala, main/testkit/src/testkit/MillTestkit.scala, main/testkit/test/src/testkit/MillTestKitSuite.scala, main/testutil/src/testutil/MillTests.scala
@lefou opening this as a draft to get an early opinion (if you're against it, it's absolutely fine and I'll just publish it as a third party library from a repo I control) 
the TestEvaluator that the mill codebase uses to test itself is extremely useful for testing some mill modules with reasonably lightweight setup. I have copied it over in some projects a few times now, including [today](https://github.com/indoorvivants/sbt-vcpkg/pull/9#discussion_r890130257). I'd love to have it as a library, as testing modules this way, though not as thorough as a bonafide integration test, is absolutely neat. 
Making it available to downstream libraries and plugins could help expand the ecosystem, in particular when such plugins are built with SBT (which is the harsh reality of the status quo, and …
=> Add a testkit module to hold the TestEvaluator

docs/antora/modules/ROOT/pages/Common_Project_Layouts.adoc
As stated on https://github.com/com-lihaoyi/mill/blob/fbedc99d436f608cbfbc3609c1834ac7b3ea2a50/readme.adoc#0104---2022-05-06, `fastOpt` and `fullOpt` have been deprecated in favor of `fastLinkJS` and `fullLinkJS`.
=> [Docs] Targets fastOpt and fullOpt have been deprecated in Mill 0.10.4

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
When the bloop module is computing the sources references for the project it uses the `moduleSourceMap` target. This puts paths into the map using `m.millModuleSegments.render` however when accessing the map to build the bloop configuration it uses `name(module)`. These differ for foreign modules resulting in the sources for foreign modules being omitted.
=> bloop: use the same naming scheme for adding to and accessing moduleSourceMap

scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
Currently if you want to pass in some `javacOptions` that start with
`-J` the Java compiler will reject them since the local java compiler
won't accept `-J` flags. You can see this in an example on JDK 17 where
you need some `-J` flags to get the java semantidb compiler plugin to
work:
```scala
object javaModule extends JavaModule {
def ivyDeps = Agg(ivy"com.sourcegraph:semanticdb-javac:0.8.2")
def javacOptions = Seq(
"-J--add-exports",
"-Jjdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
"-J--add-exports",
"-Jjdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
"-J--add-exports",
"-Jjdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED",
"-J--add-exports",
"-Jjdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
"-J--add-exports",
"-Jjdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED", …
```
=> feat: allow for a non-local Java Compiler to be used

docs/antora/modules/ROOT/pages/Configuring_Mill.adoc, scalalib/src/ScalaModule.scala
I recently wanted to play around with the static site generator that
comes with Scaladoc for Scala 3, but the upstream documentation is very
sbt-focused and a bit confusing. I was also pretty unfamiliar with the
various doc-related tasks in Mill and since there wasn't any
documentation on it, I've included some basic documentation and also an
example of how to generate a full site with Scala 3.
=> docs: add some documentation about generating a doc jar

docs/antora/modules/ROOT/pages/Intro_to_Mill.adoc
Currently there is only [one template](https://github.com/sake92/mill-scala-hello.g8). 😄  
But I hope we will soon have more of them.
I made a PR for Play Framework seed https://github.com/playframework/play-scala-seed.g8/pull/164
=> Add basic docs for 'init' command

scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
* Follow up to https://github.com/com-lihaoyi/mill/pull/1988
=> Clean the java-compiler cache when closing the worker

bsp/src/mill/bsp/BSP.scala, bsp/src/mill/bsp/MillBspLogger.scala, bsp/test/src/BspInstallDebugTests.scala, main/api/src/mill/api/Logger.scala, main/core/src/mill/eval/Evaluator.scala
This means, we can use the effective value of `Log.debugEnabled` in BSP.
This also means, we only need to send debug messages to the BSP client, when debug is enabled.
* See also PR #2006
=> BSP: Forward --debug option to BSP server

bsp/src/mill/bsp/MillBspLogger.scala
This pr makes 2 changes. First, debug messages shouldn't go through
`build/showMessage`. Taken from the BSP [docs](https://build-server-protocol.github.io/docs/specification.html#show-message):
> The show message notification is sent from a server to a client to ask
> the client to display a particular message in the user interface.
From my experience these are reserved for helpful messages that the user
should know about. So I changed this to `build/logMessage` which seems
more appropriate:
> The log message notification is sent from the server to the client to
> ask the client to log a particular message.
I also then just went ahead and removed this because even if we keep it
as log message, this will get logged all the time, and I don't think
it's that useful to log unless you think it …
=> BSP: use build/logMessage for logging

build.sc, contrib/scoverage/api/src/ScoverageReportWorkerApi.scala, contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/src/ScoverageReport.scala, contrib/scoverage/test/src/HelloWorldTests.scala, contrib/scoverage/worker2/src/ScoverageReportWorkerImpl.scala
This is the first iteration to support Scoverage 2.x in projects which already work with Scoverage 1.x
It does not specifically handle Scala 3.x, which already comes with a scoverage plugin.
This work is heavily based on #1547 by @ckipp01 .
Tasks:
Potential follow-up tasks:
* Specifically handle Scala 3 modules, as Scala 3.2 already comes with scoverage compiler support, but older Scala 3 versions are not supported at all.
* see https://github.com/lampepfl/dotty/pull/13880
=> Support for Scoverage 2.x

scalanativelib/src/ScalaNativeModule.scala, scalanativelib/test/resources/hello-native-world/src/Main.scala, scalanativelib/test/src/HelloNativeWorldTests.scala
Scala Native depends on the scala3-library `3.1.3`.
To work on Scala 3.2 you need to explicitly depend on scala3-library
for `3.2.0`.
In Scala.js it is a single artifact generated in the dotty repository,
so it's platformed. In Scala Native, however, we need to depend on the
jvm artifact, which is used by the compiler, so we patch
`scalaLibraryIvyDeps` to be `platformed = false`
=> Fix issue with lazy val on Scala Native + Scala 3.2

main/core/src/mill/define/ParseArgs.scala, main/test/src/util/ParseArgsTest.scala
Since we support separated arguments, we first separate all arguemnts and
later valdate and extract each separated group individualy.
When we get no args at all, we create no separated groups, hence we dont
have anything to validate and we miss to create a parse error for it.
This fix instead creates an empty first separated group, so we properly
validate it and detect the case of missing args.
=> Fixed inconsistency in args parser

main/src/mill/main/Resolve.scala, main/test/src/main/MainTests.scala
Added a test case for nested cross module resolve error.
* Reported via #2027
=> Fixed wrong resolver error message for cross modules

build.sc, contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/test/resources/hello-world/core/test/src/GreetSpec.scala, contrib/scoverage/test/src/HelloWorldTests.scala, contrib/scoverage/worker2/src/ScoverageReportWorkerImpl.scala
This is a follow-up to the work done in https://github.com/com-lihaoyi/mill/pull/2010 to also add support for Scala 3.
=> Support Scoverage for Scala 3

scalalib/src/PublishModule.scala, scalalib/src/publish/SonatypePublisher.scala
Avoid using `os.Inherit` which is known to break the output in server/client mode.
Fixes #387
Checked manually and the errors now appear with and without `-i`.
=> Show gpg output in server/client in publish (fix #387)

bsp/src/mill/bsp/BspCompileProblemReporter.scala, build.sc, main/api/src/mill/api/CompileProblemReporter.scala, scalalib/worker/src/mill/scalalib/worker/ZincDiagnosticCode.scala, scalalib/worker/src/mill/scalalib/worker/ZincProblem.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
At the moment this is just testing a bit. I see you already have a test
PR to bump zinc in https://github.com/com-lihaoyi/mill/pull/1845 but one
of the things that this brings in is the changes to `Problem` I made in
https://github.com/sbt/sbt/pull/6874 that expose the diagnostic code of
the diagnostic coming from dotc. I have been doing some work on that on
the compiler side in https://github.com/lampepfl/dotty/pull/15565 and
wanted to try it out with Mill.
I tried to mimic the way you currently have it set up, so let me know if
it's not the direction you'd want to go. However, the idea here would be
that the diagnostic code is forwarded when diagnostics are published via
BSP so that Metals could then capture that code and know what code
actions to offer. You can see more of the big …
=> Bump zinc and account for diagnostic code

build.sc, contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/test/src/HelloWorldTests.scala
This one was a bit tricky, as just bumping the Scala version broke the contrib.scoverage tests.
So I needed to implement a workaround for resolving the scoverage 1.x reporter API.
The issue is, that Scoverage 1.x is no longer maintained, but still the only option for projects on older Scala versions. So, we try to keep the support for it. Scala 2.13.9 and 2.13.10 are not directly supported (as there are no full-version releases targeting the compiler). But the reporting API, which is not compiler specific, is not shipped independently but inside the plugin jar. So we work around that by resolving the plugin jar against Scala version 2.13.8 (the latest supported version).
This also bumps Ammonite to 2.5.5 and Scoverage to 2.0.7.
=> Update Scala to 2.13.10

build.sc, scalalib/src/PublishModule.scala
Instead of overriding `moduleDeps` to be `PublishModule`s we iterate over the existing `moduleDeps` and we cast to `PublishModule`s if they are of that type, otherwise we throw an exception with an error message to fix the problem.
* Fixes #2082 
<details>
<summary>
</summary>
**The first version of this PR was using a `NoStackTrace` exception. Now the following doesn't apply anymore** 
This is with the `NoStackTrace` custom exception:
```scala
lorenzo@MacBook-Pro-di-Lorenzo ~/s/snunit (bump-deps) [1]> ../mill/out/dev/launcher.dest/run --no-server show snunit-tapir[3.2.0].native.publishLocal
Compiling /Users/lorenzo/scala/snunit/versions.sc
Compiling /Users/lorenzo/scala/snunit/unitd.sc
Compiling /Users/lorenzo/scala/snunit/build.sc
[1/1] show 
show …
```
=> Don't loose `moduleDeps` from super traits in `PublishModule`

scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala, scalalib/worker/src/sbt/mill/SbtLoggerUtils.scala
This stops using log4j sbt logger in favor of the global logger, which should not log warnings around SecurityManager.
This is the log I'm talking about:
```
[#1] 2022-10-25 14:45:57,759 pool-1-thread-2 ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
[#1]    at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
[#1]    at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:358)
[#1]    at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1805)
[#1]    at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterce …
```
=> Avoid calling sbt deprecated methods, stop using log4j

build.sc, scalalib/src/JsonFormatters.scala
Added additional JSON converters for new classes exposed by `core.Dependency`.
=> Update coursier to 2.1.0-M7-39-gb8f3d7532

bsp/src/mill/bsp/BSP.scala, mill
Uses the Java system property `mill.main.cli` internally.
Also accepts a `MILL_MAIN_CLI` environment variable to override the cli name (if needed).
When BSP connection files (JSON) are generated, the value of the sysprop is used as application, resulting in a BSP server setup, that will respect config changes e.g. to `.mill-version`.
Read more about the motivation in discussion:
* https://github.com/com-lihaoyi/mill/discussions/2079
=> Add actual Mill cli as sysprop and use it in BSP config

build.sc, contrib/jmh/src/mill/contrib/jmh/JmhModule.scala, contrib/jmh/test/resources/jmh/src/Bench1.scala, contrib/jmh/test/resources/jmh/src/Bench2.scala, contrib/jmh/test/src/JmhModuleTest.scala, docs/antora/modules/ROOT/pages/Contrib_Plugins.adoc, docs/antora/modules/ROOT/pages/Plugin_Jmh.adoc
Hi, I was looking around for something providing JMH Mill integration along the lines of sbt-jmh, and I found a module in this PR: https://github.com/com-lihaoyi/mill/pull/182 (file link is here: https://github.com/com-lihaoyi/mill/pull/182/files#diff-191dd5ddc345255594500610c630c72beac8c28eacd593db2d55604b41c33efa).
I copied the script locally, and it works great OOTB, it appears I'm not the only person that's done this: https://github.com/jodersky/ustats/blob/master/jmh.sc :sweat_smile:, so I thought it might be useful if this was added as a contrib module.
This PR just adds the script (with minor modifications) as a module under contrib, along with tests and documentation (let me know if anything more is needed for defining a new contrib module).
Anyway, let me know what you think, …
=> Add JMH contrib module

main/src/mill/modules/Jvm.scala
This is an extension to our workarounds to coursier concurrency issues.
We handle some issues, already detected by courier and reported as a result, as well as one which is not detected by coursier, so we try-catch it and try to match based on the exception type and the message.
Some links:
* https://github.com/com-lihaoyi/mill/issues/1028
* https://github.com/com-lihaoyi/mill/issues/1910
* https://github.com/coursier/coursier/issues/2022
* https://github.com/coursier/coursier/issues/1815
As it is hard to reproduce such kind or issues, I created a GitHub Actions workflow, which consistently failed without this very PR in step "1. Run Mill with settings that should stress coursier". After I applied this PR, all steps passed. That's not a 100-percent guarantee, but it means, we're probably …
=> Catch even more coursier concurrency glitches, some consolidations

build.sc
This release includes a security fix for [CVE-2022-37866](https://github.com/advisories/GHSA-wv7w-rj2x-556x) to prevent path-traversal with bogus module coordinates
=> Update coursier to 2.1.0-RC1

scalalib/src/Dep.scala, scalalib/src/publish/settings.scala
Hardening in context of [CVE-2022-37866](https://github.com/advisories/GHSA-wv7w-rj2x-556x)
* Ensure mill.scalalib.Dep does not accept `/`s in the coordinates
* Ensure mill.scalalib.publish.Artifact does not accept `/` in coords
=> Harden GAV handling in `Dep` and `Artifact`

.scala-steward.conf
GitHub UI now allows to manually update PRs on demand.
=> Removed .scala-steward.conf

build.sc, contrib/scalapblib/src/ScalaPBWorker.scala, contrib/scalapblib/test/src/TutorialTests.scala
Currently the ScalalPB plugins only allows specifying whole directories as source. This change allows specifying individual files as inputs.
In addition, ScalaPBC is now invoked once for all input paths instead of separate invocation for each input path. This is important because it allows setting package scoped options to take affect across all input paths.
=> scalapblib- support specifying individual source files

build.sc, contrib/bloop/src/mill/contrib/bloop/BloopFormats.scala, contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
Bloop Config introduced some binary incompatible API change between 1.5.3 and 1.5.4.
I update the upickle JSON reader/writer setup and adapted to the new API.
I just forward a `None` to the source generators, although, technically,
we probably should add a more sophisticated setup, as Mill is able to generate source code
and is also very aware of the fact it's generating it and if it needs updates.
I simply left a TODO note in the code.
=> Update bloop-config to 1.5.4 and update used API

integration/thirdparty/local/src/local/Tests.scala
We still run these tests in a forked setup, so we don't loose coverage yet.
=> Disabled local Caffeine integration tests as they are flaky

main/client/src/mill/main/client/MillEnv.java, main/client/test/resources/file-wo-final-newline.txt, main/client/test/src/mill/main/client/MillEnvTests.java
Tried to reprodude #2140, which claims, we miss the last option when the opts file does not end with a newline.
Can't reproduce locally.
Here is a hex dump of the file added:
```
$ hexdump -C main/client/test/resources/file-wo-final-newline.txt
00000000  0a 23 20 63 6f 6d 6d 65  6e 74 20 61 66 74 65 72  |.# comment after|
00000010  20 61 6e 20 65 6d 70 74  79 20 6c 69 6e 65 0a 2d  | an empty line.-|
00000020  44 50 52 4f 50 45 52 54  59 5f 50 52 4f 50 45 52  |DPROPERTY_PROPER|
00000030  4c 59 5f 53 45 54 5f 56  49 41 5f 4a 56 4d 5f 4f  |LY_SET_VIA_JVM_O|
00000040  50 54 53 3d 76 61 6c 75  65 2d 66 72 6f 6d 2d 66  |PTS=value-from-f|
00000050  69 6c 65 0a 2d 58 73 73  31 32 30 6d              |ile.-Xss120m|
0000005c
```
=> Test opts file reader to cover issue #2140

docs/antora/modules/ROOT/pages/Mill_Internals.adoc
Currently, the sentence is rendered wrong - I think the extra pair of ticks will make it work like the "Targets" in the previous sentence.
=> Add missing backticks

build.sc, scalanativelib/api/src/mill/scalanativelib/api/ScalaNativeWorkerApi.java, scalanativelib/src/ScalaNativeModule.scala, scalanativelib/test/resources/features/src/Main.scala, scalanativelib/test/src/FeaturesTests.scala, scalanativelib/worker/0.4/src/ScalaNativeWorkerImpl.scala
Scala Native 0.4.9 added support for this feature: https://github.com/scala-native/scala-native/releases/tag/v0.4.9
=> Support incremental compilation in Scala Native 0.4.9

build.sc, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/src/mill/scalajslib/api/ScalaJSApi.scala, scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala, scalajslib/worker-api/src/ScalaJSWorkerApi.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
My first approach to solve #2144 was to create a `Custom` `JsEnvConfig` which would take a `className` and then the implementation would instantiate that class with java reflection. It worked fine but didn't support parameters or builders used by the JsEnv to create itself.
Since there aren't many custom `JsEnv`s out there (the only one I know is [exoego](https://github.com/exoego/scala-js-env-jsdom-nodejs)'s fork of jsdom-nodejs, I'm proposing of supporting it officially in Mill.
This PR also changes the worker classpath to only download and load the jsEnv dependencies that are needed. This skips downloading artifacts and loading classes for jsEnvs that aren't used, like this new one for people not using it, or the deprecated phantom jsEnv.
Testing this properly means installing `jsdom` …
=> Support exoego fork of JsDom JsEnv

bsp/test/src/BspModulesTests.scala, main/src/mill/main/MainRunner.scala, main/test/resources/examples/foreign/project/build.sc, main/test/resources/examples/foreign/project/other.sc, main/test/src/main/ForeignBuildsTest.scala
With this change, we always give included files a unique foreign module path. This makes the dest path more consistent and robust.
Unfortunately, this slightly changes the encoding of foreign modules names. This is no issue when writing `.sc` files, but it will be visible in the progress output and in BSP client and IntelliJ Idea. E.g. the name of an included file in directory `proj1` containing a module `proj1`, will now have the module name "foreign-modules.proj1.build.proj1", whereas previously it was "foreign-modules.proj1.proj1".
* Fix https://github.com/com-lihaoyi/mill/issues/2130
If you import `.sc` files from the same directory, the cache location is shared with `build.sc` , resulting in colliding dest paths when modules have the same name.
Example:
```scala
// build.sc
import …
```
=> Always give included files a unique foreign module path

docs/antora/supplemental-ui/partials/head-icons.hbs
Currently [the docs](https://com-lihaoyi.github.io/mill/mill/Intro_to_Mill.html) have no favicon. This fixes that to use ![favicon.png](https://raw.githubusercontent.com/com-lihaoyi/mill/main/docs/antora/supplemental-ui/favicon.png "docs/antora/supplemental-ui/favicon.png"), which was probably the original intention
=> docs: Fix favicon

build.sc
We use our own JSON serializer (upickle) and don't use the provided ones.
=> Update bloop-config to 1.5.5 and drop unused jsoniter dependency

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
The `bloop.writeConfig` was a cached target, but it generated files outside of `T.dest`. Instead, it should be a command.
To preserve source and binary compatibilty, I created a new command `writeConfigFile`, and let the `writeConfig` target forward the result of `writeConfigFile`.
=> Bloop: Fixed re-generation of bloop config dir

scalalib/src/JavaModule.scala
It was not obvious, that `runIvyDeps` is used addionally to `ibyDeps`.
=> Refined documentation of `runIvyDeps`

scalajslib/src/mill/scalajslib/ScalaJSModule.scala
By default I expect that tests run with the same Scala.js settings as the parent.
=> Pass more settings from `ScalaJSModule` to its `Tests`

scalalib/src/JavaModule.scala, scalalib/test/src/mill/scalalib/bsp/BspModuleTests.scala
Instead we now have a compileResources that is part of compileClasspath.
Fixes #1807 
* #1826
=> Don't include resources into compileClasspath.

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/src/mill/scalajslib/ScalaJSWorkerApi.scala, scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala
* Backport of:  https://github.com/com-lihaoyi/mill/pull/2183
=> Use classpath `PathRef`s hashCode as cache key for Scala.js worker (Backport of #2183)

scalalib/api/src/mill/scalalib/api/ZincWorkerApi.scala, scalalib/api/src/mill/scalalib/api/ZincWorkerUtil.scala, scalalib/src/ScalaModule.scala, scalalib/src/ZincWorkerModule.scala, scalalib/src/mill/scalalib/SemanticDbJavaModule.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
The previous implmentation was receiving `os.Path`s so it needed to access the filesystem to know if the files did change.
Now we propagate `PathRef`s so we simply use their `hashCode` which changes if the files did change.
Here some numbers collected by compiling a Scala file 176 times and writing down the time calculating `compilersSig` took.
|               | Before  |After  |
|:--------------|:--------|:------|
|    Average    | 1364 ms | 12 ms |
| Std deviation | 6533.41 | 91.35 |
=> Use classpath PathRefs hashCode as cache key for Zinc worker

contrib/playlib/src/mill/playlib/RouteCompilerWorker.scala, contrib/playlib/src/mill/playlib/RouterModule.scala, contrib/scalapblib/src/ScalaPBModule.scala, contrib/scalapblib/src/ScalaPBWorker.scala, contrib/scoverage/src/ScoverageModule.scala, contrib/scoverage/src/ScoverageReport.scala, contrib/scoverage/src/ScoverageReportWorker.scala, contrib/twirllib/src/TwirlModule.scala, contrib/twirllib/src/TwirlWorker.scala, scalanativelib/src/ScalaNativeModule.scala, scalanativelib/src/ScalaNativeWorkerApi.scala
Porting the approach used for the Zinc and Scala.js workers to all the workers used in the mill codebase.
=> Use PathRef hashCode for workers caches

docs/antora/modules/ROOT/pages/Library_Dependencies.adoc
Thanks @lefou for adding these docs!
=> Document `ivyDepsTree` and transitive dep management

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/flyway/src/FlywayModule.scala, contrib/jmh/src/mill/contrib/jmh/JmhModule.scala, contrib/playlib/src/mill/playlib/RouterModule.scala, contrib/playlib/src/mill/playlib/Static.scala, contrib/proguard/src/Proguard.scala, contrib/scalapblib/src/ScalaPBModule.scala, contrib/scoverage/src/ScoverageModule.scala, contrib/twirllib/src/TwirlModule.scala, integration/thirdparty/local/resources/ammonite/build.sc, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalalib/src/CoursierModule.scala, scalalib/src/Dep.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/JavaModule.scala, scalalib/src/Lib.scala, scalalib/src/ScalaModule.scala, scalalib/src/ZincWorkerModule.scala, scalalib/src/dependency/versions/VersionsFinder.scala, scalalib/src/giter8/Giter8Module.scala, scalalib/src/mil/scalalib/BoundDep.scala, scalalib/src/mill/scalalib/SemanticDbJavaModule.scala, scalalib/test/src/CrossVersionTests.scala, scalalib/test/src/ResolveDepsTests.scala, scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala
`mill.scalalib.Dep` represents a generic dependency, which include potential cross-compilation properties. E.g. it knows whether it is specific to a `platform` but it does not specify the platform. And it knows whether it is specific to a Scala binary or full version, but it does not specify the exact Scala version. This mean we can define a `Dep` without knowing those context. 
In this PR I introduce a new type `mill.scalalib.BoundDep`, which is kind-of a `Dep` where all these potential open context bindings are bound to an exact context. There is no further cross-resolution necessary nor possible. By having a separate type, we always know with what kind of dependency we work. Also, we can be explicit about the "when" the binding happens. 
When mixing dependencies of multiple modules, we …
=> Bind cross-versions to the context of the originating module

.github/workflows/actions.yml, build.sc
* Re-enabled MiMa checks against previous milestone release
* Don't fail the Milestone build for MiMa checks
* Disables snapshot release for each commit, but enable manual workflow dispatch, to trigger a snapshot release (The idea is to have less frequent snapshot releases for maintenance commits)
Eventually, I'd like to have some kind of nightly-builds, so we only auto-create one snapshot per day. But I need to figure out, how to detect whether anything has changed in a github actions compatible way. Manually triggered snapshot releases should always work.
=> Tooling maintenance

main/core/src/mill/define/Cross.scala, main/core/src/mill/define/Module.scala, main/src/mill/main/Resolve.scala
Make `super.millModuleDirectChildren` available using a private lazy val + a public def.
After this PR it's possible to override `millModuleDirectChildren` and expect consistent behavior across all Mill's functionality.
What I'm especially interested in, is a way to dynamically disable modules based on build variables (like the `crossScalaVersion`). It seems to do the trick but not all the codebase is using `millModuleDirectChidren` as the source of truth. `Cross`, for example, has a copy of its implementation since `lazy val`s don't support calling `super.` on them.
=> Use `millModuleDirectChildren` consistently everywhere

scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
We need this feature to support SemanticDB generation (#2227) via a Java compiler plugin in mixed Scala/Java projects.
We already introduced non-local Java compilers in #1988. This change now also allows the use of a non-local Java compiler in mixed Java/Scala modules, if any `-J` option is given.
As compilers are cached, I added the `hashCode` of the relevant runtime `javacOptions` to the cache key.
I took the opportunity to remove non-relevant options from the existing Java compiler cache, to reduce the amount of cached compiler instances.
/CC @ckipp01 who implemented #1988.
=> Support non-local Java compiler use in mixed Java/Scala compilation

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/src/mill/scalajslib/api/ScalaJSApi.scala, scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala, scalajslib/test/src/OutputPatternsTests.scala, scalajslib/worker-api/src/ScalaJSWorkerApi.scala, scalajslib/worker/0.6/src/ScalaJSWorkerImpl.scala, scalajslib/worker/1/src/ScalaJSWorkerImpl.scala
=> Add support for scalaJSOutputPatterns

build.sc, main/src/mill/modules/Jvm.scala
I've created a small PR which adds a link to the CLI output whenever dependency resolution fails. I am happy to change the text if needed. Any feedback is welcome.
An example of the output:
Small note:
I am not really an active contributor in the open source community (yet). I am trying it out, to see if I'll enjoy it. I've decided to just get started with this easy task. Again, any feedback is welcome!
Fixes #1401
=> Add a documentation link to the coursier resolution failure output

.github/workflows/dependency-graph.yml, build.sc
- CI: show transmitted dependency graph
- Update transitive gson to 2.10.1
=> Dependency maintenance and bumps

main/src/mill/main/MainRunner.scala
This is useful when you enable deprecation warnings using:
```scala
interp.configureCompiler { c =>
val settings = c.settings
settings.nowarnings.value = false
settings.maxwarns.value = 100
settings.deprecation.value = true
}
```
Otherwise, it prints warnings for unused deprecated targets in `mill.main.MainModule`.
In `0.10.10` it prints:
```
/Users/lorenzo/scala/example-mill-4/build.sc:61: method all in trait MainModule is deprecated (since mill after 0.10.0-M3): Use the + separator, wildcards, or brace-expansion to specify multiple targets.
implicit lazy val millDiscover: _root_.mill.define.Discover[this.type] = _root_.mill.define.Discover[this.type]
^
/Users/lorenzo/scala/example-mill-4/build.sc:61: method par in trait MainModule is deprecated (since mill after 0.10.0-M3): Use the + …
```
=> Add `@nowarn` to generated ammonite script's `millDiscover`

main/src/mill/main/MainRunner.scala
This is useful when you enable deprecation warnings using:
```scala
interp.configureCompiler { c =>
val settings = c.settings
settings.nowarnings.value = false
settings.maxwarns.value = 100
settings.deprecation.value = true
}
```
Otherwise, it prints warnings for unused deprecated targets in `mill.main.MainModule`.
In `0.10.10` it prints:
```
/Users/lorenzo/scala/example-mill-4/build.sc:61: method all in trait MainModule is deprecated (since mill after 0.10.0-M3): Use the + separator, wildcards, or brace-expansion to specify multiple targets.
implicit lazy val millDiscover: _root_.mill.define.Discover[this.type] = _root_.mill.define.Discover[this.type]
^
/Users/lorenzo/scala/example-mill-4/build.sc:61: method par in trait MainModule is deprecated (since mill after 0.10.0-M3): Use the + …
```
=> Add `@nowarn` to generated ammonite script's `millDiscover` (Backport of #2242)

docs/antora/modules/ROOT/pages/Out_Dir.adoc, main/core/src/mill/eval/Evaluator.scala, main/test/src/eval/EvaluationTests.scala, readme.adoc
Also reworked the documentation about the `out/` folder.
This is in preparation of
* https://github.com/com-lihaoyi/mill/issues/2107#issuecomment-1306119724
* #2108
=> Change `out/`-layout from `foo.overridden` to `foo.super`

ci/mill-bootstrap.patch, main/core/src/mill/define/Task.scala, main/core/src/mill/eval/Evaluator.scala, main/test/src/eval/EvaluationTests.scala, main/test/src/util/TestGraphs.scala
This change ensures, we always use the `super`-`out` path when we try to store metadata and scratch files for private named tasks. As private tasks can't be seen from other traits/classes in the same module hierarchy, our previous logic to detect potential collisions of the metadata location fails. Hence we now keep the `isPrivate` property in the named target.
I also added a test case that reproduce the initial issue but now succeeds.
* Fixes: https://github.com/com-lihaoyi/mill/issues/2107
This is a binary compatibility breaking change.
By applying the same approach and tracking also `public`-ness of a target, there is potential to fix also other issues like
* https://github.com/com-lihaoyi/mill/issues/803
This PR should be merged after 
* #2262
=> Use unique `out` path for private named tasks - fixes #2107

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala, scalanativelib/test/src/HelloNativeWorldTests.scala
Some targets like `scalacOptions` were not inherited by `ScalaJSModule`'s `Tests` trait and by `ScalaNativeModule`'s `Tests` trait This fixes that by making it follow the same convention `ScalaModule` follows
=> Make ScalaJS and Native Tests modules extend ScalaModule

mill
Original pull request: https://github.com/com-lihaoyi/mill/pull/2279
=> Update default Mill version in wrapper script to 0.10.10 (Backport of #2279)

scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea-extended-hello-world/build.sc, scalalib/test/resources/gen-idea-extended-hello-world/idea/libraries/SBT_ junit_junit_2_13_4_13_2_jar.xml, scalalib/test/resources/gen-idea-extended-hello-world/idea/libraries/SBT_ org_scalameta_munit_2_13_0_7_29_jar.xml, scalalib/test/src/GenIdeaExtendedTests.scala, scalalib/test/src/GenIdeaTests.scala
Original Pull Request: https://github.com/com-lihaoyi/mill/pull/2273
=> Fix generation of library paths containing `:` for Windows (Backport of #2273)

build.sc, main/core/src/mill/define/ParseArgs.scala, main/util/src/mill/util/Version.scala, main/util/test/src/mill/util/VersionTests.scala, scalalib/src/mill/scalalib/SemanticDbJavaModule.scala
This change updates semanticdb-java to 0.8.10.
As this version properly added support for the `-build-tool:mill` option, we enable it, but only, if we really use this version (or newer) at runtime.
The thing is: Metals is sending us its preferred versions for semanticdb-scalac and semanticdb-java. There is a high change, that Mill was build with another version. (When I introduced the semanticdb-java support, Metals came with a much outdated version, resulting in  build failures due to these unexpected low version during development.) Before, Mill used the version from the context (requested by Metals), even if the built-time version was newer. Now, we compare the built-time version with the context version and use whatever is newer. This should be the safest option, but there is still a …
=> SemanticDB for Java improvements

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala
`ScalaJSModule` and `ScalaNativeModule` did not fetched their worker and tooling classpaths previously.
=> Fetch more tooling deps in `prepareOffine`

scalalib/api/src/mill/scalalib/api/ZincWorkerApi.scala, scalalib/src/JavaModule.scala, scalalib/src/ScalaModule.scala, scalalib/src/mill/scalalib/SemanticDbJavaModule.scala, scalalib/worker/src/mill/scalalib/worker/RecordingReporter.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
In it's incremental nature, Zinc does only report problems for re-compiled files,
which leads to situations, where you only see a glimpse of the overall compiler warnings.
Now, we use the Zinc internal analysis to recover all found problems. We also record all already shown problems and simply log the not shown but still valid problems after the compilation finished.
This behavior can be configured by the new target `JavaModule.zincReportCachedProblems: T[Boolean]`. It defaults to `false` to keep backward-compatible output.
=> Support reporting of all compilation problems

build.sc, main/api/src/mill/api/JarManifest.scala, main/api/src/mill/api/JarOps.scala, main/src/mill/modules/Jvm.scala, main/test/src/eval/JavaCompileJarTests.scala, scalalib/src/JavaModule.scala, scalalib/src/PublishModule.scala, scalalib/src/ScalaModule.scala
Kept deprecated forwarders in `mill.scalalib.Jvm` to maintain source compatibility.
=> Move `JarManifest` to `mill.api`

docs/antora/modules/ROOT/pages/Plugin_BuildInfo.adoc
Small typo on the docs in the BuildInfo page
=> Doc: Remove extra parenthesis and fixed typo

integration/thirdparty/local/src/UpickleTests.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/test/src/MultiModuleTests.scala
I have no idea why they fail and why they worked before, but this is
the maintenance branch of Mill 0.10.x and those failing test (which
worked before) block successful CI runs.
This hopefully un-blocks the following pull requests:
* #2324
* #2366
* #2339
=> Disabled tests that always fail CI recently

build.sc
After installing it there, it can be consumed by simply placing he version in a `.mill-version` file.
=> Added a task to install Mill into ~/.cache/mill/download

contrib/scalapblib/src/mill/contrib/scalapblib/ScalaPBModule.scala, contrib/scalapblib/test/src/mill/contrib/scalapblib/TutorialTests.scala, docs/antora/modules/ROOT/pages/Plugin_ScalaPB.adoc
Add boolean flag `scalaPBSearchDeps` that uses the `scalaPBUnpackProto()` task to add to existing `scalaPBIncludePath`, .proto files from included dependencies.
=> Add boolean flag to search for proto files in dependencies. Update docs.

contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala, main/core/src/mill/define/Cross.scala, main/core/src/mill/define/Ctx.scala, main/core/src/mill/define/Discover.scala, main/core/src/mill/define/ScriptNode.scala, main/core/src/mill/define/Task.scala, main/core/src/mill/eval/Evaluator.scala, main/core/src/mill/eval/EvaluatorPaths.scala, main/core/src/mill/eval/ParallelProfileLogger.scala, main/src/mill/main/MainModule.scala, main/src/mill/main/MainRunner.scala, main/src/mill/modules/CoursierSupport.scala, main/test/src/mill/util/TestUtil.scala, main/util/src/mill/util/Loggers.scala, testrunner/src/mill/testrunner/TestRunner.scala
Reviewed various case classes and hid their `unapply` and `copy` methods. Also added some `with`-methods where needed. This improves the ability to evolve them while still preserving binary compatibility.
=> Improve binary compatibility

bsp/test/src/mill/bsp/BspInstallDebugTests.scala, bsp/test/src/mill/bsp/BspInstallTests.scala, bsp/test/src/mill/bsp/BspModulesTests.scala, bsp/worker/src/mill/bsp/worker/MillJvmBuildServer.scala, build.sc, docs/antora/antora.yml
Updated bsp4j to 2.1.0-M4.
* Fix https://github.com/com-lihaoyi/mill/issues/2283
=> BSP: Support `mainClasses` in run and test environments

main/api/src/mill/api/PathRef.scala, main/core/src/mill/eval/Evaluator.scala
This uses `scala.util.DynamicVariable` instead of `InheritableThreadLocal` to avoid loosing some state in case we have some nested evaluation going on, e.g. in evaluator command.
I added mostly duplicate code to `Evaluator` `sequentialEvaluate` and `parallelEvaluate` instead of only one in method `evaluate`, as both are public entry points to start evaluation.
=> Reworked `PathRef.revalidate` handling based on `DynamicVariable`

example/basic/1-hello-world/build.sc, example/basic/1-hello-world/src/Foo.scala, example/basic/3-custom-tasks/build.sc, example/basic/3-custom-tasks/src/Foo.scala, example/basic/4-multi-module/bar/src/Bar.scala, example/basic/4-multi-module/build.sc, example/basic/4-multi-module/foo/src/Foo.scala, example/basic/5-nested-modules/build.sc, example/basic/5-nested-modules/qux/src/Qux.scala, example/basic/5-nested-modules/wrapper/bar/src/Bar.scala, example/basic/5-nested-modules/wrapper/foo/src/Foo.scala
We don't need to use it in all the examples, but I added it to a few. That means that someone following the examples will at least get some hints about how to do command line argument parsing, which is a common requirement when writing small CLI tools and utilities.
Not strictly Mill/build-config related, but definitely handy for what we expect people to want to do with Mill
=> Make use of MainArgs in example/basic/

example/web/1-hello-webapp/build.sc, example/web/2-todo-webapp/build.sc, example/web/4-webapp-scalajs/build.sc, example/web/5-webapp-scalajs-shared/build.sc
This fixes the content type of the static resources, letting CSS load properly in the browser
=> Bump Cask to 0.9.1 in example/web/

docs/antora/modules/ROOT/pages/Configuration.adoc, readme.adoc, scalalib/src/mill/scalalib/TestModule.scala
This PR adds ZIOTest framework to TestModule.
=> Add zio-test to TestModule

build.sc, ci/mill-bootstrap.patch, example/src/mill/integration/ExampleTestSuite.scala, integration/feature/dynamic-cross-module/test/src/DynamicCrossModuleTests.scala, integration/feature/editing/test/src/MultiLevelBuildTests.scala, integration/src/mill/integration/IntegrationTestSuite.scala, main/api/src/mill/api/SystemStreams.scala, main/core/src/mill/eval/Evaluator.scala, main/src/mill/modules/Jvm.scala, main/util/src/mill/util/Util.scala, runner/src/mill/runner/MillMain.scala, scalajslib/worker/1/src/mill/scalajslib/worker/ScalaJSWorkerImpl.scala
This should allow us to do debugging or iteration on example/integration in `.local` mode, which is a lot faster than `.fork` or `.server`
Even after https://github.com/com-lihaoyi/mill/pull/2425 landed, the `.local` integration tests are still much faster to run than `.fork` and `.server`, with publishing taking ~20s down from ~60s before which is still a very annoying wait. Better if we can avoid that, using `.local` in the common development workflow and leaving `.fork` and `.server` for CI to catch rare edge-case bugs
We basically needed to be a bit more robust in spawning subprocesses, allowing the `InputPumper` machinery to work for any redirected streams rather than being hardcoded to work with the `PipedInputStream` that `MillServerMain` uses.
I had to fix an issue in …
=> enforce stdout/stderr contents in `.local` example/integration tests

.github/workflows/actions.yml, .github/workflows/run-mill-action.yml
This means, although the bincompat-check fails, the overall report is marked as successful run.
=> CI: ignore failing bincompat reports

main/core/src/mill/define/Discover.scala
This used to happen when a target had a compile error, causing it's return type to be `Nothing`. This PR explicitly ignores that case
Tested manually. For some reason, the `compileError` macro in uTest isn't able to pick up this error, so I can't catch it and assert
=> Fix spurious `T.command` definitions must have 1 parameter list error

main/core/src/mill/eval/Evaluator.scala
Should fix https://github.com/com-lihaoyi/mill/issues/2468 I think
=> Filter out non-script paths to avoid blow up due to invalid path format

main/core/src/mill/eval/Evaluator.scala
The current code is crashing since it's trying to insert twice the same failure when it's linked to multiple tasks.
My solution was to wrap the Iterator into a `Loose.Agg` so we remove the duplicates before adding to the `MultiBiMap`, which uses `Strict.Agg`.
Before:
After:
=> Fix crash aggregating failures

.github/workflows/actions.yml, runner/src/mill/runner/MillServerMain.scala
Ignore the `UnsupportedOperationException` of `Thread.stop`. This is a quick fix to de-block users from using Java 20.
Added a bootstrap CI run using Java 20.
* Fix #2429
=> Support Java 20

runner/src/mill/runner/MillBuildBootstrap.scala, runner/src/mill/runner/MillBuildRootModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/2485
We take the `config.imports` field and pass it to `MillIvy.processMillIvyDepSignature` inside `ivyDeps`. This was overlooked in https://github.com/com-lihaoyi/mill/pull/2377, but seems easy enough to put back
Honestly not super sure how to test this. But when I run
```
./mill -i dev.run example/tasks/3-anonymous-tasks -i --import ivy:com.lihaoyi::mill-contrib-bloop:0.11.0-M8  mill.contrib.bloop.Bloop/install
```
On main branch, I get 
```
Cannot resolve external module mill.contrib.bloop.Bloop
```
On this PR I get
```
java.lang.NoSuchMethodError: 'java.lang.ThreadLocal mill.eval.Evaluator$.currentEvaluator()'
mill.contrib.bloop.Bloop$$anonfun$$lessinit$greater$1.apply(Bloop.scala:8) …
```
=> Make `--import` flag work again

.github/workflows/actions.yml, contrib/scoverage/src/mill/contrib/scoverage/ScoverageReport.scala, integration/src/mill/integration/IntegrationTestSuite.scala, main/src/mill/main/MainModule.scala, main/src/mill/main/ParseArgs.scala, main/src/mill/main/Resolve.scala, main/src/mill/main/ResolveCore.scala, main/src/mill/main/ResolveNonEmpty.scala, main/src/mill/main/TokenReaders.scala, main/test/src/mill/main/MainModuleTests.scala, main/test/src/mill/main/ParseArgsTests.scala, main/testkit/src/mill/testkit/MillTestkit.scala
In general, *most* commands do not depend on their arguments to instantiate the `mill.Command` object, and only depend on their arguments to actually execute. For that common case, we should be able to pass in `null`s for the arguments, which would allow us to do `inspect`, `path`, `plan`, etc. without needing to tediously pass in dummy arguments at the command line.
We add a `nullCommandDefaults` flag to calls to `Resolve*.resolve` in `MainModule.scala`, and make it override the MainArgs `ArgSig`s to set all default values to `null` when passed (`T.task(null)` for `Task[_]` params, primitive params it gets casted to `0` for numbers, `false` for booleans, etc.). This allows us to instantiate the `Command` object and analyze the task graph, even if we aren't able to actually execute it …
=> Enable `inspect`, `path`, etc. on `T.command`s without needing to pass in args in common cases

main/src/mill/main/TokenReaders.scala, main/src/mill/main/package.scala
Fix https://github.com/com-lihaoyi/mill/issues/2459
=> Added a deprecated type alias for removed `EvaluatorScopts`

build.sc, ci/mill-bootstrap.patch
This version was built against Mill 0.11.0-M8-24-7d871a and should be suitable for re-bootstrapping of Mill.
=> Update mill-vcs-version to 0.3.1-5-910047

main/api/src/mill/api/AggWrapper.scala, runner/src/mill/runner/MillBuildRootModule.scala
Seems like all the `IterableOnce` method implementations were deprecated at some point, and you need to pull in `IterableOps` to have non-deprecated versions
If we want to start making use of `@deprecated` in 0.11.0, we need to make sure people see the warnings, and that they're not drowned in a sea of noise
=> Enable warnings in build.sc, overhaul `Agg` to avoid triggering spurious deprecation warnings

bsp/src/mill/bsp/BspContext.scala, bsp/src/mill/bsp/BspWorker.scala, bsp/worker/src/mill/bsp/worker/BspWorkerImpl.scala, bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
The initial call to `updateEvaluator` always happens with `None`, which makes it a no-op
=> More tweaks to simplify BSP logic

integration/feature/docannotations/repo/build.sc, integration/feature/docannotations/test/src/DocAnnotationsTests.scala, main/define/src/mill/define/Discover.scala, main/resolve/src/mill/resolve/Resolve.scala, main/src/mill/main/MainModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/2198
There's a bit of duplication if a user both adds `@mainargs.arg(doc = "...")` scala annotation as well as a `@param foo` scaladoc annotation, but that's an inherent issue with mainargs and not something we aim to fix here.
We render the mainargs CLI help message the same way it's done in mainargs. There isn't a nice helper that renders the whole thing at once, so i have to piece it together from various helpers, but it's not too complex and works out ok.
Tested via additions to `integration.feature[docannotations].local.test`, and manually
```bash
$ ./mill -i dev.run example/basic/1-simple-scala -i inspect run # command with 1 arg
run(JavaModule.scala:720)
Runs this modules code in a subprocess and waits for it to finish
args <str>... …
```
=> Print out CLI help message when inspecting commands

build.sc, scalalib/test/src/mill/scalalib/HelloWorldTests.scala
Includes a fix for infinite compilation issues and a security fix. We should also consider a backport to Mill 0.10.
=> Update zinc to 1.8.1

example/misc/4-mill-build-folder/build.sc, integration/failure/invalid-meta-module/repo/build.sc, integration/feature/editing/repo/build.sc, integration/feature/editing/repo/mill-build/build.sc, integration/feature/editing/test/src/MultiLevelBuildTests.scala, runner/src/mill/runner/FileImportGraph.scala, runner/src/mill/runner/MillBuildBootstrap.scala
Fixes https://github.com/com-lihaoyi/mill/issues/2461
For now it remains hard-coded as `mill-build/`, for simplicity. Given the `mill-` prefix, it's unlikely to collide with user-defined folders. Making it configurable would open another can of worms where the `import $mill.foo` can now collide with an `object foo`, which is very unintuitive.
For now, we just parse the script files one additional time in `MillBuildBootstrap.scala`. This is a bit wasteful, but is probably fast enough for now, and we're already pretty sloppy parsing everything twice in `MillBuildRootModule#scriptSources` and `MillBuildRootModule#parseBuildFiles`, so parsing things three times isn't the end of the world. We can look into optimizing it in future if necessary
=> Make mill-build folder opt in via `import $mill.build`

build.sc, ci/mill-bootstrap.patch
This version is also released for Mill 0.11.0-M9 and should be suitable for bootstrapping
=> Update mill-vcs-version to 0.3.1-6-e80da7

example/basic/3-builtin-commands/build.sc, main/src/mill/main/MainModule.scala, main/test/src/mill/main/MainModuleTests.scala
The old array-based output is pretty useless since it doesn't tell you what targets each output actually corresponds to. For humans, `show` is now probably what they want 99% of the time, and it simplifies having to remember to use `show` or `showNamed` depending on how many targets their query returns.
We leave `showNamed` for the "always print out dictionary" behavior, which might be useful for external tools who would not appreciate the output format flip-flopping between a string and a dictionary depending on the target count.
=> Use `showNamed` output format for `show` with more than one item

main/api/src/mill/api/AggWrapper.scala
This is a super common operation to want in the builds i've come across: conditional scalac flags, conditional deps, conditional sources, etc. Better to have it built in as `Agg.when(foo)("bar", "baz")` rather than jumping through hoops with `++ (if (foo) Agg("bar", "baz") else Agg.empty)`
=> Add Agg.when operator

build.sc, contrib/testng/test/src/mill/testng/TestNGTests.scala, main/util/src/mill/util/CoursierSupport.scala
Should fix https://github.com/com-lihaoyi/mill/issues/2533, which was broken by https://github.com/com-lihaoyi/mill/pull/2476
Just requires shuffling `def testDeps` and related definitions around to make them available outside `MillScalaModule`. They moved to `MillCoursierModule`, which in order to satisfy their dependencies had to be converted to `MillJavaModule`. The overall logic of the build is unchanged
Tighted up the test artifact resolution logic for `.local` example/integration tests. Previously, they would ignore the `artifactSuffix`, which is why tests exercising `runBackground` like `example.web[1-todo-webapp].local` passed despite the bug. With the more strict test artifact resolution, this bug gets surfaced properly on `main`, and is fixed by this PR
=> Make `mill.backgroundwrapper` a `JavaModule` again

bsp/src/mill/bsp/BSP.scala, bsp/src/mill/bsp/BspWorker.scala, bsp/worker/src/mill/bsp/worker/BspWorkerImpl.scala, build.sc, contrib/buildinfo/test/src/mill/contrib/buildinfo/BuildInfoTests.scala, contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala, main/src/mill/main/MainModule.scala, runner/src/mill/runner/MillBuildBootstrap.scala, runner/src/mill/runner/MillCliConfig.scala, runner/src/mill/runner/MillIvy.scala, runner/src/mill/runner/MillMain.scala, runner/src/mill/runner/MillServerMain.scala, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalalib/src/mill/scalalib/GenIdeaImpl.scala, scalalib/src/mill/scalalib/Lib.scala, scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/src/mill/scalalib/SemanticDbJavaModule.scala, scalalib/src/mill/scalalib/TestModule.scala, scalalib/src/mill/scalalib/giter8/Giter8Module.scala, scalalib/src/mill/scalalib/publish/SonatypeHttpApi.scala, scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala
We currently encourage `import mill._`, which causes problems when people want to also `import mill.contrib.buildinfo.BuildInfo`. There's a workaround to `import mill.{BuildInfo => MillBuildInfo, _}`, which we do in several places in our own codebase, but it's a pain in the neck and an unnecessary hurdle for users to cross. The majority of users would not need to access `mill.BuildInfo` at all, so putting it in the default namespace just adds clutter.
The `mill.BuildInfo` is used throughout `mill.scalalib` and `mill.scalajslib` and so on, but is not used in `main/`, so I put it in as downstream a module as possible which turns out to be `mill.main.BuildInfo`
=> Move `mill.BuildInfo` to`mill.main.BuildInfo`

.github/workflows/actions.yml
- Further reduce the example tests on Windows, to try and avoid random hangs in Windows CI
- Break up `scalajslib` and `scalanativelib` tests into their own jobs, since they are very slow
=> Tweak windows CI

build.sc, example/basic/1-simple-scala/.mill-version, integration/feature/import-ivy-worker-invalidation/repo/build.sc, integration/feature/import-ivy-worker-invalidation/test/src/ImportIvyWorkerInvalidation.scala, main/eval/src/mill/eval/EvaluatorImpl.scala, main/eval/src/mill/eval/GroupEvaluator.scala, main/testkit/src/mill/testkit/MillTestkit.scala, runner/src/mill/runner/MillBuildBootstrap.scala
Fixes https://github.com/com-lihaoyi/mill/issues/2548. Explanation in comments.
Added an integration test to cover this, since the behavior has to do with how the bootstrap process interacts with the worker invalidation when the `build.sc` is modified, and so cannot be tested via `TestEvaluator`
=> Fix invalidation of workers pulled in from `import $ivy` when build.sc is modified

build.sc
Creates a stub `dist` module whose only purpose is to take the `dev.assembly` and put it on maven central, which the updated bootstrap script will download.
This should help reduce the number of external failure points in Mill bootstrap script; rather than having hard dependency on both Github and Maven Central, this PR reduces it to only a hard dependency on Maven Central.  Maven Central is also by default a write-only package store. That means that short of sending them a lawyer letter, the packages published there are immutable (https://central.sonatype.org/faq/can-i-change-a-component). This is in contrast to Github release assets which are read/write. 
With Github, a bug in our CI auto-upload system could easily override/delete/corrupt already-published assemblies, causing a …
=> Distribute Mill Assembly via Maven Central 

.github/workflows/actions.yml, main/src/mill/main/MillServerMain.scala
Ignore the `UnsupportedOperationException` of `Thread.stop`. This is a
quick fix to de-block users from using Java 20.
* Original Pull request: https://github.com/com-lihaoyi/mill/pull/2501
* Fix: https://github.com/com-lihaoyi/mill/issues/2545
=> Support Java 20 (Backport of #2501)

main/client/src/mill/main/client/MillEnv.java, runner/src/mill/runner/MillServerMain.scala
Trying to implement [issue-408](https://github.com/com-lihaoyi/mill/issues/408). 
Not exactly sure if it is a correct way to achieve it, so would appreciate any feedback!
=> issue-408 - server timeout setting configurable through envs

build.sc, contrib/buildinfo/src/mill/contrib/buildinfo/BuildInfo.scala
Status quo fails linking with a cryptic error message where previous version was working out of the box.
This sets the default to the static behavior on Scala.js and Scala Native so users don't need to care.
=> Enable `buildInfoStaticCompiled` on ScalaJSModule and ScalaNativeModule

build.sc
Follow up from https://github.com/com-lihaoyi/mill/pull/2562, to avoid potentially having duplicate Mill classfiles on the classpath
=> Make `contrib.buildinfo` use `compileModuleDeps` rather than `moduleDeps`

main/define/src/mill/define/DynamicModule.scala, main/resolve/src/mill/resolve/ResolveCore.scala, main/resolve/test/src/mill/main/ResolveTests.scala, main/test/src/mill/util/TestGraphs.scala
Fixes https://github.com/com-lihaoyi/mill/issues/2573
For now, I just preserved the `def millModuleDirectChildren` overriding. I couldn't figure out how to get `def enabled: Boolean` working without causing circular dependencies between `instantiateModule` depend on `resolveDirectChildren0`, resulting in an infinite recursion. Avoiding the infinite recursion would require some re-working on `ResolveCore.scala`. That can come in a follow-up, for now I just want to fix the regression and preserve the status quo (except for the new requirement of needing to extend a marker trait)
=> Add `mill.define.DynamicModule` to allow custom overriding of `millModuleDirectChildren`

build.sc, contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala, contrib/scoverage/test/src/mill/contrib/scoverage/HelloWorldTests.scala, integration/feature/scoverage/repo/build.sc, integration/feature/scoverage/test/src/ScoverageTests.scala
I also changed from `lazy val` to `def` to make overridding and `super.scoverageData`-calls easier.
=> Fix type annotation for inner scoverage module

build.sc, contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala, contrib/scoverage/test/src/mill/contrib/scoverage/HelloWorldTests.scala, integration/feature/scoverage/repo/build.sc, integration/feature/scoverage/test/src/ScoverageTests.scala
This is a follow-up on #2583.
Using a ModuleRef make accesss to the inner module for the CLI impossible.
I added that case to the integration test and changed to use a `val`.
=> Refined fix for `ScoverageModule` inner module

main/resolve/src/mill/resolve/Resolve.scala, main/resolve/test/src/mill/main/ResolveTests.scala, main/src/mill/main/RunScript.scala, main/test/src/mill/util/TestGraphs.scala
Should fix https://github.com/com-lihaoyi/mill/issues/2602. The previous `.distinct` doesn't work because `T.command`s take arguments, and their `Command` instances cannot be cached the same way that `T{}` and other tasks can be. Also, the fact that it was in `RunScript` meant that code resolving tasks without running them didn't benefit, e.g. when you run `inspect __.test`, so I moved it into `Resolve` with separate implementations for `Resolve.Task` and `Resolve.Segments`
Tested manually, both `./mill -i dev.run example/basic/1-simple-scala -i inspect __.test` and `./mill -i dev.run example/basic/1-simple-scala -i __.test` no longer contain duplicates. Also covered by new unit tests to ensure that various kinds of potential duplication (via wildcards, brace-expansion, `+`) all are …
=> Properly distinct-ify commands when resolved multiple times by query

docs/modules/ROOT/pages/Installation_IDE_Support.adoc, docs/modules/ROOT/pages/Intro_to_Mill.adoc, runner/src/mill/runner/MillCliConfig.scala, runner/src/mill/runner/MillMain.scala
In Mill `0.11.0-M8` we change Mill internals to no longer use Ammonite. Since then, we no longer support the `--repl` mode, but forgot to cleanup the CLI configuration.
=> Cleanup leftover --repl flag handling, fail when --repl is given

scalalib/src/mill/scalalib/UnidocModule.scala
The API documentation has links to local files (e.g. [mill.define.Args](https://mill-build.com/api/latest/mill/define/Args.html) points to `file:///home/runner/work/mill/mill/main/define/src/mill/define/Args.scala`). This PR is for fixing that.
There's already code to replace every occurrence of `file://path/to/project/root` with the right URL, but it's for `.scala` files so I didn't touch it. I figured `-sourcepath` was a safer way to do the same thing.
=> Fix source links in API documentation

scalajslib/src/mill/scalajslib/ScalaJSModule.scala
The default was changed by mistake in
https://github.com/com-lihaoyi/mill/commit/7f990b3ca7b71e3bd07eb18b562f64f964b1a8e1
=> Restore correct default for `esFeatures`

build.sc
This dependency is unused and created a conflict since it transitively depends on geny `0.6.5` while we depend on geny `1.0.0` (problem reported on Discord by @kubukoz)
=> Remove scalameta trees dependency

build.sc
As runtime dependencies are not transitive in Mill, we need to declare the sbt test-interface as normal dependency.
* Fix: #2595
=> Convert entrypoint.runIvyDeps to ivyDeps

docs/modules/ROOT/pages/Cross_Builds.adoc, example/cross/1-simple/build.sc, example/cross/11-default-cross-module/build.sc, main/define/src/mill/define/Cross.scala, main/resolve/src/mill/resolve/ParseArgs.scala, main/resolve/src/mill/resolve/ResolveCore.scala, main/resolve/test/src/mill/main/ResolveTests.scala, main/test/src/mill/util/TestGraphs.scala
* Implements idea https://github.com/com-lihaoyi/mill/discussions/2588
With this change, one can select the default cross segment by leaving the cross selection empty.
```
$ mill cross[].compile
```
The default selection is the first provided cross value for each cross level.
To override the default cross segment, one can override the `defaultCrossSegments` method.
=> Support default crossSegment selection with `cross[]` notation

main/client/src/mill/main/client/MillClientMain.java
In older Mill versions, we tried to detect when the Mill version changed. In that case, we stopped the server process and started a new one. This server stopping worked unrelieble and is currently not working at all.
This pragmatic change simply does not try to re-use a mill server process when the Mill version does not match. Instead, we only choose between instances with the exact version or start a new instance. This is identical to the beavior, when we run with a differnet JVM.
Resource wise, we potentially increase the amount of running processes, but we do this anyways in other situations. Also, idle Mill servers stop themselves after a some time span.
=> Differentiate by  Mill version when selecting a server worker

runner/src/mill/runner/MillBuildRootModule.scala, runner/src/mill/runner/MillIvy.scala
It's a typical use case to add plugin dependencies to a meta-build. To make this more convenient, we set the `platformSuffix` to `_mill<binary-platform>`.
* Fix https://github.com/com-lihaoyi/mill/issues/2634
=> Define reasonable `platformSuffix` in `MillBuildPlatformModule`

scalalib/src/mill/scalalib/JavaModule.scala
Hi! This is my first contribution, so please let me know if there is anything for me to do.
As far as I understand this is OK, since `bspCompileClasspath` mentions it tries not to trigger compilation, so the transitive version may also try not to trigger compilation of the module dependencies.
This would be helpful to us, since we currently cannot load projects in intellij via bsp if there is a compilation error in any module other than the topmost module. On the surface this seems similar to the issue in #2484 (failing on `buildTarget/scalacOptions` due to an error within `_.compile`).
=> use bspCompileClassesPath in bspTransitiveCompileClasspath

build.sc, docs/antora.yml
This just bumps the default version of semanticdb from 4.7.8 to 4.8.1. I
realized when using mill-scalafix that I needed to manually do this
since the new Mill version is still using an older semanticdb version
that doesn't support for example 2.13.11.
=> deps: update semanticdb to 4.8.1

LICENSE
Mill LICENSE is not reported as MIT by the Github API Updating it to use the GIthub template so it shows as MIT.
It appears as:
while other repositories have:
=> Update LICENSE to use Github template

scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
Profiled Mill compiling Mill itself and 0.07% of the time was spent in mapping the result of `compileMixed0` to `CompilationResult`.
This changes the `compileInternal` method to already use the right types so less conversions are needed.
=> Avoid intermediate mapping in ZincWorkerImpl

docs/modules/ROOT/pages/Scala_Build_Examples.adoc, example/thirdparty/acyclic/build.sc, example/thirdparty/fansi/build.sc, example/thirdparty/jimfs/build.sc
Links were broken. Changed to include the generated asciidoc instead.
* Fix https://github.com/com-lihaoyi/mill/issues/2659
=> Docs: Fix real world Mill examples section

bsp/worker/src/mill/bsp/worker/State.scala, integration/feature/init/test/src/MillInitTests.scala, runner/src/mill/runner/FileImportGraph.scala, runner/src/mill/runner/MillBuildBootstrap.scala, runner/src/mill/runner/MillMain.scala, runner/src/mill/runner/RunnerState.scala
I first added an integration test for the init command to reproduce the issues and make sure the feature now works.
Instead of failing in case there is no `build.sc`, we now check the targets against a whitelist of tasks (`init` and `version`) and continue with an empty setup.
We also accept a missing `build.sc` in case additional imports are given, which could mean, the imports contain Mill plugins which itself provide commands that could work without a `build.sc`.
Only when we discover an error afterwards, we add a message about the missing `build.sc` to the underlying error message. That means, we don't see the spurious "no build.sc" message when everything works as expected.
* Fix #2660
=> Fix `init` command and support running Mill without existing `build.sc`

example/basic/2-custom-build-logic/build.sc, integration/failure/compile-error/repo/bar.sc, integration/failure/compile-error/test/src/CompileErrorTests.scala, integration/failure/parse-error/repo/bar.sc, integration/failure/parse-error/test/src/ParseErrorTests.scala, readme.adoc, runner/src/mill/runner/Parsers.scala
This is basically a port of the following fix in the Ammonite repo https://github.com/com-lihaoyi/Ammonite/pull/1361. There were some changes when the logic was first ported from Ammonite to Mill, resulting in a much smaller code change than was necessary in the Ammonite repo
There are two related follow up PRs that AFAICT do not apply to Mill: https://github.com/com-lihaoyi/Ammonite/pull/1363 
and https://github.com/com-lihaoyi/Ammonite/pull/1369. Both have to do with the special handling of multi-statement top-level-blocks `{...}`, that is a thing in the Ammonite REPL (to allow multiple top-level declarations to be entered into the REPL before submitting it) but doesn't apply to Mill scripts.
I have updated the integration tests to include a bunch of random comments and imports to …
=> Fix line numbers in errors for scripts starting with leading comments or whitespace

example/tasks/1-task-graph/build.sc, example/tasks/1-task-graph/src/Foo.java, example/tasks/8-diy-java-modules/build.sc, main/graphviz/src/mill/main/graphviz/GraphvizTools.scala
Makes both a bit prettier in preparation for usage in slides for Scaladays 2023 Madrid
For the SVG visualization, I replaced the oval node shape with rectangular nodes, and make it go from left-to-right with the arrows pointing in the direction of the dataflow. This makes it much easier to read because nodes tend to be more wide than tall, and the graph tends to be more wide than deep, so having sibling nodes stack up vertically ends up being much more compact than having them side-by-side horizontally
=> Tweak examples and visualize rendering

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala, runner/src/mill/runner/MillBuildRootModule.scala, scalalib/src/mill/scalalib/Lib.scala
Also fixed use of hardcoded repositories set. This code was previously located in the GenIdea and moved here. But we now have proper access to the build module repositories, so using hardcoded repos is no longer justified.
=> Don't fetch sources when not explicitly requested for

build.sc, docs/modules/ROOT/pages/Extending_Mill.adoc, docs/modules/ROOT/pages/Intro_to_Mill.adoc, example/misc/4-mill-build-folder/build.sc, example/misc/5-module-run-task/build.sc, runner/src/mill/runner/MillBuild.scala, runner/src/mill/runner/MillBuildBootstrap.scala, runner/src/mill/runner/MillCliConfig.scala, runner/src/mill/runner/MillMain.scala, runner/src/mill/runner/RunnerState.scala
Add a new CLI option `--meta-level` accepting an `Int`. Default is `0` and means the root project, `1` is the parent meta-build, if defined, or the built-in bootstrap module, and so on.
This is a first draft, to get more familiar with the recursive but mutable nature of our meta-build support.
Don't hesitate to point out shortcomings.
* Fixes https://github.com/com-lihaoyi/mill/issues/2658
Review by @lihaoyi
**Example: Find version updates in the meta build**
Here is some example output (applied to the mill repo):
``` 
$ mill --meta-level 1 mill.scalalib.Dependency/showUpdates
[1657/1657] dev.run 
Found 3 dependency update for 
net.sourceforge.htmlcleaner:htmlcleaner : 2.25 -> 2.26 -> 2.27 -> 2.28 -> 2.29
com.lihaoyi:mill-contrib-buildinfo_2.13 : 0.11.2-6-261437 -> 0.11.2 …
```
=> Allow Mill CLI to select the meta-build frame it operates on

build.sc, example/basic/4-builtin-commands/build.sc, example/cross/10-static-blog/build.sc, example/misc/3-import-file-ivy/build.sc, example/misc/4-mill-build-folder/build.sc, example/misc/4-mill-build-folder/mill-build/build.sc, example/thirdparty/jimfs/build.sc, scalalib/src/mill/scalalib/JavaModule.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala
Fixes https://github.com/com-lihaoyi/mill/issues/2732
We introduce a new `localCompileClasspath`, which differs from `compileClasspath` in that it leaves out the `transitiveCompileClasspath` from upstream modules and `resolvedIvyDeps` from third party dependencies.
Also tried to do some cleanup of `JavaModule`, refactoring out a `transitiveModuleCompileModuleDeps` helper to DRY things up, re-arranging things so all the `fooModuleDeps` helpers are all together.
Tested via a new unit test `mill.scalalib.HelloWorldTests.multiModuleClasspaths`, which fails on master and passes on this PR. This test case asserts the overall "shape" of the classpaths, which should help rule out an entire class of mis-configuration w.r.t. how the classpaths are wired up
=> Fix conflicting dependencies between upstream `JavaModule`s

build.sc, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalalib/src/mill/scalalib/Dep.scala, scalalib/src/mill/scalalib/Lib.scala
In Scala 3 modules, that also define a platform, the scala library is not correctly resolved.
The current implementation exists merely as a convenience for JS and Native modules. `ScalaNativeModule` already handles a correct scala library by overriding `scalaLibraryIvyDeps`. This pull request overrides the same in `ScalaJSModule` and removed the faulty platfrom dependency from `ScalaModule`.
E.g. imagine, someone tries to build a Mill plugin with Scala 3 (which is currently not supported) and sets the platform to `_mill0.11`, then you would run into the following issue:
```scala
object root extends ScalaModule {
override def scalaVersion = "3.3.0"
override def platformSuffix = "_mill0.11"
// ..
}
```
```
>> mill ivyDepsTree
resolvedIvyDeps
Resolution failed for 1 modules: …
```
=> Fix the scala-library dependency for (generic) platform modules

main/api/src/mill/api/SystemStreams.scala, main/util/src/mill/util/Jvm.scala, scalalib/src/mill/scalalib/ScalaModule.scala
Tries to fix https://github.com/com-lihaoyi/mill/issues/2704 by ensuring the system streams are properly inherited when running `.console` or `.repl` with `-i`.
Tested via
```bash
> ./mill show dev.launcher
> cd example/basic/1-simple-scala
> /Users/lihaoyi/Github/mill/out/dev/launcher.dest/run  -i console
```
Notably this cannot be tested via `dev.run`, because we would need to apply the same `SystemStreams.withStreams(SystemStreams.original)` wrapper to `dev.run`, which would first require re-bootstrapping Mill on top of this PR
=> Try to fix console and .repl

main/define/src/mill/define/Discover.scala, main/resolve/src/mill/resolve/Resolve.scala
fixes #2749
The basic problem is that the signature of `Discover.apply()` changed, but it only changed in the argument's generic type parameters, so it was nominally the same type after erasure, and accepted the `Map[Class[_], Seq]` even though it was expecting a `Map[Class[_], (Seq, Seq)]`, but later on in the code it would blow up with a `ClassCastException`
This causes problems with Mill plugins containing external modules, which have their own `Discover[T]` macro pre-expanded and would not get re-compiled with the new 0.11.3 version of Mill.
This PR works around the problem by adding a forwarder `Discover.apply(value: Map[Class, Seq])` that does the right thing and expands the `Seq` into a `(Seq, Seq)`, while adding a dummy paramter to `case class Discover` to avoid conflicts. A …
=> Fix sneaky binary incompatibility in Discover.scala

build.sc
This version comes will less transtive dependencies.
=> Update jarjar-abrams-core to 1.9.0

build.sc, integration/feature/watch-source-input/test/src/WatchSourceInputTests.scala, runner/src/mill/runner/MillBuildRootModule.scala
The Scala version used in `MillBuildBootstrapModule` to compile the `build.sc` was hardcoded to `2.13.10`. Instead, we want to always use the same version we used to build that Mill version.
As an side effect, Mill is now compatible with new Java 21, due to the use of a newer Scala version.
=> Fix some hardcoded scala versions

example/scalabuilds/6-publish-module/build.sc
A few years ago how to handle `gpg`'s changing requirements were extensively discussed here, and very reasonably resolved. See https://github.com/com-lihaoyi/mill/pull/753
Nevertheless, having just upgraded from a very ancient `gpg`, I hit this issue and it took a small storm of googling to figure it out. Maybe it's worth adding a note to the documentation?
=> Add note about gpg --pinentry-mode=loopback argument to documentation

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala, scalajslib/worker-api/src/mill/scalajslib/worker/api/ScalaJSWorkerApi.scala, scalajslib/worker/1/src/mill/scalajslib/worker/ScalaJSWorkerImpl.scala
This PR contains various optimizations in `ScalaJSModule` and `ScalaJSWorkerImpl`.
Changes:
- Limit the conversions between types and try to propagate the values to the worker to avoid allocations
- Avoid manually splitting `sjsir` files and `jar` files manually and let the Scala.js toolchain do it with `PathIRContainer.fromClasspath(runClasspath)` passing the full runClasspath
- Avoid allocating extra lists
- Cache the `IRFileCache.Cache` together with the linker so it can be reused in multiple invocations of `fastLinkJS`
Pull request: https://github.com/com-lihaoyi/mill/pull/2783
=> Optimize ScalaJSModule and cache `IRFileCache`

runner/src/mill/runner/MillBuildBootstrap.scala
The Mill executable is a static file that is downloaded and doesn't change. Changing the `PathRef` calculation to `quick = true` makes it invalidate the cache everytime the mill executable changes.
Before it took ~160ms, after it takes ~100μs ~100 times faster. This code runs twice on every Mill command line task execution.
This also stores the `PathRef`s in memory so they don't need to be computed on every command invocation
Pull request: https://github.com/com-lihaoyi/mill/pull/2785
=> Use `quick = true` when calculating PathRef for Mill executable

main/api/src/mill/api/MillException.scala, runner/src/mill/runner/MillMain.scala, runner/src/mill/runner/MillServerMain.scala
_I needed this in various situations, so I created this PR as a base for other PRs. It's ok to keep this unmerged until we need it._
Not all build inconsistencies can't be detected before we start evaluation and not all can be reported as evaluation errors, hence this PR add an additional way to exit Mill with a proper error message. You can throw a `mill.api.MillException`. It will be handled in `MillMain` as well as `MillClientMain`, our central entry points to Mill. The error message will be reported to the user and Mill exits with code 1. No stack trace will be shown.
Pull request: https://github.com/com-lihaoyi/mill/pull/2789
=> Introduce `mill.api.MillException` to transport the error condition

scalalib/src/mill/scalalib/ScalaModule.scala
This PR changed the behavior of `ScalaModule.prepareOffline`. Before, it only fetched the compiler bridge when the `--all` flag was given. But the compiler bridge is always needed to compile, hence I removed the need for the `--all` flag.
* Fix https://github.com/com-lihaoyi/mill/issues/2632
Pull request: https://github.com/com-lihaoyi/mill/pull/2791
=> Always resolve compiler bridge in `prepareOffline`

bsp/worker/src/mill/bsp/worker/BspCompileProblemReporter.scala, bsp/worker/src/mill/bsp/worker/BspTestReporter.scala, bsp/worker/src/mill/bsp/worker/MillBspLogger.scala, bsp/worker/src/mill/bsp/worker/MillBuildServer.scala, bsp/worker/src/mill/bsp/worker/MillJavaBuildServer.scala, bsp/worker/src/mill/bsp/worker/MillJvmBuildServer.scala, bsp/worker/src/mill/bsp/worker/MillScalaBuildServer.scala, bsp/worker/src/mill/bsp/worker/State.scala, build.sc, main/api/src/mill/api/Result.scala
This PR adapts the Mill BSP server to the latest bsp4j API changes (binary incompatible). This will eventually end up in BSP protocol version `2.2.0`.
Pull request: https://github.com/com-lihaoyi/mill/pull/2794
=> Update bsp4j to 2.1.0-M6 and adapt to breaking API changes

.github/workflows/run-mill-action.yml
Some integration tests fail due to hanging client-server comunication.
This PR lowers the timeout form 360 to 90 minutes, to detect failing CI runs earlier.
=> CI: lower job timeout to 90 minutes

main/util/src/mill/util/Jvm.scala, scalalib/src/mill/scalalib/JavaModule.scala
Replaces https://github.com/com-lihaoyi/mill/pull/2755, which has grown complicated and unwieldy for the very limited benefit it might provide.
Allow stdout/stderr outputs for the built-in `runBackground` tasks to be controlled by an overridable
```scala
def runBackgroundLogToConsole: Boolean = true
```
If true, output goes to `os.Inherit`, usually the mill console. If false, output goes to `runBackground.dest/stdout.log` (+ `stderr.log`).
People who prefer elsewheres for these streams can implement their own `runBackground` tasks in terms of `doRunBackground(...)`. (Previously this was difficult, because the `mill.util.Jvm` run/spawn methods did not permit specifying stream destinations, and because the `backgroundSetup(...)` method is private.)
Pull request: …
=> Simple control over runBackground stdout/stderr streams

contrib/scalapblib/src/mill/contrib/scalapblib/ScalaPBModule.scala
It is possible that unpacked files from the classpath share the same name but not the same content. In case an existing unpacked file is replaced by a shorter file, it needs to be properly truncated lest the result be garbage.
A warning messages is logged when a proto file gets overwritten.
Pull request: https://github.com/com-lihaoyi/mill/pull/2800
=> protobuf module: fix truncation issue when unpacking

bsp/worker/src/mill/bsp/worker/BspCompileProblemReporter.scala
Previously we were emitting different URI formats if the sourceFile info was missing or not.
Not sure if this is a problem, but `targetId.getUri` is returning files as `file:///foo/bar/file.scala` while our `java.io.File` `toURI` returns `file:/foo/bar/file.scala`
Changing it to `.toPath.toUri` for consistency
=> [BSP] Use consistent file URI format

main/eval/src/mill/eval/EvaluatorImpl.scala, main/eval/src/mill/eval/GroupEvaluator.scala, main/testkit/src/mill/testkit/MillTestkit.scala, runner/src/mill/runner/MillBuildBootstrap.scala
Fixes #2802
Pull request: https://github.com/com-lihaoyi/mill/pull/2809
=> Use project root as `T.workspace` also in meta-build

scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
The Scala 3 compiler is not calling `startUnit` as the Scala 2 compiler. I checked what sbt is doing and it sends a build/publishDiagnostics for all the compiled files at the end of compilation. So I'm doing the same here.
I removed the `CompileProgress` and I'm calling fileVisited for all input files instead.
I tried to not touch the `CompileProblemReporter` trait for now since it's public API and I don't want to deal with the binary compatibility issues. Moreover, our current `fileVisited` API seems more than enough.
Fixes https://github.com/com-lihaoyi/mill/issues/2426
Pull request: https://github.com/com-lihaoyi/mill/pull/2810
=> fix: Errors not cleaning up in BSP for Scala 3

build.sc
This should fix the Java 8 incompatibility of 2.1.0-M6
Pull request: https://github.com/com-lihaoyi/mill/pull/2813
=> Update bsp4j to 2.1.0-M7

.github/workflows/publish-bridges.yml, build.sc
Releasing a new version of the bridge just for adding a Scala version is wasteful.
We can publish the bridge just for the new version (in our case `2.13.12`) without tagging a `0.0.2`.
This PR adds a `bridge_versions` input to the `workflow_dispatch` which can be `all` for the current behavior or a comma separated list of Scala versions. This way we can release the current bridge for Scala `2.13.12` and then add `2.13.12` to the list of supported bridges in a later PR.
=> Allow publishing bridge for a single version

main/eval/src/mill/eval/EvaluatorCore.scala, main/eval/src/mill/eval/JsonArrayLogger.scala
Chrome profiles support microsecond precision, so we can use `System.nanoTime` instead of `System.currentTimeMillis` to have better profiles
=> Microsecond precision in chrome profile

build.sc
`mill-scala-compiler-bridge_2.13.12` `0.0.1` is already on Maven Central so we can add `2.13.12` to the list of the supported versions. This way Mill will use published artifact instead of compiling from sources
Pull Request: https://github.com/com-lihaoyi/mill/pull/2830
=> Add 2.13.12 to compiler bridge versions

main/api/src/mill/api/PathRef.scala
Attempts to fix https://github.com/com-lihaoyi/mill/issues/2808
No real tests; the failure is timing-dependent and hard to reproduce. But hopefully just wrapping everything up in a big try-catch will fix it
Pull request: https://github.com/com-lihaoyi/mill/pull/2832
=> Try to make `PathRef` robust against concurrent filesystem modifications

scalalib/src/mill/scalalib/ScalaModule.scala
Currently, if I run `mill foo.console` without the `--interactive` flag, I get a warning and then a nonfunctional REPL:
```plaintext
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
scala> // does not respond to input
```
This PR just changes the test for interactivity in the `console` command to one that seems to work (at least in my environment). When `console` is invoked without the `--interactive` flag, the intended warning is emitted and the command fails:
```plaintext
main.console console needs to be run with the -i/--interactive flag
```
(`mill -i foo.console` works with or without this PR. This just restores the warning.)
=> Fix not-interactive warning for mill console

contrib/buildinfo/src/mill/contrib/buildinfo/BuildInfo.scala
The current Scala implementation just does not load the expected values from the resource file, when the resource file can not be found on the classpath. The Java implementation already throws a `RuntimeException` (of an `IOException`) in this case. The Scala implementation does not.
I think missing a generated resource file at runtime is most likely an runtime issue and we should also throw such exception in the Scala implementation to exit early, before a missing value can cause greater harm later. Hence, we now also throw a `RuntimeException` when the resource file/stream could not be found in the Scala implementation.
Fix https://github.com/com-lihaoyi/mill/issues/2831
=> Handle potential null-stream in buildinfo plugin

main/api/src/mill/api/PathRef.scala, main/util/src/mill/util/Util.scala, scalalib/src/mill/scalalib/CoursierModule.scala, scalalib/src/mill/scalalib/Lib.scala
This change sets the `revalidate` flag on the coursier resolved pathrefs in more situations, to better detect the case, that the cache might have changed.
Fix https://github.com/com-lihaoyi/mill/issues/2845
Pull request: https://github.com/com-lihaoyi/mill/pull/2846
=> Enable pathref revalidation for all coursier downloads

ci/shared.sc, main/api/src/mill/api/IO.scala
Specially prepared zip archives with crafted entries containing relative paths may result in overwritten files outside the destination directory. By using `os.SubPath`, we detect and fail in such cases.
=> Fix Zip Slip Vulnerabilities

docs/modules/ROOT/pages/Scala_Module_Config.adoc, scalalib/api/src/mill/scalalib/api/ZincWorkerApi.scala, scalalib/src/mill/scalalib/JavaModule.scala, scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/src/mill/scalalib/SemanticDbJavaModule.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
This was sparked by [a conversation in gitter](https://matrix.to/#/!zXvttAKLPnvdnmiYsY:matrix.am/$C1K_tZdqQwKYjFfDXcmd3kbLWRBhYcMo2cggtG6S_wM?via=matrix.am&via=gitter.im&via=matrix.org) about forcing a full recompile for a given module.
The change to `ZincWorkerApi` is not binary compatible, but it could be if I added overloads for both `compileJava` and `compileMixed` -- let me know if you think I should.
=> Add an option to disable incremental compilation with zinc

contrib/playlib/readme.adoc, contrib/playlib/src/mill/playlib/Server.scala, contrib/playlib/src/mill/playlib/SingleModule.scala, contrib/playlib/test/src/mill/playlib/PlayModuleTests.scala
- Update Play documentation
- Deprecate `SingleModule` trait
Pull Request: https://github.com/com-lihaoyi/mill/pull/2862
=> Use play-pekko-http-server in Play 3

main/client/src/mill/main/client/MillClientMain.java
Attempt to fix https://github.com/com-lihaoyi/mill/issues/2805 We now catch the exception, delete the content of the mill-worker-xyx directory and try again.
Seems to be working correcly from manual tests.
Pull request: https://github.com/com-lihaoyi/mill/pull/2879
=> Recover from client connection errors

bsp/src/mill/bsp/BspContext.scala, main/api/src/mill/api/Logger.scala, main/eval/src/mill/eval/GroupEvaluator.scala, main/src/mill/main/MainModule.scala, main/util/src/mill/util/DummyLogger.scala, main/util/src/mill/util/FileLogger.scala, main/util/src/mill/util/MultiLogger.scala, main/util/src/mill/util/PrefixLogger.scala, main/util/src/mill/util/PrintLogger.scala, main/util/src/mill/util/ProxyLogger.scala, tmp/build.sc
This requires us add another method `Logger#rawOutputStream`, which the various implementations forward without decorating with prefixes or other things. 
We cannot just use `SystemStreams.original` because when running Mill in client/server mode we still need to use the `OutputStream` that gets forwarded from server to client, as the `SystemStreams.original.out` just ends up forwarded to `out/mill-worker-hash-1/stdout` files that aren't surfaced to users
Tested manually with `./mill -i dev.run tmp -i -j 2 show foo` on an example build in the `tmp/` folder. Previously it would show the output of `show` with a prefix e.g. `[#0] "bar"`, after this PR it shows the output without any prefixes `"bar"`
`Logger#rawOutputStream` has to be a non-abstract method for binary compatibility. This makes …
=> Make `mill show` skip `-j` prefixes to ensure machine readability

build.sc, main/eval/src/mill/eval/GroupEvaluator.scala
This is related to #2844.
We report the target name in case we weren't able to detect it's declaring parent class.
Tested manually with a Mill version before the merge of #2883.
```scala
// /tmp/mill-2844/build.sc
import mill._
object mod extends Module {
object foo extends Module {
def bar = T {
baz()
}
}
private def baz = T { "baz" }
}
```
```
> mill -i dev.run /tmp/mill-2844 -i mod.foo.bar
[1691/1691] dev.run 
[info] compiling 1 Scala source to /tmp/mill-2844/out/mill-build/compile.dest/classes ...
[info] done compiling
Could not detect the parent class of target mod.baz. Please report this at https://github.com/com-lihaoyi/mill/issues/new/choose. As a workaround, you can run Mill with `--disable-callgraph-invalidation` option.
```
Pull request: …
=> Report when we could not detect the declaring parent of a target

scalajslib/test/src/mill/scalajslib/ScalaTestsErrorTests.scala, scalalib/src/mill/scalalib/JavaModule.scala, scalalib/src/mill/scalalib/ScalaModule.scala, scalanativelib/test/src/mill/scalanativelib/ScalaTestsErrorTests.scala
This puts all checks/assertions into a `protected def hierarchyChecks`, so users have an option to allow trait mix-ins which don't make sense to us now, by overriding it.
I split the logic in a set of matching trait names and the assertion logic. I also added `MavenModule` and `SbtModule` to the mix. To get that working, I moved the logic up into `JavaModule`.
=> Put hierarchy checks for test trait behind an overridable def

scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala, scalanativelib/src/mill/scalanativelib/api/ScalaNativeApi.scala, scalanativelib/worker-api/src/mill/scalanativelib/worker/api/ScalaNativeWorkerApi.scala, scalanativelib/worker/0.4/src/mill/scalanativelib/worker/ScalaNativeWorkerImpl.scala, scalanativelib/worker/0.4/src/mill/scalanativelib/worker/scala/scalanative/Utils.scala
This allows to build static and dynamic libraries other than binaries.
Pull Request: https://github.com/com-lihaoyi/mill/pull/2898
=> Support Scala Native build target

build.sc
Newer versions no longer support Java 8.
Added some Scala Steward in-place configuration.
=> Update scalafmt to 3.7.15

scalalib/src/mill/scalalib/CoursierModule.scala, scalalib/test/resources/coursier/mirror.properties, scalalib/test/src/mill/scalalib/CoursierMirrorTests.scala
Fix #2312 
Copied from 
https://github.com/coursier/coursier/blob/main/modules/coursier/shared/src/main/scala/coursier/Resolve.scala#L61
It is possible to use `Resolve().finalRepositories.future()`  to avoid the implementation detail.
But that requires `Await` and `ExecutionContext`,  I'm not sure whether worth doing it.
=> Apply coursier default config files (repositories and mirrors config)

main/client/src/mill/main/client/MillClientMain.java
On WSL(1), Mill does not support client-server mode.
As a consequence, we always need to run without a server.
=> Better detect Windows Subsystem for Linux environments

scalalib/src/mill/scalalib/Dependency.scala, scalalib/src/mill/scalalib/dependency/DependencyUpdatesImpl.scala, scalalib/src/mill/scalalib/dependency/Format.scala, scalalib/src/mill/scalalib/dependency/updates/DependencyUpdates.scala, scalalib/src/mill/scalalib/dependency/updates/ModuleDependenciesUpdates.scala
Previously, we always presented all possible updates per modules.
Since, many Mill projects declare dependencies in a shared location
and use the same versions in all modules, this list can be rather long
and redundant.
This change adds a new `--format` option to select the format,
when searching for dependency updates. The old format is now named
`PerModule` and is the default (for compatibility).
Example:
```
> mill --meta-level 1 mill.scalalib.Dependency/showUpdates
Found 1 dependency update for root module
io.github.classgraph:classgraph : 4.8.164 -> 4.8.165
```
I also added a new `PerDependency` format, which presents the dependency
with all it's possible versions and all affected modules.
Example:
```
> mill --meta-level 1 mill.scalalib.Dependency/showUpdates --format PerDependency …
```
=> Added per-dependency format to dependency update finder

.github/workflows/actions.yml, .scalafix.conf, build.sc, contrib/scoverage/src/mill/contrib/scoverage/ScoverageReportWorker.scala, contrib/twirllib/src/mill/twirllib/TwirlWorker.scala, idea/src/mill/idea/GenIdeaImpl.scala, integration/feature/private-methods/test/src/PrivateMethodsTests.scala, main/define/src/mill/define/EnclosingClass.scala, main/eval/src/mill/eval/EvaluatorCore.scala, main/eval/src/mill/eval/GroupEvaluator.scala, scalalib/src/mill/scalalib/Dep.scala, scalalib/src/mill/scalalib/GenIdeaImpl.scala
Spiritual successor to #2776. This PR makes it such that no more unused imports will slip in in future, and allows them to be auto-fixed via `./mill __.fix`
Pull request: https://github.com/com-lihaoyi/mill/pull/2918
=> Enforce ScalaFix unused imports and other things during PR validation

scalalib/src/mill/scalalib/ScalaModule.scala
As the Scala compiler is most likely only used via the build tool,
and there is probably not the exact scalac version installed on the system,
it can get tricky to find the right options for a specific Scala version.
This adds a new `scalacHelp` command to the `ScalaModule` with which one
can get the scalac built-in help with Mill.
```
> mill foo.scalacHelp
Output of scalac version: 2.13.11
with options: -help
Usage: scalac <options> <source files>
Standard options:
-Dproperty=value             Pass -Dproperty=value directly to the runtime system.
-J<flag>                     Pass <flag> directly to the runtime system.
-P:<plugin>:<opt>            Pass an option to a plugin
-V                           Print a synopsis of verbose options. [false]
-W                           Print a …
```
=> Add `ScalaModule.scalacHelp` command

idea/src/mill/idea/GenIdeaImpl.scala, integration/feature/gen-idea/repo/extended/idea/mill_modules/helloworld.test.iml, integration/feature/gen-idea/repo/hello-world/idea/mill_modules/helloworld.test.iml
This is to have explicitly configured lib dependencies before (unwanted) transitive ones from module dependencies.
* Fix https://github.com/com-lihaoyi/mill/issues/2924
=> GenIdea: Put module dependencies after library dependencies

example/web/1-todo-webapp/build.sc, example/web/2-webapp-cache-busting/build.sc, example/web/4-webapp-scalajs/build.sc, example/web/5-webapp-scalajs-shared/build.sc
Calling a `RootModule` `app` gives the false impression that its `millSourcePath` is `./app` when, in reality, it's the project root directory. `root` makes it more obvious.
Pull Request: https://github.com/com-lihaoyi/mill/pull/2928
=> Use root as the name for `RootModule`s in examples

.scalafmt.conf
This ensures that if someone is using `scalafmt` via the CLI that it
correctly knows to ignore Scala files that are also ignored via git.
Without this locally when I used `scalafmt` from the command line I got
a ton of undesired changes.
=> fix: set `project.git = true` in scalafmt settings

scalalib/src/mill/scalalib/JavaModule.scala, scalalib/src/mill/scalalib/ScalaModule.scala
it was not reporting `BuildTarget.dataKind` and `data` such that IJ will not ask `BuildTargetJavacOptions` for JavaModule and resolved as no dependency at all.
=> BSP: Add JavaModule.bspBuildTargetData to make JavaModule reports workable BuildTarget

scalalib/src/mill/scalalib/SemanticDbJavaModule.scala
This makes it accessible for downstream tooling.
* Use case: https://github.com/joan38/mill-scalafix/pull/172
Essentially, this is a backport of what we have in Mill 0.11, so this PR is in the spirit of the previous pull requests we merged.
=> Make semanticDbEnablePluginScalacOptions protected

scalalib/test/resources/hello-world-color-output/core/src/Main.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
Fixes #2947
Pull Request: https://github.com/com-lihaoyi/mill/pull/2950
=> Enable colored output for Scala 2

main/src/mill/main/RunScript.scala
Fixes #2946
In `evaluateNamed`, after evaluating `Task`s we are matching for `ImputImpl[_]` instances to construct a `Watchable`.
A `Watchable` instance contains a `hashCode` for the current result and a callback to evaluate it again and get the next result.
Instead of using the current result which was contained in `TaskResult`, we were already calling the `recalc` callback, which executes again the `T.input`s and performs their side effects twice.
Now we are returning the hashCode for the already computed result, so we don't execute the `recalc` callback right away.
Pull Request: https://github.com/com-lihaoyi/mill/pull/2952
=> Fix #2946: Avoid evaluating `T.input`s twice
