core/src/main/scala/mill/eval/Evaluator.scala
I think should use NonFatal here
=> = core use NonFatal

.travis.yml
=> [WIP] Basic CI infrastructure

scalalib/src/main/scala/mill/scalalib/GenIdea.scala
1. add resources as source.
2. I've tested that more than one  `<output>` attribute is not supported, the first one declared will be picked up. 
Issues remaining: https://github.com/lihaoyi/mill/issues/112
=> More GenIdea fixes. 

.gitignore, scalalib/src/main/scala/mill/scalalib/GenIdea.scala, scalalib/src/test/resources/gen-idea/idea/libraries/modules_scala-xml_2.12_1.0.6_scala-xml_2.12-1.0.6-sources.jar.xml, scalalib/src/test/resources/gen-idea/idea/libraries/modules_scala-xml_2.12_1.0.6_scala-xml_2.12-1.0.6.jar.xml, scalalib/src/test/resources/gen-idea/idea/libraries/scala-compiler_2.12.4_scala-compiler-2.12.4-sources.jar.xml, scalalib/src/test/resources/gen-idea/idea/libraries/scala-compiler_2.12.4_scala-compiler-2.12.4.jar.xml, scalalib/src/test/resources/gen-idea/idea/libraries/scala-library_2.12.4_scala-library-2.12.4-sources.jar.xml, scalalib/src/test/resources/gen-idea/idea/libraries/scala-library_2.12.4_scala-library-2.12.4.jar.xml, scalalib/src/test/resources/gen-idea/idea/libraries/scala-reflect_2.12.4_scala-reflect-2.12.4-sources.jar.xml, scalalib/src/test/resources/gen-idea/idea/libraries/scala-reflect_2.12.4_scala-reflect-2.12.4.jar.xml, scalalib/src/test/resources/gen-idea/idea/misc.xml, scalalib/src/test/resources/gen-idea/idea/modules.xml, scalalib/src/test/resources/gen-idea/idea_modules/iml, scalalib/src/test/resources/gen-idea/idea_modules/root.iml, scalalib/src/test/scala/mill/scalalib/GenIdeaTests.scala
resolving #51. Great issue btw.
Can be improved, but I think this what we want for now.
=> add a basic test for gen-idea

.travis.yml
Attempt to resolve: https://travis-ci.org/lihaoyi/mill/jobs/331240339
Based on: https://github.com/travis-ci/travis-ci/issues/3775#issuecomment-316569604
VM should have more resources than container
=> Run travis in VM instead of container to resolve issue with fork main

core/src/mill/main/ReplApplyHandler.scala
this used to work but stopped, I guess, after some on segments
=> fix introspection of children on console (eg build)

scalajslib/jsbridges/0.6/src/mill/scalajslib/bridge/ScalaJSBridge.scala, scalajslib/jsbridges/1.0/src/mill/scalajslib/bridge/ScalaJSBridge.scala, scalajslib/src/mill/scalajslib/ScalaJSBridge.scala, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/test/src/mill/scalajslib/HelloJSWorldTests.scala
=> scala.js run

scalalib/src/mill/scalalib/GenIdea.scala, scalalib/test/resources/gen-idea/idea_modules/iml, scalalib/test/resources/gen-idea/idea_modules/root.iml, scalalib/test/src/mill/scalalib/GenIdeaTests.scala
A few GenIdea updates - the commit messages describe them fairly well I hope.
=> GenIdea updates including a fix for #147

build.sc, docs/pages/2 - Configuring Mill.md, docs/pages/6 - Extending Mill.md, integration/test/resources/acyclic/build.sc, integration/test/resources/ammonite/build.sc, integration/test/resources/better-files/build.sc, integration/test/resources/jawn/build.sc, integration/test/resources/upickle/build.sc, main/test/src/mill/define/DiscoverTests.scala, main/test/src/mill/util/TestGraphs.scala, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/test/src/mill/scalajslib/HelloJSWorldTests.scala, scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/src/mill/scalalib/ScalaWorkerApi.scala, scalalib/src/mill/scalalib/TestRunner.scala, scalaworker/src/mill/scalaworker/ScalaWorker.scala
This PR add suport for multiple testing frameworks in one test module.
=> support multiple test frameworks

docs/pages/1 - Intro to Mill.md
documentation missing an _ for recursive variant of resolve
=> documentation, v. minor fix: _ missing

scalalib/src/mill/scalalib/GenIdea.scala
This pull request adds generation of .idea/scala_compiler.xml for scalac compiler plugins and options.
=> GenIdea: added generation of .idea/scala_compiler.xml

scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalajslib/test/resources/multi-module/client/src/Lib.scala, scalajslib/test/resources/multi-module/client/src/Main.scala, scalajslib/test/resources/multi-module/client/test/src/MainTests.scala, scalajslib/test/resources/multi-module/shared/src/shared/Utils.scala, scalajslib/test/src/mill/scalajslib/HelloJSWorldTests.scala, scalajslib/test/src/mill/scalajslib/MultiModuleTests.scala, scalajslib/test/src/mill/scalajslib/ScalaJsUtils.scala
This PR adds support for multi-module builds with scala js. Also fixes issues with running tests on multi-module builds
=> Scala js multi modules support

build.sc
=> fix #139 upgrade jline to 2.14.5

scalalib/src/mill/scalalib/Lib.scala
the diff looks a bit messy but it's most just cut and paste
=> factor out Dependency creation in Lib so it can be reused

scalaworker/src/mill/scalaworker/ScalaWorker.scala
fix #174 skip interfaces when finding tests
=> fix #174 skip interfaces when finding tests

docs/pages/1 - Intro to Mill.md
There is now a homebrew package for mill.
=> OSX - homebrew package

main/src/mill/main/MainModule.scala
=> MainModule/resolve: print results sorted alphabetically

build.sc, clientserver/src/mill/clientserver/Client.java, core/src/mill/util/ClassLoader.scala, scalalib/src/mill/scalalib/ScalaModule.scala, scalalib/src/mill/scalalib/ScalaWorkerApi.scala
=> Fixes for non-interactive (client/server) mode on Java 9

docs/pages/1 - Intro to Mill.md
=> add "-i" flag to docs examples

scalalib/src/mill/scalalib/GenIdea.scala
this is for users behind proxy to be able to generate idea project using `mill`
=> use repositories from the mill build to bootstrap idea proj generation

main/src/mill/main/RunScript.scala
This PR allows users to run commands from mill's MainModule without build.sc file
`mill version` gives following output:
```
➜  mill-empty mill version
No build file found, you should create build.sc to do something useful
[1/1] version
0.2.0-13-d86494-DIRTYaeada95f
```
But this can also lead to errors when we run `GenIdea/idea` with empty build file - it will surely fail.
=> don't fail command when there is no build.sc file in directory

docs/pages/4 - Tasks.md
Added s to T.source and fixed small typo
=> Update 4 - Tasks.md

docs/pages/1 - Intro to Mill.md
=> fix download url typo

docs/pages/2 - Configuring Mill.md
The Unmanaged Jars snippet currently shown is not working, updated with correct solution as per closed issue #361.
=> Correct Unmanaged Jars snippet

scalalib/worker/src/mill/scalalib/worker/ScalaWorker.scala
They will be classloaded by the compiler itself based on -Xplugin.
=> Plugins do not belong on the compiler classpath

scalalib/worker/src/mill/scalalib/worker/ScalaWorker.scala
So far, Mill was caching ScalaInstance which contains a classloader but
this is not enough: Zinc creates its own classloader by combining the
ScalaInstance classloader with the path to the compiler-bridge. Zinc
takes care of caching this classloader in each instance of
ScalaCompiler.
We can take advantage of this by caching an instance of Compilers since
it contains everything we want to cache (ScalaCompiler and
ScalaInstance).
This significantly reduces the amount of classloading that happens
at each compilation step, as measured by running:
```scala
export _JAVA_OPTIONS="-XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+TraceClassUnloading"
mill -i foo.compile
```
Then looking at the output of `out/mill-worker-1/logs` while adding a
new line in a source file in `foo` and …
=> Make hot compilation 2x faster by properly reusing classloaders

docs/pages/9 - Contrib Modules.md
Add a quick documentation page for the ScalaPB module
=> Add documentation for ScalaPB module

docs/VisualizePlan.svg, docs/pages/1 - Intro to Mill.md, main/src/mill/main/MainModule.scala
@lihaoyi I figure out that I was needlessly converting the plan output to strings, and then when converting back to tasks which is why I was running into the problem with external modules.
This did not make sense anyway, and now everything should work as well.
Win-Win.
=> Make visualizePlan work with external modules

build.sc, contrib/buildinfo/src/mill/contrib/BuildInfo.scala, contrib/buildinfo/test/resources/buildinfo/src/Main.scala, contrib/buildinfo/test/src/mill/contrib/BuildInfoTests.scala, docs/pages/9 - Contrib Modules.md
Simple plugin to mimic sbt-buildinfo (https://github.com/sbt/sbt-buildinfo). Not remotely as fancy but so far worked without issues for us.
I will provide some tests in a later update.
=> Simple BuildInfo plugin

docs/VisualizePlan.svg, docs/build.sc, docs/pages/1 - Intro to Mill.md
Make VisualizePlan.svg available in docs and use simpler plan to fit better.
=> Visualize plan

docs/pages/4 - Tasks.md
=> minor typo in doc: four->three

docs/pages/5 - Modules.md
Addresses #448
Thought it'd be nice to add a statement in the docs about it. Also corrected a nearby typo ("built-in").
=> Elaborate docs on using traits v classes for modules

docs/pages/9 - Contrib Modules.md
Module is still in development, but can already produce proper bundles.
=> Added mill-osgi module to documentation, contrib modules

main/api/src/mill/api/Result.scala
@lihaoyi Can you please check if these are correct?
=> Added some docs to result type

main/api/src/mill/api/Result.scala, main/core/src/eval/Evaluator.scala, main/src/MillMain.scala, main/src/main/MainRunner.scala, main/src/main/MillServerMain.scala, main/src/main/ReplApplyHandler.scala, main/src/main/RunScript.scala, main/test/src/eval/FailureTests.scala, main/test/src/util/ScriptTestSuite.scala, main/test/src/util/TestEvaluator.scala, readme.md
=> Added fail-fast behavior and -k/--keep-going parameter to disable it

scalalib/worker/src/ZincWorkerImpl.scala
That way, we do not prevent class loader unloading / garbage collection.
Also, we reduce the chance to use an outdated class loader.
=> Only hold weak references to classloaders in internal cache

main/src/modules/Util.scala
Fixes https://github.com/lihaoyi/mill/issues/451
=> Properly strip scaladoc end tags

docs/pages/1 - Intro to Mill.md
Mill was recently added to the FreeBSD Ports Collection: https://www.freshports.org/devel/mill/
=> Add FreeBSD installation instructions

scalalib/api/src/ZincWorkerApi.scala
Also added some more checks to compiler bridge compilation.
This fixes #534.
=> Support for typelevel scala compiler

build.sc, scalalib/worker/src/ZincWorkerImpl.scala
Zinc was previously on on pre-release milestone (1.3.0-M1)
=> Revert Zinc to 1.2.5 to match release notes

main/src/MillMain.scala, main/src/main/MainRunner.scala, main/src/main/MillServerMain.scala, main/src/main/ReplApplyHandler.scala, main/src/main/RunScript.scala, main/test/src/main/ClientServerTests.scala, main/test/src/util/ScriptTestSuite.scala
See https://github.com/lihaoyi/mill/issues/498
See https://github.com/lihaoyi/mill/issues/499
=> Accept sysprops via cmdline and forward to mill server

main/src/modules/Jvm.scala, scalalib/test/src/HelloWorldTests.scala
=> Downstream files overwrite upstream files on assembly

docs/pages/9 - Contrib Modules.md
=> Docker module appears to be part of BuildInfo module

contrib/bloop/src/mill.contrib.bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
Realised that the classpath wasn't being set when no ivyDep was present 😅 
Also fixed modules not re-installing after change to build.sc
=> Fixed bloop config classpath element when no ivyDep is set

build.sc, contrib/bloop/src/mill.contrib.bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala, docs/pages/9 - Contrib Modules.md
This generates correct bloop configuration for ScalaJs/ScalaNative
module.
=> Bloop config for Js/Native modules

contrib/docker/src/DockerModule.scala
=> Put docker contrib module in a package

main/src/modules/Jvm.scala
Resolve one particular package type from https://github.com/lihaoyi/mill/issues/635
=> Support 'eclipse-plugin' type dependencies

main/src/modules/Jvm.scala
=> Support dependency type maven-plugin

.appveyor.yml, .travis.yml, build.sc, ci/publish-local.sh, ci/release.sh, ci/test-mill-0.sh, ci/test-mill-1.sh, ci/test-mill-2.sh, ci/test-mill-bootstrap.sh, ci/test-mill-dev.sh
We need to upgrade the mill version used in travis and appveyor to the current version that people are likely to be using
=> Fix build, split up release and assembly

readme.md
- Fix the `dev.run` command documentation in README
=> Improve ergonomics of running and generating the launcher script

scalalib/api/src/ZincWorkerApi.scala
Same change I made against zinc: https://github.com/sbt/zinc/pull/678
=> Future-proof isDotty check

scalalib/src/GenIdeaImpl.scala
Fixes https://github.com/lihaoyi/mill/issues/673
=> Fixed StringIndexOutOfBoundsException in case of short artifact names

scalalib/src/GenIdeaImpl.scala, scalalib/src/GenIdeaModule.scala, scalalib/src/JavaModule.scala, scalalib/test/resources/gen-idea-extended-hello-world/build.sc, scalalib/test/resources/gen-idea-extended-hello-world/idea/compiler.xml, scalalib/test/resources/gen-idea-extended-hello-world/idea/libraries/scala-library-2.12.4.jar.xml, scalalib/test/resources/gen-idea-extended-hello-world/idea/misc.xml, scalalib/test/resources/gen-idea-extended-hello-world/idea/modules.xml, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/helloworld.iml, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/helloworld.test.iml, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/mill-build.iml, scalalib/test/src/GenIdeaExtendedTests.scala
* Contribute Facets to JavaModule
* Generate additional files under .idea directory
=> Initial module-specific extension support to GenIdea

mill
resolves https://github.com/lihaoyi/mill/issues/669
=> Make mill wrapper backwards compatible

main/api/src/mill/api/JsonFormatters.scala
Fixes https://github.com/lihaoyi/mill/issues/690
=> Changed JSON encoding for StackTraceElement (filename is nullable)

scalalib/src/GenIdeaImpl.scala, scalalib/src/GenIdeaModule.scala, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/helloworld.iml, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/helloworld.test.iml, scalalib/test/resources/gen-idea-hello-world/idea_modules/helloworld.iml, scalalib/test/resources/gen-idea-hello-world/idea_modules/helloworld.test.iml
Fixes https://github.com/lihaoyi/mill/issues/693
=> Use a dedicated path/target for idea compiler output

scalalib/src/Dependency.scala, scalalib/src/dependency/DependencyUpdatesImpl.scala, scalalib/src/dependency/versions/VersionsFinder.scala
Might fix https://github.com/lihaoyi/mill/issues/689
=> Use explicitly given Evaluator instance for evaluation

docs/pages/2 - Configuring Mill.md
Instructions for specs2 as a custom testing framework.
=> Add docs for using specs2 for testing.

scalalib/src/JavaModule.scala
Implements https://github.com/lihaoyi/mill/issues/711
=> Added new target TestModule.testCached which caches the last test result

docs/pages/8 - Mill Internals.md
I'm just updating what I assume is a typo in the docs.
=> Grammar update in docs

scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/helloworld.iml, scalalib/test/resources/gen-idea-extended-hello-world/idea_modules/helloworld.test.iml, scalalib/test/resources/gen-idea-hello-world/idea_modules/helloworld.iml, scalalib/test/resources/gen-idea-hello-world/idea_modules/helloworld.test.iml
Fixes https://github.com/lihaoyi/mill/issues/728
=> Create separate content entries for generated sources

mill
Lots of fixes have gone in since 0.5.0
=> Bump bootstrap Mill to 0.5.2

contrib/scalapblib/src/ScalaPBModule.scala, contrib/scalapblib/src/ScalaPBWorker.scala, contrib/scalapblib/test/protobuf/tutorial/Include.proto, contrib/scalapblib/test/src/TutorialTests.scala
This allows using import with proto files in other path.
Also add task/option to define jar path and extract proto files from there, these with scalapb's jar provide some common wrappers.
=> Add extra include path option to scalapblib.

main/client/src/mill/main/client/MillClientMain.java, main/src/main/MillServerMain.scala
Fixes https://github.com/lihaoyi/mill/issues/557
=> Re-try starting mill server after detecting a changed version

build.sc, main/client/src/mill/main/client/FileToStreamTailer.java, main/client/src/mill/main/client/MillClientMain.java, main/client/test/src/mill/main/client/FileToStreamTailerTest.java, main/src/main/MillServerMain.scala
Related to https://github.com/lihaoyi/mill/issues/740
Related to #560
=> Write mill server output to files and forward their content into client (like tail -f)

.travis.yml, ci/release-github.sh, ci/release-maven.sh, docs/pages/1 - Intro to Mill.md, mill
=> Rebootstrap mill, split CI release process into two separate jobs

docs/pages/10 - Thirdparty Modules.md
I'm not the author of the mentioned plugin, but the existing link was dead, so I replaced it with one, which I *think* is the right one.
Review suggestions: @davoclavo
=> Fixed link and updated docs for mill-ensime plugin

main/src/MillMain.scala
Fixes https://github.com/lihaoyi/mill/issues/491
=> Added --version option including the Java version and locale info

build.sc, scalanativelib/src/ScalaNativeModule.scala
- Add missing test-runner in Scala Native tools
=> Fix Scala Native for testing libraries

docs/pages/10 - Thirdparty Modules.md
See https://github.com/lefou/mill-kotlin
=> Added mill-kotlin contrib module

scalanativelib/src/ScalaNativeModule.scala, scalanativelib/test/resources/hello-native-world/test/src/utest/EmptyPackageTests.scala, scalanativelib/test/resources/hello-native-world/test/src/utest/tests/MainTests.scala, scalanativelib/test/src/HelloNativeWorldTests.scala
Porting of my [PR to Scala Native](https://github.com/scala-native/scala-native/pull/1727)
=> Allow tests in root package with Scala Native

scalalib/src/JavaModule.scala, scalalib/src/ScalaModule.scala
Fixes https://github.com/lihaoyi/mill/issues/776
=> JavaModule should not include Scala sources

docs/pages/9 - Contrib Modules.md
Mostly copied from contrib/bsp/readme.md.
=> Added info about BSP module

scalajslib/src/ScalaJSModule.scala, scalajslib/test/src/HelloJSWorldTests.scala
=> Fixed TestScalaJSModule.testCached

ci/release-maven.sh, docs/pages/1 - Intro to Mill.md, scalalib/src/PublishModule.scala
=> Fix publish

docs/pages/10 - Thirdparty Modules.md
Not sure if you want to add these but they seem core enough to me to have them in the doc.
=> Add mill-scalafix and mill-git to the doc

main/api/src/mill/api/Result.scala
This is needed for example [here](https://github.com/joan38/mill-scalafix/blob/master/mill-scalafix/src/com/goyeau/mill/scalafix/ScalafixModule.scala#L35-L51) where I [patched it how I can](https://github.com/joan38/mill-scalafix/blob/master/mill-scalafix/src/com/goyeau/mill/scalafix/ScalafixModule.scala#L22-L28)
=> Add flatMap on Result

ci/release-maven.sh
@lihaoyi I forgot to put back the default gpg args when overriding.
=> Fix master release

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
=> Make bloopDir if it doesn't exists

scalalib/src/scalafmt/ScalafmtWorker.scala
Learning mills reading [reformat code part](http://www.lihaoyi.com/mill/page/configuring-mill.html#reformatting-your-code), the `scalareformat` task fails as #676 said. I'm using mill v0.7.0, problem still exists.
Inspired by #677, Here comes this pull request.
=> Fix fail `scalareformat` task execution when config file not exists

contrib/bsp/src/mill/contrib/bsp/MillBuildServer.scala, contrib/bsp/src/mill/contrib/bsp/ModuleUtils.scala
This is fixing https://github.com/lihaoyi/mill/issues/893
=> Fix BSP compile and clean

scalalib/src/CoursierModule.scala, scalalib/src/JavaModule.scala, scalalib/src/ZincWorkerModule.scala
Inspired by [this Gitter message](https://gitter.im/lihaoyi/mill?at=5ef62e5d6c06cd1bf4576e67).
Thanks @hypatian
=> Use default coursier repos

scalalib/src/ScalaModule.scala
scalacPluginClasspath should be added to Tests trait.
=> add scalacPluginClasspath to Tests

readme.md
I was annoyed that the Readme had no example, so I posted that one hidden in the documentation here, since this is what gives this projects its face.
IMHO
=> Add example

bsp/src/mill/bsp/ModuleUtils.scala, contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/flyway/src/FlywayModule.scala, contrib/playlib/src/mill/playlib/RouterModule.scala, contrib/playlib/src/mill/playlib/Static.scala, contrib/scoverage/src/ScoverageModule.scala, contrib/tut/src/TutModule.scala, integration/test/resources/ammonite/build.sc, integration/test/resources/caffeine/build.sc, main/core/src/eval/Evaluator.scala, scalajslib/src/ScalaJSModule.scala, scalalib/src/CoursierModule.scala, scalalib/src/GenIdeaImpl.scala, scalalib/src/JavaModule.scala, scalalib/src/ZincWorkerModule.scala, scalalib/src/dependency/versions/VersionsFinder.scala, scalanativelib/src/ScalaNativeModule.scala
This should allow to use environment variables e.g. for repository authentication. See https://gitter.im/lihaoyi/mill?at=5f872eeccdb04d1ea081cd4f and following discussion.
=> Changed CoursierModule.repositories to a Task

bsp/src/mill/bsp/BSP.scala, bsp/src/mill/bsp/BspLoggedReporter.scala, bsp/src/mill/bsp/MillBuildServer.scala, bsp/src/mill/bsp/ModuleUtils.scala, bsp/src/mill/bsp/Utils.scala, build.sc, scalalib/worker/src/ZincWorkerImpl.scala
=> Upgrade bsp4j and implement buildTarget/javacOptions and fix build/taskFinish

main/api/src/mill/api/ClassLoader.scala, main/src/modules/Jvm.scala, scalalib/worker/src/ZincWorkerImpl.scala
=> Add "xsbti" as a shared prefix of the Scala compiler class loader

build.sc, ci/test-mill-0.sh, contrib/testng/test/resources/demo/test/src/example1/SimpleTest.java, contrib/testng/test/resources/demo/test/src/lambdatest/SimpleLambdaTest.java, contrib/testng/test/src/mill/testng/TestNGTests.scala
=> Testng integration test, that covers #553

scalajslib/test/src/HelloJSWorldTests.scala
My previous PR disabled most tests because of this mistake
=> Run all Scala.js tests

main/core/src/define/Overrides.scala
This PR is motivated by the following gitter conversation: https://gitter.im/lihaoyi/mill?at=5fd7bc7867034a3e900aacd0
=> Use root-package mill in quasi quote

.github/workflows/actions.yml, ci/test-mill-0.sh, ci/test-mill-bootstrap-0.sh, ci/test-mill-bootstrap-1.sh
This depends on a fix in PR #1080 and needs a rebase.
=> Run all contrib tests, not only selected ones

build.sc, contrib/bloop/src/mill/contrib/bloop/BloopFormats.scala, contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala
=> Support Scala.js ESModule on Bloop

scalalib/src/GenIdea.scala, scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea-hello-world/build.sc, scalalib/test/resources/gen-idea-hello-world/idea_modules/helloworld.test.iml
This also should make Idea respect the runIvyDeps and fixes https://github.com/lihaoyi/mill/issues/1110
Commits:
* Reformatted GenIdeaImpl
* More code commenting
* GenIdea: implemented scopes for libraries (PROVIDED, RUNTIME)
* Replaced hardcoded scala versions with generated
=> GenIdea: implemented scopes for libraries (PROVIDED, RUNTIME)

build.sc, contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala, scalanativelib/src/ScalaNativeModule.scala
- Remove Scala Native deprecations
=> Update bloop to 1.4.6-33-1c6f6712

build.sc, main/api/src/mill/api/JsonFormatters.scala, scalalib/src/JavaModule.scala, scalalib/src/TestRunner.scala, scalalib/test/src/TestRunnerTests.scala
This support will be used by default on Windows platform.
=> Added support to use an argument file for TestRunner

build.sc
=> Use one target to encapsulate VscVersion plugin use

scalalib/src/JavaModule.scala, scalalib/src/ScalaModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/1208
=> Respect the forkArgs and forkEnv settings in repl and console targets

main/test/src/util/ScriptTestSuite.scala
We still need to work around coursier concurrency issues
=> Default to 1 thread in ScriptedTestSuite

main/src/modules/Jvm.scala, main/test/src/mill/modules/JvmTests.scala
Also added Jvm.createClasspathPassingJar.
Made sure previous Jvm.createJar method signature is still present for binary compatibility.
=> Added useCpPassingJar parameter to Jvm.createJar.

scalalib/src/PublishModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/1227
=> Support multiple comma-separated gpg args in PublishModule.publish

scalalib/src/TestModule.scala
=> Small typo

scalalib/src/JavaModule.scala
=> Default-inherit the resolutionCustomizer in tests from parent module

bsp/src/mill/bsp/BspLoggedReporter.scala, main/api/src/mill/api/BuildReporter.scala, scalalib/worker/src/ZincWorkerImpl.scala
This addresses #1011 
Thanks @ckipp01 for testing my previous version and providing the SBT example.
=> Improved code around range end position problem reporter

scalalib/test/src/GenIdeaExtendedTests.scala, scalalib/test/src/GenIdeaTests.scala
- GenIdeaTests: test and improved internal test helper
- GenIdeaTests: adapted coursier cache path normalization
=> Improved tests for GenIdea

contrib/scoverage/test/src/HelloWorldTests.scala
The coursier concurrency issue is hurting us again.
=> Disabled parallel test for scoverage again

.github/workflows/actions.yml, build.sc, ci/mill-bootstrap.patch
- Setup mima plugin to check for binary compatibility
- Enable binary compatibility checks in CI
=> Setup mima plugin to check for binary compatibility

main/core/src/eval/Evaluator.scala, main/src/main/RunScript.scala, scalalib/src/GenIdea.scala, scalalib/src/GenIdeaImpl.scala
Fix https://github.com/com-lihaoyi/mill/issues/950
=> GenIdea: Report errors

build.sc, main/src/modules/Jvm.scala
Works around https://github.com/com-lihaoyi/mill/issues/1028.
=> Retry coursier resolution in case of concurrent download issues

main/api/src/mill/api/Ctx.scala, main/core/src/mill/define/Task.scala, main/core/src/mill/eval/Evaluator.scala
Fix https://github.com/com-lihaoyi/mill/issues/1544
=> Add `T.ctx().workspace` to access to project top level directory

build.sc
=> Only set COURSIER_CACHE on WSL if undefined

bsp/src/mill/bsp/MillScalaBuildServer.scala
Fix https://github.com/com-lihaoyi/mill/issues/1323
=> Fixed empty BSP response for buildTarget/scalaTestClasses

bsp/src/mill/bsp/BspCompileProblemReporter.scala, bsp/src/mill/bsp/MillBuildServer.scala, main/api/src/mill/api/CompileProblemReporter.scala, scalalib/worker/src/ZincWorkerImpl.scala
Fix https://github.com/com-lihaoyi/mill/issues/987
=> BSP: Listen for all compiled files and properly reset diagnostics

docs/antora/modules/ROOT/pages/Extending_Mill.adoc, docs/antora/modules/ROOT/pages/Intro_to_Mill.adoc
Backported from pull request: https://github.com/com-lihaoyi/mill/pull/1524
=> Updated documetation and usage to reflect new `+` separator

scalalib/src/mill/scalalib/bsp/BspModule.scala
The enables lookup of `$ivy` imports.
=> BSP: added local cached Ammonite dependencies to classpath for .sc files

scalalib/src/ZincWorkerModule.scala, scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
* Clenaup
* Added return types
* Removed deprecated API calls
* try harder to use correct javac for compilation of Zinc bridge
Fix https://github.com/com-lihaoyi/mill/issues/1595
=> Reviewed ZincWorker

main/src/main/MainModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/1648
This issue was introduced in https://github.com/com-lihaoyi/mill/issues/1648
which is a backport of https://github.com/com-lihaoyi/mill/pull/1521
It was probably introduced while resolving merge conflicts and
is not present in the main branch.
=> Fixed argument handling of show command

scalajslib/src/ScalaJSModule.scala
Fix for https://github.com/com-lihaoyi/mill/issues/1665
=> Fixed #1665: Default to ECMAScript 2015

docs/antora/modules/ROOT/pages/Thirdparty_Plugins.adoc
[mill-scalablytyped](https://github.com/lolgab/mill-scalablytyped)
=> Add mill-scalablytyped to Thirdparty_plugins.adoc

scalalib/src/ScalaModule.scala, scalalib/test/src/HelloWorldTests.scala
This PR build upon PR https://github.com/com-lihaoyi/mill/pull/1717
Fix https://github.com/com-lihaoyi/mill/issues/1647
=> Use newer Ammonite main when version is 2.5.0 or newer

scalalib/src/JavaModule.scala, scalalib/src/ScalaModule.scala
Fix https://github.com/com-lihaoyi/mill/issues/1707
=> Do not include hidden files when generating docJar

main/src/mill/modules/Jvm.scala
- Reworked the coursier resolver retry logic
- Formatting
- Added retry logic in another place where we also fetch artifacts
Fix https://github.com/com-lihaoyi/mill/issues/1028
=> Reworked the coursier resolver retry logic

docs/antora/modules/ROOT/pages/Intro_to_Mill.adoc
I hope that this addition to the docs, might make it easier for a beginner to get started with VSCode / mill. As far as I can tell, using bloop works reasonably well.
=> Doc for using bloop as the build server

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
=> Bloop: Replace deprecated API call

main/src/mill/modules/Jvm.scala, scalalib/src/JavaModule.scala, scalalib/test/src/HelloJavaTests.scala
=> Added `docJarUseArgsFile` target and default to `true` on Windows

build.sc, ci/publish-local.sh, ci/test-mill-bootstrap-0.sh, ci/test-mill-bootstrap-1.sh, ci/test-mill-release.sh, readme.adoc
- Added installLocal target and deprecated ci/publish-local.sh script
- Docuemented new `installLocal` target
- Use new target instead of script
=> Added `installLocal` target and deprecated ci/publish-local.sh script

build.sc, docs/antora/supplemental-ui/css/search.css, docs/antora/supplemental-ui/js/search-ui.js, docs/antora/supplemental-ui/partials/header-content.hbs
CSS and JS are copied from node_modules, I followed instructions from here https://gitlab.com/antora/antora-lunr-extension  
The index itself is around 600+KB so it doesnt add too much to the site.
This is how it looks like from local:
=> Add search functionality based on @antora/lunr-extension

docs/antora/modules/ROOT/pages/Common_Project_Layouts.adoc
Fixes https://github.com/com-lihaoyi/mill/issues/1897
=> Fixed links to examples in documentation

main/api/src/mill/api/PathRef.scala
I think this is sufficient.
* Fix #1808
=> Fix filesystem-dependent sig in PathRef

docs/antora/modules/ROOT/pages/Common_Project_Layouts.adoc
=> [Docs] Fix import on scalanative example module

ci/shared.sc, ci/upload.sc
This fixed compile issues, when compiled outside of Ammonite.
=> Import mainargs @main annotation in scripts

build.sc
This version supports Scala 2.13.9
=> Update Ammonite to 2.5.4-33-0af04a5b

main/src/mill/modules/Jvm.scala
We reuse the same retry logic as we do for retrying concurrent download issues.
* Fix https://github.com/com-lihaoyi/mill/issues/1910
=> Retry coursier artifact loading when "checksum not found"

build.sc, contrib/playlib/test/src/mill/playlib/PlayModuleTests.scala, contrib/playlib/test/src/mill/playlib/PlaySingleApiModuleTests.scala, contrib/playlib/test/src/mill/playlib/PlaySingleModuleTests.scala, contrib/playlib/test/src/mill/playlib/PlayTestSuite.scala
Also re-enabled some tests which were previously disabled because of issue:
* https://github.com/com-lihaoyi/mill/issues/554
=> Share all play (test) versions from main builds

build.sc
=> Update mill-moduledefs to 0.10.9

mill
Also respect an already set DEFAULT_MILL_VERSION variable.
* Adapted from https://github.com/lefou/millw/pull/42
* Fix https://github.com/com-lihaoyi/mill/issues/2123
=> Preserve first position of some args in mill script

main/api/src/mill/api/JarOps.scala, main/test/resources/examples/javac/resources/META-INF/License, main/test/src/eval/JavaCompileJarTests.scala
Fix https://github.com/com-lihaoyi/mill/issues/2136#issuecomment-1326772654
=> Fixed `META-INF` handling in `JarOps.jar`

build.sc
I tried to keep POSIX shell compatibility, hence it's a bit lenghty.
Fix https://github.com/com-lihaoyi/mill/issues/2140
=> Reworked `.mill-jvm-opts` reader to support files without final newline

build.sc
See issue https://github.com/coursier/coursier/issues/2603
and PR https://github.com/coursier/coursier/pull/2591
=> Downgrade coursier to avoid stale metadata issues

scalajslib/src/mill/scalajslib/ScalaJSModule.scala
* Backport of:  https://github.com/com-lihaoyi/mill/pull/2180
=> Pass more settings from `ScalaJSModule` to its `Tests` (Backport of #2180) 

docs/antora/modules/ROOT/pages/Installation.adoc
Fix https://github.com/com-lihaoyi/mill/discussions/2190
=> Doc: Fix download URL of Mill bootstrap script

.git-blame-ignore-revs, scalalib/test/resources/scalafmt/core/src/Main.scala, scalalib/test/resources/scalafmt/core/src/Person.scala, scalalib/test/resources/scalafmt/core/util.sc
I overlooked the failing tests and accidentally merged PR #2219.
=> Fix scalafmt tests

main/src/mill/main/MainModule.scala, main/test/src/main/MainModuleTests.scala
Also added tests for `MillMain.clean` 
Fix https://github.com/com-lihaoyi/mill/issues/2256
=> Fixed module cleaning and added tests

main/src/mill/main/MainModule.scala, main/test/src/main/MainModuleTests.scala
Also added tests for `MillMain.clean`
Fix https://github.com/com-lihaoyi/mill/issues/2256
Original pull request: https://github.com/com-lihaoyi/mill/pull/2257
=> Fixed module cleaning and added tests (Backport of #2257)

scalalib/src/GenIdeaImpl.scala, scalalib/test/resources/gen-idea-extended-hello-world/build.sc, scalalib/test/resources/gen-idea-extended-hello-world/idea/libraries/SBT_ junit_junit_2_13_4_13_2_jar.xml, scalalib/test/resources/gen-idea-extended-hello-world/idea/libraries/SBT_ org_scalameta_munit_2_13_0_7_29_jar.xml, scalalib/test/src/GenIdeaExtendedTests.scala, scalalib/test/src/GenIdeaTests.scala
=> fix generation of library paths containing `:` for Windows

mill
=> Update default Mill version in wrapper script to 0.10.10

main/src/mill/modules/Jvm.scala
Original pull request: https://github.com/com-lihaoyi/mill/pull/2287
=> Added another retry candidate for coursier resolution (Backport of #2287)

readme.adoc
Fixes 
* https://github.com/com-lihaoyi/mill/issues/2204
* https://github.com/com-lihaoyi/mill/issues/2300
=> Added some upgrade notes

build.sc
This is a binary incompatible change.
=> Update upickle to 3.0.0-M2 and Ammonite to 3.0.0-M0-1-beb96bfb

main/api/src/mill/api/JsonFormatters.scala, main/core/src/mill/define/BaseModule.scala, main/core/src/mill/define/Ctx.scala, main/core/src/mill/define/Module.scala, main/core/src/mill/define/ParseArgs.scala, main/core/src/mill/define/Segment.scala, main/core/src/mill/define/Segments.scala, main/core/src/mill/define/Task.scala, scalajslib/test/src/HelloJSWorldTests.scala, scalajslib/test/src/ScalaJsUtils.scala, scalalib/src/PublishModule.scala, scalalib/src/dependency/versions/VersionParser.scala
Various compiler warning fixes and small changes like explicit types or complete match statements.
=> Code review and cleanups

scalalib/src/TestModule.scala
Weaver is a test framework developed by Disney Streaming:
https://github.com/disneystreaming/weaver-test
This PR adds a `TestModule.Weaver` convenience trait.
=> Add Weaver TestModule

docs/antora/modules/ROOT/pages/Getting_Started.adoc, main/src/mill/MillCliConfig.scala, main/src/mill/MillMain.scala
* Fix https://github.com/com-lihaoyi/mill/issues/2350
=> Re-added `--color` and `--predef` cli args

main/src/mill/main/MillIvyHook.scala, scalalib/src/mill/scalalib/bsp/MillBuildModule.scala
We forgot to process the `Mill_VERSION`, `MILL_BIN_VERSION` and the empty version.
* Fix #2360
=> Process ivy dependency includes in MillBuildModule

testrunner/src/TestRunner.scala
An intermittent failure occurs when running tests with `-j 0 ...` on a
machine with plenty of cores. This is due to concurrent use of
scala.collection.mutable.Buffer.
This PR uses a concurrent collection to allow concurrent tests to append
events safely.
Original Pull Request: https://github.com/com-lihaoyi/mill/pull/2314
=> Fix concurrency issue with test event reporting (Backport of #2314)

contrib/twirllib/src/mill/twirllib/TwirlModule.scala
=> Use scala-parser-combinators:1.1.2 on scala 2, 2.1.0 otherwise

scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala, scalanativelib/worker-api/src/mill/scalanativelib/worker/api/ScalaNativeWorkerApi.scala, scalanativelib/worker/0.4/src/mill/scalanativelib/worker/ScalaNativeWorkerImpl.scala
This is useful for debugging Scala Native applications
=> Add nativeDump to ScalaNativeModule

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
=> BSP: Remove query part from target identitfier URI and some cleanups

.git-blame-ignore-revs, .scalafmt.conf, bsp/src/mill/bsp/BspWorker.scala, bsp/worker/src/mill/bsp/worker/MillJavaBuildServer.scala, contrib/twirllib/src/mill/twirllib/TwirlModule.scala, integration/local/src/mill/integration/CrossTests.scala, main/api/src/mill/api/JsonFormatters.scala, main/core/src/mill/define/Discover.scala, main/src/mill/MillCliConfig.scala, main/src/mill/modules/CoursierSupport.scala, scalajslib/test/src/mill/scalajslib/MultiModuleTests.scala, scalalib/src/mill/scalalib/IvyDepsTreeArgs.scala, scalalib/src/mill/scalalib/bsp/BspModule.scala, scalalib/src/mill/scalalib/bsp/MillBuildModule.scala, scalalib/test/src/mill/scalalib/GenIdeaExtendedTests.scala, scalalib/test/src/mill/scalalib/GenIdeaTests.scala, scalalib/test/src/mill/scalalib/HelloJavaTests.scala, scalalib/test/src/mill/scalalib/HelloWorldTests.scala
- Update Scalafmt to 3.7.3
- Reformatted some files
- Update .git-blame-ignore-revs
=> Updated scalafmt to 3.7.3 and reformatted code base

.github/workflows/actions.yml
=> Rename CI jobs to reduce boilerplate in PR checks UI

runner/src/mill/runner/MillBuildBootstrap.scala, runner/src/mill/runner/MillBuildRootModule.scala
* Fix https://github.com/com-lihaoyi/mill/issues/2419
=> Properly use sig of millBootClasspath if there is no meta build

build.sc
Fixes https://github.com/com-lihaoyi/mill/issues/2441
=> Update windows-ansi to 0.0.5

build.sc, ci/mill-bootstrap.patch
=> Fix uploadToGithub command

.github/workflows/actions.yml, main/src/mill/main/ResolveCore.scala, main/test/src/mill/main/MainModuleTests.scala, main/testkit/src/mill/testkit/MillTestkit.scala
Now I can actually see which windows job is running what without it being truncated
=> Tweak CI to improve UI display

main/define/src/mill/define/package.scala
=> Added deprecated type aliases for mill.define.Target

build.sc, ci/mill-bootstrap.patch
Also update the patch file. This should reduce the collision for scala-steward PRs.
=> Format build.sc

build.sc, ci/mill-bootstrap.patch
* See https://github.com/lefou/mill-vcs-version/pull/111
=> Silence git stderr output

readme.adoc
Just 2 small typos and 1 bit of formatting. If this PR is too small to bother with, I could try finding some more typos in the website.
=> Fix a couple minor typos and formatting

build.sc
=> Fix edit page links in website

contrib/bloop/src/mill/contrib/Bloop.scala, contrib/bloop/src/mill/contrib/bloop/Bloop.scala
=> Fix package of `mill.contrib.bloop.Bloop` module

docs/modules/ROOT/pages/Installation_IDE_Support.adoc
Gave the bootstrap scripts our general recommendation. 
Also added more clarifying warnings to other installation methods.
* Fix #2674
=> Reworked installation documentation

CONTRIBUTING.adoc, docs/modules/ROOT/pages/Scala_Module_Config.adoc
As promised, a small contribution to documentation.
=> #2673 doc - use maven through corporate proxy

build.sc
Pull request: https://github.com/com-lihaoyi/mill/pull/2707
=> Update mainargs to 0.5.1

build.sc
Pull request: https://github.com/com-lihaoyi/mill/pull/2712
=> Update zio-test to 2.0.16

build.sc
Pull request: https://github.com/com-lihaoyi/mill/pull/2708
=> Update semanticdb-scala to 4.8.8 and semanticdb-java to 0.9.5

build.sc
Pull request: https://github.com/com-lihaoyi/mill/pull/2710
=> Update coursier interface to 1.0.18

build.sc
Pull request: https://github.com/com-lihaoyi/mill/pull/2711
=> Update mill-scip to 0.3.5

build.sc
Pull request: https://github.com/com-lihaoyi/mill/pull/2709
=> Refactor and update dependencies of codesig tests

build.sc, readme.adoc
Pull request: https://github.com/com-lihaoyi/mill/pull/2715
=> Post release: Update MiMa baseline

build.sc, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/Changelog.adoc, readme.adoc
Pull request: https://github.com/com-lihaoyi/mill/pull/2717
=> Added a changelog to the Mill site

build.sc
Pull request: https://github.com/com-lihaoyi/mill/pull/2716
=> Update various transitive runtime dependencies

readme.adoc
Pull request: https://github.com/com-lihaoyi/mill/pull/2718
=> Added historic release dates to changelog

docs/modules/ROOT/pages/Thirdparty_Plugins.adoc
See also https://github.com/alexarchambault/mill-native-image/pull/61
=> doc: add missing nativeImageClassPath def in NativeImage example

main/util/src/mill/util/CoursierSupport.scala
Pull Request: https://github.com/com-lihaoyi/mill/pull/2824
=> Avoid calculating PathRef for filtered out deps

contrib/proguard/readme.adoc
Pretty much all these new entries will be needed to use this plugin successfully
=> docs: proguard - more detailed example

build.sc, docs/modules/ROOT/pages/Builtin_Commands.adoc, example/basic/4-builtin-commands/build.sc
=> Fixed paragraph example rendering and reworked built-in command section

build.sc
Fix false positive MiMa issue introduced in https://github.com/com-lihaoyi/mill/pull/2570
=> Fix MiMa errors

build.sc, contrib/bloop/test/src/mill/contrib/bloop/BloopTests.scala, contrib/playlib/src/mill/playlib/PlayModule.scala, docs/antora/modules/ROOT/pages/Common_Project_Layouts.adoc, docs/antora/modules/ROOT/pages/Configuration.adoc, scalajslib/src/mill/scalajslib/ScalaJSModule.scala, scalalib/src/CrossSbtModule.scala, scalalib/src/CrossScalaModule.scala, scalalib/src/SbtModule.scala, scalalib/src/ScalaModule.scala, scalalib/test/src/HelloWorldTests.scala, scalalib/test/src/TestClassLoaderTests.scala, scalalib/test/src/TestRunnerTests.scala, scalanativelib/src/ScalaNativeModule.scala, scalanativelib/test/src/HelloNativeWorldTests.scala
Provided type aliases for traits removed in Mill 0.11 and deprecated removed traits.
=> Ease transition to Mill 0.11 API

docs/modules/ROOT/pages/Thirdparty_Plugins.adoc
Add [mill-missinglink](https://github.com/hoangmaihuy/mill-missinglink), [mill-scala-tsi](https://github.com/hoangmaihuy/mill-scala-tsi) and [mill-universal-packager](https://github.com/hoangmaihuy/mill-universal-packager) to ThirdParty plugin doc.
=> Doc: Add some ThirdParty plugins

example/scalamodule/11-repository-config/build.sc
Add mirror config file documentation.
=> add mirror config doc

example/scalabuilds/6-publish-module/build.sc
A tiny doc PR, that attempt to help someone publishing via sonatype and getting back a 403.
=> Sonatype note

build.sc, readme.adoc
- Added Mill 0.10.15 to changelog
- Include Mill 0.10.15 in docsite
=> Update Changelog and doc site

runner/src/mill/runner/MillBuildRootModule.scala
Fix https://github.com/com-lihaoyi/mill/issues/2966
=> Fix overeager caching of `cliImports` value in `generatedScriptSources`

docs/modules/ROOT/pages/Thirdparty_Plugins.adoc
Does this seem reasonable? Thank you!
=> Add mill-daemon to third party plugins documentation

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/Target_Query_Syntax.adoc, docs/modules/ROOT/pages/Tasks.adoc, example/basic/1-simple-scala/build.sc, example/tasks/2-primary-tasks/build.sc
Tried to collect and document all ways to specify a target in Mill in a single page.
Documentation in a foreign language is not my expertise, so please comment, fix, or open more PRs. Thanks!
=> Documentation for query syntax

.scalafmt.conf, docs/antora.yml, readme.adoc
Pull request: https://github.com/com-lihaoyi/mill/pull/3002
=> Prepare release 0.11.7

build.sc
Fix https://github.com/com-lihaoyi/mill/issues/3004
=> Update mainargs from 0.6.1 to 0.6.2

docs/modules/ROOT/pages/Installation_IDE_Support.adoc
Fix https://github.com/com-lihaoyi/mill/issues/2906
=> Update documentation, removed obsolete waning about Metals warnings

contrib/buildinfo/src/mill/contrib/buildinfo/BuildInfo.scala, contrib/buildinfo/test/src/mill/contrib/buildinfo/BuildInfoTests.scala
Fix https://github.com/com-lihaoyi/mill/issues/3073
=> Fix BuildInfo static Java file generator

build.sc, scalalib/src/mill/scalalib/Assembly.scala
This include one code change due to changed API.
=> Update jarjar-abrams-core from 1.9.0 to 1.14.0

build.sc
Pull request: https://github.com/com-lihaoyi/mill/pull/3107
=> Update Scala Native to 0.5.0-RC3

build.sc
Pull Request: https://github.com/com-lihaoyi/mill/pull/3120
=> Update Scala Native to 0.5.0

contrib/scoverage/readme.adoc
Fix https://github.com/com-lihaoyi/mill/issues/3136
=> Fix typo in scoverage documentation

build.sc
Pull Request: https://github.com/com-lihaoyi/mill/pull/3216
=> Update Scala Native 0.5 from 0.5.1 to 0.5.3

example/web/5-webapp-scalajs-shared/build.sc, example/web/5-webapp-scalajs-shared/client/src/ClientApp.scala
Fixes #3056 
Pull Request: https://github.com/com-lihaoyi/mill/pull/3212
=> Migrate 5-webapp-scalajs-shared example to Scala 3

bsp/worker/src/mill/bsp/worker/State.scala
Fixes https://github.com/com-lihaoyi/mill/issues/3241
Pull Request: https://github.com/com-lihaoyi/mill/pull/3242
=> [BSP] Fix uri for foreign modules

docs/modules/ROOT/pages/Java_Module_Config.adoc
Fixed dependancies to dependencies
=> Fixed Typo in Maven Blocked Documentation

build.sc, readme.adoc
* Added 0.11.11 to MiMa checks
* Document re-tagging and updated changelog
=> After release chore

idea/src/mill/idea/GenIdeaImpl.scala, integration/ide/gen-idea/repo/hello-idea/build.sc, integration/ide/gen-idea/repo/hello-idea/idea/libraries/scala_js_SDK_3_3_1.xml, integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/helloideajs.iml, integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/helloideajs.test.iml, integration/ide/gen-idea/repo/hello-idea/idea/modules.xml
* Related to https://github.com/com-lihaoyi/mill/issues/3344
=> GenIdea: Make Scala SDK specific for JS / Native

idea/src/mill/idea/GenIdeaImpl.scala, integration/ide/gen-idea/repo/hello-idea/build.sc, integration/ide/gen-idea/repo/hello-idea/idea/libraries/scala_js_SDK_3_3_1.xml, integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/helloideajs.iml, integration/ide/gen-idea/repo/hello-idea/idea/mill_modules/helloideajs.test.iml, integration/ide/gen-idea/repo/hello-idea/idea/modules.xml
* Related to https://github.com/com-lihaoyi/mill/issues/3344
Backport of Pull request: https://github.com/com-lihaoyi/mill/pull/3345
=> GenIdea: Make Scala SDK specific for JS / Native (backport #3345)

build.sc
Since 0.12.x is meant to be bincompatible with 0.11.x
=> Hardcode millBinPlatform to 0.11

build.sc, readme.adoc
Backport of pull request: https://github.com/com-lihaoyi/mill/pull/3401
Pull request: https://github.com/com-lihaoyi/mill/pull/3402
=> After release chore (Backport #3401)

scalalib/src/mill/scalalib/GenIdeaImpl.scala
In case you use anything of this impl, please migrate to mill.idea.GenIdeaImpl.
=> Flesh out deprecated mill.scalalib.GenIdeaImpl to catch downstream users

integration/invalidation/invalidation/src/ScriptsInvalidationTests.scala
Need to retry the entire `integrationTest` block to ensure it has a clean slate each try
=> Broaden flaky test retry

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.adoc, docs/supplemental-ui/partials/header-content.hbs, readme.adoc
Gitter seems totally borked these days and most discussion is in discord, this makes it official
=> Swap gitter references to Discord

scalalib/src/mill/scalalib/JavaModule.scala
Resolves https://github.com/com-lihaoyi/mill/issues/3464
=> Add reference to `runMain` in `run` error message

build.mill
Fixes https://github.com/com-lihaoyi/mill/issues/3563 (hopefully)
=> Update coursier to 2.1.13

contrib/package.mill, example/package.mill, integration/package.mill
This removes some unused imports I stumbled upon while working on https://github.com/com-lihaoyi/mill/pull/3579
=> Remove some unused imports

main/codesig/src/LocalSummary.scala, main/codesig/test/cases/callgraph/basic/20-array-method/src/Hello.java, main/codesig/test/src/CallGraphTests.scala
Fixes https://github.com/com-lihaoyi/mill/issues/3616
=> Fix crash in codesig analysis for method calls on arrays

main/init/package.mill
Adds milestone case for parsing millLastTag from millVersion
=> adding milestone pattern to examples list

scalanativelib/src/mill/scalanativelib/ScalaNativeModule.scala
We need to rebootstrap on this before we can properly land https://github.com/com-lihaoyi/mill/pull/3637
=> Add MILL_TEST_RESOURCE_DIR without removing MILL_TEST_RESOURCE_FOLDER

build.mill
=> upgrade moduledefs and mainargs

build.mill
Should add support for Java 24.
=> Update asm from 9.7 to 9.7.1

build.mill
Pulls in https://github.com/com-lihaoyi/os-lib/pull/323
=> Bump OS-Lib to 0.11.2

build.mill
Pulls in https://github.com/com-lihaoyi/os-lib/pull/324
=> Bump OS-Lib to 0.11.3

example/kotlinlib/web/3-hello-kotlinjs/build.mill, example/kotlinlib/web/4-webapp-kotlinjs/build.mill, example/kotlinlib/web/5-webapp-kotlinjs-shared/build.mill, kotlinlib/src/mill/kotlinlib/js/KotlinJsModule.scala, kotlinlib/test/src/mill/kotlinlib/js/KotlinJsCompileTests.scala, kotlinlib/test/src/mill/kotlinlib/js/KotlinJsKotestModuleTests.scala, kotlinlib/test/src/mill/kotlinlib/js/KotlinJsKotlinTestPackageModuleTests.scala, kotlinlib/test/src/mill/kotlinlib/js/KotlinJsKotlinVersionsTests.scala, kotlinlib/test/src/mill/kotlinlib/js/KotlinJsLinkTests.scala, kotlinlib/test/src/mill/kotlinlib/js/KotlinJsNodeRunTests.scala
Fix https://github.com/com-lihaoyi/mill/issues/3771
=> Rename `KotlinJS` to `KotlinJs`

build.mill
Should be binary compatible to 0.3.1
=> Update com.lihaoyi:sourcecode to 0.4.2

scalalib/src/mill/scalalib/internal/ModuleUtils.scala
This now points to the right file, the previous comment points to nowhere.
=> Correct comment in ModuleUtils

readme.adoc
=> fix(readme): wrong path in example

docs/package.mill, scalalib/src/mill/javalib/palantirformat/PalantirFormatModule.scala, scalalib/test/src/mill/javalib/palantirformat/PalantirFormatModuleTest.scala
Noticed this issue when working on https://github.com/com-lihaoyi/mill/pull/3919. Added a test case to the unit tests to cover it
=> Make PalantirFormat not fail when `src` folder doesn't exist

docs/modules/ROOT/pages/comparisons/why-mill.adoc, readme.adoc
=> Prepare changelog for 0.12.2

runner/src/mill/runner/MillBuildRootModule.scala
Someone reported on discord the auto override behavior not working, this should help narrow it down
=> Add --plugin-require to auto-override-plugin to try and detect issues

integration/feature/run-background/resources/build.mill, integration/feature/run-background/resources/src/BackgroundMain.java, integration/feature/run-background/src/RunBackgroundTests.scala
Covers the improvement we implemented in https://github.com/com-lihaoyi/mill/pull/3971. Fails on any commit before that PR
=> Add unit test for runBackground logging behavior

docs/modules/ROOT/pages/extending/thirdparty-plugins.adoc
Follow up from https://github.com/com-lihaoyi/mill/discussions/3900
=>  Third-Party Plugins: Adding the Docker Jib Project 

.github/workflows/run-tests.yml, docs/modules/ROOT/pages/comparisons/java-compile.adoc, docs/modules/ROOT/pages/index.adoc, example/extending/jvmcode/6-module-cached-classloader/bar/src/Bar.java, main/server/test/src/mill/main/server/ClientServerTests.scala
Add some subheadings to break up the large page
=> Doc & Test Suite tweaks

runner/client/src/mill/runner/client/MillProcessLauncher.java
Was meant to land in https://github.com/com-lihaoyi/mill/pull/4053 but got lost in the merge
This hardcoding is just a hack until https://github.com/com-lihaoyi/mill/issues/4055 is resolved
=> Re-enable harcdoded prompt sizing for windows

readme.adoc
Adapt the command lines to the updated examples
=> Fix Readme Test Command Line

dist/package.mill, integration/feature/launcher-old-versions/src/LauncherOldVersionsTests.scala, integration/package.mill, mill.ps1
Fixes https://github.com/com-lihaoyi/mill/issues/2161
- Adds some integration tests for older mill versions
- Includes the `mill.ps1` file
=> More Mill launcher integration work

scalalib/src/mill/scalalib/dependency/metadata/MavenMetadataLoader.scala, scalalib/src/mill/scalalib/dependency/metadata/MetadataLoader.scala, scalalib/src/mill/scalalib/dependency/versions/VersionsFinder.scala
Should fix https://github.com/com-lihaoyi/mill/issues/3876
=> Try to address version updates check race condition

build.mill
Needs to happen separately from https://github.com/com-lihaoyi/mill/pull/4118 since I need it on both the PR branch and on the main target branch for the selective testing to be effective
=> Stub out mill version for selective testing

.github/workflows/post-build-selective.yml, .github/workflows/run-tests.yml
Improves #4202 
Example reports: https://github.com/sake92/mill/actions/runs/12563637492
If you click on a failed job on the left, you will see annotations section on the top.  
It shows which tests failed and the reason message.
=> Add junit report action

main/util/src/mill/util/PromptLogger.scala
Fix https://github.com/com-lihaoyi/mill/issues/4171
=> PromptLogger: Clean lines that contain a tab character

build.mill, scalalib/src/mill/scalalib/JsonFormatters.scala
And coursier-interface to 1.0.27 (that uses coursier 2.1.23 under-the-hood)
=> Update coursier to 2.1.23

example/javalib/publishing/8-native-image-config/build.mill, example/javalib/publishing/8-native-image-config/foo/src/foo/Foo.java
extracted from https://github.com/com-lihaoyi/mill/pull/4340
=> Add second graal doc example

example/android/javalib/1-hello-world/build.mill, example/android/kotlinlib/1-hello-kotlin/build.mill, scalalib/src/mill/javalib/android/AndroidAppModule.scala
After running Instrumental tests the XML will automatically created in the **out/app/it/testTask.dest/** directory
Using this online tool [link](https://lotterfriends.github.io/online-junit-parser/#case.0.0) we can validate that the XML is correct
=> Part of Android Studio Integration: JUnit XML generation

scalalib/src/mill/scalalib/PublishModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/4378
=> Fix publishM2Local

build.mill, mill-build/build.sc
Now that https://github.com/joan38/mill-scalafix/pull/225 is available
=> Re-enable scalafix 

build.mill, example/thirdparty/mockito/build.mill
also fix some selective test execution over-selection due to `millLastTag`
=> Disable flaky mockito test

scalalib/src/mill/scalalib/JavaModule.scala
This PR mainly fixes the output of `JavaModule.showModuleDeps` when run concurrently.
It also includes runtime module dependencies.
=> Fix `showModuleDeps` output

main/client/src/mill/main/client/EnvVars.java
Motivation:
Add some doc about the `MILL_TEST_RESOURCE_DIR`
=> chore: Add some note to MILL_TEST_RESOURCE_DIR

docs/modules/ROOT/pages/pythonlib/linting.adoc, example/pythonlib/linting/3-coverage/build.mill, example/pythonlib/linting/3-coverage/src/main.py, example/pythonlib/linting/3-coverage/test/src/test_main.py, pythonlib/src/mill/pythonlib/CoverageModule.scala
The actual analysis is delegated to the well-known coverage.py package.
=> Add coverage module for python

build.mill
Pulls in https://github.com/com-lihaoyi/os-lib/pull/350
=> Bump OS-Lib version

docs/modules/ROOT/pages/scalalib/web-examples.adoc, example/scalalib/web/9-todo-http4s/build.mill, example/scalalib/web/9-todo-http4s/resources/webapp/index.css, example/scalalib/web/9-todo-http4s/resources/webapp/main.js, example/scalalib/web/9-todo-http4s/src/WebApp.scala, example/scalalib/web/9-todo-http4s/test/src/WebAppTests.scala
Closes https://github.com/com-lihaoyi/mill/issues/4433
=> Add Http4s TodoMVC Example

example/scalalib/web/3-todo-http4s/src/WebApp.scala
followup https://github.com/com-lihaoyi/mill/pull/4446#issuecomment-2628677738
=> Remove debug

build.mill, scalalib/package.mill
Should fix locale specific isues in checkstyle tests
Fix https://github.com/com-lihaoyi/mill/issues/4534
=> Explicitly set locale in scalalib tests to `LC_ALL=C.utf8`

ci/mill-bootstrap.patch
=> Update bootstap patch file

scalalib/src/mill/scalalib/AssemblyModule.scala
Forward-port of https://github.com/com-lihaoyi/mill/pull/4566
=> Add scaladoc to AssemblyModule.scala

scalalib/src/mill/scalalib/TestModuleUtil.scala
Forward port of https://github.com/com-lihaoyi/mill/pull/4571
=> Forward port "Fix hang on `mill.integration.invalidation[selective-execution]`"

main/package.mill, runner/src/mill/runner/MillBuildRootModule.scala, scalalib/src/mill/scalalib/Lib.scala
This reports #4546 on the `0.12.x` branch
=> Rework millEmbeddedDeps stuff (0.12.x)

contrib/bloop/src/mill/contrib/bloop/BloopImpl.scala
See https://github.com/com-lihaoyi/mill/pull/4600
=> Backport: Improve performances of `Bloop/install` (#4600)

runner/src/mill/runner/MillMain.scala
Fixes #4641, tho I'm not 100% sure if this is the right thing to do.
=> Fix BSP reimport issue

core/api/src/mill/api/Logger.scala, core/internal/src/mill/internal/MultiLogger.scala, core/internal/src/mill/internal/PrefixLogger.scala, core/internal/src/mill/internal/ProxyLogger.scala
Part of https://github.com/com-lihaoyi/mill/issues/3603
Mostly just describing what they do now
=> Scaladoc for `mill.api.Logging` methods 

build.mill, core/api/src/mill/api/Ctx.scala, core/define/src/mill/define/Evaluator.scala, core/exec/src/mill/exec/GroupExecution.scala, core/src/mill/eval/EvaluatorImpl.scala, core/src/mill/eval/EvaluatorProxy.scala, core/src/mill/eval/SelectiveExecution.scala, integration/feature/mill-jvm-opts/resources/build.mill, scalajslib/src/mill/scalajslib/worker/ScalaJSWorker.scala, scalalib/src/mill/scalalib/ZincWorkerModule.scala, scalanativelib/src/mill/scalanativelib/worker/ScalaNativeWorker.scala
Fixes https://github.com/com-lihaoyi/mill/issues/3571
=> Make `mill.api.Ctx` a `trait`

website/docs/modules/ROOT/pages/cli/installation-ide.adoc
=> update documentation to warn about PowerShell pitfall

example/depth/sandbox/2-test/build.mill, example/depth/sandbox/3-breaking/build.mill, example/javalib/testing/4-test-grouping/build.mill, example/javalib/web/4-hello-micronaut/build.mill, example/javalib/web/5-todo-micronaut/build.mill, example/kotlinlib/testing/4-test-grouping/build.mill, example/scalalib/testing/4-test-grouping/build.mill, scalalib/src/mill/scalalib/TestModule.scala, scalalib/src/mill/scalalib/TestModuleUtil.scala
Turns on https://github.com/com-lihaoyi/mill/pull/4614 by default in 0.13.x, leaving the default as of in 0.12.x
=> Turn on `testEnableWorkStrealing` by default

scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
Fixes https://github.com/com-lihaoyi/mill/issues/4556
=> Add some retries to try and work around scaladoc flakiness

main/util/src/mill/util/PromptLogger.scala, main/util/src/mill/util/PromptLoggerUtil.scala, scalalib/src/mill/scalalib/TestModuleUtil.scala, testrunner/src/mill/testrunner/TestRunnerUtils.scala
Also backported some code cleanups from https://github.com/com-lihaoyi/mill/pull/4681
=> 0.12.x improvements to Test parallelism UI

testkit/src/mill/testkit/TestBaseModule.scala
=> Make source path configurable in TestBaseModule

scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala
Backports https://github.com/com-lihaoyi/mill/pull/4684 to 0.12.x
Hopefully this should help fix some of the flakiness we're seeing in backport PRs
=> Backport "Add some retries to try and work around scaladoc flakiness" to 0.12.x

build.mill, example/fundamentals/tasks/7-forking-futures/build.mill, main/api/src/mill/api/Ctx.scala, main/eval/src/mill/eval/ExecutionContexts.scala, scalalib/src/mill/scalalib/TestModuleUtil.scala
Backport of https://github.com/com-lihaoyi/mill/pull/4714
=> Backport "Use priority queue to run Mill executor tasks, prioritizing first async task and de-prioritizing subsequent ones" to 0.12.x

core/api/src/mill/api/Ctx.scala, core/exec/src/mill/exec/ExecutionContexts.scala, scalalib/src/mill/scalalib/TestModuleUtil.scala, testrunner/src/mill/testrunner/Model.scala, testrunner/src/mill/testrunner/TestRunnerMain0.scala, testrunner/src/mill/testrunner/TestRunnerUtils.scala
Forward port of https://github.com/com-lihaoyi/mill/pull/4719
=> (main) Improvements precision of `testParallelism` scheduler lifetime management

bsp/worker/src/mill/bsp/worker/MillBuildServer.scala
=> Fix BSP sync

scalalib/src/mill/scalalib/JavaModule.scala, scalalib/worker/src/mill/scalalib/worker/DiscoverMainClassesMain.scala
Backports https://github.com/com-lihaoyi/mill/pull/4760
Fixes https://github.com/com-lihaoyi/mill/issues/4659
Tested manually, the problem reproduces reliably on `main` and goes away with this PR
=> Backport Fix main class discovery in scala 3

integration/feature/full-run-logs/src/FullRunLogsTests.scala, main/eval/src/mill/eval/EvaluatorCore.scala, main/eval/src/mill/eval/GroupEvaluator.scala
Backport of https://github.com/com-lihaoyi/mill/pull/4617, and some of the cleanups from https://github.com/com-lihaoyi/mill/pull/4661
=> Backport "Add failed tasks count to Mill's progress indicator"

example/android/javalib/1-hello-world/build.mill, example/android/kotlinlib/1-hello-kotlin/build.mill
The tests now run concurrently with workers,
therefore the `out.json` is separated per worker.
=> Fix Android Example Tests

website/package.mill
Fixes https://github.com/com-lihaoyi/mill/issues/4783
=> Fix rendering of bootstrap script installation command

scalalib/src/mill/scalalib/Dep.scala
Forward port of a fix in https://github.com/com-lihaoyi/mill/pull/4830
=> Avoid cyclic dependency in Dep

.config/mill-version, ci/mill-bootstrap.patch, contrib/package.mill, core/codesig/package.mill, dist/package.mill, example/package.mill, example/thirdparty/mockito/build.mill, integration/package.mill, website/package.mill
Depends on a Mill version containing
* https://github.com/com-lihaoyi/mill/pull/4843
=> Fix deprecated API use: millSourcePath, millModuleSegments, millInternal

build.mill, ci/mill-bootstrap.patch, contrib/package.mill, dist/package.mill, example/package.mill, integration/package.mill, main/package.mill, scalalib/package.mill
Depends on a Mill version containing
* https://github.com/com-lihaoyi/mill/pull/4838
=> Replace deprecated API: ZincWorkerXxx

ci/mill-bootstrap.patch, dist/package.mill, website/package.mill
Depends on a Mill version containing
* https://github.com/com-lihaoyi/mill/pull/4840
=> Replace deprecated API: log.outputStream and log.errorStream

runner/client/src/mill/runner/client/MillProcessLauncher.java
Seems to be needed for https://github.com/com-lihaoyi/mill/pull/4856
=> Add robustness around invalid `out/mill-java-home` file

scalalib/src/mill/scalalib/JavaModule.scala, scalalib/src/mill/scalalib/RunModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/4889
=> Move `JavaModule#runBackground` to `RunModule` and clean up bincompat forwarders

core/internal/src/mill/internal/LinePrefixOutputStream.scala
Fix https://github.com/com-lihaoyi/mill/issues/4903
Follow up to https://github.com/com-lihaoyi/mill/pull/4769
=> Don't attempt to get the color of the empty string

main/util/src/mill/util/LinePrefixOutputStream.scala
Fix https://github.com/com-lihaoyi/mill/issues/4903
Original pull request: https://github.com/com-lihaoyi/mill/pull/4902
=> Don't attempt to get the color of the empty string (backport #4902)

kotlinlib/src/mill/kotlinlib/KotlinModule.scala, main/util/src/mill/util/Jvm.scala, scalalib/src/mill/scalalib/RunModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/3481
=> Use `os.Shellable` to handle CLI parameter lists where appropriate

docs/modules/ROOT/pages/cli/installation-ide.adoc
Fix https://github.com/com-lihaoyi/mill/issues/4953
=> Update Windows installation instructions and a PowerShell warning

mill, mill.bat, scripts/src/mill.bat, scripts/src/mill.sh
I forgot to add the source script files in PR https://github.com/com-lihaoyi/mill/pull/4867
=> Fix: Added missing script files

example/fundamentals/dependencies/3-search-updates/build.mill, libs/scalalib/src/mill/scalalib/dependency/DependencyUpdatesImpl.scala, website/docs/modules/ROOT/pages/extending/import-mvn-plugins.adoc, website/docs/modules/ROOT/pages/fundamentals/library-deps.adoc
Fix https://github.com/com-lihaoyi/mill/issues/4990
=> Fix documentation still using outdated dependency imports

runner/test/src/mill/runner/MillMainTests.scala
Those never made it into https://github.com/com-lihaoyi/mill/pull/4969
which was based on top of https://github.com/com-lihaoyi/mill/pull/4624
and added those tests initially.
=> Re-add test-cases for version reader

build.mill, core/util/src/mill/util/Jvm.scala, integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.iml, integration/ide/gen-idea/resources/extended/idea/mill_modules/mill-build.mill-build.iml, integration/ide/gen-idea/resources/hello-idea/idea/mill_modules/mill-build.iml, libs/main/test/src/mill/main/MainModuleTests.scala, libs/scalalib/src/mill/scalalib/JvmWorkerModule.scala, runner/client/src/mill/runner/client/JLineNativeLoader.java
This reverts commit d2552c4e53a15e504cd2198e556cc9b8347d152c.
Just to see if this can fix the main build
CC @alexarchambault
=> Revert "Copy GraalVM under shorter path on Windows CI (#4917)"

libs/main/test/src/mill/main/MainModuleTests.scala
Same workaround as a test nearby (see #4944)
Comes from https://github.com/com-lihaoyi/mill/pull/4917, but shouldn't be a problem
=> Try to fix transient issue on CI

libs/scalalib/src/mill/scalalib/UnidocModule.scala
Fix https://github.com/com-lihaoyi/mill/issues/5034
=> Fix: UnidocModule does not allow customization of Scala compiler flags, e.g.` -Xsource:3` (main branch)

core/api/src/mill/api/MillException.scala, core/define/src/mill/define/Task.scala, runner/daemon/src/mill/daemon/MillDaemonMain.scala, runner/launcher/src/mill/launcher/MillProcessLauncher.java, website/blog/modules/ROOT/pages/7-graal-native-executables.adoc, website/docs/modules/ROOT/pages/depth/process-architecture.adoc
This brings the terminology in line with the package and module name, and away from the name "server" which can be confusing
=> Rename MillServerMain to MillDaemonMain

docs/modules/ROOT/pages/index.adoc
backport of https://github.com/com-lihaoyi/mill/pull/5104
=> Backports "Tweaks to landing page"

contrib/sonatypecentral/readme.adoc, contrib/sonatypecentral/src/mill/contrib/sonatypecentral/SonatypeCentralPublishModule.scala, contrib/sonatypecentral/src/mill/contrib/sonatypecentral/SonatypeCentralPublisher.scala, contrib/sonatypecentral/src/mill/contrib/sonatypecentral/package.scala
This was deleted as part of https://github.com/com-lihaoyi/mill/pull/5107, but although we don't promise compatibility we should try to preserve it on a best effort basis
=> Put back sonatype contrib module in 0.12.x

integration/bootstrap/no-java-bootstrap/src/NoJavaBootstrapTests.scala, mill-build/src/millbuild/Deps.scala
Seems Scala Steward hasn't opened PRs in the Mill repo for a while, so let's manually bump this
=> Update coursier jvm-index to 0.0.4-111-eb6e08

bsp/package.mill, build.mill, main/package.mill, scalalib/src/mill/javalib/revapi/RevapiModule.scala, scalalib/src/mill/scalalib/PublishModule.scala
Fix https://github.com/com-lihaoyi/mill/issues/5116
=> Deprecate `PublishModule.publishSelfDependency`

runner/daemon/src/mill/daemon/MillMain.scala, runner/daemon/src/mill/daemon/MillScalaParserImpl.scala
An attempt to fix https://github.com/com-lihaoyi/mill/issues/5125. I don't have a repro, so I don't know if this fixes it, but at least it shouldn't make it any worse
=> Broaden scope of `MillScalaParser.current` dynamic variable binding

integration/feature/inspect/src/InspectTests.scala, libs/scalalib/src/mill/scalalib/JavaModule.scala, libs/scalalib/test/src/mill/scalalib/CrossVersionTests.scala
Fix https://github.com/com-lihaoyi/mill/issues/4939
Also make the tree as string available via a protected task `mvnDepsTree`.
=> Renamed `mvnDepsTree` to `showMvnDepsTree`

core/define/src/mill/define/Discover.scala, core/define/src/mill/define/Module.scala, core/define/src/mill/define/Task.scala, core/define/test/src/mill/define/DiscoverTests.scala, core/exec/test/src/mill/exec/PlanTests.scala, core/util/src/mill/mill.scala, libs/main/src/mill/main/Inspect.scala, libs/scalajslib/test/src/mill/scalajslib/EsModuleRemapTests.scala, libs/scalalib/src/mill/scalalib/AssemblyModule.scala, libs/scalalib/test/src/mill/scalalib/LauncherTests.scala, runner/meta/src/mill/meta/MillBuildRootModule.scala
Forgot to commit this in https://github.com/com-lihaoyi/mill/pull/5168
=> `Task.Cached` -> `Task.Simple`

example/javalib/dependencies/5-repository-config/build.mill, example/kotlinlib/dependencies/5-repository-config/build.mill, example/scalalib/dependencies/5-repository-config/build.mill, libs/scalalib/src/mill/scalalib/CoursierModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/5113
=> Document `def repositories` task as the preferred alternative to `def repositoriesTask`

core/constants/src/mill/constants/Util.java, integration/feature/mill-jvm-opts-header/resources/build.mill
Fixes https://github.com/com-lihaoyi/mill/issues/5224
=> Fix crash on empty yaml header line

core/util/src/mill/mill.scala, libs/kotlinlib/src/mill/kotlinlib/ksp/KspModule.scala, libs/scalajslib/src/mill/scalajslib/ScalaJSModule.scala, libs/scalalib/test/src/mill/scalalib/ScalaAssemblyAppendTests.scala, libs/scalalib/test/src/mill/scalalib/ScalaAssemblyExcludeTests.scala, libs/scalalib/test/src/mill/scalalib/ScalaValidatedPathRefTests.scala, testkit/src/mill/testkit/UnitTester.scala
Follow up to https://github.com/com-lihaoyi/mill/pull/5256
=> Deprecate `mill.Target` for removal

core/util/src/mill/util/Jvm.scala, libs/scalalib/src/mill/scalalib/CoursierModule.scala, libs/scalalib/src/mill/scalalib/JavaModule.scala, libs/scalalib/src/mill/scalalib/Lib.scala
Follow-up of https://github.com/com-lihaoyi/mill/pull/4626 (see https://github.com/com-lihaoyi/mill/pull/4626#discussion_r2075254872)
That should help for Mill 1.0 upgrades
=> Move checkGradleModules parameter last, ensure it has a default value

core/define/src/mill/define/TaskModule.scala, core/define/test/src/mill/define/TestGraphs.scala, core/exec/test/src/mill/exec/ModuleTests.scala, core/resolve/src/mill/resolve/Resolve.scala, core/resolve/test/src/mill/resolve/ModuleTests.scala, example/fundamentals/modules/12-default-tasks/build.mill, integration/invalidation/selective-execution/resources/build.mill, libs/init/src/mill/init/BuildGenModule.scala, libs/javascriptlib/src/mill/javascriptlib/TestModule.scala, libs/kotlinlib/src/mill/kotlinlib/ktfmt/KtfmtModule.scala, libs/kotlinlib/src/mill/kotlinlib/ktlint/KtlintModule.scala, libs/main/src/mill/main/Inspect.scala, libs/main/test/src/mill/main/MainModuleTests.scala, libs/pythonlib/src/mill/pythonlib/PythonModule.scala, libs/pythonlib/src/mill/pythonlib/RuffModule.scala, libs/pythonlib/src/mill/pythonlib/TestModule.scala, libs/scalalib/src/mill/javalib/palantirformat/PalantirFormatModule.scala, libs/scalalib/src/mill/scalalib/JavaModule.scala, libs/scalalib/src/mill/scalalib/PublishModule.scala, libs/scalalib/src/mill/scalalib/SonatypeCentralPublishModule.scala, libs/scalalib/src/mill/scalalib/TestModule.scala, libs/scalalib/src/mill/scalalib/scalafmt/ScalafmtModule.scala, libs/scalalib/src/mill/scalalib/spotless/SpotlessModule.scala
fixes https://github.com/com-lihaoyi/mill/issues/5403
=> Rename `defaultCommandName` to `defaultTask`

main/client/src/mill/main/client/ServerLauncher.java, main/client/src/mill/main/client/Util.java, runner/client/src/mill/runner/client/MillProcessLauncher.java
Backport of https://github.com/com-lihaoyi/mill/pull/5440
Fix https://github.com/com-lihaoyi/mill/issues/5416
Reproduce with (Mill 0.12): 
```console
> mill -j1 integration.feature[mill-jvm-property].native.__.test
```
=> Fix -D property passing with graal native launcher (backport #5440)

main/server/test/src/mill/main/server/ClientServerTests.scala
Fixup of failing tests I accidentally broke in https://github.com/com-lihaoyi/mill/pull/5442
=> Fix ClientServerTests

integration/ide/gen-idea/resources/hello-idea/idea/scala_compiler.xml, runner/meta/src/mill/meta/MillBuildRootModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/5507
Tested manually
=> Silence warning about encoded package names 

core/constants/src/mill/constants/OutFiles.java, example/fundamentals/out-dir/1-out-files/build.mill, integration/invalidation/process-file-deleted-exit/src/ProcessFileDeletedExit.scala, testkit/test/resources/example-test-example-project/build.mill, testkit/test/src/mill/testkit/ExampleTesterTests.scala, testkit/test/src/mill/testkit/IntegrationTesterTests.scala
This wasn't made on purpose, was it?
=> Fix deamon / daemon typo

libs/javalib/src/mill/javalib/CoursierModule.scala, libs/javalib/src/mill/javalib/JavaModule.scala
Fixes https://github.com/com-lihaoyi/mill/issues/5573.
Tested manually on the example from the linked issue
=> Make `def repositories` and `repositoriesTask` transitive

build.mill
Pulls in https://github.com/com-lihaoyi/mill/pull/5581 to improve the local dev loop
=> Rebootstrap

core/api/test/resources/log4j.properties, core/api/test/resources/log4j2.properties, core/api/test/resources/logback.xml
We're using logback rather than log4j, and so need the appropriate config file to configure it
=> Properly silence jgit logback logs

core/internal/src/mill/internal/JsonArrayLogger.scala
Attempts to fix some non-deterministic mis-ordering of the JSON output:
```json
{"ph":"B","name":"integration.bootstrap[no-java-bootstrap].test.compile","cat":"job","ts":3132004455961,"pid":1,"tid":5},
{"ph":"E","ts":3132004456172,"pid":1,"tid":5},
{"ph":"E","ts":3132004456903,"pid":1,"tid":3},
{"ph":"B","name":"integration.ide[bsp-server-reload].test.compile","cat":"job","ts":3132004456947,"pid":1,"tid":3},
{"ph":"E","ts":3132004457098,"pid":1,"tid":3},
{"ph":"E","ts":3132004569581,"pid":1,"tid":1},
{"ph":"E","ts":3132004594910,"pid":1,"tid":1},
]
{"ph":"E","ts":3132004600874,"pid":1,"tid":1}
```
Haven't managed to reliably reproduce it, but this is the only thing I can think of that would cause things to write in the wrong order. This PR ensures that the `writeThread` has completed and …
=> Synchronize writes in `JsonArrayLogger`

libs/javalib/src/mill/javalib/TestModuleUtil.scala
Previously every iteration we would loop through the entire `claim.log` file and emit a `logger.ticker` for every class found. Depending on scheduling could result in older already-complete classes being shown in the prompt for a fraction of a second before being over-written, which would cause a noticeable flicker in the prompt lines. This PR makes us explicitly
track the last test class and it's start `nanoTime`, so we don't `logger.ticker` earlier already-completed classes that are no longer relevant
Tested manually on our example Netty build's `common.test`; the flicker is noticeable on `1.0.3`, goes away with this patch
=> Fix flicker in PromptLogger reporting of current test class running for each worker

integration/feature/system-java/resources/build.mill, integration/feature/system-java/src/SystemJavaTests.scala
Follow up of https://github.com/com-lihaoyi/mill/pull/5705
=> Add integration test for `mill-jvm-version: system`

example/javalib/linting/4-spotless/build.mill
Fix https://github.com/com-lihaoyi/mill/issues/5804
=> Fix links to API documentation

core/api/daemon/src/mill/api/daemon/MillURLClassLoader.scala, libs/util/src/mill/util/Jvm.scala
Fix https://github.com/com-lihaoyi/mill/issues/5789
The implementation is based on this commit: https://github.com/SBuild-org/sbuild/commit/4b8efad967b8eff422eb7179729b550e09159d6b
=> Register MillURLClassLoader as parallel capable classloader

runner/daemon/src/mill/daemon/Watching.scala
Disables certain entries written to `fsNotifyWatchLog` which cause indefinite loops, CPU usage and disk trashing in watch mode.
Essentially:
- writing to watch log generates an event
- which then gets picked up by mill
- which gets written to watch log
- which then generates an event
Fixes https://github.com/com-lihaoyi/mill/issues/5843
=> Disable certain `fsNotifyWatchLog` logging to prevent indefinite loops

build.mill
This should add support for Java 25 to Mill 0.12.x
=> Update asm-tree to 9.8

contrib/flyway/src/mill/contrib/flyway/FlywayModule.scala, mill-build/src/millbuild/Deps.scala
Should resolve https://github.com/com-lihaoyi/mill/issues/5952
=> Bump flyway to 11.8.2
